import { SafeScopeReasoningDomain } from '../reasoning-orchestrator/reasoning-orchestrator.types';
import { InspectionIntelligenceRule, inspectionActions as actions } from './inspection-intelligence-rule.types';
import { MineContextAssessment, MineType } from './mine-context.types';

type Signals = Record<string, boolean>;
type Standard = { citation: string; summary: string; evidence: string[] };
type Definition = {
  id: string;
  domain: SafeScopeReasoningDomain;
  confidence?: 'moderate' | 'high';
  when: (signals: Signals, context: MineContextAssessment) => boolean;
  initiating: string;
  failure: string;
  exposure: string;
  consequences: string;
  related?: InspectionIntelligenceRule['related'];
  questions: string[];
  controls: InspectionIntelligenceRule['controls'];
  standards?: Partial<Record<MineType, Standard[]>>;
  limitation?: string;
};

const SIGNAL_PATTERNS: Record<string, RegExp[]> = {
  conveyor: [/\bconveyor\b/, /\bbelt line\b/, /\btail pulley\b/, /\bhead pulley\b/, /\btail drum\b/, /\bbelt flight\b/],
  crusherScreen: [/\bcrusher\b/, /\bscreen deck\b/, /\bscreen plant\b/, /\bcrushing plant\b/],
  guardingFailure: [/\b(missing|removed|open|broken|no|without|exposed|unguarded)\b.*\b(guard|barrier|shield)/, /\b(exposed|unguarded|unshielded)\b.*\b(belt|drive|pulley|shaft|moving part|tail drum|sheave)/],
  cleanupMaintenance: [/\b(cleanup|cleaning|shoveling|maintenance|repair|servicing|clearing|unjam|jam)\b/],
  stopControl: [/\b(emergency stop|e-stop|stop cord|pull cord|pull cable|lanyard switch)\b/],
  uncertainControl: [/\b(unclear|unknown|not verified|missing|inoperative|not working|no evidence|no railing|without railing)\b/],
  walkway: [/\b(walkway|travelway|catwalk|access way|passageway)\b/],
  opening: [/\b(opening|floor hole|drop[- ]off|unprotected edge|missing cover|no railing|without railing)\b/],
  ladder: [/\b(ladder|ladderway|screen deck access)\b/],
  ladderDefect: [/\b(damaged|broken|loose|unsecured|missing rung|defective|unstable)\b/],
  housekeeping: [/\b(debris|spillage|rocks|material buildup|poor housekeeping|mud|trip hazard)\b/],
  berm: [/\bberm|guardrail|windrow\b/],
  bermFailure: [/\b(missing|low|inadequate|no|damaged)\b.*\b(berm|guardrail|windrow)/, /\b(berm|guardrail|windrow)\b.*\b(missing|low|inadequate|damaged)/],
  mobile: [/\b(haul truck|loader|pickup|dozer|grader|mobile equipment|shuttle car|scoop|lhd|load-haul-dump)\b/],
  backing: [/\b(backing|reversing|reverse)\b/],
  pedestrian: [/\b(pedestrian|miner on foot|miners on foot|worker on foot|spotter)\b/],
  trafficConflict: [/\b(blind corner|intersection|interaction|same route|traffic control|right of way|close proximity)\b/],
  unattended: [/\b(unattended|parked|operator left|left running)\b/],
  parkingControl: [/\b(chock|parking brake|lowered|blocked|turned into bank|secured)\b/],
  seatbeltRops: [/\b(seat ?belt|rops|rollover protective structure|operator restraint)\b/],
  ground: [/\b(highwall|loose ground|loose rib|roof|rib|back|slough|scaling|rock fall|ground condition)\b/],
  surfaceGround: [/\b(highwall|bank|pit wall|quarry wall)\b/],
  undergroundGround: [/\b(loose rib|loose roof|unsupported roof|back condition|scaling|ground support)\b/],
  hopper: [/\b(stockpile|surge pile|feed hopper|hopper|bin|silo|drawhole)\b/],
  engulfment: [/\b(engulf|entrap|caving material|sliding material|bridged material|working on pile|entered hopper|inside hopper)\b/],
  electrical: [/\b(electrical|energized|power cable|trailing cable|conductor|panel|switchgear)\b/],
  cableDamage: [/\b(damaged|frayed|cut|exposed|run over|crushed|poor splice)\b.*\b(cable|conductor)/, /\b(cable|conductor)\b.*\b(damaged|frayed|cut|exposed|wet|water|crushed|jacket)/],
  wet: [/\b(wet|water|standing water|damp|muddy heading)\b/],
  panelOpen: [/\b(open panel|missing cover|open energized|exposed energized|breaker slot|cover plate)\b/],
  leak: [/\b(leak|leaking|spill|release|uncovered|open container)\b/],
  fuelOil: [/\b(fuel|diesel fuel|lube|lubricant|used oil|waste oil)\b/],
  drainage: [/\b(drain|ditch|sump|soil|waterway|drainage path)\b/],
  cylinder: [/\b(oxygen|acetylene|compressed gas|welding) cylinder\b/],
  cylinderFailure: [/\b(unsecured|not secured|missing cap|stored together|no separation|damaged)\b/],
  hotWork: [/\b(hot work|welding|cutting|brazing|grinding)\b/],
  combustibles: [/\b(combustible|flammable|fuel|oil|cardboard|wood|rubber|belt)\b/],
  noise: [/\b(noise|loud|hearing|crusher noise|screen noise|drill noise)\b/],
  exposureUnknown: [/\b(no monitoring|without monitoring|not monitored|unknown exposure|no sampling|not sampled|duration unknown|no evidence)\b/],
  dust: [/\b(dust|silica|respirable|airborne particulate|drill dust|crusher dust)\b/],
  dustTask: [/\b(drill|drilling|crusher|crush|crushing|screen|screening|cutting|grinding|dry sweeping)\b/],
  diesel: [/\b(diesel|diesel exhaust|diesel particulate|dpm|equipment exhaust)\b/],
  ventilation: [/\b(ventilation|airflow|air flow|fan|vent tubing|exhaust|stagnant air|methane)\b/],
  escapeway: [/\b(escapeway|escape route|refuge|refuge chamber|lifeline)\b/],
  blockedUnclear: [/\b(blocked|obstructed|damaged|unclear|unknown|not verified|missing)\b/],
  training: [/\b(training|task training|new miner|experienced miner|hazard awareness|site-specific)\b/],
  contractor: [/\b(contractor|independent contractor|vendor|service technician|service crew)\b/],
  coalBelt: [/\b(belt conveyor|belt line|belt entry|belt haulage)\b/],
  coalFire: [/\b(fire|smoke|slippage|combustible accumulation|coal dust|guarding|roller|bearing)\b/],
  methane: [/\b(methane|gas buildup|flammable gas|methane monitor)\b/],
  permissibility: [/\b(permissible|permissibility|approved equipment|electrical enclosure)\b/],
  explosives: [/\b(explosive|blasting|blast area|detonator|magazine|misfire)\b/],
};

function buildSignals(text: string): Signals {
  return Object.fromEntries(Object.entries(SIGNAL_PATTERNS).map(([key, patterns]) => [key, patterns.some((pattern) => pattern.test(text))]));
}

const surfaceMnm: MineType[] = ['surface_metal_nonmetal'];
const undergroundMnm: MineType[] = ['underground_metal_nonmetal'];
const mnm: MineType[] = [...surfaceMnm, ...undergroundMnm];
const coal: MineType[] = ['surface_coal', 'underground_coal'];
const isType = (context: MineContextAssessment, types: MineType[]) => types.includes(context.mineType);

const definitions: Definition[] = [
  {
    id: 'msha-conveyor-guarding-servicing', domain: 'machine_guarding_loto',
    when: (s, c) => isType(c, mnm) && s.conveyor && s.guardingFailure && s.cleanupMaintenance,
    initiating: 'A miner performing cleanup or maintenance can access an unguarded conveyor pulley, belt, shaft, or nip point.',
    failure: 'Moving parts or unexpected belt motion can draw the miner into the conveyor when guarding and power-off/blocking controls are incomplete.',
    exposure: 'Hands, tools, clothing, or the miner’s body can enter the pinch, entanglement, or caught-in zone during cleanup or servicing.',
    consequences: 'Crushing, entanglement, amputation, or fatal caught-in injury.',
    related: [{ domain: 'machine_guarding', rationale: 'Accessible moving conveyor parts require mine-specific guarding review.' }, { domain: 'lockout_tagout', rationale: 'Repair, maintenance, or cleanup may require power-off and blocking against hazardous motion.' }],
    questions: ['Was the belt stopped, power disconnected, restart prevented, and hazardous motion blocked before access?', 'Which pulley, belt, shaft, nip point, and guard opening are accessible?', 'Is the mine surface M/NM or underground M/NM, and who examined the guard and work procedure?'],
    controls: actions('Stop the conveyor task, remove miners from the danger zone, and disconnect power.', 'Lock/tag where used by the mine, block hazardous motion, barricade access, and verify zero motion before cleanup.', 'Install and maintain a guard that prevents contact with the moving part throughout operation.', 'Correct the task procedure and workplace examination and train affected miners on guarding and power-off/blocking controls.', 'Document guard condition, power-disconnection/restart prevention, blocking, examination, and safe restart.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.14107(a)', summary: 'Guarding moving machine parts at surface M/NM mines.', evidence: ['surface M/NM applicability', 'moving part and access', 'guard condition', 'miner task/proximity'] }, { citation: '30 CFR 56.14105', summary: 'Procedures during repairs or maintenance at surface M/NM mines.', evidence: ['repair/maintenance/cleanup task', 'power-off status', 'blocking against motion', 'restart prevention'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.14107(a)', summary: 'Guarding moving machine parts at underground M/NM mines.', evidence: ['underground M/NM applicability', 'moving part and access', 'guard condition', 'miner task/proximity'] }, { citation: '30 CFR 57.14105', summary: 'Procedures during repairs or maintenance at underground M/NM mines.', evidence: ['servicing task', 'power-off status', 'blocking', 'restart prevention'] }] },
  },
  {
    id: 'msha-crusher-screen-guarding', domain: 'machine_guarding',
    when: (s, c) => isType(c, mnm) && s.crusherScreen && s.guardingFailure,
    initiating: 'A crusher or screen drive, belt, pulley, shaft, or similar moving component is accessible to miners.',
    failure: 'Rotating or reciprocating machinery can catch, pull in, pinch, or strike a miner when the guard is absent or ineffective.',
    exposure: 'Operators, screen attendants, cleanup crews, and maintenance miners may enter the moving-part danger zone.',
    consequences: 'Entanglement, crushing, amputation, laceration, or fatal trauma.',
    questions: ['Which crusher/screen component is exposed and can a miner contact it from a walking or working surface?', 'Is the component operating, and what guard design/opening/security is present?', 'Are cleanup, inspection, lubrication, or maintenance tasks performed nearby?'],
    controls: actions('Stop affected equipment or exclude miners from the moving-part zone.', 'Disconnect power for access and install a secured temporary barrier pending permanent guarding.', 'Install a durable guard that prevents contact and supports required inspection and maintenance.', 'Add the component to workplace/pre-operational examinations and task-specific training.', 'Verify guard construction/security, reach prevention, examination record, and safe operation before return to service.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.14107(a)', summary: 'Surface M/NM moving-machine-parts guarding.', evidence: ['crusher/screen component', 'moving status', 'walking/working surface access', 'guard condition'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.14107(a)', summary: 'Underground M/NM moving-machine-parts guarding.', evidence: ['crusher/screen component', 'moving status', 'miner access', 'guard condition'] }] },
  },
  {
    id: 'msha-conveyor-stop-control', domain: 'machine_guarding', confidence: 'moderate',
    when: (s, c) => isType(c, mnm) && s.conveyor && s.stopControl && s.uncertainControl,
    initiating: 'A conveyor emergency stop or pull-cord control is missing, defective, or not verified for the observed operating area.',
    failure: 'A miner may be unable to stop hazardous belt motion promptly after entanglement, material movement, or another emergency develops.',
    exposure: 'Miners working or traveling near the conveyor may remain exposed while access, operability, coverage, and restart behavior are uncertain.',
    consequences: 'Worsened caught-in injury, delayed emergency response, material release, or fire escalation.',
    questions: ['What stop device is provided, what conveyor area does it cover, and is it accessible from the exposure location?', 'Was operability/function tested without exposing miners to startup or motion?', 'What startup warning, reset, inspection, and defect-correction process applies?'],
    controls: actions('Keep miners clear and stop the affected conveyor until the control is evaluated.', 'Use controlled shutdown and barricading while a qualified mine electrician/mechanic verifies the device.', 'Repair or install the mine-approved stop/control system with protected, accessible coverage for the operating area.', 'Add functional checks, defect reporting, startup warnings, and miner training to the examination program.', 'Document device location, controlled functional test, repair, reset/startup behavior, and responsible-person verification.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.14100', summary: 'Examination and correction of safety defects on self-propelled and other equipment.', evidence: ['device as safety defect', 'operability and affected operation', 'examination and correction record'] }, { citation: '30 CFR 56.14201', summary: 'Conveyor start-up warnings at surface M/NM mines.', evidence: ['audible warning coverage', 'persons affected by startup', 'warning duration/function'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.14100', summary: 'Equipment safety-defect examination and correction underground.', evidence: ['device condition', 'operability/exposure', 'examination and correction'] }, { citation: '30 CFR 57.14201', summary: 'Underground M/NM conveyor start-up warnings.', evidence: ['warning system and coverage', 'startup exposure', 'function'] }] },
  },
  {
    id: 'msha-conveyor-walkway-access', domain: 'walking_working_surfaces', confidence: 'moderate',
    when: (s, c) => isType(c, mnm) && s.conveyor && s.walkway && (s.uncertainControl || s.guardingFailure),
    initiating: 'A mine walkway or travelway runs beside a conveyor without confirmed safe access, separation, or guarding.',
    failure: 'Restricted clearance, an unguarded conveyor, spillage, or inadequate railing can place miners in contact with moving equipment or a fall path.',
    exposure: 'Miners using the route may pass within reach of belt components or be forced into unsafe footing or clearance.',
    consequences: 'Caught-in, struck-by, trip/fall, or fall-to-lower-level injury.',
    questions: ['What walkway width, clearance, surface, railing, and conveyor separation are present?', 'Which conveyor parts are within reach and is the route required for regular travel or maintenance?', 'Are alternate access, crossovers, lighting, and housekeeping adequate?'],
    controls: actions('Restrict the route where miners cannot pass safely beside the conveyor.', 'Barricade hazardous reach/fall areas and provide a controlled alternate route.', 'Provide compliant conveyor walkway clearance, guarding, railing, crossovers, and durable access.', 'Include conveyor walkways in workplace examinations and access/housekeeping assignments.', 'Measure and document clearance, guard reach, railing, surface condition, lighting, and route reopening.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.11009', summary: 'Surface M/NM walkways along conveyors.', evidence: ['walkway location and use', 'clearance/separation', 'conveyor exposure', 'safe passage'] }, { citation: '30 CFR 56.14109', summary: 'Unguarded conveyors with adjacent travelways.', evidence: ['unguarded conveyor', 'adjacent travelway', 'miner exposure', 'guardrail location'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.11009', summary: 'Underground M/NM walkways along conveyors.', evidence: ['walkway and conveyor geometry', 'clearance', 'safe passage'] }, { citation: '30 CFR 57.14109', summary: 'Underground unguarded conveyors with adjacent travelways.', evidence: ['unguarded conveyor', 'travelway proximity', 'miner exposure'] }] },
  },
  {
    id: 'msha-travelway-opening', domain: 'fall_protection',
    when: (s, c) => isType(c, mnm) && s.walkway && s.opening,
    initiating: 'An opening, drop-off, or edge is located above, below, or near a mine travelway without confirmed protection.',
    failure: 'A miner can step, slip, or be displaced into the opening when a cover, railing, or barrier is absent or deficient.',
    exposure: 'Regular travel or task work places miners within the fall path.',
    consequences: 'Fall-to-lower-level injury, entrapment, or fatal trauma.',
    questions: ['What are the opening dimensions, fall distance, route use, and approach geometry?', 'What railing, barrier, or secured load-rated cover is present?', 'Is the condition temporary, and who examined the travelway before use?'],
    controls: actions('Barricade the opening and reroute miners immediately.', 'Install a secured temporary cover or railing under qualified review.', 'Provide permanent railing, barrier, or load-rated cover appropriate to the travelway.', 'Add travelway/opening examinations and controls for temporary opening creation.', 'Document dimensions, protection strength/security, route examination, and reopening approval.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.11012', summary: 'Protection for openings above, below, or near surface M/NM travelways.', evidence: ['opening and travelway geometry', 'fall distance', 'miner travel', 'railing/barrier/cover'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.11012', summary: 'Protection for openings near underground M/NM travelways.', evidence: ['opening dimensions/location', 'miner travel', 'protective system'] }] },
  },
  {
    id: 'msha-ladder-access', domain: 'ladders',
    when: (s, c) => isType(c, mnm) && s.ladder && s.ladderDefect,
    initiating: 'A ladder or ladderway used for mine access is damaged, unstable, unsecured, or otherwise deficient.',
    failure: 'The ladder, rung, anchorage, footing, or user position can shift or fail during ascent/descent.',
    exposure: 'Miners accessing a screen deck, platform, plant, or underground level may fall or lose contact.',
    consequences: 'Fall injury, fracture, head/spinal trauma, or secondary contact injury.',
    questions: ['What ladder type, defect, anchorage, footing, angle, landing, and access height apply?', 'Is this fixed construction condition or unsafe use, and has the ladder been removed from service?', 'What alternative safe access is available?'],
    controls: actions('Remove the ladder from service and block the access point.', 'Provide inspected alternate access and secure the work area.', 'Repair/replace and anchor the ladder or install designed stairs/platform access.', 'Include ladder condition/use in workplace examinations and miner task training.', 'Document defect disposition, construction/anchorage, setup, landing protection, and pre-use inspection.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.11003', summary: 'Construction and maintenance of ladders at surface M/NM mines.', evidence: ['ladder construction/defect', 'maintenance condition', 'mine access use'] }, { citation: '30 CFR 56.11011', summary: 'Safe use of ladders at surface M/NM mines.', evidence: ['ladder use/setup', 'secure footing/support', 'miner exposure'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.11003', summary: 'Construction and maintenance of underground M/NM ladders.', evidence: ['ladder condition/construction', 'access use'] }, { citation: '30 CFR 57.11011', summary: 'Safe ladder use underground.', evidence: ['setup/support', 'miner use', 'defect'] }] },
  },
  {
    id: 'msha-travelway-housekeeping', domain: 'walking_working_surfaces',
    when: (s, c) => isType(c, mnm) && s.walkway && s.housekeeping,
    initiating: 'Debris, spillage, loose rock, mud, or material buildup obstructs or degrades a mine travelway.',
    failure: 'The route no longer provides orderly footing or clearance, allowing slips, trips, falls, or forced movement toward adjacent hazards.',
    exposure: 'Miners repeatedly traveling the route can contact the obstruction or unstable surface.',
    consequences: 'Same-level fall, strain, fracture, or secondary conveyor/mobile-equipment contact.',
    questions: ['What material, route length, clearance, lighting, drainage, and traffic frequency apply?', 'Is the source recurring from spillage, tracking, drainage, or storage?', 'What examination and cleanup frequency is assigned?'],
    controls: actions('Remove miners from an unsafe route and clean or remove the immediate obstruction.', 'Provide a controlled alternate route and temporary drainage/spillage controls.', 'Correct the source and provide durable drainage, containment, storage, and travelway surfacing.', 'Assign workplace examination and housekeeping ownership by area/shift.', 'Document the cleared route, source correction, lighting/drainage, and follow-up examination.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.20003(a)', summary: 'Orderly workplaces and passageways at surface M/NM mines.', evidence: ['travelway/workplace', 'material accumulation', 'miner exposure', 'cleanup/examination'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.20003(a)', summary: 'Orderly underground M/NM workplaces and passageways.', evidence: ['underground travelway', 'obstruction/spillage', 'miner exposure'] }] },
  },
  {
    id: 'msha-surface-berm', domain: 'powered_haulage',
    when: (s, c) => c.mineType === 'surface_metal_nonmetal' && s.berm && s.bermFailure,
    initiating: 'A surface mine elevated roadway or dump point lacks a confirmed adequate berm or guardrail.',
    failure: 'A haulage unit can overtravel the edge during approach, backing, turning, or dumping.',
    exposure: 'Operators and nearby miners may be exposed to rollover, edge fall, material movement, and recovery hazards.',
    consequences: 'Rollover, crushing, ejection, burial, or fatal powered-haulage injury.',
    questions: ['What equipment size, berm height/geometry, drop-off, route, and dump approach apply?', 'Are stop blocks, spotters, lighting, ground stability, and dumping restraints present?', 'Who examined the roadway/dump point and when did conditions change?'],
    controls: actions('Close the roadway or dump point and remove equipment from edge exposure.', 'Use an alternate location or controlled route under mine supervision.', 'Restore berm/guardrail and dumping restraint geometry appropriate to the equipment and ground.', 'Add berm, ground, lighting, and dump-point checks to workplace examinations and traffic rules.', 'Measure and document berm/equipment relationship, ground condition, examination, and reopening.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.9300', summary: 'Berms or guardrails on surface M/NM elevated roadways and dump sites.', evidence: ['surface M/NM context', 'drop-off and roadway/dump geometry', 'equipment size', 'berm/guardrail'] }] },
  },
  {
    id: 'msha-mobile-traffic', domain: 'mobile_equipment',
    when: (s, c) => c.detected && s.mobile && (s.pedestrian || s.trafficConflict || s.backing),
    initiating: 'Mine mobile equipment and people or other vehicles occupy a route with incomplete separation, visibility, or traffic controls.',
    failure: 'Blind spots, backing, turning, speed, right-of-way ambiguity, or warning failure can place equipment into an occupied path.',
    exposure: 'Miners on foot or in light vehicles can enter the haulage unit’s travel, swing, or reverse zone.',
    consequences: 'Run-over, struck-by, collision, pinned-between, or fatal crushing injury.',
    questions: ['What equipment, route, blind areas, speed, pedestrian/light-vehicle traffic, and intersection geometry apply?', 'What traffic rules, separation, berms, signs, lights, horns/alarms, radio calls, and spotters are used?', 'Was the operator authorized/trained and were warning devices examined?'],
    controls: actions('Stop conflicting movement and separate miners/vehicles from the active route.', 'Use barricades, controlled crossings, spotters, radio protocol, and verified warning devices.', 'Redesign routes/intersections with physical separation, visibility, lighting, and proximity controls.', 'Maintain mine traffic rules, operator/task training, pre-operational checks, and workplace examinations.', 'Observe representative movement and document route separation, visibility, warning devices, communication, and training.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.9100', summary: 'Surface M/NM traffic control and rules governing movement.', evidence: ['traffic interaction', 'rules/signals', 'route and right-of-way', 'miner exposure'] }, { citation: '30 CFR 56.14132(a)', summary: 'Horns and backup alarms on surface M/NM mobile equipment.', evidence: ['equipment type', 'obstructed view/backing', 'alarm/horn function', 'exposure'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.9100', summary: 'Underground M/NM traffic control and movement rules.', evidence: ['underground haulage context', 'traffic interaction', 'rules/signals'] }, { citation: '30 CFR 57.14132(a)', summary: 'Underground M/NM horns and backup alarms.', evidence: ['equipment and visibility', 'warning-device function', 'miner exposure'] }] },
  },
  {
    id: 'msha-unattended-parking', domain: 'mobile_equipment', confidence: 'moderate',
    when: (s, c) => isType(c, mnm) && s.mobile && s.unattended && (s.uncertainControl || !s.parkingControl),
    initiating: 'Unattended mine mobile equipment lacks confirmed parking, lowering, chocking, or securement controls.',
    failure: 'Gravity, grade, brake loss, vibration, or unintended control movement can allow rolling or raised-component descent.',
    exposure: 'Miners, vehicles, and structures in the movement zone may be struck or crushed.',
    consequences: 'Runaway collision, pinned-between injury, crushing, or equipment/property damage.',
    questions: ['What equipment, grade, parking brake, transmission position, wheel position, chocks, and raised components apply?', 'Was the engine left running and is movement or unauthorized operation possible?', 'What mine parking procedure and examination evidence apply?'],
    controls: actions('Clear the potential movement zone and secure the equipment under qualified operator control.', 'Set brakes, lower attachments, chock/block where required, and prevent unauthorized operation.', 'Correct parking systems and provide engineered parking areas/chock storage for recurring locations.', 'Reinforce mine parking procedures, operator task training, and pre-operational brake checks.', 'Document grade, brake/attachment/chock condition, securement, defect correction, and operator verification.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.14207', summary: 'Parking procedures for unattended surface M/NM mobile equipment.', evidence: ['unattended status', 'grade/location', 'brakes/wheels/chocks', 'raised components'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.14207', summary: 'Parking procedures for unattended underground M/NM equipment.', evidence: ['unattended status', 'grade', 'securement and attachments'] }] },
  },
  {
    id: 'msha-seatbelt-rops-ambiguity', domain: 'mobile_equipment', confidence: 'moderate',
    when: (s, c) => isType(c, mnm) && s.mobile && s.seatbeltRops && s.uncertainControl,
    initiating: 'Seat-belt, operator-restraint, or rollover-protection adequacy is not established for mine mobile equipment.',
    failure: 'A collision, rollover, or abrupt movement can eject or crush an operator when protection is absent, defective, or unused.',
    exposure: 'The operator may not remain within the protected zone during loss of control or rollover.',
    consequences: 'Ejection, crushing, head/spinal trauma, or fatal rollover injury.',
    questions: ['What equipment type/manufacture date and ROPS/restraint requirements apply?', 'Are belt, latch, anchor, ROPS structure, and operator use verified?', 'What pre-operational examination and defect-correction record exists?'],
    controls: actions('Remove equipment from service if required restraint/ROPS condition is unsafe or unknown.', 'Restrict operation pending qualified inspection of restraint and protective structure.', 'Repair/replace approved restraint components and ROPS defects without unapproved modification.', 'Maintain operator use rules, pre-operational examinations, and defect reporting/training.', 'Document equipment applicability, component inspection, repair, and observed operator use.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.14130', summary: 'ROPS and seat-belt requirements for covered surface M/NM equipment.', evidence: ['equipment type/manufacture date', 'ROPS applicability', 'seat belt condition/use'] }, { citation: '30 CFR 56.14131', summary: 'Seat belts for surface M/NM haulage trucks.', evidence: ['haulage truck type', 'seat-belt availability/condition/use'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.14130', summary: 'ROPS and seat-belt requirements where applicable underground.', evidence: ['equipment/application', 'protective structure', 'restraint condition/use'] }] },
  },
  {
    id: 'msha-ground-control', domain: 'ground_control',
    when: (s, c) => c.detected && s.ground,
    initiating: 'Mining ground indicators suggest loose, unsupported, fractured, or unstable rock/coal above or beside a work or travel area.',
    failure: 'Weathering, geologic discontinuities, water, blasting, vibration, stress, or changed geometry can release material.',
    exposure: 'Miners and equipment may occupy the fall, slough, burst, or runout zone.',
    consequences: 'Struck-by, crushing, burial, entrapment, or fatal ground-fall injury.',
    questions: ['What mine type, face/roof/rib/highwall geometry, cracks/loose material, water, and recent blasting/weather are present?', 'Where are miners, equipment, and travel relative to the fall/runout zone?', 'What examination, scaling, support, barricading, and ground-control plan apply?'],
    controls: actions('Withdraw miners/equipment and barricade or post the affected ground-fall zone.', 'Have an experienced/qualified mine examiner assess and control scaling/support work.', 'Scale, support, bench, drain, or reconfigure the ground using the mine’s approved/qualified method.', 'Increase workplace/preshift examinations after change and reinforce ground-control reporting.', 'Document condition, examination, correction/support, exclusion zone, and safe reopening basis.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.3200', summary: 'Correction or control of hazardous ground conditions at surface M/NM mines.', evidence: ['ground condition', 'miner exposure', 'posting/barrier', 'correction/support'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.3200', summary: 'Correction or control of hazardous ground conditions at underground M/NM mines.', evidence: ['roof/rib/back condition', 'miner work/travel', 'posting/barrier', 'scaling/support'] }], underground_coal: [{ citation: '30 CFR 75.202(a)', summary: 'Protection from falls of roof, face, and ribs in underground coal mines.', evidence: ['underground coal context', 'roof/face/rib condition', 'work/travel exposure', 'support/control'] }] },
  },
  {
    id: 'msha-hopper-engulfment', domain: 'material_handling',
    when: (s, c) => isType(c, mnm) && s.hopper && s.engulfment,
    initiating: 'A miner may enter or work where loose material in a hopper, bin, silo, tank, drawhole, or surge pile can cave or slide.',
    failure: 'Bridged or unstable material can release suddenly and flow around, bury, or pull the miner into the opening.',
    exposure: 'The miner is in the material movement/engulfment zone during clearing, probing, feeding, or pile work.',
    consequences: 'Engulfment, suffocation, crushing, entrapment, or fatal injury.',
    questions: ['What storage/transfer structure, material behavior, bridge/void, task, and entry location apply?', 'Can mechanical/remote means eliminate entry and is feed/movement isolated and blocked?', 'What lifeline, attendant, communication, access, and rescue provisions are required by the mine procedure?'],
    controls: actions('Stop material movement and remove miners from the engulfment zone.', 'Barricade access and use remote/mechanical clearing under qualified mine supervision.', 'Engineer flow, access, isolation, mechanical handling, and retrieval so entry into caving/sliding material is eliminated.', 'Implement task-specific isolation, entry, communication, rescue, and training controls.', 'Document material condition, isolation/blocking, remote method, access control, and qualified verification.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.16002', summary: 'Surface M/NM bins, hoppers, silos, tanks, and surge piles.', evidence: ['structure/material', 'normal/abnormal task', 'entry/engulfment exposure', 'mechanical handling and safeguards'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.16002', summary: 'Underground M/NM bins, hoppers, silos, tanks, and surge piles.', evidence: ['structure/material', 'entry/task', 'caving/sliding exposure', 'isolation/safeguards'] }] },
  },
  {
    id: 'msha-electrical-cable', domain: 'electrical',
    when: (s, c) => isType(c, mnm) && s.electrical && s.cableDamage,
    initiating: 'A mine power or trailing cable is damaged or exposed to mechanical/wet-location deterioration.',
    failure: 'Insulation, conductor, splice, or protection can fail, energizing the cable surface, water, equipment, or ground.',
    exposure: 'Miners may contact electrical energy directly or through conductive tools, wet ground, or mobile equipment.',
    consequences: 'Shock, electrocution, arc burn, fire, equipment damage, or secondary fall.',
    questions: ['What cable, voltage, circuit, damage depth, energized status, and protective device apply?', 'Is it a trailing cable, in water/wet ground, or exposed to mobile/mechanical damage?', 'Who is qualified to de-energize, test, repair/replace, and examine it before reuse?'],
    controls: actions('De-energize and remove the cable/circuit from service and keep miners clear.', 'Protect the area and use only an authorized compliant temporary repair if applicable.', 'Replace or properly repair the cable and provide bridging, routing, strain relief, and wet/mechanical protection.', 'Add cable condition/routing to workplace and pre-operational examinations and qualified repair procedures.', 'Document de-energization/test, damage, repair/replacement, routing/protection, and qualified examination.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.12004', summary: 'Surface M/NM electrical conductors and mechanical-damage protection.', evidence: ['cable/conductor and voltage', 'damage/mechanical exposure', 'energized status', 'protection'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.12004', summary: 'Underground M/NM electrical conductors and mechanical-damage protection.', evidence: ['underground cable/conductor', 'damage/wet/mechanical exposure', 'energized status', 'protection'] }] },
  },
  {
    id: 'msha-electrical-panel', domain: 'electrical',
    when: (s, c) => isType(c, mnm) && s.electrical && s.panelOpen,
    initiating: 'A mine electrical enclosure or panel has an open cover, missing plate, or accessible energized parts.',
    failure: 'The enclosure no longer prevents contact or entry of conductive contamination and may expose a developing dangerous condition.',
    exposure: 'Miners may contact energized parts or initiate an arc while operating or approaching the equipment.',
    consequences: 'Shock, electrocution, arc burn, fire, or secondary fall.',
    questions: ['What equipment, voltage, energized condition, cover/plate defect, and access are present?', 'Can unqualified miners approach or operate it?', 'Has a qualified mine electrician de-energized/tested and examined the condition?'],
    controls: actions('Restrict access and have a qualified person de-energize/test the equipment.', 'Barricade and label the area pending permanent enclosure repair.', 'Install the correct cover/plate and restore enclosure, grounding, and environmental integrity.', 'Add panel covers/access to electrical examinations and restrict work to authorized qualified persons.', 'Document voltage/status, qualified examination, correct repair, enclosure closure, and access control.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.12032', summary: 'Surface M/NM electrical inspection and cover plates.', evidence: ['equipment/voltage', 'cover or opening condition', 'shock/fire hazard', 'inspection/correction'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.12032', summary: 'Underground M/NM electrical inspection and cover plates.', evidence: ['equipment/voltage', 'cover condition', 'access and hazard', 'inspection/correction'] }] },
  },
  {
    id: 'msha-fuel-oil-release', domain: 'environmental_release',
    when: (s, c) => isType(c, mnm) && s.fuelOil && s.leak,
    initiating: 'Fuel, lubricant, or used oil is leaking or released at a mine work/storage area.',
    failure: 'Containment loss can spread liquid to travelways, drainage, soil, equipment, or ignition sources.',
    exposure: 'Miners may slip or contact the material; the release may reach the environment or contribute fuel to a fire.',
    consequences: 'Slip/fall injury, skin exposure, fire, equipment damage, or environmental contamination.',
    related: [{ domain: 'walking_working_surfaces', rationale: 'Released oil or fuel can contaminate mine walking and working surfaces.' }, { domain: 'fire_protection', rationale: 'Fuel involvement depends on material properties and ignition sources.', possible: true }],
    questions: ['What material, quantity/rate, source, container/equipment, and SDS/product information apply?', 'Can it reach a travelway, drain, ditch, sump, soil, water, or ignition source?', 'What closure, compatible containment, spill response, and disposal controls are present?'],
    controls: actions('Stop the release if safe, isolate ignition/access, protect drainage, and deploy the mine spill response.', 'Barricade contaminated travelways and place the source in compatible secondary containment.', 'Repair/replace the source and engineer compatible closed storage, transfer, and drainage containment.', 'Maintain fuel/lube inspections, housekeeping, spill response, and miner communication/training.', 'Document source correction, quantity/path, cleanup, containment, travelway condition, and disposition.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.4102', summary: 'Surface M/NM control of flammable/combustible liquid spillage and leakage.', evidence: ['material and quantity', 'leak/spill source', 'fire/travel/environment pathway', 'cleanup/containment'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.4102', summary: 'Underground M/NM control of spillage and leakage.', evidence: ['material/source', 'underground spread/fire pathway', 'cleanup/containment'] }] },
  },
  {
    id: 'msha-compressed-gas', domain: 'compressed_gas',
    when: (s, c) => isType(c, mnm) && s.cylinder && s.cylinderFailure,
    initiating: 'A compressed-gas or welding cylinder at a mine lacks confirmed securing, valve protection, or safe oxygen/fuel separation.',
    failure: 'Impact or falling can damage a valve and release pressure; oxygen/fuel involvement can intensify fire.',
    exposure: 'Miners in the storage, shop, or traffic path may be struck or exposed to gas/fire.',
    consequences: 'Projectile/struck-by injury, crushing, fire, explosion, or atmospheric effects.',
    questions: ['What gas, storage/use status, securing, cap, separation, ventilation, and traffic protection apply?', 'Are oxygen cylinders separated from combustibles and fuel gas as required?', 'Who examined the shop/storage condition?'],
    controls: actions('Keep miners/traffic clear and secure/cap the cylinder or move it to safe storage.', 'Separate oxygen/fuel gas and establish protected temporary storage.', 'Provide designed racks, restraints, valve protection, separation, ventilation, and impact protection.', 'Add cylinder handling/storage to shop inspections and miner task training.', 'Document gas identity, securing/cap, storage/use status, separation, and examination.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.4601', summary: 'Oxygen-cylinder storage at surface M/NM mines.', evidence: ['oxygen cylinder identity', 'storage status', 'combustible/fuel-gas separation', 'secure storage'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.4601', summary: 'Oxygen-cylinder storage at underground M/NM mines.', evidence: ['gas identity', 'storage/use status', 'separation and securing'] }] },
  },
  {
    id: 'msha-hot-work', domain: 'welding_cutting_hot_work',
    when: (s, c) => isType(c, mnm) && s.hotWork && s.combustibles,
    initiating: 'Mine hot work creates sparks, slag, flame, or heat near combustible or flammable material.',
    failure: 'Ignition can occur at the work area or in concealed/adjacent locations without removal, shielding, ventilation, and fire watch controls.',
    exposure: 'Miners and mine property may be exposed to fire, smoke, cylinder involvement, or explosion.',
    consequences: 'Burns, smoke inhalation, fire spread, explosion trauma, or fatal injury.',
    questions: ['What hot-work process, combustibles/flammables, distance, enclosure, and adjacent spaces apply?', 'What extinguishing equipment, fire watch, ventilation, gas testing, and post-work examination are in place?', 'Are cylinders, hoses, and work surfaces prepared and protected?'],
    controls: actions('Stop hot work and remove/protect combustibles and flammable atmosphere.', 'Establish extinguishing equipment, shielding, ventilation, exclusion, and fire watch under mine procedure.', 'Relocate/isolate work and engineer spark/heat containment and source ventilation.', 'Use mine hot-work authorization, trained roles, cylinder controls, and post-work fire checks.', 'Document area examination, combustibles, atmosphere/ventilation, extinguisher/fire watch, and post-work inspection.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.4600', summary: 'Extinguishing equipment for welding/cutting at surface M/NM mines.', evidence: ['welding/cutting task', 'combustible exposure', 'extinguishing equipment', 'fire controls'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.4600', summary: 'Extinguishing equipment for underground M/NM welding/cutting.', evidence: ['hot-work location', 'combustibles/atmosphere', 'extinguishing and ventilation controls'] }] },
  },
  {
    id: 'msha-noise-exposure', domain: 'noise_exposure', confidence: 'moderate',
    when: (s, c) => c.detected && s.noise && s.exposureUnknown,
    initiating: 'Crusher, screen, drill, or mobile-equipment noise may expose miners, but level, dose, and duration evidence are incomplete.',
    failure: 'Repeated sound energy can exceed protective capacity when source controls and hearing conservation are inadequate.',
    exposure: 'Miners near the source may receive full-shift or task-based noise dose.',
    consequences: 'Noise-induced hearing loss, tinnitus, communication interference, or missed warnings.',
    questions: ['What source, sound level/peak, task duration, frequency, distance, and number of miners apply?', 'What dosimetry/sound measurements and instrument calibration are available?', 'What engineering controls, hearing protection, audiometry, and hearing-conservation evidence exist?'],
    controls: actions('Limit time/distance and restrict unprotected exposure pending assessment.', 'Use suitable hearing protection and temporary operating/barrier controls based on qualified selection.', 'Reduce noise through enclosure, isolation, damping, maintenance, or quieter equipment/process.', 'Complete mine noise monitoring and hearing-conservation/training duties where triggered.', 'Document calibrated dosimetry/measurements, controls, protection selection, notification, and follow-up.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 62.110', summary: 'MSHA occupational noise action level across mining sectors.', evidence: ['mine noise source', 'dose/level and duration', 'monitoring basis', 'miner exposure'] }], underground_metal_nonmetal: [{ citation: '30 CFR 62.110', summary: 'MSHA occupational noise action level for underground M/NM miners.', evidence: ['source', 'dose/duration', 'monitoring and miner exposure'] }], surface_coal: [{ citation: '30 CFR 62.110', summary: 'MSHA occupational noise action level for surface coal.', evidence: ['noise dose and duration', 'miner exposure', 'monitoring'] }], underground_coal: [{ citation: '30 CFR 62.110', summary: 'MSHA occupational noise action level for underground coal.', evidence: ['noise dose and duration', 'miner exposure', 'monitoring'] }] },
  },
  {
    id: 'msha-dust-silica', domain: 'health_respiratory', confidence: 'moderate',
    when: (s, c) => isType(c, mnm) && s.dust && s.dustTask,
    initiating: 'A mine crushing, screening, drilling, cutting, or cleanup task may release respirable dust or silica.',
    failure: 'Dry generation and inadequate capture, wet methods, ventilation, or housekeeping can keep fine particles airborne.',
    exposure: 'Miners may inhale respirable dust depending on material, task, distance, duration, and controls.',
    consequences: 'Silicosis, chronic lung disease, lung cancer, irritation, or other dust-related illness; conclusions require exposure evidence.',
    questions: ['What material/silica content, task, duration, frequency, distance, and visible emissions apply?', 'What wet method, enclosure, local exhaust, cab filtration, ventilation, and housekeeping controls operate?', 'What exposure monitoring/objective data and respiratory-program evidence are available?'],
    controls: actions('Limit dust-generating work and remove unprotected miners until controls are verified.', 'Apply effective wet methods/source capture and controlled interim respiratory protection where required.', 'Engineer enclosure, collection, ventilation, wet suppression, and cab filtration for the source.', 'Maintain exposure monitoring, control plans, housekeeping, respiratory-program duties, and miner training.', 'Document material/task, controls, duration, monitoring results, respiratory basis, and qualified IH review.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 56.5002', summary: 'Surface M/NM surveys for dust, gas, mist, and fume control adequacy.', evidence: ['dust agent/material', 'task/duration', 'survey/monitoring', 'control performance'] }, { citation: '30 CFR 56.5005', summary: 'Surface M/NM control of harmful airborne contaminants.', evidence: ['airborne contaminant', 'feasible prevention/exhaust/dilution controls', 'exposure evidence'] }], underground_metal_nonmetal: [{ citation: '30 CFR 57.5002', summary: 'Underground M/NM airborne exposure monitoring.', evidence: ['agent/task', 'duration/frequency', 'monitoring', 'ventilation/control performance'] }, { citation: '30 CFR 57.5005', summary: 'Underground M/NM airborne-contaminant controls.', evidence: ['contaminant and exposure', 'ventilation/source controls', 'monitoring'] }] },
  },
  {
    id: 'msha-training-contractor', domain: 'training_procedure_gap', confidence: 'moderate',
    when: (s, c) => c.detected && (s.training || s.contractor || c.contractorContext) && s.uncertainControl,
    initiating: 'A miner, contractor, vendor, or service worker may perform or enter mine work without confirmed applicable training or hazard awareness.',
    failure: 'Missing task/site knowledge can leave mine-specific traffic, electrical, ground, equipment, restricted-area, and emergency hazards unrecognized.',
    exposure: 'The person may enter or perform a task before role, experience, mine type, frequency, and training obligations are established.',
    consequences: 'Increased likelihood of struck-by, caught-in, electrical, ground-control, or emergency-response injury.',
    questions: ['Is the person a miner, new miner, experienced miner, contractor miner, infrequent service worker, vendor, or visitor?', 'What mine type, assigned task, prior experience, frequency/duration, and supervision apply?', 'What new-miner, experienced-miner, task, annual, Part 48, or site-specific hazard-awareness records apply?'],
    controls: actions('Pause unsupervised mine exposure/task work until role and required training are verified.', 'Provide site-specific hazard awareness and experienced-miner/competent-person supervision as applicable.', 'Complete the applicable approved training and task qualification before independent work.', 'Maintain role determination, contractor coordination, task changes, refresher schedules, and certified records.', 'Document person classification, mine/training part, course/task content, instructor/competent person, date, and record.'),
    standards: { surface_metal_nonmetal: [{ citation: '30 CFR 46.7', summary: 'New task training for miners at covered Part 46 operations.', evidence: ['Part 46 mine coverage', 'miner status', 'new/changed task', 'training and competent-person practice'] }, { citation: '30 CFR 46.11', summary: 'Site-specific hazard awareness for applicable persons at covered mines.', evidence: ['person role/frequency', 'mine hazards', 'accompaniment', 'hazard-awareness evidence'] }], underground_metal_nonmetal: [{ citation: '30 CFR 48.7', summary: 'Training of miners assigned to new underground tasks.', evidence: ['Part 48 applicability', 'miner role', 'new task', 'training record'] }], surface_coal: [{ citation: '30 CFR 48.27', summary: 'Training for miners assigned to new tasks at surface coal mines.', evidence: ['surface coal/Part 48 applicability', 'miner role', 'new task and record'] }], underground_coal: [{ citation: '30 CFR 48.7', summary: 'Underground coal new-task training.', evidence: ['underground coal/Part 48 applicability', 'miner role', 'task and training record'] }] },
  },
  {
    id: 'msha-underground-ventilation-diesel', domain: 'ventilation', confidence: 'moderate',
    when: (s, c) => c.mineType === 'underground_metal_nonmetal' && (s.ventilation || s.diesel),
    initiating: 'Underground M/NM airflow or diesel exhaust conditions may allow contaminants to accumulate in a heading or work area.',
    failure: 'Insufficient airflow, damaged ventilation controls, poorly maintained diesel equipment, or high utilization can raise gas, fume, or DPM exposure.',
    exposure: 'Miners may inhale diesel particulate, carbon monoxide, nitrogen dioxide, fumes, or oxygen-deficient air depending on measurements.',
    consequences: 'Acute irritation/toxicity, impaired escape, chronic diesel-particulate health effects, or asphyxiation; conclusions require monitoring.',
    questions: ['What heading/area, airflow direction/quantity, fan/tubing condition, diesel fleet, duty cycle, and symptoms apply?', 'What gas and DPM monitoring results, calibration, ventilation plan, and equipment maintenance records are available?', 'Are miners able to withdraw and is alternate ventilation or equipment restriction available?'],
    controls: actions('Remove miners from suspected unsafe air and restrict diesel operation pending measurements.', 'Restore ventilation and limit equipment under qualified mine ventilation/IH review.', 'Engineer ventilation, diesel emissions controls, fleet maintenance, traffic/duty-cycle limits, or lower-emission equipment.', 'Maintain the ventilation plan, DPM monitoring, equipment maintenance, miner notification, and exposure training.', 'Document airflow/gas/DPM results, instrument checks, ventilation correction, equipment maintenance, and qualified review.'),
    standards: { underground_metal_nonmetal: [{ citation: '30 CFR 57.8520', summary: 'Underground M/NM written ventilation plan.', evidence: ['underground area and ventilation system', 'plan provisions/revisions', 'airflow and contaminant conditions'] }, { citation: '30 CFR 57.5060', summary: 'Underground M/NM diesel particulate matter exposure limit and controls.', evidence: ['DPM exposure basis', 'diesel equipment/use', 'monitoring', 'engineering/work-practice controls'] }, { citation: '30 CFR 57.5071', summary: 'Underground M/NM DPM exposure monitoring.', evidence: ['personal full-shift monitoring', 'sampling method', 'results and corrective actions'] }] },
  },
  {
    id: 'msha-underground-escapeway', domain: 'emergency_preparedness', confidence: 'moderate',
    when: (s, c) => c.mineType === 'underground_metal_nonmetal' && s.escapeway && s.blockedUnclear,
    initiating: 'An underground M/NM escapeway, refuge, or escape route is obstructed, degraded, or not verified.',
    failure: 'Fire, ground fall, inundation, ventilation loss, or another emergency may make the route unavailable or delay travel/refuge.',
    exposure: 'Underground miners may be unable to reach the surface or a suitable refuge within the planned route/time.',
    consequences: 'Entrapment, smoke/gas exposure, delayed rescue, or multiple-fatality escalation.',
    questions: ['Which escapeway/refuge is affected and is the second separate route maintained and travelable?', 'What obstruction, marking, communication, self-rescue, refuge, and check-in/out conditions apply?', 'What examination and evacuation-plan evidence confirms availability?'],
    controls: actions('Remove the obstruction or withdraw affected miners if required escape capability is unavailable.', 'Control entry and provide verified alternate escape/refuge arrangements under mine emergency planning.', 'Restore and maintain separate escapeways, refuges, markings, communication, and route infrastructure.', 'Maintain examinations, escape/evacuation plans, drills, self-rescue readiness, and miner instruction.', 'Walk/document routes, obstructions, refuge/communication, examination, and responsible-person verification.'),
    standards: { underground_metal_nonmetal: [{ citation: '30 CFR 57.11050', summary: 'Underground M/NM escapeways and refuges.', evidence: ['mine level/workplace', 'separate escapeways', 'travelability', 'refuge need/location'] }, { citation: '30 CFR 57.11053', summary: 'Underground M/NM escape and evacuation plans.', evidence: ['plan/route applicability', 'hazards and miners', 'communication/drill evidence'] }] },
  },
  {
    id: 'msha-coal-belt', domain: 'fire_protection', confidence: 'moderate',
    when: (s, c) => c.mineType === 'underground_coal' && s.coalBelt && (s.coalFire || s.uncertainControl),
    initiating: 'An underground coal belt conveyor presents guarding, component-maintenance, combustible-accumulation, or fire-detection uncertainty.',
    failure: 'Moving parts, belt slippage, hot bearings, friction, or combustible accumulations can cause contact injury or initiate/propagate fire.',
    exposure: 'Miners in belt entries or nearby escapeways may encounter moving equipment, smoke, heat, or impaired escape.',
    consequences: 'Caught-in injury, mine fire, smoke/toxic exposure, evacuation impairment, or multiple-fatality escalation.',
    questions: ['What belt component, guarding, slippage/bearing condition, combustible accumulation, fire detection/suppression, and examination evidence apply?', 'Is the belt entry part of or adjacent to an escapeway and what airflow/CO monitoring is present?', 'Which coal-specific safeguard, approved plan, and examination provisions govern this belt?'],
    controls: actions('Stop the affected belt or exclude miners where guarding/fire conditions are unsafe.', 'Remove accumulations, control ignition, barricade moving parts, and establish fire watch/monitoring under mine procedure.', 'Repair guarding/components and restore designed detection, suppression, ventilation, and cleanup controls.', 'Maintain belt examinations, fire-response readiness, approved-plan controls, and miner training.', 'Document belt condition, guarding, accumulations, sensors/suppression, airflow, examination, and repair.'),
    standards: { underground_coal: [{ citation: '30 CFR 75.1722(a)', summary: 'Guarding of moving machine parts in underground coal mines.', evidence: ['coal mine context', 'moving component', 'miner access', 'guard condition'] }, { citation: '30 CFR 75.1731(a)', summary: 'Maintenance of belt conveyor components in underground coal mines.', evidence: ['belt component condition', 'examination/maintenance', 'fire or mechanical hazard'] }] },
  },
  {
    id: 'msha-coal-ventilation', domain: 'ventilation', confidence: 'moderate',
    when: (s, c) => c.mineType === 'underground_coal' && (s.methane || s.ventilation),
    initiating: 'Underground coal methane or ventilation-control conditions are reported without complete airflow, gas, plan, and examination evidence.',
    failure: 'Damaged or ineffective controls can reduce/d redirect airflow and permit methane, dust, smoke, or harmful gases to accumulate.',
    exposure: 'Miners may enter a hazardous atmosphere or ignition/fire pathway depending on measurements and approved-plan conditions.',
    consequences: 'Explosion, fire, asphyxiation, toxic exposure, or impaired escape; applicability requires coal-specific qualified review.',
    questions: ['What methane/airflow readings, locations, instrument checks, and trend are available?', 'Which ventilation control/plan provision is affected and what production/equipment state exists?', 'What certified examinations and withdrawal/correction actions occurred?'],
    controls: actions('Withdraw miners and stop affected activity if safe atmospheric conditions are not verified.', 'Restore ventilation controls and perform qualified gas/airflow checks before re-entry.', 'Repair/engineer approved ventilation and monitoring controls for the mine plan and mining system.', 'Maintain certified examinations, plan compliance, instrument checks, records, and miner response training.', 'Document readings, instrument calibration, control condition, examination, correction, and re-entry authorization.'),
    standards: { underground_coal: [{ citation: '30 CFR 75.333', summary: 'Ventilation controls in underground coal mines.', evidence: ['underground coal context', 'control type/location', 'condition and airflow effect', 'approved plan/examination'] }] },
  },
  {
    id: 'msha-coal-escapeway', domain: 'emergency_preparedness', confidence: 'moderate',
    when: (s, c) => c.mineType === 'underground_coal' && s.escapeway && s.blockedUnclear,
    initiating: 'An underground coal escapeway is obstructed, unclear, or not confirmed travelable.',
    failure: 'A fire, explosion, ventilation event, or ground condition may leave miners without two effective escape routes.',
    exposure: 'Miners underground may be delayed or unable to reach the surface during an emergency.',
    consequences: 'Entrapment, smoke/gas exposure, delayed rescue, or multiple fatalities.',
    questions: ['Is the mine bituminous/lignite or anthracite and which designated escapeway is affected?', 'Are two distinct routes travelable, marked, separated, examined, and supported by lifelines/self-rescue?', 'What approved plan and certified examination record applies?'],
    controls: actions('Remove the obstruction or withdraw miners if designated escape capability is unavailable.', 'Control entry and provide verified alternate emergency arrangements under mine management.', 'Restore designated escapeways, separation, markings/lifelines, ground support, and communication.', 'Maintain certified examinations, drills, self-rescue readiness, and escapeway training.', 'Document route walk, condition, marking/separation, examination, correction, and reopening.'),
    standards: { underground_coal: [{ citation: '30 CFR 75.380', summary: 'Escapeways for underground bituminous and lignite coal mines.', evidence: ['coal type', 'designated routes', 'travelability/separation', 'marking/examination'] }] },
  },
  {
    id: 'msha-coal-mapping-uncertain', domain: 'industrial_hygiene', confidence: 'moderate',
    when: (s, c) => isType(c, coal) && (s.dust || s.permissibility),
    initiating: 'A coal-mine dust or electrical-permissibility concern is present, but the current inspection mapping lacks enough coal-specific facts for a defensible citation.',
    failure: 'Dust exposure/accumulation or nonpermissible electrical equipment could contribute to chronic exposure, ignition, fire, or explosion depending on mine type and approved equipment/plan facts.',
    exposure: 'Coal miners may inhale respirable dust or encounter an ignition source in a hazardous location.',
    consequences: 'Pneumoconiosis/respiratory disease, fire, explosion, burns, or fatal mine emergency.',
    questions: ['Is this surface or underground coal, and what dust standard/program or equipment approval/permissibility requirement applies?', 'What sampling, mine plan, equipment approval plate, location classification, methane, and examination evidence exist?', 'Which coal-specific qualified reviewer should confirm the applicable Part 70/71/75/77 provision?'],
    controls: actions('Restrict the affected exposure/equipment until coal-specific conditions are evaluated.', 'Use verified dust controls or approved/permissible equipment under qualified mine review.', 'Engineer dust capture/ventilation or replace equipment with approved systems suited to the mine location.', 'Maintain coal-specific sampling/plan, equipment approval, examination, and miner training programs.', 'Document mine type, location, dust/atmospheric data, equipment approval, examinations, and qualified citation review.'),
    standards: {},
    limitation: 'Coal dust/permissibility citation matching is incomplete; do not substitute Part 56/57 or OSHA citations without coal-specific applicability review.',
  },
  {
    id: 'msha-explosives-boundary', domain: 'training_procedure_gap', confidence: 'moderate',
    when: (s, c) => c.detected && s.explosives,
    initiating: 'A mine blasting or explosives context is present and requires restricted, qualified-person review.',
    failure: 'Inadequate exclusion, communication, storage, authorization, or post-blast status control can expose miners; operational details are intentionally not inferred.',
    exposure: 'Miners or contractors may enter a blast/explosives hazard area without verified authorization and mine procedures.',
    consequences: 'Blast trauma, flyrock, fire, toxic fumes, misfire exposure, or fatal injury.',
    questions: ['What mine type, authorized role, blast-area status, exclusion, warning, communication, and mine procedure apply?', 'Is this storage, transport, pre-blast, post-blast, or suspected misfire context?', 'Has the area been secured and referred to the mine’s authorized blasting personnel?'],
    controls: actions('Keep all unauthorized persons out and notify mine management/authorized blasting personnel.', 'Maintain exclusion and warning controls under the mine’s approved procedures.', 'Have authorized specialists correct storage/site/control deficiencies without operational guidance from HazLenz.', 'Verify role authorization, training, contractor coordination, and approved mine procedures.', 'Document area security, notifications, authorized review, status release, and training records.'),
    standards: {},
    limitation: 'Explosives/blasting citation selection and operations require authorized mine specialists; HazLenz provides no operational blasting instructions.',
  },
];

export class MshaInspectionIntelligenceService {
  analyze(textValue: string, context: MineContextAssessment): { rules: InspectionIntelligenceRule[]; citationLimitations: string[] } {
    if (!context.detected) return { rules: [], citationLimitations: [] };
    const text = String(textValue || '').toLowerCase();
    const signals = buildSignals(text);
    const matched = definitions.filter((definition) => definition.when(signals, context));
    const incompleteMatched = matched.filter((definition) => (definition.standards?.[context.mineType] || []).length === 0);
    return {
      rules: matched.map((definition) => ({
        id: definition.id,
        domain: definition.domain,
        confidence: definition.confidence,
        matches: [/.*/],
        initiating: definition.initiating,
        failure: definition.failure,
        exposure: definition.exposure,
        consequences: definition.consequences,
        related: definition.related,
        questions: definition.questions,
        controls: definition.controls,
        standards: { msha: definition.standards?.[context.mineType] || [] },
      })),
      citationLimitations: [
        ...matched.flatMap((definition) => definition.limitation ? [definition.limitation] : []),
        ...(context.mineType === 'surface_coal' && incompleteMatched.length > 0
          ? ['Surface coal citation mapping is incomplete for one or more matched hazards; do not substitute Part 56, 57, or OSHA citations.']
          : []),
      ],
    };
  }
}
