const { chromium, request } = require('/Users/mckinley/Desktop/Safety_InSite/frontend-next/node_modules/playwright');
const fs=require('fs'); const backend='http://127.0.0.1:4238', frontend='http://localhost:3009';
const email='recon.owner@example.test', password='Recon!123'; const chrome='/Users/mckinley/Library/Caches/ms-playwright/chromium-1223/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
const cases=[
 {key:'removal',title:'Reconciliation Removal',initial:'The operating conveyor has an exposed nip point and the adjacent electrical cabinet has energized conductors exposed. Workers clear jams while the floor is oily.',revised:'The conveyor guard is installed and verified before inspection. The adjacent electrical cabinet remains open with energized conductors exposed. Workers still cross an oily floor.'},
 {key:'addition',title:'Reconciliation Addition',initial:'A forklift reverses through a congested aisle without a clear pedestrian separation.',revised:'A forklift reverses through a congested aisle without pedestrian separation, and a nearby conveyor has an exposed moving nip point.'},
 {key:'material-change',title:'Reconciliation Material Change',initial:'A damaged extension ladder is being used on an uneven loading dock without secured feet.',revised:'A powered industrial truck is reversing through the loading dock aisle with pedestrians nearby and no effective separation.'},
];
async function j(r){return r.json().catch(()=>({}))}
async function finish(page, id, events){let history=[];for(let i=0;i<12;i++){const body=await page.locator('body').innerText();history.push({i,body:body.slice(-900),buttons:await page.getByRole('button').allTextContents()});if(/Corrective action/.test(body)){await page.getByRole('button',{name:/Complete inspection and generate report/i}).click();await page.waitForTimeout(1200);break;}const req=page.locator('article').filter({hasText:'Review: required'}).getByRole('button',{name:'Review this finding'});if(await req.count()===0)break;await req.first().click();await page.waitForTimeout(100);if(await page.getByRole('button',{name:/Continue to risk review/i}).count()){await page.getByRole('button',{name:/Continue to risk review/i}).click();await page.waitForTimeout(100);await page.getByRole('button',{name:/Confirm risk and finalize finding/i}).click();await page.waitForTimeout(700);}}return history;}
(async()=>{const api=await request.newContext();const auth=await j(await api.post(backend+'/auth/login',{data:{email,password}}));const h={Authorization:`Bearer ${auth.token}`,'Content-Type':'application/json'};let sr=await api.get(backend+'/sites?limit=100',{headers:h});let sites=await j(sr);let site=sites.data?.[0]||await j(await api.post(backend+'/sites',{headers:h,data:{name:'Reconciliation Site'}}));const browser=await chromium.launch({headless:true,executablePath:chrome});const out=[];
for(const cse of cases){const ir=await api.post(backend+'/inspections',{headers:h,data:{siteId:site.id,title:cse.title}});const inspection=await j(ir);const page=await (await browser.newContext({viewport:{width:1440,height:1000}})).newPage();const events=[];page.on('response',r=>{if(/inspections|safescope|reports|actions|tasks/.test(r.url()))events.push({url:r.url(),status:r.status()})});await page.goto(frontend+'/login');await page.evaluate(({token,user,id,siteId,title})=>{localStorage.setItem('sentinel_auth_token',token);localStorage.setItem('sentinel_auth_user',JSON.stringify(user));localStorage.setItem('sentinel_selected_inspection_context',JSON.stringify({persistedInspectionId:id,persistedSiteId:siteId,persistenceState:'saved',inspectionType:'guided_inspection',inspectionTitle:title,workflowDepth:'guided'}));},{token:auth.token,user:auth.user,id:inspection.id,siteId:site.id,title:cse.title});await page.goto(frontend+'/inspection-workspace');await page.getByLabel('What did you observe?').fill(cse.initial);await page.getByLabel('Location or area').fill('Production area');await page.getByLabel('Work activity').fill('Inspection');await page.getByRole('button',{name:/Save and review with HazLenz AI/i}).click();await page.waitForTimeout(5000);const before=await j(await api.get(backend+'/inspections/'+inspection.id,{headers:h}));const baselineFindings=before.findings||[];const baselineAnalysis=before.observations?.[0]?.analyses?.find(a=>a.status==='current');const baselineHistory=await finish(page,inspection.id,events);const baselineCompleted=await j(await api.get(backend+'/inspections/'+inspection.id,{headers:h}));
 const classify=await api.post(backend+'/safescope-v2/classify',{headers:h,data:{text:cse.revised,scopes:['all'],structuredObservation:{narrative:cse.revised,evidenceSource:['direct_observation'],unknownFacts:[],unresolvedContradictions:[],userConfirmedFacts:[]}}});const revisedResult=await j(classify);const obsId=baselineCompleted.observations?.[0]?.id;const saved=await api.post(backend+`/inspections/observations/${obsId}/analyses`,{headers:h,data:{engineVersion:'hazlenz-production',resultSnapshot:revisedResult,idempotencyKey:`reconcile-${cse.key}-v2`,requestVersion:2}});const savedBody=await j(saved);const after=await j(await api.get(backend+'/inspections/'+inspection.id,{headers:h}));
 const repeat=await api.post(backend+`/inspections/observations/${obsId}/analyses`,{headers:h,data:{engineVersion:'hazlenz-production',resultSnapshot:revisedResult,idempotencyKey:`reconcile-${cse.key}-v3`,requestVersion:3}});const afterRepeat=await j(await api.get(backend+'/inspections/'+inspection.id,{headers:h}));
 out.push({key:cse.key,inspectionId:inspection.id,observationId:obsId,initial:cse.initial,revised:cse.revised,baseline:{analysisId:baselineAnalysis?.id,findings:baselineFindings.map(f=>({id:f.id,key:f.hazardKey,status:f.status,review:f.finalReviewId})),status:baselineCompleted.status,history:baselineHistory},reanalysis:{http:saved.status,analysisId:savedBody.id,findings:(after.findings||[]).map(f=>({id:f.id,key:f.hazardKey,status:f.status,review:f.finalReviewId,originatingAnalysisId:f.originatingAnalysisId})),analyses:after.observations?.[0]?.analyses?.map(a=>({id:a.id,version:a.requestVersion,status:a.status})),repeatHttp:repeat.status,repeatFindings:(afterRepeat.findings||[]).map(f=>({id:f.id,key:f.hazardKey,status:f.status,review:f.finalReviewId}))},events});await page.close();}
fs.writeFileSync(__dirname+'/RECONCILIATION_RESULTS.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out.map(x=>({key:x.key,id:x.inspectionId,baseline:x.baseline.findings.map(f=>f.key),after:x.reanalysis.findings,repeat:x.reanalysis.repeatFindings})),null,2));await browser.close();await api.dispose();})();
