import { EvidenceGapQuestionRecord } from './evidence-gap-question.types';

export const EVIDENCE_GAP_QUESTION_REGISTRY: EvidenceGapQuestionRecord[] = [
  {
    id: 'gap-conveyor-loto',
    scenarioFamilyId: 'conveyor-cleanup',
    hazardDomain: 'machine_guarding',
    evidenceGapId: 'LOTO status',
    question: 'Was a verified Lockout/Tagout (LOTO) procedure applied before cleaning?',
    reasonForQuestion: 'Conveyor cleaning near moving parts is high-risk; verifying energy isolation is critical.',
    relatedMechanismOfInjury: 'rotating_equipment_nip_point',
    relatedExposurePathway: 'worker near belt',
    relatedMissingControl: 'no LOTO',
    relatedStandardFamilyCandidate: 'candidate-machine-guarding',
    priority: 'critical',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['photo of lock', 'tag details'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-stairway-handrail',
    scenarioFamilyId: 'unguarded-conveyor-pulley',
    hazardDomain: 'machine_guarding',
    evidenceGapId: 'guard presence',
    question: 'Is there a physical guard present between the worker and the nip point?',
    reasonForQuestion: 'Nip points require physical guarding to prevent entanglement.',
    relatedMechanismOfInjury: 'rotating_equipment_nip_point',
    relatedExposurePathway: 'access to area',
    relatedMissingControl: 'guarding',
    relatedStandardFamilyCandidate: 'candidate-machine-guarding',
    priority: 'high',
    answerType: 'photo',
    examplesOfUsefulEvidence: ['photo of guard'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-door-sensor',
    scenarioFamilyId: 'powered-door-malfunction',
    hazardDomain: 'machine_guarding',
    evidenceGapId: 'sensor status',
    question: 'Have the automatic door sensors been tested to ensure they detect and reverse for obstructions?',
    reasonForQuestion: 'Powered doors must automatically reverse to prevent crush injuries.',
    relatedMechanismOfInjury: 'crush_point',
    relatedExposurePathway: 'pedestrian traffic',
    relatedMissingControl: 'sensor failure',
    relatedStandardFamilyCandidate: 'candidate-machine-guarding',
    priority: 'high',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['test log'],
    confidenceImpact: 'medium',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-extinguisher-clearance',
    scenarioFamilyId: 'fire-extinguisher-ambiguity',
    hazardDomain: 'fire_protection',
    evidenceGapId: 'clearance measurements',
    question: 'Is there at least 3 feet of clear access to the fire extinguisher?',
    reasonForQuestion: 'Extinguishers must be immediately accessible for emergency use.',
    relatedMechanismOfInjury: 'fire_extinguisher_access_failure',
    relatedExposurePathway: 'emergency access',
    relatedMissingControl: 'clearance',
    relatedStandardFamilyCandidate: 'candidate-fire-protection',
    priority: 'moderate',
    answerType: 'text',
    examplesOfUsefulEvidence: ['clearance measurements'],
    confidenceImpact: 'medium',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-energized-energy-state',
    scenarioFamilyId: 'energized-servicing',
    hazardDomain: 'machine_guarding',
    evidenceGapId: 'energy state',
    question: 'Is all stored and potential energy controlled, even if the main power is off?',
    reasonForQuestion: 'Energized equipment can restart or move due to stored energy.',
    relatedMechanismOfInjury: 'unexpected_startup',
    relatedExposurePathway: 'repairman',
    relatedMissingControl: 'LOTO',
    relatedStandardFamilyCandidate: 'candidate-loto',
    priority: 'critical',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['LOTO audit'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-mobile-pedestrian-separation',
    scenarioFamilyId: 'mobile-pedestrian',
    hazardDomain: 'mobile_equipment',
    evidenceGapId: 'separation measures',
    question: 'Are there physical barriers or designated pedestrian walkways fully separating foot traffic from equipment routes?',
    reasonForQuestion: 'Physical separation is the primary control for pedestrian/equipment interaction.',
    relatedMechanismOfInjury: 'pedestrian_strike',
    relatedExposurePathway: 'worker on foot',
    relatedMissingControl: 'separation',
    relatedStandardFamilyCandidate: 'candidate-mobile-equipment',
    priority: 'high',
    answerType: 'photo',
    examplesOfUsefulEvidence: ['photo of barriers'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-elevated-fall-height',
    scenarioFamilyId: 'elevated-fall',
    hazardDomain: 'fall_protection',
    evidenceGapId: 'fall height',
    question: 'What is the maximum potential fall height from the work area?',
    reasonForQuestion: 'Fall protection requirements depend on specific elevation heights.',
    relatedMechanismOfInjury: 'fall_from_height',
    relatedExposurePathway: 'worker',
    relatedMissingControl: 'guardrail',
    relatedStandardFamilyCandidate: 'candidate-fall-protection',
    priority: 'high',
    answerType: 'text',
    examplesOfUsefulEvidence: ['height measurement'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-chemical-identity',
    scenarioFamilyId: 'chemical-exposure-unclear',
    hazardDomain: 'hazcom',
    evidenceGapId: 'chemical identity',
    question: 'What is the specific chemical substance, and has an SDS been verified for it?',
    reasonForQuestion: 'Safe handling and PPE requirements depend entirely on chemical identity.',
    relatedMechanismOfInjury: 'chemical_exposure',
    relatedExposurePathway: 'worker',
    relatedMissingControl: 'labeling',
    relatedStandardFamilyCandidate: 'candidate-hazcom',
    priority: 'moderate',
    answerType: 'text',
    examplesOfUsefulEvidence: ['SDS document', 'container label'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-electrical-equipment-state',
    scenarioFamilyId: 'electrical-damage',
    hazardDomain: 'electrical',
    evidenceGapId: 'equipment state',
    question: 'Has this equipment been de-energized and tagged out for inspection?',
    reasonForQuestion: 'Inspecting damaged electrical equipment while energized is extremely hazardous.',
    relatedMechanismOfInjury: 'shock',
    relatedExposurePathway: 'user',
    relatedMissingControl: 'insulation',
    relatedStandardFamilyCandidate: 'candidate-electrical',
    priority: 'high',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['LOTO status report'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-emergency-egress-clearance',
    scenarioFamilyId: 'blocked-emergency-access',
    hazardDomain: 'emergency_preparedness',
    evidenceGapId: 'clearance status',
    question: 'Is the exit route entirely clear of all obstructions, including temporary storage?',
    reasonForQuestion: 'Emergency routes must be free of obstructions at all times.',
    relatedMechanismOfInjury: 'egress_blockage',
    relatedExposurePathway: 'occupants',
    relatedMissingControl: 'clearance',
    relatedStandardFamilyCandidate: 'candidate-emergency-preparedness',
    priority: 'moderate',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['photo of exit path'],
    confidenceImpact: 'medium',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  }
];
