import { EvidenceGapQuestionRecord } from './evidence-gap-question.types';

export const EVIDENCE_GAP_QUESTION_REGISTRY: EvidenceGapQuestionRecord[] = [
  {
    id: 'gap-conveyor-loto',
    scenarioFamilyId: 'conveyor-cleanup',
    hazardDomain: 'machine_guarding',
    evidenceGapId: 'LOTO status',
    question: 'Was a verified Lockout/Tagout (LOTO) procedure applied before cleaning?',
    reasonForQuestion: 'Conveyor cleaning near moving parts is high-risk; verifying energy isolation is critical.',
    relatedMechanismOfInjury: 'rotating_equipment_nip_point',
    relatedExposurePathway: 'worker near belt',
    relatedMissingControl: 'no LOTO',
    relatedStandardFamilyCandidate: 'candidate-machine-guarding',
    priority: 'critical',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['photo of lock', 'tag details'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-stairway-handrail',
    scenarioFamilyId: 'unguarded-conveyor-pulley',
    hazardDomain: 'machine_guarding',
    evidenceGapId: 'guard presence',
    question: 'Is there a physical guard present between the worker and the nip point?',
    reasonForQuestion: 'Nip points require physical guarding to prevent entanglement.',
    relatedMechanismOfInjury: 'rotating_equipment_nip_point',
    relatedExposurePathway: 'access to area',
    relatedMissingControl: 'guarding',
    relatedStandardFamilyCandidate: 'candidate-machine-guarding',
    priority: 'high',
    answerType: 'photo',
    examplesOfUsefulEvidence: ['photo of guard'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-door-sensor',
    scenarioFamilyId: 'powered-door-malfunction',
    hazardDomain: 'machine_guarding',
    evidenceGapId: 'sensor status',
    question: 'Have the automatic door sensors been tested to ensure they detect and reverse for obstructions?',
    reasonForQuestion: 'Powered doors must automatically reverse to prevent crush injuries.',
    relatedMechanismOfInjury: 'crush_point',
    relatedExposurePathway: 'pedestrian traffic',
    relatedMissingControl: 'sensor failure',
    relatedStandardFamilyCandidate: 'candidate-machine-guarding',
    priority: 'high',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['test log'],
    confidenceImpact: 'medium',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-extinguisher-clearance',
    scenarioFamilyId: 'fire-extinguisher-ambiguity',
    hazardDomain: 'fire_protection',
    evidenceGapId: 'clearance measurements',
    question: 'Is there at least 3 feet of clear access to the fire extinguisher?',
    reasonForQuestion: 'Extinguishers must be immediately accessible for emergency use.',
    relatedMechanismOfInjury: 'fire_extinguisher_access_failure',
    relatedExposurePathway: 'emergency access',
    relatedMissingControl: 'clearance',
    relatedStandardFamilyCandidate: 'candidate-fire-protection',
    priority: 'moderate',
    answerType: 'text',
    examplesOfUsefulEvidence: ['clearance measurements'],
    confidenceImpact: 'medium',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-energized-energy-state',
    scenarioFamilyId: 'energized-servicing',
    hazardDomain: 'machine_guarding',
    evidenceGapId: 'energy state',
    question: 'Is all stored and potential energy controlled, even if the main power is off?',
    reasonForQuestion: 'Energized equipment can restart or move due to stored energy.',
    relatedMechanismOfInjury: 'unexpected_startup',
    relatedExposurePathway: 'repairman',
    relatedMissingControl: 'LOTO',
    relatedStandardFamilyCandidate: 'candidate-loto',
    priority: 'critical',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['LOTO audit'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-mobile-pedestrian-separation',
    scenarioFamilyId: 'mobile-pedestrian',
    hazardDomain: 'mobile_equipment',
    evidenceGapId: 'separation measures',
    question: 'Are there physical barriers or designated pedestrian walkways fully separating foot traffic from equipment routes?',
    reasonForQuestion: 'Physical separation is the primary control for pedestrian/equipment interaction.',
    relatedMechanismOfInjury: 'pedestrian_strike',
    relatedExposurePathway: 'worker on foot',
    relatedMissingControl: 'separation',
    relatedStandardFamilyCandidate: 'candidate-mobile-equipment',
    priority: 'high',
    answerType: 'photo',
    examplesOfUsefulEvidence: ['photo of barriers'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-elevated-fall-height',
    scenarioFamilyId: 'elevated-fall',
    hazardDomain: 'fall_protection',
    evidenceGapId: 'fall height',
    question: 'What is the maximum potential fall height from the work area?',
    reasonForQuestion: 'Fall protection requirements depend on specific elevation heights.',
    relatedMechanismOfInjury: 'fall_from_height',
    relatedExposurePathway: 'worker',
    relatedMissingControl: 'guardrail',
    relatedStandardFamilyCandidate: 'candidate-fall-protection',
    priority: 'high',
    answerType: 'text',
    examplesOfUsefulEvidence: ['height measurement'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-chemical-identity',
    scenarioFamilyId: 'chemical-exposure-unclear',
    hazardDomain: 'hazcom',
    evidenceGapId: 'chemical identity',
    question: 'What is the specific chemical substance, and has an SDS been verified for it?',
    reasonForQuestion: 'Safe handling and PPE requirements depend entirely on chemical identity.',
    relatedMechanismOfInjury: 'chemical_exposure',
    relatedExposurePathway: 'worker',
    relatedMissingControl: 'labeling',
    relatedStandardFamilyCandidate: 'candidate-hazcom',
    priority: 'moderate',
    answerType: 'text',
    examplesOfUsefulEvidence: ['SDS document', 'container label'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-electrical-equipment-state',
    scenarioFamilyId: 'electrical-damage',
    hazardDomain: 'electrical',
    evidenceGapId: 'equipment state',
    question: 'Has this equipment been de-energized and tagged out for inspection?',
    reasonForQuestion: 'Inspecting damaged electrical equipment while energized is extremely hazardous.',
    relatedMechanismOfInjury: 'shock',
    relatedExposurePathway: 'user',
    relatedMissingControl: 'insulation',
    relatedStandardFamilyCandidate: 'candidate-electrical',
    priority: 'high',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['LOTO status report'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-emergency-egress-clearance',
    scenarioFamilyId: 'blocked-emergency-access',
    hazardDomain: 'emergency_preparedness',
    evidenceGapId: 'clearance status',
    question: 'Is the exit route entirely clear of all obstructions, including temporary storage?',
    reasonForQuestion: 'Emergency routes must be free of obstructions at all times.',
    relatedMechanismOfInjury: 'egress_blockage',
    relatedExposurePathway: 'occupants',
    relatedMissingControl: 'clearance',
    relatedStandardFamilyCandidate: 'candidate-emergency-preparedness',
    priority: 'moderate',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['photo of exit path'],
    confidenceImpact: 'medium',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-crane-rigging-cert',
    scenarioFamilyId: 'damaged_rigging_or_wrong_hardware',
    hazardDomain: 'cranes_rigging_hoisting',
    evidenceGapId: 'rigging certification',
    question: 'Is the rigging certified for this load and application?',
    reasonForQuestion: 'Rigging must be rated and certified to ensure safe lifting.',
    relatedMechanismOfInjury: 'rigging_failure',
    relatedExposurePathway: 'worker near rigging',
    relatedMissingControl: 'insufficient inspection',
    relatedStandardFamilyCandidate: 'candidate-cranes-rigging',
    priority: 'critical',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['certification tag'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-crane-ground-capacity',
    scenarioFamilyId: 'crane_outrigger_ground_stability',
    hazardDomain: 'cranes_rigging_hoisting',
    evidenceGapId: 'ground bearing capacity',
    question: 'Has the ground bearing capacity been verified for the crane load?',
    reasonForQuestion: 'Crane tip-over is a major hazard when outriggers are not properly supported.',
    relatedMechanismOfInjury: 'crane_tip_over',
    relatedExposurePathway: 'crane operator',
    relatedMissingControl: 'ground support',
    relatedStandardFamilyCandidate: 'candidate-cranes-rigging',
    priority: 'critical',
    answerType: 'text',
    examplesOfUsefulEvidence: ['ground analysis report'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-crane-hoist-limit-test',
    scenarioFamilyId: 'hoist_limit_or_load_control_gap',
    hazardDomain: 'cranes_rigging_hoisting',
    evidenceGapId: 'switch test status',
    question: 'Have the hoist limit switches been tested and verified as operational?',
    reasonForQuestion: 'Limit switches prevent overtravel which can cause catastrophic failures.',
    relatedMechanismOfInjury: 'hoist_failure',
    relatedExposurePathway: 'operator',
    relatedMissingControl: 'limit switch',
    relatedStandardFamilyCandidate: 'candidate-cranes-rigging',
    priority: 'critical',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['test log'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-crane-exclusion-zone',
    scenarioFamilyId: 'suspended_load_line_of_fire',
    hazardDomain: 'cranes_rigging_hoisting',
    evidenceGapId: 'exclusion zone status',
    question: 'Is a clear exclusion zone established and maintained for the suspended load?',
    reasonForQuestion: 'Exclusion zones prevent struck-by injuries.',
    relatedMechanismOfInjury: 'struck_by_falling_object',
    relatedExposurePathway: 'employee position',
    relatedMissingControl: 'exclusion zone',
    relatedStandardFamilyCandidate: 'candidate-cranes-rigging',
    priority: 'high',
    answerType: 'photo',
    examplesOfUsefulEvidence: ['photo of barriers'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-blood-sharps-disposal',
    scenarioFamilyId: 'sharps_or_needle_exposure',
    hazardDomain: 'bloodborne_pathogens',
    evidenceGapId: 'disposal method',
    question: 'Are sharps being disposed of immediately into designated, puncture-resistant containers?',
    reasonForQuestion: 'Improper disposal of sharps is a major cause of needle-stick injuries.',
    relatedMechanismOfInjury: 'puncture',
    relatedExposurePathway: 'employee handling',
    relatedMissingControl: 'sharps_container',
    relatedStandardFamilyCandidate: 'candidate-bloodborne',
    priority: 'critical',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['container status'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-blood-cleanup-ppe',
    scenarioFamilyId: 'blood_or_body_fluid_cleanup',
    hazardDomain: 'bloodborne_pathogens',
    evidenceGapId: 'cleanup procedure',
    question: 'Is appropriate PPE being used for blood cleanup?',
    reasonForQuestion: 'Contact with blood poses infection risk.',
    relatedMechanismOfInjury: 'infection',
    relatedExposurePathway: 'cleanup_staff',
    relatedMissingControl: 'ppe',
    relatedStandardFamilyCandidate: 'candidate-bloodborne',
    priority: 'high',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['PPE verification'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-blood-sharps-container-full',
    scenarioFamilyId: 'contaminated_sharps_disposal_gap',
    hazardDomain: 'bloodborne_pathogens',
    evidenceGapId: 'disposal protocol',
    question: 'Is the sharps container managed before it becomes overfilled?',
    reasonForQuestion: 'Full containers increase puncture risk.',
    relatedMechanismOfInjury: 'puncture',
    relatedExposurePathway: 'staff_access',
    relatedMissingControl: 'proper_disposal',
    relatedStandardFamilyCandidate: 'candidate-bloodborne',
    priority: 'high',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['container status'],
    confidenceImpact: 'medium',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-ergo-repetitive-force',
    scenarioFamilyId: 'repetitive_force_posture_exposure',
    hazardDomain: 'ergonomics',
    evidenceGapId: 'ergonomic risk assessment',
    question: 'Has an ergonomic assessment been completed for this repetitive task?',
    reasonForQuestion: 'Ergonomic assessments identify and control musculoskeletal hazards.',
    relatedMechanismOfInjury: 'musculoskeletal_disorder',
    relatedExposurePathway: 'worker_posture',
    relatedMissingControl: 'ergonomic_tools',
    relatedStandardFamilyCandidate: 'candidate-ergonomics',
    priority: 'high',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['assessment report'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-ergo-lifting-aid',
    scenarioFamilyId: 'manual_material_handling_overexertion',
    hazardDomain: 'ergonomics',
    evidenceGapId: 'lifting aid availability',
    question: 'Are lifting aids available and utilized for heavy material handling?',
    reasonForQuestion: 'Lifting aids reduce the risk of overexertion.',
    relatedMechanismOfInjury: 'overexertion_strains',
    relatedExposurePathway: 'worker',
    relatedMissingControl: 'material_handling_aids',
    relatedStandardFamilyCandidate: 'candidate-ergonomics',
    priority: 'high',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['lifting aid check'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-ergo-workstation-layout',
    scenarioFamilyId: 'awkward_reach_workstation_design',
    hazardDomain: 'ergonomics',
    evidenceGapId: 'layout assessment',
    question: 'Is the workstation layout optimized to minimize awkward reaches?',
    reasonForQuestion: 'Poor layout increases strain and injury risk.',
    relatedMechanismOfInjury: 'musculoskeletal_disorder',
    relatedExposurePathway: 'worker_reach',
    relatedMissingControl: 'workstation_design',
    relatedStandardFamilyCandidate: 'candidate-ergonomics',
    priority: 'moderate',
    answerType: 'text',
    examplesOfUsefulEvidence: ['layout photo'],
    confidenceImpact: 'medium',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-ih-dust-suppression',
    scenarioFamilyId: 'respirable_dust_or_silica_exposure',
    hazardDomain: 'industrial_hygiene',
    evidenceGapId: 'exposure level',
    question: 'Has the airborne dust concentration been assessed or measured?',
    reasonForQuestion: 'Measuring dust levels ensures exposure controls are effective.',
    relatedMechanismOfInjury: 'respiratory_disease',
    relatedExposurePathway: 'worker_inhalation',
    relatedMissingControl: 'dust_suppression',
    relatedStandardFamilyCandidate: 'candidate-ih',
    priority: 'critical',
    answerType: 'text',
    examplesOfUsefulEvidence: ['dust measurement'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-ih-welding-ventilation',
    scenarioFamilyId: 'welding_fume_exposure',
    hazardDomain: 'industrial_hygiene',
    evidenceGapId: 'ventilation performance',
    question: 'Is localized exhaust ventilation effectively capturing welding fumes at the source?',
    reasonForQuestion: 'Fumes must be captured to prevent inhalation.',
    relatedMechanismOfInjury: 'respiratory_disease',
    relatedExposurePathway: 'welder_inhalation',
    relatedMissingControl: 'exhaust_ventilation',
    relatedStandardFamilyCandidate: 'candidate-ih',
    priority: 'high',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['ventilation test'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-ih-noise-survey',
    scenarioFamilyId: 'noise_exposure_uncertainty',
    hazardDomain: 'industrial_hygiene',
    evidenceGapId: 'noise assessment',
    question: 'Has a noise survey been conducted to determine the need for hearing protection?',
    reasonForQuestion: 'Noise surveys identify the required level of hearing protection.',
    relatedMechanismOfInjury: 'hearing_loss',
    relatedExposurePathway: 'worker_noise_exposure',
    relatedMissingControl: 'hearing_protection',
    relatedStandardFamilyCandidate: 'candidate-ih',
    priority: 'high',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['noise survey report'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-ih-heat-hydration',
    scenarioFamilyId: 'heat_stress_exposure',
    hazardDomain: 'industrial_hygiene',
    evidenceGapId: 'hydration access',
    question: 'Is adequate, cool drinking water readily available and accessible to all workers?',
    reasonForQuestion: 'Hydration is crucial for preventing heat stress.',
    relatedMechanismOfInjury: 'heat_stress',
    relatedExposurePathway: 'worker',
    relatedMissingControl: 'rest_breaks',
    relatedStandardFamilyCandidate: 'candidate-ih',
    priority: 'high',
    answerType: 'boolean',
    examplesOfUsefulEvidence: ['water station photo'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },

  {
    id: 'gap-p4-emergency-exit-readiness',
    scenarioFamilyId: 'emergency_exit_alarm_response_gap',
    hazardDomain: 'emergency_preparedness',
    evidenceGapId: 'emergency readiness',
    question: 'Is the exit route, alarm/lighting, and emergency equipment fully accessible and functional for the occupied area?',
    reasonForQuestion: 'Emergency response controls must be available before an emergency occurs; obstruction or failed warning systems can delay evacuation or response.',
    relatedMechanismOfInjury: 'delayed_egress',
    relatedExposurePathway: 'employees in occupied area',
    relatedMissingControl: 'clear exit route and emergency response readiness',
    relatedStandardFamilyCandidate: 'candidate-emergency-preparedness',
    priority: 'high',
    answerType: 'photo',
    examplesOfUsefulEvidence: ['exit route photo', 'alarm or light test record', 'emergency equipment access photo'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-p4-ppe-selection-use',
    scenarioFamilyId: 'ppe_selection_use_gap',
    hazardDomain: 'ppe',
    evidenceGapId: 'ppe hazard assessment',
    question: 'What hazard is present, and is the selected PPE correct, serviceable, and worn properly for that exposure?',
    reasonForQuestion: 'PPE only helps when matched to the hazard, maintained, and used correctly after feasible source controls are considered.',
    relatedMechanismOfInjury: 'exposure or injury due to missing or wrong PPE',
    relatedExposurePathway: 'employee performing task',
    relatedMissingControl: 'ppe selection and inspection',
    relatedStandardFamilyCandidate: 'candidate-ppe',
    priority: 'high',
    answerType: 'photo',
    examplesOfUsefulEvidence: ['task photo', 'PPE label/rating photo', 'PPE condition photo', 'hazard assessment note'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-p4-hazardous-materials-storage',
    scenarioFamilyId: 'hazardous_materials_storage_compatibility_gap',
    hazardDomain: 'hazardous_materials',
    evidenceGapId: 'storage compatibility and containment',
    question: 'What material is stored, and are labeling, compatibility, container condition, and secondary containment verified?',
    reasonForQuestion: 'Hazardous material controls depend on the material identity, compatibility, container integrity, and spill/fire exposure potential.',
    relatedMechanismOfInjury: 'chemical_exposure_or_fire',
    relatedExposurePathway: 'employees near storage or transfer area',
    relatedMissingControl: 'labeling, compatible storage, or containment',
    relatedStandardFamilyCandidate: 'candidate-hazardous-materials',
    priority: 'high',
    answerType: 'photo',
    examplesOfUsefulEvidence: ['container label photo', 'SDS reference', 'storage layout photo', 'containment photo'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-p4-health-respiratory-program',
    scenarioFamilyId: 'health_respiratory_program_gap',
    hazardDomain: 'health_respiratory',
    evidenceGapId: 'respiratory protection basis',
    question: 'What contaminant and exposure level are driving respirator use, and are respirator selection, fit test, training, and cartridge/filter controls verified?',
    reasonForQuestion: 'Respiratory protection must be selected from the contaminant and exposure basis and supported by program elements when required.',
    relatedMechanismOfInjury: 'inhalation_exposure',
    relatedExposurePathway: 'employee breathing zone',
    relatedMissingControl: 'respirator selection and program verification',
    relatedStandardFamilyCandidate: 'candidate-health-respiratory',
    priority: 'high',
    answerType: 'text',
    examplesOfUsefulEvidence: ['exposure assessment', 'respirator type photo', 'fit test record', 'cartridge selection note'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-p4-roof-rib-ground-control',
    scenarioFamilyId: 'roof_rib_highwall_loose_material_gap',
    hazardDomain: 'roof_rib_control',
    evidenceGapId: 'ground stability and exposure',
    question: 'Has the roof, rib, highwall, or loose material condition been examined, controlled, and kept clear of exposed workers?',
    reasonForQuestion: 'Loose or unstable ground can create struck-by, crush, or engulfment exposure if workers or equipment are positioned in the fall zone.',
    relatedMechanismOfInjury: 'struck_by_falling_material',
    relatedExposurePathway: 'worker or equipment below unstable ground',
    relatedMissingControl: 'ground examination, scaling, barricade, or support',
    relatedStandardFamilyCandidate: 'candidate-roof-rib-control',
    priority: 'critical',
    answerType: 'photo',
    examplesOfUsefulEvidence: ['ground condition photo', 'barricade photo', 'scaling record', 'qualified exam note'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-p4-fire-protection-readiness',
    scenarioFamilyId: 'fire_extinguisher_hot_work_readiness_gap',
    hazardDomain: 'fire_protection',
    evidenceGapId: 'fire protection readiness',
    question: 'Is fire protection equipment accessible/inspected, and are combustibles, ignition sources, permit controls, and fire watch needs addressed?',
    reasonForQuestion: 'Fire protection readiness depends on accessible equipment, controlled ignition/fuel sources, and appropriate hot-work controls.',
    relatedMechanismOfInjury: 'fire_or_explosion',
    relatedExposurePathway: 'employees performing or near hot work',
    relatedMissingControl: 'extinguisher access, inspection, fire watch, or combustible control',
    relatedStandardFamilyCandidate: 'candidate-fire-protection',
    priority: 'high',
    answerType: 'photo',
    examplesOfUsefulEvidence: ['extinguisher access photo', 'inspection tag photo', 'hot work permit', 'fire watch assignment'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  },
  {
    id: 'gap-p4-ventilation-airflow-control',
    scenarioFamilyId: 'ventilation_airflow_gap',
    hazardDomain: 'ventilation',
    evidenceGapId: 'airflow control verification',
    question: 'Is the ventilation control present, intact, operating, and adequate for the contaminant, atmosphere, or mine air-control need?',
    reasonForQuestion: 'Ventilation findings require evidence that airflow, capture, direction, and control condition are adequate for the hazard being controlled.',
    relatedMechanismOfInjury: 'inhalation_exposure_or_atmospheric_hazard',
    relatedExposurePathway: 'worker breathing zone or affected work area',
    relatedMissingControl: 'ventilation control or airflow verification',
    relatedStandardFamilyCandidate: 'candidate-ventilation',
    priority: 'high',
    answerType: 'photo',
    examplesOfUsefulEvidence: ['ventilation control photo', 'airflow measurement', 'smoke capture observation', 'exam record'],
    confidenceImpact: 'high',
    humanReviewTrigger: true,
    advisoryGuardrails: { advisoryOnly: true, doesNotDeclareViolation: true, requiresQualifiedReview: true }
  }

];
