import { ScenarioFamilyKnowledgeRecord } from './scenario-family.types';

export const SCENARIO_FAMILY_REGISTRY: ScenarioFamilyKnowledgeRecord[] = [
  {
    id: 'conveyor-cleanup',
    title: 'Conveyor cleanup near moving parts',
    domain: 'machine_guarding',
    applicableIndustries: ['mining', 'manufacturing'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['cleaning', 'clearing spillage', 'moving conveyor', 'missing guard', 'inadequate guard', 'nip point', 'exposed rotating parts'],
    equipmentIndicators: ['conveyor'],
    taskIndicators: ['cleanup', 'maintenance', 'inspection', 'operation'],
    unsafeConditionIndicators: ['moving parts', 'exposed', 'unguarded'],
    operationalStateIndicators: ['running'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['rotating_equipment_nip_point'],
    exposureIndicators: ['worker near belt'],
    missingOrFailedControlIndicators: ['guard missing', 'no LOTO'],
    criticalEvidenceQuestions: ['Is conveyor running?', 'Was LOTO applied?'],
    evidenceGaps: ['LOTO status', 'guard presence'],
    controlHierarchyGuidance: ['LOTO', 'guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['LOTO training', 'guard installation'],
    confidenceBoosters: ['clear observation of moving parts'],
    confidenceReducers: ['vague description of maintenance'],
    semanticConflictTriggers: ['not running', 'locked out'],
    humanReviewTriggers: ['high risk task'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'unguarded_conveyor_pulley',
    title: 'Unguarded conveyor pulley',
    domain: 'machine_guarding',
    applicableIndustries: ['mining'],
    applicableJurisdictions: ['msha'],
    commonObservationPhrases: ['unguarded tail pulley', 'exposed drive', 'nip point'],
    equipmentIndicators: ['conveyor'],
    taskIndicators: ['inspection', 'maintenance', 'cleanup', 'operation'],
    unsafeConditionIndicators: ['unguarded', 'exposed'],
    operationalStateIndicators: ['operational'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['crush_point'],
    exposureIndicators: ['access to area'],
    missingOrFailedControlIndicators: ['guarding'],
    criticalEvidenceQuestions: ['Is guard missing?'],
    evidenceGaps: ['access control'],
    controlHierarchyGuidance: ['guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['guard installation'],
    confidenceBoosters: ['clear observation of guarding failure'],
    confidenceReducers: ['vague description'],
    semanticConflictTriggers: ['guarded'],
    humanReviewTriggers: ['high risk'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'rotating_shaft_guarding',
    title: 'Exposed rotating shaft',
    domain: 'machine_guarding',
    applicableIndustries: ['mining', 'manufacturing'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['exposed rotating shaft', 'rotating shaft', 'nip point'],
    equipmentIndicators: ['machinery', 'conveyor', 'forklift', 'ladder', 'panel', 'tank'],
    taskIndicators: ['maintenance', 'inspection', 'operation', 'cleanup'],
    unsafeConditionIndicators: ['exposed', 'unguarded'],
    operationalStateIndicators: ['operational'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['rotating_equipment_nip_point'],
    exposureIndicators: ['access to area'],
    missingOrFailedControlIndicators: ['guarding'],
    criticalEvidenceQuestions: ['Is guard missing?'],
    evidenceGaps: ['access control'],
    controlHierarchyGuidance: ['guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['guard installation'],
    confidenceBoosters: ['clear observation of rotating hazard'],
    confidenceReducers: ['vague description'],
    semanticConflictTriggers: ['guarded'],
    humanReviewTriggers: ['high risk'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'point_of_operation_guarding',
    title: 'Point of operation guarding failure',
    domain: 'machine_guarding',
    applicableIndustries: ['manufacturing'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['point of operation', 'unguarded', 'pinch point'],
    equipmentIndicators: ['machinery', 'conveyor', 'forklift', 'ladder', 'panel', 'tank'],
    taskIndicators: ['operation', 'inspection', 'maintenance', 'cleanup'],
    unsafeConditionIndicators: ['unguarded', 'exposed'],
    operationalStateIndicators: ['operational'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['crush_point'],
    exposureIndicators: ['access to point'],
    missingOrFailedControlIndicators: ['guarding'],
    criticalEvidenceQuestions: ['Is guard missing?'],
    evidenceGaps: ['access control'],
    controlHierarchyGuidance: ['guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['guard installation'],
    confidenceBoosters: ['clear observation of guarding failure'],
    confidenceReducers: ['vague description'],
    semanticConflictTriggers: ['guarded'],
    humanReviewTriggers: ['high risk'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'unguarded-hazard-generic',
    title: 'Generic unguarded hazard',
    domain: 'machine_guarding',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['missing guard', 'inadequate guard', 'unguarded', 'nip point', 'exposed rotating'],
    equipmentIndicators: [],
    taskIndicators: [],
    unsafeConditionIndicators: ['missing guard', 'inadequate guard', 'unguarded'],
    operationalStateIndicators: ['operational'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['rotating_equipment_nip_point'],
    exposureIndicators: ['access to area'],
    missingOrFailedControlIndicators: ['guarding'],
    criticalEvidenceQuestions: ['Is guard missing?', 'Is access restricted?'],
    evidenceGaps: ['access control'],
    controlHierarchyGuidance: ['guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['guard installation'],
    confidenceBoosters: ['clear observation of guarding failure'],
    confidenceReducers: ['vague description'],
    semanticConflictTriggers: ['guarded'],
    humanReviewTriggers: ['high risk'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  }
  ,
  {
    id: 'electrical_panel_access',
    title: 'Blocked electrical panel access or working clearance',
    domain: 'electrical',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['electrical panel', 'panel door', 'blocked panel', 'working clearance', 'disconnects', 'stored materials'],
    equipmentIndicators: ['electrical panel', 'panel', 'disconnect'],
    taskIndicators: ['operation', 'maintenance', 'inspection', 'access'],
    unsafeConditionIndicators: ['blocked', 'obstructed', 'no clearance', 'stored materials'],
    operationalStateIndicators: ['energized', 'operational'],
    energySourceIndicators: ['electrical'],
    mechanismOfInjuryIndicators: ['electrical_shock_arc_flash_access_clearance'],
    exposureIndicators: ['employees cannot safely access', 'worker access', 'maintenance access'],
    missingOrFailedControlIndicators: ['blocked access', 'missing clearance', 'obstructed access'],
    criticalEvidenceQuestions: ['Is the panel energized?', 'What clearance is available?', 'Are disconnects accessible?'],
    evidenceGaps: ['energized status', 'clearance distance', 'access path condition'],
    controlHierarchyGuidance: ['clear access', 'maintain working clearance', 'remove stored materials'],
    candidateStandardFamilies: ['electrical'],
    correctiveActionThemes: ['restore clearance', 'remove obstruction', 'verify electrical access'],
    confidenceBoosters: ['blocked electrical panel with access or clearance issue'],
    confidenceReducers: ['panel mentioned without electrical access issue'],
    semanticConflictTriggers: ['clear access maintained', 'panel not electrical'],
    humanReviewTriggers: ['electrical hazard review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'damaged_cord_wet_location',
    title: 'Damaged electrical cord in wet location',
    domain: 'electrical',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['damaged insulation', 'damaged cord', 'extension cord', 'wet processing area', 'wet location'],
    equipmentIndicators: ['cord', 'extension cord', 'electrical cord'],
    taskIndicators: ['maintenance', 'cleanup', 'operation', 'inspection'],
    unsafeConditionIndicators: ['damaged insulation', 'wet', 'wet location', 'exposed conductor'],
    operationalStateIndicators: ['in use', 'energized'],
    energySourceIndicators: ['electrical'],
    mechanismOfInjuryIndicators: ['electrical_shock'],
    exposureIndicators: ['employees handle the cord', 'worker handling cord', 'employee contact'],
    missingOrFailedControlIndicators: ['damaged insulation', 'no protection', 'cord damage'],
    criticalEvidenceQuestions: ['Is the cord energized?', 'Is conductor exposed?', 'Is the area wet?'],
    evidenceGaps: ['energized status', 'extent of insulation damage', 'wet location confirmation'],
    controlHierarchyGuidance: ['remove damaged cord from service', 'replace cord', 'verify GFCI or protection where applicable'],
    candidateStandardFamilies: ['electrical'],
    correctiveActionThemes: ['remove from service', 'replace damaged cord', 'verify electrical protection'],
    confidenceBoosters: ['damaged cord plus wet location or employee handling'],
    confidenceReducers: ['cord mentioned without damage or exposure'],
    semanticConflictTriggers: ['cord removed from service', 'not energized'],
    humanReviewTriggers: ['electrical shock hazard review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'housekeeping_slip_trip',
    title: 'Housekeeping slip, trip, or same-level fall exposure',
    domain: 'slip_trip_fall',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['oil', 'loose aggregate', 'pedestrian walkway', 'walkway', 'slip', 'trip', 'housekeeping'],
    equipmentIndicators: ['floor', 'walkway', 'travelway'],
    taskIndicators: ['housekeeping', 'walking', 'access', 'inspection'],
    unsafeConditionIndicators: ['oil', 'loose aggregate', 'debris', 'poor housekeeping', 'slippery'],
    operationalStateIndicators: ['normal travel'],
    energySourceIndicators: ['gravity'],
    mechanismOfInjuryIndicators: ['slip_trip_fall_same_level'],
    exposureIndicators: ['employees use the walkway', 'pedestrian travel path', 'employee walking'],
    missingOrFailedControlIndicators: ['poor housekeeping', 'blocked access', 'debris'],
    criticalEvidenceQuestions: ['Is this a normal walking path?', 'What material is on the walking surface?', 'Is access required?'],
    evidenceGaps: ['walking surface condition', 'employee travel frequency', 'cleanup status'],
    controlHierarchyGuidance: ['remove material', 'restore walking surface', 'maintain housekeeping inspection'],
    candidateStandardFamilies: ['walking_working_surfaces'],
    correctiveActionThemes: ['clean walkway', 'remove slip/trip hazard', 'verify walking surface'],
    confidenceBoosters: ['walkway contamination with employee access'],
    confidenceReducers: ['floor mentioned without employee access or walking surface hazard'],
    semanticConflictTriggers: ['walkway clean', 'area barricaded'],
    humanReviewTriggers: ['walking-working surface exposure review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'fire_extinguisher_access_inspection',
    title: 'Blocked or overdue fire extinguisher access and inspection',
    domain: 'fire_protection',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['fire extinguisher', 'blocked extinguisher', 'inspection tag', 'expired tag', 'stacked pallets'],
    equipmentIndicators: ['fire extinguisher', 'extinguisher'],
    taskIndicators: ['housekeeping', 'inspection', 'emergency access'],
    unsafeConditionIndicators: ['blocked', 'expired', 'not inspected', 'obstructed'],
    operationalStateIndicators: ['emergency response readiness'],
    energySourceIndicators: ['thermal/fire'],
    mechanismOfInjuryIndicators: ['delayed_emergency_response'],
    exposureIndicators: ['ready access', 'employees would not have access', 'fire emergency'],
    missingOrFailedControlIndicators: ['blocked access', 'expired inspection', 'missing inspection'],
    criticalEvidenceQuestions: ['Is access blocked?', 'Is the inspection tag current?', 'Is the extinguisher visible and reachable?'],
    evidenceGaps: ['inspection date', 'access clearance', 'extinguisher location'],
    controlHierarchyGuidance: ['restore access', 'inspect extinguisher', 'maintain emergency equipment visibility'],
    candidateStandardFamilies: ['fire_protection'],
    correctiveActionThemes: ['clear access', 'update inspection', 'verify emergency readiness'],
    confidenceBoosters: ['blocked extinguisher with expired inspection tag'],
    confidenceReducers: ['extinguisher mentioned without access or inspection issue'],
    semanticConflictTriggers: ['access clear', 'inspection current'],
    humanReviewTriggers: ['emergency response equipment review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'mobile_equipment_pedestrian_interaction',
    title: 'Mobile equipment and pedestrian interaction',
    domain: 'mobile_equipment',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['forklift', 'shared pedestrian aisle', 'marked walkway', 'separation barrier', 'moving equipment'],
    equipmentIndicators: ['forklift', 'mobile equipment', 'powered industrial truck'],
    taskIndicators: ['transport', 'operation', 'travel'],
    unsafeConditionIndicators: ['no marked walkway', 'no separation barrier', 'shared aisle', 'employees walking beside moving equipment'],
    operationalStateIndicators: ['operating', 'moving'],
    energySourceIndicators: ['mobile equipment kinetic energy'],
    mechanismOfInjuryIndicators: ['struck_by_mobile_equipment'],
    exposureIndicators: ['employees walking beside moving equipment', 'pedestrian aisle', 'employee travel path'],
    missingOrFailedControlIndicators: ['no marked walkway', 'no separation barrier', 'missing traffic control'],
    criticalEvidenceQuestions: ['Are pedestrians separated from mobile equipment?', 'Is the travel path marked?', 'What controls are present?'],
    evidenceGaps: ['traffic control layout', 'pedestrian frequency', 'equipment operating path'],
    controlHierarchyGuidance: ['separate pedestrians', 'mark walkways', 'install barriers or traffic controls'],
    candidateStandardFamilies: ['powered_industrial_trucks'],
    correctiveActionThemes: ['pedestrian separation', 'traffic control', 'operator and pedestrian visibility'],
    confidenceBoosters: ['forklift operating near pedestrians without separation'],
    confidenceReducers: ['forklift mentioned without pedestrian exposure'],
    semanticConflictTriggers: ['separation barrier present', 'no pedestrian access'],
    humanReviewTriggers: ['mobile equipment struck-by exposure review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'excavation_protective_system_ambiguity',
    title: 'Excavation protective system unclear or missing',
    domain: 'excavation_trenching',
    applicableIndustries: ['construction', 'mining'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['excavation', 'trench', 'vertical walls', 'protective system', 'spoil pile', 'deeper than five feet'],
    equipmentIndicators: ['excavator', 'excavation', 'trench'],
    taskIndicators: ['trenching', 'excavation', 'work inside excavation'],
    unsafeConditionIndicators: ['vertical walls', 'no visible protective system', 'spoil pile near edge', 'cave-in'],
    operationalStateIndicators: ['active excavation'],
    energySourceIndicators: ['gravity', 'soil pressure'],
    mechanismOfInjuryIndicators: ['caught_in_cave_in'],
    exposureIndicators: ['worker is inside excavation', 'employee in trench', 'worker in excavation'],
    missingOrFailedControlIndicators: ['no protective system', 'missing protective system', 'spoil pile near edge'],
    criticalEvidenceQuestions: ['What is the excavation depth?', 'Is a protective system installed?', 'Where is the spoil pile located?'],
    evidenceGaps: ['depth confirmation', 'protective system status', 'soil/spoil condition'],
    controlHierarchyGuidance: ['verify protective system', 'move spoil pile', 'competent person review'],
    candidateStandardFamilies: ['excavation_trenching'],
    correctiveActionThemes: ['remove worker until reviewed', 'install protective system', 'verify excavation controls'],
    confidenceBoosters: ['worker inside excavation with vertical walls and no protective system'],
    confidenceReducers: ['excavation mentioned without worker exposure or depth'],
    semanticConflictTriggers: ['protective system installed', 'worker not inside excavation'],
    humanReviewTriggers: ['excavation competent person review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  }

  ];

