import { ScenarioFamilyKnowledgeRecord } from './scenario-family.types';

export const SCENARIO_FAMILY_REGISTRY: ScenarioFamilyKnowledgeRecord[] = [
  {
    id: 'conveyor-cleanup',
    title: 'Conveyor cleanup near moving parts',
    domain: 'machine_guarding',
    applicableIndustries: ['mining', 'manufacturing'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['cleaning', 'clearing spillage', 'moving conveyor', 'missing guard', 'inadequate guard', 'nip point', 'exposed rotating parts'],
    equipmentIndicators: ['conveyor'],
    taskIndicators: ['cleanup', 'maintenance', 'inspection', 'operation', 'shoveling', 'clearing', 'scrape', 'scraping', 'housekeeping', 'shovels'],
    unsafeConditionIndicators: ['moving parts', 'exposed', 'unguarded'],
    operationalStateIndicators: ['running'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['rotating_equipment_nip_point'],
    exposureIndicators: ['worker near belt'],
    missingOrFailedControlIndicators: ['guard missing', 'no LOTO'],
    criticalEvidenceQuestions: ['Is conveyor running?', 'Was LOTO applied?'],
    evidenceGaps: ['LOTO status', 'guard presence'],
    controlHierarchyGuidance: ['LOTO', 'guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['LOTO training', 'guard installation'],
    confidenceBoosters: ['clear observation of moving parts'],
    confidenceReducers: ['vague description of maintenance'],
    semanticConflictTriggers: ['not running', 'locked out'],
    humanReviewTriggers: ['high risk task'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'unguarded_conveyor_pulley',
    title: 'Unguarded conveyor pulley',
    domain: 'machine_guarding',
    applicableIndustries: ['mining'],
    applicableJurisdictions: ['msha'],
    commonObservationPhrases: ['unguarded tail pulley', 'exposed drive', 'nip point'],
    equipmentIndicators: ['conveyor'],
    taskIndicators: [],
    unsafeConditionIndicators: ['unguarded', 'exposed'],
    operationalStateIndicators: ['operational'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['rotating_equipment_entanglement'],
    exposureIndicators: ['access to area'],
    missingOrFailedControlIndicators: ['guarding'],
    criticalEvidenceQuestions: ['Is guard missing?'],
    evidenceGaps: ['access control'],
    controlHierarchyGuidance: ['guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['guard installation'],
    confidenceBoosters: ['clear observation of guarding failure'],
    confidenceReducers: ['vague description'],
    semanticConflictTriggers: ['guarded'],
    humanReviewTriggers: ['high risk'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'rotating_shaft_guarding',
    title: 'Exposed rotating shaft',
    domain: 'machine_guarding',
    applicableIndustries: ['mining', 'manufacturing'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['exposed rotating shaft', 'rotating shaft', 'nip point'],
    equipmentIndicators: ['machinery', 'rotating shaft', 'pump', 'coupling', 'motor', 'shaft', 'conveyor'],
    taskIndicators: [],
    unsafeConditionIndicators: ['exposed', 'unguarded'],
    operationalStateIndicators: ['operational'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['rotating_equipment_entanglement'],
    exposureIndicators: ['access to area'],
    missingOrFailedControlIndicators: ['guarding'],
    criticalEvidenceQuestions: ['Is guard missing?'],
    evidenceGaps: ['access control'],
    controlHierarchyGuidance: ['guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['guard installation'],
    confidenceBoosters: ['clear observation of rotating hazard'],
    confidenceReducers: ['vague description'],
    semanticConflictTriggers: ['guarded'],
    humanReviewTriggers: ['high risk'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'point_of_operation_guarding',
    title: 'Point of operation guarding failure',
    domain: 'machine_guarding',
    applicableIndustries: ['manufacturing'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['point of operation', 'unguarded', 'pinch point'],
    equipmentIndicators: ['machinery', 'press brake', 'shear', 'punch', 'grinder', 'table saw', 'saw'],
    taskIndicators: [],
    unsafeConditionIndicators: ['unguarded', 'exposed'],
    operationalStateIndicators: ['operational'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['cut_amputation_point_of_operation'],
    exposureIndicators: ['access to point'],
    missingOrFailedControlIndicators: ['guarding'],
    criticalEvidenceQuestions: ['Is guard missing?'],
    evidenceGaps: ['access control'],
    controlHierarchyGuidance: ['guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['guard installation'],
    confidenceBoosters: ['clear observation of guarding failure'],
    confidenceReducers: ['vague description'],
    semanticConflictTriggers: ['guarded'],
    humanReviewTriggers: ['high risk'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'unguarded-hazard-generic',
    title: 'Generic unguarded hazard',
    domain: 'machine_guarding',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['missing guard', 'inadequate guard', 'unguarded', 'nip point', 'exposed rotating'],
    equipmentIndicators: [],
    taskIndicators: [],
    unsafeConditionIndicators: ['missing guard', 'inadequate guard', 'unguarded'],
    operationalStateIndicators: ['operational'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['rotating_equipment_nip_point'],
    exposureIndicators: ['access to area'],
    missingOrFailedControlIndicators: ['guarding'],
    criticalEvidenceQuestions: ['Is guard missing?', 'Is access restricted?'],
    evidenceGaps: ['access control'],
    controlHierarchyGuidance: ['guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['guard installation'],
    confidenceBoosters: ['clear observation of guarding failure'],
    confidenceReducers: ['vague description'],
    semanticConflictTriggers: ['guarded'],
    humanReviewTriggers: ['high risk'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  }
  ,
  {
    id: 'electrical_panel_access',
    title: 'Blocked electrical panel access or working clearance',
    domain: 'electrical',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['electrical panel', 'panel door', 'blocked panel', 'working clearance', 'disconnects', 'stored materials'],
    equipmentIndicators: ['electrical panel', 'panel', 'disconnect'],
    taskIndicators: ['operation', 'maintenance', 'inspection', 'access'],
    unsafeConditionIndicators: ['blocked', 'obstructed', 'no clearance', 'stored materials'],
    operationalStateIndicators: ['energized', 'operational'],
    energySourceIndicators: ['electrical'],
    mechanismOfInjuryIndicators: ['arc_flash'],
    exposureIndicators: ['employees cannot safely access', 'worker access', 'maintenance access'],
    missingOrFailedControlIndicators: ['blocked access', 'missing clearance', 'obstructed access'],
    criticalEvidenceQuestions: ['Is the panel energized?', 'What clearance is available?', 'Are disconnects accessible?'],
    evidenceGaps: ['energized status', 'clearance distance', 'access path condition'],
    controlHierarchyGuidance: ['clear access', 'maintain working clearance', 'remove stored materials'],
    candidateStandardFamilies: ['electrical'],
    correctiveActionThemes: ['restore clearance', 'remove obstruction', 'verify electrical access'],
    confidenceBoosters: ['blocked electrical panel with access or clearance issue'],
    confidenceReducers: ['panel mentioned without electrical access issue'],
    semanticConflictTriggers: ['clear access maintained', 'panel not electrical'],
    humanReviewTriggers: ['electrical hazard review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'damaged_cord_wet_location',
    title: 'Damaged electrical cord in wet location',
    domain: 'electrical',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['damaged insulation', 'damaged cord', 'extension cord', 'wet processing area', 'wet location'],
    equipmentIndicators: ['cord', 'extension cord', 'electrical cord'],
    taskIndicators: ['maintenance', 'cleanup', 'operation', 'inspection'],
    unsafeConditionIndicators: ['damaged insulation', 'wet', 'wet location', 'exposed conductor'],
    operationalStateIndicators: ['in use', 'energized'],
    energySourceIndicators: ['electrical'],
    mechanismOfInjuryIndicators: ['electrical_shock'],
    exposureIndicators: ['employees handle the cord', 'worker handling cord', 'employee contact'],
    missingOrFailedControlIndicators: ['damaged insulation', 'no protection', 'cord damage'],
    criticalEvidenceQuestions: ['Is the cord energized?', 'Is conductor exposed?', 'Is the area wet?'],
    evidenceGaps: ['energized status', 'extent of insulation damage', 'wet location confirmation'],
    controlHierarchyGuidance: ['remove damaged cord from service', 'replace cord', 'verify GFCI or protection where applicable'],
    candidateStandardFamilies: ['electrical'],
    correctiveActionThemes: ['remove from service', 'replace damaged cord', 'verify electrical protection'],
    confidenceBoosters: ['damaged cord plus wet location or employee handling'],
    confidenceReducers: ['cord mentioned without damage or exposure'],
    semanticConflictTriggers: ['cord removed from service', 'not energized'],
    humanReviewTriggers: ['electrical shock hazard review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'housekeeping_slip_trip',
    title: 'Housekeeping slip, trip, or same-level fall exposure',
    domain: 'slip_trip_fall',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['oil', 'loose aggregate', 'pedestrian walkway', 'walkway', 'slip', 'trip', 'housekeeping'],
    equipmentIndicators: ['floor', 'walkway', 'travelway'],
    taskIndicators: [],
    unsafeConditionIndicators: ['oil', 'loose aggregate', 'debris', 'poor housekeeping', 'slippery'],
    operationalStateIndicators: ['normal travel'],
    energySourceIndicators: ['gravity'],
    mechanismOfInjuryIndicators: ['slip_trip_fall_same_level'],
    exposureIndicators: ['employees use the walkway', 'pedestrian travel path', 'employee walking'],
    missingOrFailedControlIndicators: ['poor housekeeping', 'blocked access', 'debris'],
    criticalEvidenceQuestions: ['Is this a normal walking path?', 'What material is on the walking surface?', 'Is access required?'],
    evidenceGaps: ['walking surface condition', 'employee travel frequency', 'cleanup status'],
    controlHierarchyGuidance: ['remove material', 'restore walking surface', 'maintain housekeeping inspection'],
    candidateStandardFamilies: ['walking_working_surfaces'],
    correctiveActionThemes: ['clean walkway', 'remove slip/trip hazard', 'verify walking surface'],
    confidenceBoosters: ['walkway contamination with employee access'],
    confidenceReducers: ['floor mentioned without employee access or walking surface hazard'],
    semanticConflictTriggers: ['walkway clean', 'area barricaded'],
    humanReviewTriggers: ['walking-working surface exposure review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'fire_extinguisher_access_inspection',
    title: 'Blocked or overdue fire extinguisher access and inspection',
    domain: 'fire_protection',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['fire extinguisher', 'blocked extinguisher', 'inspection tag', 'expired tag', 'stacked pallets'],
    equipmentIndicators: ['fire extinguisher', 'extinguisher'],
    taskIndicators: ['housekeeping', 'inspection', 'emergency access'],
    unsafeConditionIndicators: ['blocked', 'expired', 'not inspected', 'obstructed'],
    operationalStateIndicators: ['emergency response readiness'],
    energySourceIndicators: ['thermal/fire'],
    mechanismOfInjuryIndicators: ['delayed_emergency_response'],
    exposureIndicators: ['ready access', 'employees would not have access', 'fire emergency'],
    missingOrFailedControlIndicators: ['blocked access', 'expired inspection', 'missing inspection'],
    criticalEvidenceQuestions: ['Is access blocked?', 'Is the inspection tag current?', 'Is the extinguisher visible and reachable?'],
    evidenceGaps: ['inspection date', 'access clearance', 'extinguisher location'],
    controlHierarchyGuidance: ['restore access', 'inspect extinguisher', 'maintain emergency equipment visibility'],
    candidateStandardFamilies: ['fire_protection'],
    correctiveActionThemes: ['clear access', 'update inspection', 'verify emergency readiness'],
    confidenceBoosters: ['blocked extinguisher with expired inspection tag'],
    confidenceReducers: ['extinguisher mentioned without access or inspection issue'],
    semanticConflictTriggers: ['access clear', 'inspection current'],
    humanReviewTriggers: ['emergency response equipment review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'mobile_equipment_pedestrian_interaction',
    title: 'Mobile equipment and pedestrian interaction',
    domain: 'mobile_equipment',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['forklift', 'shared pedestrian aisle', 'marked walkway', 'separation barrier', 'moving equipment'],
    equipmentIndicators: ['forklift', 'mobile equipment', 'powered industrial truck'],
    taskIndicators: ['transport', 'operation', 'travel'],
    unsafeConditionIndicators: ['no marked walkway', 'no separation barrier', 'shared aisle', 'employees walking beside moving equipment'],
    operationalStateIndicators: ['operating', 'moving'],
    energySourceIndicators: ['mobile equipment kinetic energy'],
    mechanismOfInjuryIndicators: ['struck_by_mobile_equipment'],
    exposureIndicators: ['employees walking beside moving equipment', 'pedestrian aisle', 'employee travel path'],
    missingOrFailedControlIndicators: ['no marked walkway', 'no separation barrier', 'missing traffic control'],
    criticalEvidenceQuestions: ['Are pedestrians separated from mobile equipment?', 'Is the travel path marked?', 'What controls are present?'],
    evidenceGaps: ['traffic control layout', 'pedestrian frequency', 'equipment operating path'],
    controlHierarchyGuidance: ['separate pedestrians', 'mark walkways', 'install barriers or traffic controls'],
    candidateStandardFamilies: ['powered_industrial_trucks'],
    correctiveActionThemes: ['pedestrian separation', 'traffic control', 'operator and pedestrian visibility'],
    confidenceBoosters: ['forklift operating near pedestrians without separation'],
    confidenceReducers: ['forklift mentioned without pedestrian exposure'],
    semanticConflictTriggers: ['separation barrier present', 'no pedestrian access'],
    humanReviewTriggers: ['mobile equipment struck-by exposure review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'excavation_protective_system_ambiguity',
    title: 'Excavation protective system unclear or missing',
    domain: 'excavation_trenching',
    applicableIndustries: ['construction', 'mining'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['excavation', 'trench', 'vertical walls', 'protective system', 'spoil pile', 'deeper than five feet'],
    equipmentIndicators: ['excavator', 'excavation', 'trench'],
    taskIndicators: ['trenching', 'excavation', 'work inside excavation'],
    unsafeConditionIndicators: ['vertical walls', 'no visible protective system', 'spoil pile near edge', 'cave-in'],
    operationalStateIndicators: ['active excavation'],
    energySourceIndicators: ['gravity', 'soil pressure'],
    mechanismOfInjuryIndicators: ['caught_in_cave_in'],
    exposureIndicators: ['worker is inside excavation', 'employee in trench', 'worker in excavation'],
    missingOrFailedControlIndicators: ['no protective system', 'missing protective system', 'spoil pile near edge'],
    criticalEvidenceQuestions: ['What is the excavation depth?', 'Is a protective system installed?', 'Where is the spoil pile located?'],
    evidenceGaps: ['depth confirmation', 'protective system status', 'soil/spoil condition'],
    controlHierarchyGuidance: ['verify protective system', 'move spoil pile', 'competent person review'],
    candidateStandardFamilies: ['excavation_trenching'],
    correctiveActionThemes: ['remove worker until reviewed', 'install protective system', 'verify excavation controls'],
    confidenceBoosters: ['worker inside excavation with vertical walls and no protective system'],
    confidenceReducers: ['excavation mentioned without worker exposure or depth'],
    semanticConflictTriggers: ['protective system installed', 'worker not inside excavation'],
    humanReviewTriggers: ['excavation competent person review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'scaffold_guardrail_planking',
    title: 'Scaffold guardrail and planking deficiencies',
    domain: 'fall_protection',
    applicableIndustries: ['construction', 'industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['scaffold', 'scaffolding', 'split planks', 'missing guardrails', 'missing midrails', 'no toe boards'],
    equipmentIndicators: ['scaffold', 'scaffolding'],
    taskIndicators: ['construction_work', 'elevated_work'],
    unsafeConditionIndicators: ['missing_guardrails', 'warped planks', 'no toe boards'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['gravity'],
    mechanismOfInjuryIndicators: ['fall_from_height'],
    exposureIndicators: ['worker_on_scaffold'],
    missingOrFailedControlIndicators: ['fall_protection_or_edge_protection'],
    criticalEvidenceQuestions: ['Are standard guardrails installed?', 'Are the walk planks fully spanned?'],
    evidenceGaps: ['scaffold height', 'guardrail status'],
    controlHierarchyGuidance: ['install guardrails', 'replace damaged planks'],
    candidateStandardFamilies: ['fall_protection'],
    correctiveActionThemes: ['scaffold safety inspection', 'install fall barriers'],
    confidenceBoosters: ['workers on high scaffold without rails'],
    confidenceReducers: ['scaffold resting on ground unoccupied'],
    semanticConflictTriggers: ['fully guarded'],
    humanReviewTriggers: ['fall hazard review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'ladder_access_setup',
    title: 'Unsafe ladder setup or access',
    domain: 'fall_protection',
    applicableIndustries: ['construction', 'industrial'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['ladder', 'step ladder', 'extension ladder', 'loose soil', 'no safety feet', 'top step'],
    equipmentIndicators: ['ladder', 'step ladder', 'extension ladder'],
    taskIndicators: ['access', 'maintenance'],
    unsafeConditionIndicators: ['unsafe_setup', 'cracked rail', 'bent spreader'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['gravity'],
    mechanismOfInjuryIndicators: ['fall_from_height'],
    exposureIndicators: ['worker_on_ladder'],
    missingOrFailedControlIndicators: ['fall_protection_or_edge_protection'],
    criticalEvidenceQuestions: ['Is the ladder secured?', 'Does it extend 3 feet above landing?'],
    evidenceGaps: ['ladder securement', 'extension height'],
    controlHierarchyGuidance: ['tie off ladder', 'extend rails 3 feet'],
    candidateStandardFamilies: ['fall_protection'],
    correctiveActionThemes: ['ladder safety training', 'replace damaged ladder'],
    confidenceBoosters: ['ladder placed on unstable surface'],
    confidenceReducers: ['ladder stored in rack'],
    semanticConflictTriggers: ['secured and tied off'],
    humanReviewTriggers: ['fall hazard review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'elevated_work_fall_exposure',
    title: 'Elevated work unprotected edge fall exposure',
    domain: 'fall_protection',
    applicableIndustries: ['construction', 'industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['roof edge', 'unprotected edge', 'floor hole', 'open floor hole', 'no harness'],
    equipmentIndicators: ['mezzanine', 'roof', 'catwalk'],
    taskIndicators: ['elevated_work', 'operation'],
    unsafeConditionIndicators: ['missing_fall_protection', 'unprotected_edge', 'floor_opening'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['gravity'],
    mechanismOfInjuryIndicators: ['fall_from_height'],
    exposureIndicators: ['worker_near_edge'],
    missingOrFailedControlIndicators: ['fall_protection_or_edge_protection'],
    criticalEvidenceQuestions: ['Is personal fall arrest used?', 'Are edges fully guardrailed?'],
    evidenceGaps: ['fall arrest equipment status', 'edge protection presence'],
    controlHierarchyGuidance: ['install guardrails', 'deploy personal fall arrest systems'],
    candidateStandardFamilies: ['fall_protection'],
    correctiveActionThemes: ['fall protection training', 'guardrail installation'],
    confidenceBoosters: ['employee working near roof edge with no tie off'],
    confidenceReducers: ['work at ground level'],
    semanticConflictTriggers: ['tied off', 'guardrails in place'],
    humanReviewTriggers: ['high fall risk review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'chemical_label_sds_ppe',
    title: 'Missing chemical labels, SDS, or improper PPE',
    domain: 'hazcom_chemical_exposure',
    applicableIndustries: ['industrial', 'manufacturing'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['unlabeled container', 'missing sds', 'no ghs label', 'no goggles'],
    equipmentIndicators: ['chemical_container'],
    taskIndicators: ['chemical_handling', 'decanting'],
    unsafeConditionIndicators: ['unlabeled_container', 'no_ghs_label', 'missing_sds'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['chemical'],
    mechanismOfInjuryIndicators: ['chemical_exposure'],
    exposureIndicators: ['chemical_contact_exposure'],
    missingOrFailedControlIndicators: ['chemical_labeling', 'sds_availability', 'chemical_ppe'],
    criticalEvidenceQuestions: ['Is GHS labeling present?', 'Is the corresponding SDS available?', 'Is proper chemical PPE worn?'],
    evidenceGaps: ['chemical identity', 'sds presence', 'ppe adequacy'],
    controlHierarchyGuidance: ['label all chemical containers', 'provide SDS binder', 'wear chemical goggles/gloves'],
    candidateStandardFamilies: ['hazard_communication'],
    correctiveActionThemes: ['chemical labeling audit', 'provide PPE', 'sds updates'],
    confidenceBoosters: ['unlabeled solvent decanted with no goggles'],
    confidenceReducers: ['sealed manufacturer chemical drums'],
    semanticConflictTriggers: ['ghs labeled', 'fully protected'],
    humanReviewTriggers: ['chemical hazard review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'ventilation_exposure_uncertainty',
    title: 'Inadequate ventilation or airborne exposure uncertainty',
    domain: 'hazcom_chemical_exposure',
    applicableIndustries: ['industrial', 'manufacturing'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['unventilated', 'enclosed room', 'weld fumes', 'silica dust', 'paint fumes', 'exhaust'],
    equipmentIndicators: ['degreasing_tank', 'generator'],
    taskIndicators: ['chemical_work', 'welding', 'painting', 'grinding'],
    unsafeConditionIndicators: ['failed_ventilation', 'unventilated_area', 'fumes_accumulation'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['chemical', 'respirable_dust'],
    mechanismOfInjuryIndicators: ['chemical_exposure'],
    exposureIndicators: ['chemical_vapor_inhalation', 'respirable_dust_inhalation'],
    missingOrFailedControlIndicators: ['local_exhaust_ventilation', 'respiratory_protection'],
    criticalEvidenceQuestions: ['Is active mechanical ventilation running?', 'Is local exhaust provided at source?'],
    evidenceGaps: ['ventilation air flow rate', 'dust concentration', 'respirator rating'],
    controlHierarchyGuidance: ['install local exhaust ventilation', 'provide respirators'],
    candidateStandardFamilies: ['hazard_communication'],
    correctiveActionThemes: ['ventilation system service', 'provide respirators'],
    confidenceBoosters: ['welding in tight unventilated mechanical room with visible fumes'],
    confidenceReducers: ['work performed in open outdoor yard'],
    semanticConflictTriggers: ['active local exhaust ventilation running'],
    humanReviewTriggers: ['industrial hygiene review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'suspended_load_line_of_fire',
    title: 'Suspended load line of fire exposure',
    domain: 'cranes_rigging_hoisting',
    applicableIndustries: ['construction', 'mining'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['suspended load', 'line of fire', 'under the load'],
    equipmentIndicators: ['crane', 'hoist', 'rigging'],
    taskIndicators: ['lifting', 'rigging'],
    unsafeConditionIndicators: ['employee under load', 'exclusion zone breach'],
    operationalStateIndicators: ['lifting'],
    energySourceIndicators: ['mechanical', 'gravity'],
    mechanismOfInjuryIndicators: ['struck_by_falling_object'],
    exposureIndicators: ['employee position'],
    missingOrFailedControlIndicators: ['exclusion zone', 'clear communication'],
    criticalEvidenceQuestions: ['Is the exclusion zone clear?', 'Is the load control path managed?'],
    evidenceGaps: ['exclusion zone status', 'worker location'],
    controlHierarchyGuidance: ['establish exclusion zone', 'manage load path'],
    candidateStandardFamilies: ['cranes_rigging'],
    correctiveActionThemes: ['clear suspended-load zone', 'restrict lift path'],
    confidenceBoosters: ['worker observed under suspended crane load'],
    confidenceReducers: ['clear zone established'],
    semanticConflictTriggers: ['load lowered', 'area clear'],
    humanReviewTriggers: ['lifting hazard review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'damaged_rigging_or_wrong_hardware',
    title: 'Damaged rigging or inappropriate hardware',
    domain: 'cranes_rigging_hoisting',
    applicableIndustries: ['construction', 'mining', 'manufacturing'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['frayed sling', 'damaged rigging', 'incorrect shackle', 'hardware failure'],
    equipmentIndicators: ['rigging', 'sling', 'shackle', 'hook'],
    taskIndicators: ['lifting', 'rigging'],
    unsafeConditionIndicators: ['frayed', 'damaged', 'improper hardware'],
    operationalStateIndicators: ['pre-lift'],
    energySourceIndicators: ['mechanical', 'gravity'],
    mechanismOfInjuryIndicators: ['rigging_failure'],
    exposureIndicators: ['worker near rigging'],
    missingOrFailedControlIndicators: ['insufficient inspection'],
    criticalEvidenceQuestions: ['Is the rigging certified?', 'Are there signs of damage?'],
    evidenceGaps: ['rigging certification', 'inspection status'],
    controlHierarchyGuidance: ['remove from service', 'inspect rigging'],
    candidateStandardFamilies: ['cranes_rigging'],
    correctiveActionThemes: ['rigging inspection', 'use certified hardware'],
    confidenceBoosters: ['clear evidence of fraying'],
    confidenceReducers: ['rigging looks new'],
    semanticConflictTriggers: ['rigging inspected'],
    humanReviewTriggers: ['rigging inspection review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'crane_outrigger_ground_stability',
    title: 'Crane outrigger or ground stability issue',
    domain: 'cranes_rigging_hoisting',
    applicableIndustries: ['construction', 'mining'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['unstable ground', 'outrigger sink', 'no matting'],
    equipmentIndicators: ['crane', 'outrigger'],
    taskIndicators: ['setup', 'lifting'],
    unsafeConditionIndicators: ['sinking', 'soft ground', 'no pad'],
    operationalStateIndicators: ['setup'],
    energySourceIndicators: ['mechanical', 'gravity'],
    mechanismOfInjuryIndicators: ['crane_tip_over'],
    exposureIndicators: ['crane operator', 'nearby workers'],
    missingOrFailedControlIndicators: ['ground support', 'matting'],
    criticalEvidenceQuestions: ['Are pads/mats used?', 'Is the ground firm?'],
    evidenceGaps: ['ground bearing capacity', 'pad presence'],
    controlHierarchyGuidance: ['use mats', 'verify ground'],
    candidateStandardFamilies: ['cranes_rigging'],
    correctiveActionThemes: ['setup stability', 'use outrigger pads'],
    confidenceBoosters: ['outrigger sinking into soil'],
    confidenceReducers: ['hard pavement'],
    semanticConflictTriggers: ['mats installed'],
    humanReviewTriggers: ['crane setup review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'hoist_limit_or_load_control_gap',
    title: 'Hoist limit switch or load control gap',
    domain: 'cranes_rigging_hoisting',
    applicableIndustries: ['construction', 'mining', 'manufacturing'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['limit switch failure', 'hoist overtravel', 'load control loss'],
    equipmentIndicators: ['hoist', 'limit switch'],
    taskIndicators: ['lifting'],
    unsafeConditionIndicators: ['overtravel', 'no control'],
    operationalStateIndicators: ['lifting'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['hoist_failure'],
    exposureIndicators: ['operator', 'workers in lift path'],
    missingOrFailedControlIndicators: ['limit switch', 'control system'],
    criticalEvidenceQuestions: ['Does the limit switch function?', 'Is the load managed?'],
    evidenceGaps: ['switch test status', 'load control method'],
    controlHierarchyGuidance: ['test limit switches', 'implement load control'],
    candidateStandardFamilies: ['cranes_rigging'],
    correctiveActionThemes: ['hoist maintenance', 'limit switch testing'],
    confidenceBoosters: ['hoist bypassed limit'],
    confidenceReducers: ['limit functional'],
    semanticConflictTriggers: ['switches tested'],
    humanReviewTriggers: ['hoist system review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'sharps_or_needle_exposure',
    title: 'Sharps or needle stick exposure',
    domain: 'bloodborne_pathogens',
    applicableIndustries: ['healthcare', 'industrial_cleaning'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['needle', 'sharps', 'stab', 'puncture'],
    equipmentIndicators: ['needles', 'sharps_container'],
    taskIndicators: ['disposal', 'handling'],
    unsafeConditionIndicators: ['exposed_sharps', 'improper_disposal'],
    operationalStateIndicators: ['disposal'],
    energySourceIndicators: ['biological'],
    mechanismOfInjuryIndicators: ['puncture'],
    exposureIndicators: ['employee handling'],
    missingOrFailedControlIndicators: ['sharps_container', 'ppe'],
    criticalEvidenceQuestions: ['Are sharps properly contained?'],
    evidenceGaps: ['disposal method'],
    controlHierarchyGuidance: ['use sharps containers', 'wear puncture-resistant gloves'],
    candidateStandardFamilies: ['bloodborne_pathogens'],
    correctiveActionThemes: ['sharps disposal training', 'provide sharps containers'],
    confidenceBoosters: ['needle left in open'],
    confidenceReducers: ['proper container used'],
    semanticConflictTriggers: ['sharps contained'],
    humanReviewTriggers: ['bloodborne exposure review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'blood_or_body_fluid_cleanup',
    title: 'Blood or body fluid cleanup',
    domain: 'bloodborne_pathogens',
    applicableIndustries: ['healthcare', 'industrial_cleaning', 'janitorial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['blood cleanup', 'body fluid', 'spill'],
    equipmentIndicators: ['cleanup_kit'],
    taskIndicators: ['cleaning'],
    unsafeConditionIndicators: ['no_ppe', 'unprotected_cleanup'],
    operationalStateIndicators: ['cleaning'],
    energySourceIndicators: ['biological'],
    mechanismOfInjuryIndicators: ['infection'],
    exposureIndicators: ['cleanup_staff'],
    missingOrFailedControlIndicators: ['ppe', 'cleanup_procedure'],
    criticalEvidenceQuestions: ['Is proper cleanup PPE used?'],
    evidenceGaps: ['cleanup procedure'],
    controlHierarchyGuidance: ['wear gloves/goggles', 'use spill kit'],
    candidateStandardFamilies: ['bloodborne_pathogens'],
    correctiveActionThemes: ['cleanup training', 'provide spill kits'],
    confidenceBoosters: ['blood cleanup with no gloves'],
    confidenceReducers: ['fully protected'],
    semanticConflictTriggers: ['ppe used'],
    humanReviewTriggers: ['bloodborne exposure review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'contaminated_sharps_disposal_gap',
    title: 'Contaminated sharps disposal gap',
    domain: 'bloodborne_pathogens',
    applicableIndustries: ['healthcare', 'industrial_cleaning'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['overflowing sharps container', 'sharps in trash'],
    equipmentIndicators: ['sharps_container'],
    taskIndicators: ['disposal'],
    unsafeConditionIndicators: ['full_container', 'improper_disposal'],
    operationalStateIndicators: ['disposal'],
    energySourceIndicators: ['biological'],
    mechanismOfInjuryIndicators: ['puncture'],
    exposureIndicators: ['staff_access'],
    missingOrFailedControlIndicators: ['proper_disposal'],
    criticalEvidenceQuestions: ['Is container full?'],
    evidenceGaps: ['disposal protocol'],
    controlHierarchyGuidance: ['replace container', 'follow disposal protocol'],
    candidateStandardFamilies: ['bloodborne_pathogens'],
    correctiveActionThemes: ['disposal training', 'replace container'],
    confidenceBoosters: ['sharps in regular trash'],
    confidenceReducers: ['container replaced'],
    semanticConflictTriggers: ['properly disposed'],
    humanReviewTriggers: ['bloodborne exposure review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'repetitive_force_posture_exposure',
    title: 'Repetitive force or awkward posture exposure',
    domain: 'ergonomics',
    applicableIndustries: ['manufacturing', 'logistics'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['repetitive motion', 'awkward posture', 'strain'],
    equipmentIndicators: ['workstation'],
    taskIndicators: ['production', 'assembly'],
    unsafeConditionIndicators: ['high_force', 'repetitive_strain'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['musculoskeletal_disorder'],
    exposureIndicators: ['worker_posture'],
    missingOrFailedControlIndicators: ['ergonomic_tools', 'workstation_setup'],
    criticalEvidenceQuestions: ['Is the workstation ergonomic?'],
    evidenceGaps: ['ergonomic risk assessment'],
    controlHierarchyGuidance: ['improve workstation setup', 'rotate tasks'],
    candidateStandardFamilies: ['ergonomics'],
    correctiveActionThemes: ['ergonomic assessment', 'workstation redesign'],
    confidenceBoosters: ['repetitive motion with awkward posture'],
    confidenceReducers: ['ergonomic tools used'],
    semanticConflictTriggers: ['workstation adjusted'],
    humanReviewTriggers: ['ergonomic review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'manual_material_handling_overexertion',
    title: 'Manual material handling overexertion',
    domain: 'ergonomics',
    applicableIndustries: ['logistics', 'manufacturing'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['lifting heavy', 'carrying heavy', 'overexertion'],
    equipmentIndicators: ['material'],
    taskIndicators: ['lifting', 'carrying'],
    unsafeConditionIndicators: ['excessive_weight', 'heavy_lifting'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['overexertion_strains'],
    exposureIndicators: ['worker'],
    missingOrFailedControlIndicators: ['material_handling_aids'],
    criticalEvidenceQuestions: ['Are handling aids used?'],
    evidenceGaps: ['lifting aid availability'],
    controlHierarchyGuidance: ['use lifting aids', 'reduce weight'],
    candidateStandardFamilies: ['ergonomics'],
    correctiveActionThemes: ['lifting training', 'provide aids'],
    confidenceBoosters: ['heavy lifting without aids'],
    confidenceReducers: ['lifting aids used'],
    semanticConflictTriggers: ['aids used'],
    humanReviewTriggers: ['ergonomic review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'awkward_reach_workstation_design',
    title: 'Awkward reach workstation design',
    domain: 'ergonomics',
    applicableIndustries: ['manufacturing', 'assembly'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['reaching too far', 'awkward reach', 'poor layout'],
    equipmentIndicators: ['workstation'],
    taskIndicators: ['assembly'],
    unsafeConditionIndicators: ['extended_reach', 'poor_design'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['musculoskeletal_disorder'],
    exposureIndicators: ['worker_reach'],
    missingOrFailedControlIndicators: ['workstation_design'],
    criticalEvidenceQuestions: ['Is workstation adjustable?'],
    evidenceGaps: ['layout assessment'],
    controlHierarchyGuidance: ['improve layout', 'make adjustable'],
    candidateStandardFamilies: ['ergonomics'],
    correctiveActionThemes: ['workstation redesign', 'ergonomic adjustment'],
    confidenceBoosters: ['frequent reaching outside neutral zone'],
    confidenceReducers: ['workstation well organized'],
    semanticConflictTriggers: ['workstation layout improved'],
    humanReviewTriggers: ['ergonomic review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'respirable_dust_or_silica_exposure',
    title: 'Respirable dust or silica exposure',
    domain: 'industrial_hygiene',
    applicableIndustries: ['construction', 'mining', 'manufacturing'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['dust', 'silica', 'clouds', 'respirable'],
    equipmentIndicators: ['grinder', 'drill'],
    taskIndicators: ['cutting', 'drilling'],
    unsafeConditionIndicators: ['dust_accumulation', 'lack_of_ventilation'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['dust'],
    mechanismOfInjuryIndicators: ['respiratory_disease'],
    exposureIndicators: ['worker_inhalation'],
    missingOrFailedControlIndicators: ['dust_suppression', 'respiratory_protection'],
    criticalEvidenceQuestions: ['Is dust suppression active?'],
    evidenceGaps: ['exposure level'],
    controlHierarchyGuidance: ['use wet methods', 'provide respirators'],
    candidateStandardFamilies: ['industrial_hygiene'],
    correctiveActionThemes: ['dust control', 'respirator training'],
    confidenceBoosters: ['visible dust with no suppression'],
    confidenceReducers: ['wet methods active'],
    semanticConflictTriggers: ['dust suppression active'],
    humanReviewTriggers: ['industrial hygiene review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'welding_fume_exposure',
    title: 'Welding fume exposure',
    domain: 'industrial_hygiene',
    applicableIndustries: ['manufacturing', 'construction'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['welding fumes', 'smoke', 'fume'],
    equipmentIndicators: ['welder'],
    taskIndicators: ['welding'],
    unsafeConditionIndicators: ['no_exhaust', 'poor_fume_removal'],
    operationalStateIndicators: ['welding'],
    energySourceIndicators: ['fumes'],
    mechanismOfInjuryIndicators: ['respiratory_disease'],
    exposureIndicators: ['welder_inhalation'],
    missingOrFailedControlIndicators: ['exhaust_ventilation', 'respiratory_protection'],
    criticalEvidenceQuestions: ['Is localized exhaust ventilation used?'],
    evidenceGaps: ['ventilation performance'],
    controlHierarchyGuidance: ['use localized exhaust', 'wear respirators'],
    candidateStandardFamilies: ['industrial_hygiene'],
    correctiveActionThemes: ['ventilation repair', 'fume control'],
    confidenceBoosters: ['welding fumes in enclosed space'],
    confidenceReducers: ['ventilation used'],
    semanticConflictTriggers: ['exhaust ventilation running'],
    humanReviewTriggers: ['industrial hygiene review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'noise_exposure_uncertainty',
    title: 'Noise exposure uncertainty',
    domain: 'industrial_hygiene',
    applicableIndustries: ['manufacturing', 'mining'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['too loud', 'noise', 'hearing protection'],
    equipmentIndicators: ['machinery'],
    taskIndicators: ['operation'],
    unsafeConditionIndicators: ['high_decibels', 'lack_of_hearing_protection'],
    operationalStateIndicators: ['noisy_operation'],
    energySourceIndicators: ['sound'],
    mechanismOfInjuryIndicators: ['hearing_loss'],
    exposureIndicators: ['worker_noise_exposure'],
    missingOrFailedControlIndicators: ['hearing_protection', 'engineering_noise_controls'],
    criticalEvidenceQuestions: ['Is hearing protection required?'],
    evidenceGaps: ['noise assessment'],
    controlHierarchyGuidance: ['use engineering controls', 'provide hearing protection'],
    candidateStandardFamilies: ['industrial_hygiene'],
    correctiveActionThemes: ['noise survey', 'provide hearing protection'],
    confidenceBoosters: ['very high noise without protection'],
    confidenceReducers: ['hearing protection worn'],
    semanticConflictTriggers: ['hearing protection worn'],
    humanReviewTriggers: ['industrial hygiene review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'heat_stress_exposure',
    title: 'Heat stress exposure',
    domain: 'industrial_hygiene',
    applicableIndustries: ['construction', 'industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['hot', 'heat stress', 'heat exhaustion'],
    equipmentIndicators: ['temp_monitor'],
    taskIndicators: ['outdoor_work'],
    unsafeConditionIndicators: ['high_temperature', 'lack_of_hydration'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['thermal'],
    mechanismOfInjuryIndicators: ['heat_stress'],
    exposureIndicators: ['worker'],
    missingOrFailedControlIndicators: ['rest_breaks', 'water'],
    criticalEvidenceQuestions: ['Is water and shade available?'],
    evidenceGaps: ['hydration access'],
    controlHierarchyGuidance: ['provide water', 'take breaks'],
    candidateStandardFamilies: ['industrial_hygiene'],
    correctiveActionThemes: ['heat stress training', 'provide hydration/shade'],
    confidenceBoosters: ['high heat with no water'],
    confidenceReducers: ['water and shade provided'],
    semanticConflictTriggers: ['rest breaks taken'],
    humanReviewTriggers: ['industrial hygiene review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'crane_outrigger_ground_stability',
    title: 'Crane outrigger or ground stability gap',
    domain: 'cranes_rigging_hoisting',
    applicableIndustries: ['construction', 'mining'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['unstable ground', 'no outrigger mats', 'sinking outrigger'],
    equipmentIndicators: ['crane', 'outrigger'],
    taskIndicators: ['lifting'],
    unsafeConditionIndicators: ['sinking outrigger'],
    operationalStateIndicators: ['lifting'],
    energySourceIndicators: ['mechanical', 'gravity'],
    mechanismOfInjuryIndicators: ['crane_tipover'],
    exposureIndicators: ['worker near crane'],
    missingOrFailedControlIndicators: ['mats', 'ground stabilization'],
    criticalEvidenceQuestions: ['Are mats used?', 'Is ground stable?'],
    evidenceGaps: ['outrigger stabilization'],
    controlHierarchyGuidance: ['stabilize ground'],
    candidateStandardFamilies: ['cranes_rigging'],
    correctiveActionThemes: ['crane stabilization'],
    confidenceBoosters: ['sinking outrigger'],
    confidenceReducers: ['mats used'],
    semanticConflictTriggers: ['stable'],
    humanReviewTriggers: ['crane setup review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'hoist_limit_or_load_control_gap',
    title: 'Hoist limit or load control gap',
    domain: 'cranes_rigging_hoisting',
    applicableIndustries: ['construction', 'mining', 'manufacturing'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['no load limit', 'uncontrolled load'],
    equipmentIndicators: ['hoist'],
    taskIndicators: ['lifting'],
    unsafeConditionIndicators: ['uncontrolled load'],
    operationalStateIndicators: ['lifting'],
    energySourceIndicators: ['mechanical', 'gravity'],
    mechanismOfInjuryIndicators: ['struck_by'],
    exposureIndicators: ['worker'],
    missingOrFailedControlIndicators: ['hoist limit'],
    criticalEvidenceQuestions: ['Is hoist limit functional?'],
    evidenceGaps: ['hoist control'],
    controlHierarchyGuidance: ['test hoist'],
    candidateStandardFamilies: ['cranes_rigging'],
    correctiveActionThemes: ['hoist inspection'],
    confidenceBoosters: ['uncontrolled load'],
    confidenceReducers: ['hoist tested'],
    semanticConflictTriggers: ['controlled'],
    humanReviewTriggers: ['hoist review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'sharps_or_needle_exposure',
    title: 'Sharps or needle exposure gap',
    domain: 'bloodborne_pathogens',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['used needle', 'sharps'],
    equipmentIndicators: ['needle'],
    taskIndicators: ['handling'],
    unsafeConditionIndicators: ['exposed needle'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['biological'],
    mechanismOfInjuryIndicators: ['sharps_injury'],
    exposureIndicators: ['sharps contact'],
    missingOrFailedControlIndicators: ['sharps container'],
    criticalEvidenceQuestions: ['Is sharps container available?'],
    evidenceGaps: ['disposal'],
    controlHierarchyGuidance: ['use container'],
    candidateStandardFamilies: ['bloodborne_pathogens'],
    correctiveActionThemes: ['sharps disposal'],
    confidenceBoosters: ['exposed needle'],
    confidenceReducers: ['container used'],
    semanticConflictTriggers: ['contained'],
    humanReviewTriggers: ['sharps review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'blood_or_body_fluid_cleanup',
    title: 'Blood or body fluid cleanup gap',
    domain: 'bloodborne_pathogens',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['blood cleanup'],
    equipmentIndicators: ['PPE'],
    taskIndicators: ['cleanup'],
    unsafeConditionIndicators: ['no PPE'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['biological'],
    mechanismOfInjuryIndicators: ['inhalation_or_contact'],
    exposureIndicators: ['cleanup'],
    missingOrFailedControlIndicators: ['PPE'],
    criticalEvidenceQuestions: ['Is PPE worn?'],
    evidenceGaps: ['PPE'],
    controlHierarchyGuidance: ['use PPE'],
    candidateStandardFamilies: ['bloodborne_pathogens'],
    correctiveActionThemes: ['cleanup'],
    confidenceBoosters: ['no PPE'],
    confidenceReducers: ['PPE worn'],
    semanticConflictTriggers: ['protected'],
    humanReviewTriggers: ['cleanup review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'contaminated_sharps_disposal_gap',
    title: 'Contaminated sharps disposal gap',
    domain: 'bloodborne_pathogens',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['improper disposal'],
    equipmentIndicators: ['sharps container'],
    taskIndicators: ['disposal'],
    unsafeConditionIndicators: ['improper disposal'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['biological'],
    mechanismOfInjuryIndicators: ['sharps_injury'],
    exposureIndicators: ['sharps handling'],
    missingOrFailedControlIndicators: ['container'],
    criticalEvidenceQuestions: ['Is approved container used?'],
    evidenceGaps: ['container'],
    controlHierarchyGuidance: ['use container'],
    candidateStandardFamilies: ['bloodborne_pathogens'],
    correctiveActionThemes: ['disposal'],
    confidenceBoosters: ['improper disposal'],
    confidenceReducers: ['container used'],
    semanticConflictTriggers: ['contained'],
    humanReviewTriggers: ['disposal review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'repetitive_force_posture_exposure',
    title: 'Repetitive force posture exposure',
    domain: 'ergonomics',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['repetitive motion'],
    equipmentIndicators: ['workstation'],
    taskIndicators: ['work'],
    unsafeConditionIndicators: ['repetitive'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['musculoskeletal_disorder'],
    exposureIndicators: ['motion'],
    missingOrFailedControlIndicators: ['ergonomic'],
    criticalEvidenceQuestions: ['Is workstation adjustable?'],
    evidenceGaps: ['adjustment'],
    controlHierarchyGuidance: ['adjust workstation'],
    candidateStandardFamilies: ['ergonomics'],
    correctiveActionThemes: ['ergonomic improvement'],
    confidenceBoosters: ['repetitive motion'],
    confidenceReducers: ['ergonomic assist'],
    semanticConflictTriggers: ['ergonomic'],
    humanReviewTriggers: ['ergonomic review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'manual_material_handling_overexertion',
    title: 'Manual material handling overexertion gap',
    domain: 'ergonomics',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['heavy lifting'],
    equipmentIndicators: ['load'],
    taskIndicators: ['lifting'],
    unsafeConditionIndicators: ['heavy'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['strains'],
    exposureIndicators: ['lifting'],
    missingOrFailedControlIndicators: ['assist'],
    criticalEvidenceQuestions: ['Is load weight clear?'],
    evidenceGaps: ['weight'],
    controlHierarchyGuidance: ['use assist'],
    candidateStandardFamilies: ['ergonomics'],
    correctiveActionThemes: ['mechanical assist'],
    confidenceBoosters: ['heavy lifting'],
    confidenceReducers: ['assist used'],
    semanticConflictTriggers: ['assist used'],
    humanReviewTriggers: ['lifting review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'awkward_reach_workstation_design',
    title: 'Awkward reach workstation design gap',
    domain: 'ergonomics',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['awkward reach'],
    equipmentIndicators: ['workstation'],
    taskIndicators: ['work'],
    unsafeConditionIndicators: ['awkward reach'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['musculoskeletal_disorder'],
    exposureIndicators: ['reaching'],
    missingOrFailedControlIndicators: ['design'],
    criticalEvidenceQuestions: ['Is reach within limits?'],
    evidenceGaps: ['reach'],
    controlHierarchyGuidance: ['redesign workstation'],
    candidateStandardFamilies: ['ergonomics'],
    correctiveActionThemes: ['redesign workstation'],
    confidenceBoosters: ['awkward reach'],
    confidenceReducers: ['good design'],
    semanticConflictTriggers: ['ergonomic design'],
    humanReviewTriggers: ['ergonomic design review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'respirable_dust_or_silica_exposure',
    title: 'Respirable dust or silica exposure gap',
    domain: 'industrial_hygiene',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['dust', 'silica'],
    equipmentIndicators: ['dust collector'],
    taskIndicators: ['work'],
    unsafeConditionIndicators: ['dust'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['inhalation'],
    exposureIndicators: ['dust'],
    missingOrFailedControlIndicators: ['collector'],
    criticalEvidenceQuestions: ['Is dust collector used?'],
    evidenceGaps: ['dust'],
    controlHierarchyGuidance: ['improve dust control'],
    candidateStandardFamilies: ['industrial_hygiene'],
    correctiveActionThemes: ['dust control'],
    confidenceBoosters: ['dust'],
    confidenceReducers: ['dust collector used'],
    semanticConflictTriggers: ['dust free'],
    humanReviewTriggers: ['IH review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'welding_fume_exposure',
    title: 'Welding fume exposure gap',
    domain: 'industrial_hygiene',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['welding fumes'],
    equipmentIndicators: ['welder'],
    taskIndicators: ['welding'],
    unsafeConditionIndicators: ['fumes'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['thermal'],
    mechanismOfInjuryIndicators: ['inhalation'],
    exposureIndicators: ['fumes'],
    missingOrFailedControlIndicators: ['ventilation'],
    criticalEvidenceQuestions: ['Is ventilation running?'],
    evidenceGaps: ['fumes'],
    controlHierarchyGuidance: ['improve ventilation'],
    candidateStandardFamilies: ['industrial_hygiene'],
    correctiveActionThemes: ['fume control'],
    confidenceBoosters: ['welding fumes'],
    confidenceReducers: ['ventilation running'],
    semanticConflictTriggers: ['ventilated'],
    humanReviewTriggers: ['IH review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'noise_exposure_uncertainty',
    title: 'Noise exposure uncertainty gap',
    domain: 'industrial_hygiene',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['loud noise'],
    equipmentIndicators: ['machinery'],
    taskIndicators: ['work'],
    unsafeConditionIndicators: ['loud'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['noise'],
    mechanismOfInjuryIndicators: ['hearing_loss'],
    exposureIndicators: ['noise'],
    missingOrFailedControlIndicators: ['hearing protection'],
    criticalEvidenceQuestions: ['Is hearing protection worn?'],
    evidenceGaps: ['noise'],
    controlHierarchyGuidance: ['wear hearing protection'],
    candidateStandardFamilies: ['industrial_hygiene'],
    correctiveActionThemes: ['hearing protection'],
    confidenceBoosters: ['loud noise'],
    confidenceReducers: ['protection worn'],
    semanticConflictTriggers: ['quiet'],
    humanReviewTriggers: ['IH review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'heat_stress_exposure',
    title: 'Heat stress exposure gap',
    domain: 'industrial_hygiene',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['hot'],
    equipmentIndicators: ['environment'],
    taskIndicators: ['work'],
    unsafeConditionIndicators: ['hot'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['thermal'],
    mechanismOfInjuryIndicators: ['heat_stress'],
    exposureIndicators: ['heat'],
    missingOrFailedControlIndicators: ['rest/water/shade'],
    criticalEvidenceQuestions: ['Is rest provided?'],
    evidenceGaps: ['heat'],
    controlHierarchyGuidance: ['provide rest'],
    candidateStandardFamilies: ['industrial_hygiene'],
    correctiveActionThemes: ['heat management'],
    confidenceBoosters: ['hot'],
    confidenceReducers: ['rest provided'],
    semanticConflictTriggers: ['cool'],
    humanReviewTriggers: ['IH review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'ppe_missing_gap',
    title: 'PPE missing or inadequate for task',
    domain: 'ppe',
    applicableIndustries: ['construction', 'industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['missing PPE', 'inadequate PPE'],
    equipmentIndicators: [],
    taskIndicators: [],
    unsafeConditionIndicators: ['missing PPE'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['various'],
    exposureIndicators: ['worker exposed'],
    missingOrFailedControlIndicators: ['ppe'],
    criticalEvidenceQuestions: ['Is PPE required?'],
    evidenceGaps: ['ppe status'],
    controlHierarchyGuidance: ['provide PPE'],
    candidateStandardFamilies: ['ppe'],
    correctiveActionThemes: ['provide PPE'],
    confidenceBoosters: ['missing PPE observed'],
    confidenceReducers: ['PPE provided'],
    semanticConflictTriggers: ['PPE worn'],
    humanReviewTriggers: ['PPE review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'hazardous_materials_handling_gap',
    title: 'Hazardous materials handling deficiency',
    domain: 'hazardous_materials',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['unlabeled hazmat', 'missing hazmat procedure'],
    equipmentIndicators: ['container'],
    taskIndicators: ['handling'],
    unsafeConditionIndicators: ['unlabeled'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['chemical'],
    mechanismOfInjuryIndicators: ['chemical_exposure'],
    exposureIndicators: ['worker exposure'],
    missingOrFailedControlIndicators: ['labeling'],
    criticalEvidenceQuestions: ['Is material identified?'],
    evidenceGaps: ['hazmat identity'],
    controlHierarchyGuidance: ['label hazmat'],
    candidateStandardFamilies: ['hazardous_materials'],
    correctiveActionThemes: ['labeling', 'sds provided'],
    confidenceBoosters: ['unlabeled hazmat'],
    confidenceReducers: ['labeled'],
    semanticConflictTriggers: ['identified'],
    humanReviewTriggers: ['hazmat review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'health_respiratory_protection_gap',
    title: 'Respiratory protection deficiency',
    domain: 'health_respiratory',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['no respirator'],
    equipmentIndicators: ['respirator'],
    taskIndicators: ['work'],
    unsafeConditionIndicators: ['no respirator'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['chemical'],
    mechanismOfInjuryIndicators: ['respiratory_exposure'],
    exposureIndicators: ['inhalation'],
    missingOrFailedControlIndicators: ['respirator'],
    criticalEvidenceQuestions: ['Is respirator required?'],
    evidenceGaps: ['exposure'],
    controlHierarchyGuidance: ['use respirator'],
    candidateStandardFamilies: ['health_respiratory'],
    correctiveActionThemes: ['respiratory protection'],
    confidenceBoosters: ['no respirator'],
    confidenceReducers: ['respirator used'],
    semanticConflictTriggers: ['used'],
    humanReviewTriggers: ['respiratory review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'material_handling_safe_lifting_gap',
    title: 'Material handling lifting deficiency',
    domain: 'material_handling',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['improper lift'],
    equipmentIndicators: ['material'],
    taskIndicators: ['lifting'],
    unsafeConditionIndicators: ['improper lift'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['gravity'],
    mechanismOfInjuryIndicators: ['strains'],
    exposureIndicators: ['lifting'],
    missingOrFailedControlIndicators: ['lifting technique'],
    criticalEvidenceQuestions: ['Is load weight clear?'],
    evidenceGaps: ['weight'],
    controlHierarchyGuidance: ['mechanical assist'],
    candidateStandardFamilies: ['material_handling'],
    correctiveActionThemes: ['mechanical assist'],
    confidenceBoosters: ['improper lift'],
    confidenceReducers: ['mechanical assist used'],
    semanticConflictTriggers: ['assist used'],
    humanReviewTriggers: ['lifting review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'roof_rib_control_stability_gap',
    title: 'Roof rib control stability deficiency',
    domain: 'roof_rib_control',
    applicableIndustries: ['mining'],
    applicableJurisdictions: ['msha'],
    commonObservationPhrases: ['unstable rib'],
    equipmentIndicators: ['rib'],
    taskIndicators: ['work'],
    unsafeConditionIndicators: ['unstable'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['gravity'],
    mechanismOfInjuryIndicators: ['struck_by'],
    exposureIndicators: ['working'],
    missingOrFailedControlIndicators: ['support'],
    criticalEvidenceQuestions: ['Is rib supported?'],
    evidenceGaps: ['stability'],
    controlHierarchyGuidance: ['support'],
    candidateStandardFamilies: ['roof_rib_control'],
    correctiveActionThemes: ['install support'],
    confidenceBoosters: ['unstable rib'],
    confidenceReducers: ['supported'],
    semanticConflictTriggers: ['stable'],
    humanReviewTriggers: ['roof control review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'trenching_and_excavation_cavein_gap',
    title: 'Trenching excavation cave-in deficiency',
    domain: 'trenching_and_excavation',
    applicableIndustries: ['construction'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['no shoring'],
    equipmentIndicators: ['trench'],
    taskIndicators: ['excavation'],
    unsafeConditionIndicators: ['no shoring'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['gravity'],
    mechanismOfInjuryIndicators: ['cave_in'],
    exposureIndicators: ['worker'],
    missingOrFailedControlIndicators: ['shoring'],
    criticalEvidenceQuestions: ['Is shoring used?'],
    evidenceGaps: ['protection'],
    controlHierarchyGuidance: ['use shoring'],
    candidateStandardFamilies: ['trenching_and_excavation'],
    correctiveActionThemes: ['install shoring'],
    confidenceBoosters: ['no shoring'],
    confidenceReducers: ['shoring used'],
    semanticConflictTriggers: ['shored'],
    humanReviewTriggers: ['excavation review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'ventilation_airflow_gap',
    title: 'Ventilation airflow deficiency',
    domain: 'ventilation',
    applicableIndustries: ['mining'],
    applicableJurisdictions: ['msha'],
    commonObservationPhrases: ['low airflow'],
    equipmentIndicators: ['ventilation'],
    taskIndicators: ['work'],
    unsafeConditionIndicators: ['low airflow'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['ventilation'],
    mechanismOfInjuryIndicators: ['inhalation'],
    exposureIndicators: ['work'],
    missingOrFailedControlIndicators: ['ventilation'],
    criticalEvidenceQuestions: ['Is airflow measured?'],
    evidenceGaps: ['airflow'],
    controlHierarchyGuidance: ['improve ventilation'],
    candidateStandardFamilies: ['ventilation'],
    correctiveActionThemes: ['improve ventilation'],
    confidenceBoosters: ['low airflow'],
    confidenceReducers: ['good airflow'],
    semanticConflictTriggers: ['adequate'],
    humanReviewTriggers: ['ventilation review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'confined_space_atmosphere_gap',
    title: 'Confined space atmosphere deficiency',
    domain: 'confined_space',
    applicableIndustries: ['industrial'],
    applicableJurisdictions: ['osha'],
    commonObservationPhrases: ['untested atmosphere'],
    equipmentIndicators: ['confined space'],
    taskIndicators: ['entry'],
    unsafeConditionIndicators: ['untested'],
    operationalStateIndicators: ['active'],
    energySourceIndicators: ['chemical'],
    mechanismOfInjuryIndicators: ['inhalation'],
    exposureIndicators: ['entry'],
    missingOrFailedControlIndicators: ['testing'],
    criticalEvidenceQuestions: ['Is atmosphere tested?'],
    evidenceGaps: ['atmosphere'],
    controlHierarchyGuidance: ['test atmosphere'],
    candidateStandardFamilies: ['confined_space'],
    correctiveActionThemes: ['test atmosphere'],
    confidenceBoosters: ['untested'],
    confidenceReducers: ['tested'],
    semanticConflictTriggers: ['safe'],
    humanReviewTriggers: ['confined space review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },

  {
    id: 'emergency_exit_alarm_response_gap',
    title: 'Emergency exit, alarm, or response readiness gap',
    domain: 'emergency_preparedness',
    applicableIndustries: ['industrial', 'construction', 'mining', 'manufacturing'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['blocked exit', 'exit access', 'emergency alarm', 'evacuation route', 'muster point', 'emergency lighting', 'exit sign'],
    equipmentIndicators: ['exit door', 'alarm panel', 'emergency light', 'exit sign', 'eyewash', 'shower'],
    taskIndicators: ['evacuation', 'emergency response', 'inspection', 'maintenance'],
    unsafeConditionIndicators: ['blocked exit', 'alarm not audible', 'missing emergency light', 'obstructed emergency equipment', 'unclear evacuation route'],
    operationalStateIndicators: ['occupied area', 'active work area'],
    energySourceIndicators: ['emergency condition', 'fire', 'chemical release'],
    mechanismOfInjuryIndicators: ['delayed_egress', 'delayed_emergency_response', 'secondary_exposure'],
    exposureIndicators: ['employees in occupied area', 'responders', 'workers relying on emergency route'],
    missingOrFailedControlIndicators: ['clear exit route', 'alarm communication', 'emergency lighting', 'response procedure'],
    criticalEvidenceQuestions: ['Is the exit route fully clear?', 'Are alarms/emergency lights functional?', 'Is emergency equipment accessible?'],
    evidenceGaps: ['exit clearance', 'alarm function', 'emergency lighting', 'response equipment access'],
    controlHierarchyGuidance: ['clear exit route', 'restore emergency alarm/lighting', 'verify emergency equipment access'],
    candidateStandardFamilies: ['emergency_preparedness', 'emergency_response'],
    correctiveActionThemes: ['restore exit clearance', 'repair alarm or lighting', 'verify emergency response readiness'],
    confidenceBoosters: ['blocked exit route in occupied work area', 'emergency shower blocked by stored material'],
    confidenceReducers: ['temporary staging outside exit path', 'route clearly marked and unobstructed'],
    semanticConflictTriggers: ['exit clear', 'alarm tested', 'emergency light functional'],
    humanReviewTriggers: ['emergency response readiness review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'ppe_selection_use_gap',
    title: 'PPE selection, condition, or use gap',
    domain: 'ppe',
    applicableIndustries: ['industrial', 'construction', 'mining', 'manufacturing'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['no eye protection', 'no gloves', 'wrong gloves', 'damaged ppe', 'missing face shield', 'no hearing protection', 'no respirator'],
    equipmentIndicators: ['gloves', 'goggles', 'face shield', 'hard hat', 'respirator', 'hearing protection', 'fall harness'],
    taskIndicators: ['chemical handling', 'grinding', 'cutting', 'welding', 'noise exposure', 'dust exposure', 'maintenance'],
    unsafeConditionIndicators: ['missing ppe', 'damaged ppe', 'wrong ppe for hazard', 'ppe not worn'],
    operationalStateIndicators: ['active task', 'exposure present'],
    energySourceIndicators: ['chemical', 'mechanical', 'noise', 'thermal', 'biological'],
    mechanismOfInjuryIndicators: ['eye_injury', 'skin_contact', 'inhalation_exposure', 'hearing_loss', 'burn'],
    exposureIndicators: ['employee performing task', 'employee near exposure source'],
    missingOrFailedControlIndicators: ['hazard assessment', 'ppe selection', 'ppe inspection', 'training'],
    criticalEvidenceQuestions: ['What hazard is the PPE intended to control?', 'Is PPE matched to the exposure and task?', 'Is the PPE serviceable and worn correctly?'],
    evidenceGaps: ['hazard assessment', 'ppe type', 'ppe condition', 'task exposure'],
    controlHierarchyGuidance: ['control hazard at source before relying on PPE', 'select PPE based on hazard assessment', 'verify PPE condition and use'],
    candidateStandardFamilies: ['ppe'],
    correctiveActionThemes: ['complete PPE hazard assessment', 'provide correct PPE', 'replace damaged PPE', 'verify training and fit/use'],
    confidenceBoosters: ['employee grinding without eye/face protection', 'chemical handling without compatible gloves'],
    confidenceReducers: ['PPE present and worn correctly', 'task performed without exposure'],
    semanticConflictTriggers: ['ppe worn correctly', 'hazard eliminated', 'task stopped'],
    humanReviewTriggers: ['ppe hazard assessment review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'hazardous_materials_storage_compatibility_gap',
    title: 'Hazardous materials storage, compatibility, or secondary containment gap',
    domain: 'hazardous_materials',
    applicableIndustries: ['industrial', 'construction', 'mining', 'manufacturing'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['chemical storage', 'incompatible chemicals', 'flammable cabinet', 'secondary containment', 'leaking drum', 'unlabeled drum'],
    equipmentIndicators: ['drum', 'chemical container', 'flammable cabinet', 'secondary containment pallet', 'tank', 'IBC tote'],
    taskIndicators: ['storage', 'transfer', 'handling', 'spill cleanup'],
    unsafeConditionIndicators: ['leaking container', 'incompatible storage', 'no containment', 'unknown contents', 'damaged container'],
    operationalStateIndicators: ['stored material', 'active transfer'],
    energySourceIndicators: ['chemical_energy', 'flammable_material', 'pressure'],
    mechanismOfInjuryIndicators: ['chemical_burn', 'fire_or_explosion', 'inhalation_exposure', 'skin_absorption'],
    exposureIndicators: ['employees storing or transferring material', 'nearby workers', 'emergency responders'],
    missingOrFailedControlIndicators: ['labeling', 'segregation', 'secondary_containment', 'compatible_storage'],
    criticalEvidenceQuestions: ['What material is stored?', 'Are incompatible materials separated?', 'Is secondary containment adequate?', 'Is the container intact and labeled?'],
    evidenceGaps: ['chemical identity', 'compatibility', 'containment', 'container condition'],
    controlHierarchyGuidance: ['identify material', 'segregate incompatibles', 'repair or replace leaking containers', 'provide containment'],
    candidateStandardFamilies: ['hazardous_materials', 'hazard_communication'],
    correctiveActionThemes: ['label material', 'segregate storage', 'restore containment', 'repair leaking container'],
    confidenceBoosters: ['leaking unlabeled drum near work area', 'acid and oxidizer stored together without segregation'],
    confidenceReducers: ['materials labeled and segregated in approved storage'],
    semanticConflictTriggers: ['compatible storage verified', 'secondary containment present', 'container intact'],
    humanReviewTriggers: ['hazardous material storage review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'health_respiratory_program_gap',
    title: 'Respiratory protection selection, fit, or program gap',
    domain: 'health_respiratory',
    applicableIndustries: ['industrial', 'construction', 'mining', 'manufacturing'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['respirator', 'dust mask', 'N95', 'half mask', 'fit test', 'cartridge', 'respiratory protection'],
    equipmentIndicators: ['respirator', 'filter cartridge', 'N95', 'PAPR', 'dust mask'],
    taskIndicators: ['grinding', 'cutting', 'painting', 'spraying', 'dusty task', 'chemical handling'],
    unsafeConditionIndicators: ['wrong respirator', 'no fit test', 'unknown cartridge', 'dust mask used for chemical vapor', 'facial hair seal issue'],
    operationalStateIndicators: ['active exposure', 'respirator in use'],
    energySourceIndicators: ['atmospheric_hazard', 'chemical_energy', 'respirable_dust'],
    mechanismOfInjuryIndicators: ['inhalation_exposure', 'silica_or_dust_disease', 'chemical_exposure'],
    exposureIndicators: ['employee wearing or needing respirator', 'employee near airborne contaminant'],
    missingOrFailedControlIndicators: ['exposure_assessment', 'respirator_selection', 'fit_testing', 'medical_clearance', 'cartridge_changeout'],
    criticalEvidenceQuestions: ['What contaminant is present?', 'Has exposure been assessed?', 'Is the respirator selected for the contaminant?', 'Are fit test and program elements verified?'],
    evidenceGaps: ['contaminant identity', 'exposure level', 'respirator type', 'fit test status', 'cartridge selection'],
    controlHierarchyGuidance: ['control exposure at source first', 'select respirator from exposure assessment', 'verify program requirements'],
    candidateStandardFamilies: ['health_respiratory', 'industrial_hygiene'],
    correctiveActionThemes: ['conduct exposure assessment', 'select correct respirator', 'verify fit test and training', 'confirm cartridge/filter changeout'],
    confidenceBoosters: ['employee spraying solvent with dust mask', 'silica dust task with no respirator program evidence'],
    confidenceReducers: ['source controls effective and respirator program documented'],
    semanticConflictTriggers: ['fit tested', 'correct cartridge verified', 'exposure controlled below need for respirator'],
    humanReviewTriggers: ['respiratory protection program review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'roof_rib_highwall_loose_material_gap',
    title: 'Roof, rib, highwall, or loose material stability gap',
    domain: 'roof_rib_control',
    applicableIndustries: ['mining', 'construction', 'quarry', 'tunneling'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['loose rock', 'highwall', 'rib', 'roof control', 'scaling', 'falling material', 'ground condition'],
    equipmentIndicators: ['highwall', 'rib', 'roof', 'bench', 'slope', 'scaler'],
    taskIndicators: ['inspection', 'scaling', 'drilling', 'loading', 'travelway work', 'maintenance'],
    unsafeConditionIndicators: ['loose material', 'unsupported ground', 'cracks', 'sloughing', 'overhang', 'unscaled area'],
    operationalStateIndicators: ['active work area', 'travelway open'],
    energySourceIndicators: ['gravity', 'geologic_instability'],
    mechanismOfInjuryIndicators: ['struck_by_falling_material', 'crush', 'engulfment'],
    exposureIndicators: ['worker below loose material', 'equipment operator near highwall', 'travelway users'],
    missingOrFailedControlIndicators: ['ground examination', 'scaling', 'barricade', 'support', 'setback'],
    criticalEvidenceQuestions: ['Has the area been examined by a competent/qualified person?', 'Is loose material scaled or barricaded?', 'Are workers positioned outside the fall zone?'],
    evidenceGaps: ['ground exam', 'loose material condition', 'worker position', 'barricade or scaling status'],
    controlHierarchyGuidance: ['remove workers from fall zone', 'barricade unstable ground', 'scale or support loose material', 'document examination'],
    candidateStandardFamilies: ['roof_rib_control', 'ground_control'],
    correctiveActionThemes: ['restrict access', 'scale loose material', 'document ground exam', 'verify safe position'],
    confidenceBoosters: ['worker below cracked highwall with loose rock visible', 'travelway below unsupported loose material'],
    confidenceReducers: ['area scaled and barricaded', 'qualified exam documented'],
    semanticConflictTriggers: ['scaled', 'barricaded', 'no worker exposure'],
    humanReviewTriggers: ['ground control review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'fire_extinguisher_hot_work_readiness_gap',
    title: 'Fire protection, extinguisher, or hot-work readiness gap',
    domain: 'fire_protection',
    applicableIndustries: ['industrial', 'construction', 'mining', 'manufacturing'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['blocked extinguisher', 'missing extinguisher', 'hot work', 'fire watch', 'flammable storage', 'sprinkler blocked'],
    equipmentIndicators: ['fire extinguisher', 'sprinkler', 'fire alarm', 'hot work permit', 'welding equipment'],
    taskIndicators: ['hot work', 'welding', 'cutting', 'grinding', 'flammable storage'],
    unsafeConditionIndicators: ['blocked extinguisher', 'expired inspection tag', 'no fire watch', 'combustibles near hot work', 'sprinkler obstruction'],
    operationalStateIndicators: ['active hot work', 'occupied area', 'flammable storage'],
    energySourceIndicators: ['thermal_energy', 'flammable_material', 'ignition_source'],
    mechanismOfInjuryIndicators: ['fire_or_explosion', 'burn', 'smoke_inhalation'],
    exposureIndicators: ['employees performing hot work', 'nearby workers', 'emergency responders'],
    missingOrFailedControlIndicators: ['extinguisher_access', 'inspection', 'fire_watch', 'combustible_control', 'permit'],
    criticalEvidenceQuestions: ['Is the extinguisher accessible and inspected?', 'Are combustibles controlled?', 'Is fire watch or permit control needed?'],
    evidenceGaps: ['extinguisher access', 'inspection status', 'combustible clearance', 'fire watch status'],
    controlHierarchyGuidance: ['restore extinguisher access', 'remove combustibles', 'verify inspection', 'establish hot-work controls'],
    candidateStandardFamilies: ['fire_protection', 'welding_cutting_hot_work'],
    correctiveActionThemes: ['clear extinguisher access', 'inspect or replace extinguisher', 'establish fire watch', 'control combustibles'],
    confidenceBoosters: ['active hot work with combustibles nearby and no extinguisher access'],
    confidenceReducers: ['hot work permit active and fire watch present'],
    semanticConflictTriggers: ['extinguisher accessible', 'fire watch present', 'combustibles removed'],
    humanReviewTriggers: ['fire protection readiness review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  }
,

  {
    id: 'emergency_eyewash_shower_access_gap',
    title: 'Emergency eyewash or shower access/readiness gap',
    domain: 'emergency_preparedness',
    applicableIndustries: ['industrial', 'manufacturing', 'laboratory', 'maintenance'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['eyewash blocked', 'safety shower blocked', 'emergency shower', 'eyewash station', 'chemical splash', 'plumbed eyewash'],
    equipmentIndicators: ['eyewash', 'safety shower', 'drench hose', 'chemical station'],
    taskIndicators: ['chemical handling', 'battery charging', 'corrosive transfer', 'maintenance', 'cleanup'],
    unsafeConditionIndicators: ['blocked access', 'not tested', 'missing inspection tag', 'low flow', 'obstructed shower', 'no emergency rinse'],
    operationalStateIndicators: ['chemical exposure potential', 'occupied area'],
    energySourceIndicators: ['chemical_energy'],
    mechanismOfInjuryIndicators: ['chemical_burn', 'delayed_emergency_response'],
    exposureIndicators: ['employees handling corrosives', 'nearby workers', 'maintenance employees'],
    missingOrFailedControlIndicators: ['emergency eyewash access', 'emergency shower access', 'inspection or test verification'],
    criticalEvidenceQuestions: ['Is emergency rinse equipment immediately accessible?', 'Has flow/function been verified?', 'What chemical exposure requires emergency rinse capability?'],
    evidenceGaps: ['chemical exposure type', 'equipment access', 'flow/function test', 'inspection status'],
    controlHierarchyGuidance: ['restore immediate access', 'verify eyewash/shower flow', 'match emergency equipment to chemical exposure'],
    candidateStandardFamilies: ['emergency_preparedness', 'hazardous_materials'],
    correctiveActionThemes: ['clear eyewash/shower access', 'test emergency equipment', 'document inspection', 'verify chemical exposure controls'],
    confidenceBoosters: ['corrosive chemical handling with blocked eyewash', 'safety shower inaccessible during chemical transfer'],
    confidenceReducers: ['eyewash accessible and test current', 'no corrosive or splash exposure'],
    semanticConflictTriggers: ['eyewash clear', 'shower tested', 'chemical exposure removed'],
    humanReviewTriggers: ['chemical emergency readiness review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'emergency_action_plan_communication_gap',
    title: 'Emergency action plan communication or drill readiness gap',
    domain: 'emergency_preparedness',
    applicableIndustries: ['industrial', 'construction', 'mining', 'manufacturing'],
    applicableJurisdictions: ['osha', 'msha'],
    commonObservationPhrases: ['no evacuation plan', 'no muster point', 'employees do not know alarm', 'emergency drill', 'no emergency contact', 'unclear evacuation route'],
    equipmentIndicators: ['alarm', 'radio', 'muster board', 'evacuation map', 'emergency contact list'],
    taskIndicators: ['emergency planning', 'evacuation', 'training', 'drill', 'incident response'],
    unsafeConditionIndicators: ['unclear procedure', 'missing emergency contact', 'no drill record', 'employees unaware of alarm', 'unclear muster point'],
    operationalStateIndicators: ['occupied area', 'multi-employer worksite', 'active operation'],
    energySourceIndicators: ['emergency condition', 'fire', 'chemical release', 'severe weather'],
    mechanismOfInjuryIndicators: ['delayed_egress', 'delayed_emergency_response', 'secondary_exposure'],
    exposureIndicators: ['employees relying on emergency instructions', 'contractors or visitors'],
    missingOrFailedControlIndicators: ['emergency communication', 'training', 'evacuation procedure', 'muster accountability'],
    criticalEvidenceQuestions: ['Do employees know alarm signals and evacuation routes?', 'Is the muster/accountability process defined?', 'Are emergency contacts and procedures current?'],
    evidenceGaps: ['employee awareness', 'alarm meaning', 'muster location', 'emergency contact list', 'drill/training record'],
    controlHierarchyGuidance: ['communicate emergency procedures', 'verify alarm recognition', 'conduct drill or briefing', 'post current emergency contacts'],
    candidateStandardFamilies: ['emergency_preparedness', 'training_procedure_gap'],
    correctiveActionThemes: ['update emergency action plan', 'brief employees and contractors', 'post evacuation/muster information', 'document emergency drill or training'],
    confidenceBoosters: ['employees cannot identify alarm response', 'no posted evacuation route in occupied facility'],
    confidenceReducers: ['recent drill documented and emergency map posted'],
    semanticConflictTriggers: ['drill completed', 'employees briefed', 'evacuation route posted'],
    humanReviewTriggers: ['emergency planning review'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  }

];
