import { ScenarioFamilyKnowledgeRecord } from './scenario-family.types';

export const SCENARIO_FAMILY_REGISTRY: ScenarioFamilyKnowledgeRecord[] = [
  {
    id: 'conveyor-cleanup',
    title: 'Conveyor cleanup near moving parts',
    domain: 'machine_guarding',
    applicableIndustries: ['mining', 'manufacturing'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['cleaning', 'clearing spillage', 'moving conveyor', 'missing guard', 'inadequate guard', 'nip point', 'exposed rotating parts'],
    equipmentIndicators: ['conveyor'],
    taskIndicators: ['cleanup', 'maintenance'],
    unsafeConditionIndicators: ['moving parts', 'exposed'],
    operationalStateIndicators: ['running'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['rotating_equipment_nip_point'],
    exposureIndicators: ['worker near belt'],
    missingOrFailedControlIndicators: ['guard missing', 'no LOTO'],
    criticalEvidenceQuestions: ['Is conveyor running?', 'Was LOTO applied?'],
    evidenceGaps: ['LOTO status', 'guard presence'],
    controlHierarchyGuidance: ['LOTO', 'guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['LOTO training', 'guard installation'],
    confidenceBoosters: ['clear observation of moving parts'],
    confidenceReducers: ['vague description of maintenance'],
    semanticConflictTriggers: ['not running', 'locked out'],
    humanReviewTriggers: ['high risk task'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  },
  {
    id: 'unguarded-hazard-generic',
    title: 'Generic unguarded hazard',
    domain: 'machine_guarding',
    applicableIndustries: ['mining', 'manufacturing', 'construction'],
    applicableJurisdictions: ['msha', 'osha'],
    commonObservationPhrases: ['missing guard', 'inadequate guard', 'unguarded', 'nip point', 'exposed rotating'],
    equipmentIndicators: ['conveyor', 'forklift', 'ladder', 'panel', 'tank', 'machinery'],
    taskIndicators: [],
    unsafeConditionIndicators: ['missing guard', 'unguarded'],
    operationalStateIndicators: ['operational'],
    energySourceIndicators: ['mechanical'],
    mechanismOfInjuryIndicators: ['rotating_equipment_nip_point'],
    exposureIndicators: ['access to area'],
    missingOrFailedControlIndicators: ['guarding'],
    criticalEvidenceQuestions: ['Is guard missing?', 'Is access restricted?'],
    evidenceGaps: ['access control'],
    controlHierarchyGuidance: ['guarding'],
    candidateStandardFamilies: ['machine_guarding'],
    correctiveActionThemes: ['guard installation'],
    confidenceBoosters: ['clear observation of guarding failure'],
    confidenceReducers: ['vague description'],
    semanticConflictTriggers: ['guarded'],
    humanReviewTriggers: ['high risk'],
    advisoryOnly: true,
    doesNotDeclareViolation: true,
    requiresQualifiedReview: true
  }
];
