import { SafeScopeEquipmentKnowledgeRegistry } from './equipment-knowledge.types';

export const SAFESCOPE_EQUIPMENT_KNOWLEDGE_REGISTRY: SafeScopeEquipmentKnowledgeRegistry = {
  engine: 'safescope_equipment_knowledge_registry_v1',
  mode: 'read_only_test_only_context',
  guardrails: {
    readOnly: true,
    contextOnly: true,
    doesNotModifyReasoning: true,
    doesNotDeclareViolation: true,
    doesNotCreateCitation: true,
    doesNotUseUnapprovedKnowledge: true,
  },
  records: [
    {
      equipmentId: 'haul_truck',
      label: 'Haul Truck',
      category: 'powered_haulage',
      aliases: ['haul truck', 'off-road truck', 'dump truck', 'rock truck', 'loaded haul truck'],
      commonJurisdictions: ['msha'],
      commonHazardDomains: ['powered_haulage', 'mobile_equipment', 'fall_protection', 'traffic_control'],
      commonScenarioTriggers: [
        'dump point',
        'berm',
        'haul road',
        'stockpile dumping',
        'backing',
        'reverse alarm',
        'traffic pattern',
        'access ladder',
      ],
      inspectionFocusAreas: [
        'haul road condition',
        'berm adequacy',
        'dump point control',
        'visibility and blind spots',
        'backup alarm or warning system',
        'seatbelt use',
        'braking and steering condition',
        'access ladder and handholds',
        'traffic pattern and separation',
      ],
      correctiveActionThemes: [
        'establish or verify traffic controls',
        'verify berm and dump-point controls',
        'separate pedestrians from haulage activity',
        'verify reverse alarm or spotter controls',
        'remove defective equipment from service pending review',
        'document objective completion evidence',
      ],
      conflictNotes: [
        'Haul truck identity alone should not automatically classify as powered haulage.',
        'Dumping, berm, haul road, stockpile, backing, and active haulage route context strengthen powered haulage classification.',
        'Access ladder or missing handhold context may classify as fall protection.',
        'Pedestrian crossing/signage/barrier context may classify as traffic control.',
      ],
      systems: [
        {
          systemId: 'haulage_controls',
          label: 'Haulage Controls',
          commonFailureModes: ['inadequate berm', 'unclear dump point', 'poor traffic pattern', 'limited visibility'],
          relatedHazardDomains: ['powered_haulage', 'traffic_control'],
          evidenceQuestions: [
            'What traffic controls, berms, dump-point controls, visibility controls, and separation methods are in place?',
            'Is the haulage route interacting with pedestrian work areas?',
          ],
          verificationEvidence: ['haul road photos', 'berm photos', 'traffic plan', 'dump point inspection notes'],
        },
        {
          systemId: 'access_system',
          label: 'Access System',
          commonFailureModes: ['damaged ladder', 'missing handhold', 'slip/trip access point'],
          relatedHazardDomains: ['fall_protection', 'walking_working_surfaces'],
          evidenceQuestions: [
            'Is the access ladder, step, platform, and handhold system intact and suitable for the task?',
          ],
          verificationEvidence: ['access ladder photo', 'handhold photo', 'repair record', 'follow-up inspection result'],
        },
      ],
      guardrails: {
        contextOnly: true,
        doesNotDeclareViolation: true,
        doesNotCreateCitation: true,
        doesNotOverrideRegulation: true,
        requiresQualifiedReview: true,
      },
    },
    {
      equipmentId: 'front_end_loader',
      label: 'Front-End Loader',
      category: 'mobile_equipment',
      aliases: ['front-end loader', 'loader', 'wheel loader'],
      commonJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
      commonHazardDomains: ['mobile_equipment', 'traffic_control', 'fall_protection'],
      commonScenarioTriggers: [
        'blind spot',
        'spotter',
        'backup alarm',
        'raised bucket',
        'pedestrian exposure',
        'pre-op inspection',
      ],
      inspectionFocusAreas: [
        'operator visibility',
        'backup alarm',
        'seatbelt',
        'brakes and steering',
        'bucket position',
        'pedestrian separation',
        'pre-operation inspection records',
      ],
      correctiveActionThemes: [
        'separate pedestrians from equipment operation',
        'verify backup alarm and visibility controls',
        'lower or secure raised attachments',
        'address pre-op defects before operation',
        'document repair and verification evidence',
      ],
      conflictNotes: [
        'Loader backing or blind spot terms generally support mobile equipment classification.',
        'Pedestrian crossing/signage/barrier context may support traffic control.',
        'Access ladder/handhold context may support fall protection.',
      ],
      systems: [
        {
          systemId: 'visibility_warning',
          label: 'Visibility and Warning Systems',
          commonFailureModes: ['blind spot', 'backup alarm not functioning', 'spotter not assigned'],
          relatedHazardDomains: ['mobile_equipment', 'traffic_control'],
          evidenceQuestions: [
            'What operator visibility, alarm, camera, mirror, spotter, and pedestrian separation controls are in place?',
          ],
          verificationEvidence: ['backup alarm test', 'spotter assignment', 'visibility control photo', 'operator confirmation'],
        },
        {
          systemId: 'attachment_position',
          label: 'Attachment Position',
          commonFailureModes: ['raised bucket near employees', 'unsecured attachment', 'crush/struck-by exposure'],
          relatedHazardDomains: ['mobile_equipment'],
          evidenceQuestions: [
            'Is the bucket or attachment lowered, secured, or controlled to prevent struck-by or crush exposure?',
          ],
          verificationEvidence: ['bucket position photo', 'operator instruction record', 'follow-up observation'],
        },
      ],
      guardrails: {
        contextOnly: true,
        doesNotDeclareViolation: true,
        doesNotCreateCitation: true,
        doesNotOverrideRegulation: true,
        requiresQualifiedReview: true,
      },
    },
    {
      equipmentId: 'forklift',
      label: 'Forklift / Powered Industrial Truck',
      category: 'mobile_equipment',
      aliases: ['forklift', 'powered industrial truck', 'lift truck'],
      commonJurisdictions: ['osha_general_industry', 'osha_construction'],
      commonHazardDomains: ['mobile_equipment', 'traffic_control', 'material_handling'],
      commonScenarioTriggers: [
        'forklift',
        'seatbelt',
        'travel path',
        'pedestrian walkway',
        'load handling',
        'operator visibility',
      ],
      inspectionFocusAreas: [
        'seatbelt/operator restraint',
        'travel path controls',
        'load stability',
        'pedestrian separation',
        'pre-use inspection',
        'backup alarm or horn',
        'operator visibility',
      ],
      correctiveActionThemes: [
        'verify pre-use inspection and remove unsafe equipment from service',
        'establish pedestrian/equipment separation',
        'verify operator restraint and visibility controls',
        'verify load handling controls',
      ],
      conflictNotes: [
        'Forklift plus seatbelt/pre-use/backing terms should generally support mobile equipment.',
        'Forklift traffic crossing pedestrian walkway with signage/barrier issues may support traffic control.',
        'Load stability or suspended/stacked material terms may support material handling.',
      ],
      systems: [
        {
          systemId: 'operator_protection',
          label: 'Operator Protection',
          commonFailureModes: ['seatbelt use unclear', 'operator restraint not used', 'visibility limitations'],
          relatedHazardDomains: ['mobile_equipment'],
          evidenceQuestions: [
            'Is the operator restraint used and are operator visibility and travel controls adequate?',
          ],
          verificationEvidence: ['operator restraint observation', 'pre-use inspection record', 'training record'],
        },
        {
          systemId: 'pedestrian_interaction',
          label: 'Pedestrian Interaction',
          commonFailureModes: ['pedestrian crossing conflict', 'no signage', 'no barrier', 'unclear right-of-way'],
          relatedHazardDomains: ['traffic_control', 'mobile_equipment'],
          evidenceQuestions: [
            'What pedestrian separation, signage, barriers, and right-of-way controls are in place?',
          ],
          verificationEvidence: ['walkway photo', 'barrier/signage photo', 'traffic plan', 'employee communication record'],
        },
      ],
      guardrails: {
        contextOnly: true,
        doesNotDeclareViolation: true,
        doesNotCreateCitation: true,
        doesNotOverrideRegulation: true,
        requiresQualifiedReview: true,
      },
    },
    {
      equipmentId: 'excavator',
      label: 'Excavator',
      category: 'construction_equipment',
      aliases: ['excavator', 'trackhoe', 'backhoe excavator', 'hydraulic excavator'],
      commonJurisdictions: ['osha_construction', 'msha', 'osha_general_industry'],
      commonHazardDomains: ['mobile_equipment', 'excavation_trenching', 'traffic_control', 'material_handling'],
      commonScenarioTriggers: [
        'swing radius',
        'excavator bucket',
        'trenching',
        'excavation',
        'working near edge',
        'spotter',
        'underground utility',
        'struck-by exposure',
      ],
      inspectionFocusAreas: [
        'swing radius control',
        'pedestrian/equipment separation',
        'bucket and attachment condition',
        'underground utility clearance',
        'trench/excavation edge distance',
        'spotter and communication controls',
        'pre-operation inspection',
      ],
      correctiveActionThemes: [
        'establish swing-radius exclusion area',
        'verify spotter and communication controls',
        'confirm excavation/trench protective requirements separately',
        'verify attachment condition and securement',
        'document pre-use inspection and correction evidence',
      ],
      conflictNotes: [
        'Excavator identity alone should not automatically classify as excavation/trenching.',
        'Trench, excavation, spoil pile, or protective-system terms strengthen excavation/trenching classification.',
        'Swing radius, spotter, and struck-by terms generally support mobile equipment or traffic control.',
      ],
      systems: [
        {
          systemId: 'swing_radius',
          label: 'Swing Radius / Counterweight Area',
          commonFailureModes: ['uncontrolled swing radius', 'pedestrians inside swing area', 'no spotter'],
          relatedHazardDomains: ['mobile_equipment', 'traffic_control'],
          evidenceQuestions: [
            'Is the swing radius controlled, barricaded, communicated, or monitored to keep employees out of the hazard area?',
          ],
          verificationEvidence: ['swing-radius control photo', 'spotter assignment', 'pre-task briefing record'],
        },
        {
          systemId: 'excavation_interface',
          label: 'Excavation Interface',
          commonFailureModes: ['equipment operating too close to excavation edge', 'unclear utility clearance', 'unstable edge'],
          relatedHazardDomains: ['excavation_trenching', 'mobile_equipment', 'ground_control'],
          evidenceQuestions: [
            'Is the excavator operating near an excavation, trench, edge, underground utility, or unstable ground condition?',
          ],
          verificationEvidence: ['excavation photo', 'utility clearance record', 'competent person review', 'setback confirmation'],
        },
      ],
      guardrails: {
        contextOnly: true,
        doesNotDeclareViolation: true,
        doesNotCreateCitation: true,
        doesNotOverrideRegulation: true,
        requiresQualifiedReview: true,
      },
    },
    {
      equipmentId: 'dozer',
      label: 'Dozer',
      category: 'mobile_equipment',
      aliases: ['dozer', 'bulldozer', 'crawler dozer'],
      commonJurisdictions: ['msha', 'osha_construction'],
      commonHazardDomains: ['mobile_equipment', 'ground_control', 'powered_haulage', 'traffic_control'],
      commonScenarioTriggers: [
        'dozer operating on slope',
        'push pile',
        'stockpile',
        'edge berm',
        'limited visibility',
        'reverse travel',
        'rollover risk',
      ],
      inspectionFocusAreas: [
        'slope/grade stability',
        'edge distance',
        'operator visibility',
        'backup alarm',
        'seatbelt/ROPS context',
        'track/undercarriage condition',
        'traffic separation',
      ],
      correctiveActionThemes: [
        'evaluate slope and edge conditions before operation',
        'verify rollover/seatbelt/operator protection context',
        'establish traffic and pedestrian separation',
        'address visibility or backup-warning issues',
        'remove defective equipment from service pending review',
      ],
      conflictNotes: [
        'Dozer operating on slopes or unstable ground may overlap with ground control.',
        'Dozer traffic interaction may overlap with traffic control.',
        'Stockpile/dump area context may overlap with powered haulage.',
      ],
      systems: [
        {
          systemId: 'slope_edge_operation',
          label: 'Slope / Edge Operation',
          commonFailureModes: ['operating near edge', 'unstable slope', 'rollover risk'],
          relatedHazardDomains: ['mobile_equipment', 'ground_control'],
          evidenceQuestions: [
            'Is the dozer operating near a slope, edge, stockpile, dump point, or unstable ground condition?',
          ],
          verificationEvidence: ['slope photo', 'edge distance photo', 'operator instruction record', 'qualified review'],
        },
        {
          systemId: 'operator_visibility',
          label: 'Operator Visibility',
          commonFailureModes: ['limited rear visibility', 'backup alarm concern', 'pedestrian exposure'],
          relatedHazardDomains: ['mobile_equipment', 'traffic_control'],
          evidenceQuestions: [
            'What visibility, alarm, spotter, and pedestrian-separation controls are in place?',
          ],
          verificationEvidence: ['backup alarm test', 'visibility controls photo', 'spotter assignment'],
        },
      ],
      guardrails: {
        contextOnly: true,
        doesNotDeclareViolation: true,
        doesNotCreateCitation: true,
        doesNotOverrideRegulation: true,
        requiresQualifiedReview: true,
      },
    },
    {
      equipmentId: 'skid_steer',
      label: 'Skid Steer / Compact Track Loader',
      category: 'mobile_equipment',
      aliases: ['skid steer', 'compact track loader', 'ctl', 'compact loader'],
      commonJurisdictions: ['osha_construction', 'osha_general_industry', 'msha'],
      commonHazardDomains: ['mobile_equipment', 'traffic_control', 'material_handling'],
      commonScenarioTriggers: [
        'skid steer',
        'compact track loader',
        'attachment',
        'bucket raised',
        'backup alarm',
        'pedestrian exposure',
        'blind spot',
      ],
      inspectionFocusAreas: [
        'attachment securement',
        'operator visibility',
        'backup alarm',
        'seatbelt/restraint',
        'pedestrian separation',
        'raised bucket/attachment position',
        'pre-use inspection',
      ],
      correctiveActionThemes: [
        'lower or secure raised attachments',
        'verify attachment locking and condition',
        'separate pedestrians from operating equipment',
        'verify alarm/visibility controls',
        'document pre-use inspection and correction evidence',
      ],
      conflictNotes: [
        'Raised bucket or attachment context generally supports mobile equipment.',
        'Pedestrian walkway/signage/barrier context may support traffic control.',
        'Load handling or unstable loads may support material handling.',
      ],
      systems: [
        {
          systemId: 'attachment_securement',
          label: 'Attachment Securement',
          commonFailureModes: ['attachment not locked', 'raised bucket near employees', 'hydraulic attachment concern'],
          relatedHazardDomains: ['mobile_equipment', 'material_handling'],
          evidenceQuestions: [
            'Is the attachment secured, lowered where appropriate, and controlled to prevent struck-by or crush exposure?',
          ],
          verificationEvidence: ['attachment photo', 'locking mechanism confirmation', 'operator signoff'],
        },
      ],
      guardrails: {
        contextOnly: true,
        doesNotDeclareViolation: true,
        doesNotCreateCitation: true,
        doesNotOverrideRegulation: true,
        requiresQualifiedReview: true,
      },
    },
    {
      equipmentId: 'aerial_lift',
      label: 'Aerial Lift / Manlift',
      category: 'access_equipment',
      aliases: ['aerial lift', 'manlift', 'boom lift', 'scissor lift', 'mobile elevated work platform', 'mewp'],
      commonJurisdictions: ['osha_construction', 'osha_general_industry'],
      commonHazardDomains: ['fall_protection', 'mobile_equipment', 'electrical', 'training_procedure_gap'],
      commonScenarioTriggers: [
        'aerial lift',
        'manlift',
        'boom lift',
        'scissor lift',
        'working at height',
        'fall arrest',
        'overhead powerline',
        'outrigger',
        'platform gate',
      ],
      inspectionFocusAreas: [
        'fall protection/tie-off requirements',
        'platform gate and guardrails',
        'ground condition and setup',
        'overhead electrical exposure',
        'operator training/authorization',
        'pre-use inspection',
        'outrigger/stabilizer use where applicable',
      ],
      correctiveActionThemes: [
        'verify fall protection method and anchorage requirements',
        'evaluate overhead electrical exposure',
        'verify pre-use inspection and operator authorization',
        'remove unsafe lift from service pending review',
        'document setup and correction evidence',
      ],
      conflictNotes: [
        'Aerial lift context often overlaps fall protection and mobile equipment.',
        'Overhead powerline terms may strengthen electrical classification.',
        'Training/operator authorization terms may support training/procedure gap.',
      ],
      systems: [
        {
          systemId: 'platform_fall_protection',
          label: 'Platform / Fall Protection',
          commonFailureModes: ['gate open', 'tie-off unclear', 'guardrail damaged', 'fall arrest unclear'],
          relatedHazardDomains: ['fall_protection'],
          evidenceQuestions: [
            'What fall protection method is required and in place for the lift type and task?',
          ],
          verificationEvidence: ['platform photo', 'harness/tie-off observation', 'pre-use inspection record'],
        },
        {
          systemId: 'setup_environment',
          label: 'Setup Environment',
          commonFailureModes: ['unstable ground', 'overhead powerline', 'outrigger not used', 'traffic exposure'],
          relatedHazardDomains: ['mobile_equipment', 'electrical', 'traffic_control'],
          evidenceQuestions: [
            'Is the lift set up on suitable ground and clear of overhead electrical or traffic hazards?',
          ],
          verificationEvidence: ['setup photo', 'ground condition note', 'powerline clearance review', 'traffic control photo'],
        },
      ],
      guardrails: {
        contextOnly: true,
        doesNotDeclareViolation: true,
        doesNotCreateCitation: true,
        doesNotOverrideRegulation: true,
        requiresQualifiedReview: true,
      },
    },
    {
      equipmentId: 'telehandler',
      label: 'Telehandler',
      category: 'material_handling',
      aliases: ['telehandler', 'rough terrain forklift', 'extendable boom forklift', 'reach forklift'],
      commonJurisdictions: ['osha_construction', 'osha_general_industry'],
      commonHazardDomains: ['mobile_equipment', 'material_handling', 'traffic_control', 'fall_protection'],
      commonScenarioTriggers: [
        'telehandler',
        'rough terrain forklift',
        'extended boom',
        'load chart',
        'outrigger',
        'fork attachment',
        'suspended load',
        'platform attachment',
      ],
      inspectionFocusAreas: [
        'load chart and capacity',
        'boom extension/angle',
        'attachment compatibility',
        'ground conditions',
        'operator visibility',
        'pedestrian separation',
        'platform attachment controls where applicable',
      ],
      correctiveActionThemes: [
        'verify load chart/capacity and attachment compatibility',
        'establish pedestrian and traffic separation',
        'confirm ground/setup conditions',
        'verify operator authorization and pre-use inspection',
        'document correction and follow-up evidence',
      ],
      conflictNotes: [
        'Telehandler load chart/load stability terms may support material handling.',
        'Backing/visibility/pedestrian terms may support mobile equipment or traffic control.',
        'Platform attachment or work-at-height terms may support fall protection.',
      ],
      systems: [
        {
          systemId: 'load_handling',
          label: 'Load Handling / Boom Capacity',
          commonFailureModes: ['capacity unclear', 'load chart not reviewed', 'unstable load', 'extended boom instability'],
          relatedHazardDomains: ['material_handling', 'mobile_equipment'],
          evidenceQuestions: [
            'Is the load within capacity for boom angle/extension, attachment, and ground condition?',
          ],
          verificationEvidence: ['load chart review', 'attachment photo', 'ground condition note', 'operator confirmation'],
        },
      ],
      guardrails: {
        contextOnly: true,
        doesNotDeclareViolation: true,
        doesNotCreateCitation: true,
        doesNotOverrideRegulation: true,
        requiresQualifiedReview: true,
      },
    },
    {
      equipmentId: 'conveyor',
      label: 'Conveyor',
      category: 'fixed_plant',
      aliases: ['conveyor', 'belt conveyor', 'conveyor belt', 'conveyor drive'],
      commonJurisdictions: ['msha', 'osha_general_industry'],
      commonHazardDomains: ['machine_guarding', 'lockout_tagout', 'walking_working_surfaces'],
      commonScenarioTriggers: [
        'belt',
        'pulley',
        'tail pulley',
        'head pulley',
        'nip point',
        'return roller',
        'cleanup around conveyor',
        'unexpected startup',
      ],
      inspectionFocusAreas: [
        'guards at pulleys and nip points',
        'moving parts accessibility',
        'emergency stop or pull cord',
        'cleanup exposure',
        'lockout during maintenance',
        'walkway/travelway condition',
      ],
      correctiveActionThemes: [
        'guard accessible moving parts',
        'verify hazardous energy control before maintenance or cleanup',
        'restrict access until reviewed',
        'document guard repair/replacement',
        'verify restart and warning controls where applicable',
      ],
      conflictNotes: [
        'Conveyor belt/pulley/nip-point terms generally support machine guarding.',
        'Cleaning/maintenance with startup or energy isolation terms may support LOTO.',
        'Debris/travelway obstruction near conveyor may support walking-working surfaces.',
      ],
      systems: [
        {
          systemId: 'moving_parts',
          label: 'Moving Parts',
          commonFailureModes: ['unguarded pulley', 'accessible nip point', 'removed guard', 'moving belt exposure'],
          relatedHazardDomains: ['machine_guarding'],
          evidenceQuestions: [
            'Are moving belts, pulleys, rollers, shafts, and nip points guarded or otherwise inaccessible?',
          ],
          verificationEvidence: ['guard photo', 'before-and-after photo', 'maintenance record', 'qualified review signoff'],
        },
        {
          systemId: 'energy_control',
          label: 'Energy Control',
          commonFailureModes: ['unexpected startup', 'no lockout verification', 'cleanup while energized'],
          relatedHazardDomains: ['lockout_tagout'],
          evidenceQuestions: [
            'Have all hazardous energy sources been identified, isolated, controlled, and verified before work?',
          ],
          verificationEvidence: ['lockout checklist', 'authorized employee confirmation', 'zero-energy verification record'],
        },
      ],
      guardrails: {
        contextOnly: true,
        doesNotDeclareViolation: true,
        doesNotCreateCitation: true,
        doesNotOverrideRegulation: true,
        requiresQualifiedReview: true,
      },
    },
    {
      equipmentId: 'electrical_panel',
      label: 'Electrical Panel',
      category: 'electrical_equipment',
      aliases: ['electrical panel', 'panel', 'breaker panel', 'control cabinet', 'energized panel'],
      commonJurisdictions: ['osha_general_industry', 'osha_construction', 'msha'],
      commonHazardDomains: ['electrical', 'lockout_tagout', 'ppe', 'fire_protection'],
      commonScenarioTriggers: [
        'exposed live parts',
        'open panel',
        'blocked panel',
        'arc flash',
        'energized electrical panel',
        'breaker',
        'control cabinet',
      ],
      inspectionFocusAreas: [
        'live-part exposure',
        'panel access/clearance',
        'cover/door condition',
        'GFCI/wet location context',
        'qualified electrical work',
        'arc flash boundary and PPE',
        'de-energization and lockout context',
      ],
      correctiveActionThemes: [
        'restrict access pending qualified electrical review',
        'guard or close exposed live parts',
        'restore panel access/clearance',
        'verify GFCI/wet-location protection where applicable',
        'document qualified review and objective correction evidence',
      ],
      conflictNotes: [
        'Arc flash, exposed live parts, panels, and GFCI terms should generally support electrical.',
        'Lockout terms may also apply, but energized electrical work should not automatically become LOTO.',
        'PPE terms may be secondary when the primary hazard is energized electrical exposure.',
      ],
      systems: [
        {
          systemId: 'live_parts',
          label: 'Live Parts / Energized Components',
          commonFailureModes: ['exposed live parts', 'open panel', 'missing cover', 'arc flash boundary unclear'],
          relatedHazardDomains: ['electrical', 'ppe'],
          evidenceQuestions: [
            'Is the equipment energized, guarded, de-energized, or otherwise protected from contact by employees?',
            'Is a qualified electrical person needed to evaluate the condition?',
          ],
          verificationEvidence: ['panel photo', 'qualified electrical review', 'repair record', 'follow-up inspection photo'],
        },
      ],
      guardrails: {
        contextOnly: true,
        doesNotDeclareViolation: true,
        doesNotCreateCitation: true,
        doesNotOverrideRegulation: true,
        requiresQualifiedReview: true,
      },
    },
  ],
};
