/**
 * §207 -- RENDER THE HUMAN-READABLE PREREGISTRATION ARTIFACTS.
 *
 * WRITES MARKDOWN AND TEXT ONLY. ZERO PROVIDER CALLS. ZERO DATABASE OPERATIONS.
 *
 * Everything here is DERIVED from the frozen modules, so a rendered artifact cannot disagree with
 * the hashed payload. Nothing is transcribed by hand.
 */

import { writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';

import {
  FROZEN_TRUTH_CASES, expectedProjectedFactCount, governedCaseIds, safetyCriticalFactIds,
  zeroDeclarationCaseIds,
} from './lib/expert-207-truth-specification';
import {
  AXIS_AMENDMENTS, INSTRUMENT_DEVIATION, ORDINARY_QUALITY_CRITERIA, ORDINARY_QUALITY_RULE,
  PREREGISTERED_GATES, adjudicationPlan, gateApplicabilityMatrix, instrumentBudget,
} from './lib/expert-207-gates';
import { callPlan, spendPlan } from './lib/expert-207-protocols';
import {
  SECTION_207_DIR, preregistrationIdentity,
} from './lib/expert-207-preregistration';
import { cohortExecutionPermitted } from './lib/expert-207-execution-gate';

const repoRoot = join(__dirname, '..', '..');
const outDir = join(repoRoot, 'verification', SECTION_207_DIR);
const write = (name: string, body: string): void => {
  const p = join(outDir, name);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, body, 'utf8');
  console.log(`wrote ${p} (${Buffer.byteLength(body, 'utf8')} bytes)`);
};

const identity = preregistrationIdentity();
const budget = instrumentBudget();
const plan = adjudicationPlan();
const matrix = gateApplicabilityMatrix();

// ---------------------------------------------------------------- truth specification

const ts: string[] = [];
ts.push('# §207 — FROZEN TRUTH SPECIFICATION FOR THE 24 FRESH EXPERT HAZLENZ ACCEPTANCE CASES');
ts.push('');
ts.push('**RENDERED FROM THE FROZEN SOURCE. DO NOT EDIT THIS FILE — edit');
ts.push('`backend/scripts/lib/expert-207-truth-specification.ts`, re-freeze, and re-render.**');
ts.push('');
ts.push(`Preregistration identity: \`${identity}\``);
ts.push('');
ts.push(`${FROZEN_TRUTH_CASES.length} cases · ${expectedProjectedFactCount()} expected projected `
  + `facts · ${safetyCriticalFactIds().length} of them frozen safety-critical · `
  + `${zeroDeclarationCaseIds().length} zero-declaration cases · `
  + `${governedCaseIds().length} governed cases`);
ts.push('');
ts.push('**This specification grades SEMANTIC CORRECTNESS AND PRESERVATION, never stylistic');
ts.push('similarity to the wording used here.** No deterministic code compares model output against');
ts.push('it, and none may be added — that is the retired §160 semantic matcher, and D08 closes');
ts.push('against reintroducing it.');
ts.push('');

for (const c of FROZEN_TRUTH_CASES) {
  const p = plan.find(x => x.caseId === c.caseId);
  const gates = matrix.find(m => m.caseId === c.caseId);
  ts.push('---');
  ts.push('');
  ts.push(`## ${c.caseId} — ${c.block}`);
  ts.push('');
  ts.push(`**Purpose.** ${c.purpose}`);
  ts.push('');
  ts.push(`| | |`);
  ts.push(`|---|---|`);
  ts.push(`| failure families | ${c.failureFamiliesExercised.join(', ')} |`);
  ts.push(`| location / task | ${c.location} — ${c.task} |`);
  ts.push(`| jurisdiction | ${c.jurisdiction} |`);
  ts.push(`| hazard families supplied | ${c.allowedHazardFamilies.join(', ')} |`);
  ts.push(`| frozen safety classification | **${c.caseSafetyClassification}** |`);
  ts.push(`| expected owed facts | ${c.expectedOwedFactCount.min}–${c.expectedOwedFactCount.max} |`);
  ts.push(`| clarification required | ${c.clarificationRequired ? 'yes' : 'no'} |`);
  ts.push(`| governed evidence | ${c.governed === null ? 'none supplied'
    : c.governed.suppliedSourceIds.join(', ')} |`);
  ts.push(`| adjudicated row axes | ${p?.rowAxes.join(', ') ?? ''} |`);
  ts.push(`| adjudicated fact axes | ${(p?.factAxisSets ?? []).map(s => s.join('/')).join('  •  ')
    || '— (no projected fact)'} |`);
  ts.push(`| contributes to gates | ${gates?.gateIds.join(', ') ?? ''} |`);
  ts.push('');
  ts.push('### Exact observation supplied');
  ts.push('');
  ts.push(`> ${c.observation}`);
  ts.push('');
  ts.push('### Supplied context');
  ts.push('');
  ts.push('**Established by the text:**');
  for (const s of c.establishedByTheText) ts.push(`- ${s}`);
  ts.push('');
  ts.push('**Not established by the text:**');
  for (const s of c.notEstablishedByTheText) ts.push(`- ${s}`);
  ts.push('');
  if (c.governed !== null) {
    ts.push('### Governed-evidence condition');
    ts.push('');
    for (const r of c.governed.records) {
      ts.push(`**\`${r.sourceId}\`** — ${r.bearsOnFactIds.length > 0
        ? `BEARS ON ${r.bearsOnFactIds.join(', ')}` : '**OFF POINT BY DESIGN**'}`);
      ts.push('');
      ts.push(`> ${r.text}`);
      ts.push('');
    }
    ts.push('**Authority boundary:**');
    for (const s of c.governed.authorityBoundary) ts.push(`- ${s}`);
    ts.push('');
    ts.push('**May be concluded from the supplied evidence:**');
    for (const s of c.governed.mayBeConcludedFromSuppliedEvidence) ts.push(`- ${s}`);
    ts.push('');
    ts.push('**Requires restraint (CANNOT_DETERMINE or equivalent):**');
    for (const s of c.governed.requiresRestraint) ts.push(`- ${s}`);
    ts.push('');
    ts.push('**Prohibited source / citation claims:**');
    for (const s of c.governed.prohibitedSourceOrCitationClaims) ts.push(`- ${s}`);
    ts.push('');
  }
  ts.push('### Decision-critical safety properties');
  ts.push('');
  ts.push('| id | status | decision-critical | property |');
  ts.push('|---|---|---|---|');
  for (const pr of c.expectedProperties) {
    ts.push(`| ${pr.propertyId} | **${pr.status}** | ${pr.decisionCritical ? 'YES' : 'no'} | `
      + `${pr.statement} |`);
  }
  ts.push('');
  for (const pr of c.expectedProperties) ts.push(`- **${pr.propertyId} why:** ${pr.why}`);
  ts.push('');
  if (c.expectedOwedFacts.length === 0) {
    ts.push('### Expected owed facts');
    ts.push('');
    ts.push('**NONE. The frozen correct answer on this case is ZERO DECLARATIONS.**');
    ts.push('');
  }
  for (const f of c.expectedOwedFacts) {
    ts.push(`### Owed fact \`${f.factId}\` — ${f.safetyClassification}`);
    ts.push('');
    ts.push(`**Owed property.** ${f.owedProperty}`);
    ts.push('');
    ts.push(`- **conjuncts (all must survive):** ${f.conjuncts.map(x => `“${x}”`).join('; ')}`);
    if (f.independentOf.length > 0) {
      ts.push(`- **independent of:** ${f.independentOf.join(', ')} — settling those leaves this open`);
      ts.push(`- **may not be collapsed into:** ${f.mayNotBeCollapsedInto.join(', ')}`);
    }
    ts.push(`- **affectedDecision:** ${f.expectedAffectedDecision}`
      + (f.acceptableAlternativeAffectedDecisions.length > 0
        ? ` (acceptable alternatives: ${f.acceptableAlternativeAffectedDecisions.join(', ')})`
        : ' (no acceptable alternative)'));
    ts.push('- **essential qualifiers that must survive:**');
    for (const q of f.essentialQualifiers) ts.push(`  - ${q}`);
    ts.push('- **acceptable branch partition:**');
    for (const b of f.acceptableBranchPartition) ts.push(`  - ${b}`);
    ts.push('- **what changes under each state:**');
    for (const d of f.decisionChangeUnderEachState) ts.push(`  - *${d.state}* → ${d.decisionToday}`);
    ts.push('- **PROHIBITED decision claims (the F7 boundary, frozen):**');
    for (const x of f.prohibitedDecisionClaims) ts.push(`  - ${x}`);
    ts.push('- **acceptable evidence that would settle it:**');
    for (const e of f.acceptableEvidenceToSettle) ts.push(`  - ${e}`);
    ts.push(`- **a sufficient clarification must establish:** ${f.clarificationMustEstablish}`);
    ts.push('- **unacceptable neighbouring properties (substitution, not near miss):**');
    for (const n of f.unacceptableNeighbouringProperties) ts.push(`  - ${n}`);
    ts.push('');
  }
  ts.push('### False-gap traps — apparent gaps that are NOT legitimate unresolved facts');
  ts.push('');
  for (const t of c.falseGapTraps) {
    ts.push(`- **${t.trapId} — ${t.apparentGap}.** ${t.whyItIsNotALegitimateUnresolvedFact}`);
  }
  ts.push('');
  if (c.temporalOrSequenceRequirements.length > 0) {
    ts.push('### Temporal / sequence requirements');
    ts.push('');
    for (const t of c.temporalOrSequenceRequirements) ts.push(`- ${t}`);
    ts.push('');
  }
  ts.push('### Containment and authority expectation');
  ts.push('');
  for (const s of c.containmentAndAuthorityExpectation) ts.push(`- ${s}`);
  ts.push('');
  ts.push(`**Design intent.** ${c.designIntent}`);
  ts.push('');
}
write('TRUTH-SPECIFICATION-207.md', `${ts.join('\n')}\n`);

// ---------------------------------------------------------------- gates and matrix

const gm: string[] = [];
gm.push('# §207 — PREREGISTERED GATES, APPLICABILITY MATRIX AND ORDINARY-QUALITY RULE');
gm.push('');
gm.push('**RENDERED FROM THE FROZEN SOURCE.** Preregistration identity: '
  + `\`${identity}\``);
gm.push('');
gm.push('## 1. Gate definitions');
gm.push('');
for (const g of PREREGISTERED_GATES) {
  gm.push(`### ${g.gateId} — ${g.kind}`);
  gm.push('');
  gm.push(`**${g.statement}**`);
  gm.push('');
  gm.push(`| | |`);
  gm.push(`|---|---|`);
  gm.push(`| threshold | ${g.threshold} |`);
  gm.push(`| measured on | ${g.measuredOn} |`);
  gm.push(`| denominator | ${g.denominatorDescription} |`);
  gm.push(`| minimum denominator | ${g.minimumDenominator} — below this the gate is `
    + `COVERAGE_INSUFFICIENT, which is **not** a pass |`);
  gm.push(`| §204 origin | ${g.section204Origin ?? '—'} |`);
  gm.push('');
  gm.push(`**Fails if.** ${g.failsIf}`);
  gm.push('');
  gm.push(`**§207 freeze review.** ${g.freezeReview}`);
  gm.push('');
}
gm.push('## 2. Hard versus ordinary classification');
gm.push('');
gm.push('| gate | kind | can it be compensated by any other result? |');
gm.push('|---|---|---|');
for (const g of PREREGISTERED_GATES) {
  gm.push(`| ${g.gateId} | ${g.kind} | ${g.kind === 'HARD_SAFETY_CRITICAL'
    ? '**NO — a hard gate is pass/fail for acceptance and nothing offsets it**'
    : g.kind === 'MEASUREMENT_ONLY' ? 'n/a — passes and fails nothing'
      : 'does not block advancement, but its failure is reported by name'} |`);
}
gm.push('');
gm.push('## 3. Per-case gate applicability matrix');
gm.push('');
const allGateIds = PREREGISTERED_GATES.map(g => g.gateId);
gm.push(`| case | frozen classification | ${allGateIds.join(' | ')} |`);
gm.push(`|---|---|${allGateIds.map(() => '---').join('|')}|`);
for (const m of matrix) {
  gm.push(`| ${m.caseId} | ${m.frozenClassification} | `
    + `${allGateIds.map(id => (m.gateIds.includes(id) ? '●' : '')).join(' | ')} |`);
}
gm.push('');
gm.push('## 4. Ordinary-quality acceptance rule');
gm.push('');
gm.push(`**Form:** ${ORDINARY_QUALITY_RULE.form}. **Aggregate percentage threshold: `
  + `${String(ORDINARY_QUALITY_RULE.aggregatePercentageThreshold)}.**`);
gm.push('');
gm.push(`**Why no percentage.** ${ORDINARY_QUALITY_RULE.whyNoPercentage}`);
gm.push('');
gm.push(`**Effect of failure.** ${ORDINARY_QUALITY_RULE.effectOfFailure}`);
gm.push('');
gm.push(`**Can override a hard gate:** ${String(ORDINARY_QUALITY_RULE.canOverrideAHardGate)}.`);
gm.push('');
for (const c of ORDINARY_QUALITY_CRITERIA) {
  gm.push(`### ${c.criterionId}`);
  gm.push('');
  gm.push(`**${c.statement}**`);
  gm.push('');
  gm.push(`- **measured on:** ${c.measuredOn}`);
  gm.push(`- **threshold:** ${c.threshold}`);
  gm.push(`- **justification from intended product capability:** ${c.justification}`);
  gm.push('');
}
gm.push('## 5. Instrument budget and the amendments');
gm.push('');
gm.push(`| | |`);
gm.push(`|---|---|`);
gm.push(`| cases | ${budget.cases} |`);
gm.push(`| row-level judgments | ${budget.rowJudgments} |`);
gm.push(`| fact-level judgments | ${budget.factJudgments} |`);
gm.push(`| **total substantive judgments** | **${budget.totalJudgments}** |`);
gm.push(`| §205 target | ${budget.section205Total} |`);
gm.push(`| added by amendments | ${budget.addedByAmendments} |`);
gm.push(`| full factorial would be | ${budget.fullFactorialWouldBe} |`);
gm.push('');
gm.push(`**Deviation.** ${INSTRUMENT_DEVIATION.reason} Reversible by the product owner: `
  + `${String(INSTRUMENT_DEVIATION.reversibleByProductOwner)}. `
  + `Consequence of reversal: ${INSTRUMENT_DEVIATION.consequenceOfReversal}`);
gm.push('');
for (const a of AXIS_AMENDMENTS) {
  gm.push(`### ${a.amendmentId} — add axis ${a.axis} (required by ${a.requiredByGate})`);
  gm.push('');
  gm.push(`- **cases:** ${a.caseIds.join(', ')}`);
  gm.push(`- **rationale:** ${a.rationale}`);
  gm.push(`- **if reversed:** ${a.ifReversed}`);
  gm.push('');
}
gm.push('## 6. Provider-call and spend projection');
gm.push('');
const cp = callPlan();
const sp = spendPlan();
gm.push(`| | |`);
gm.push(`|---|---|`);
gm.push(`| first-pass calls | ${cp.firstPassCalls} |`);
gm.push(`| verifier calls | ${cp.verifierCallsExpected} expected, ${cp.verifierCallsMax} max |`);
gm.push(`| governed-stage calls | ${cp.governedStageCallsExpected} expected, `
  + `${cp.governedStageCallsMax} max |`);
gm.push(`| **expected total** | **${cp.expectedTotal}** |`);
gm.push(`| structural max | ${cp.structuralMax} |`);
gm.push(`| retry allowance | ${cp.retryAllowancePerCall} per call, ${cp.retryAllowancePerRun} per run |`);
gm.push(`| **hard call ceiling (abort)** | **${cp.hardCallCeiling}** |`);
gm.push(`| expected spend | USD ${sp.expectedUsd} |`);
gm.push(`| ceiling-scenario spend | USD ${sp.ceilingScenarioUsd} |`);
gm.push(`| **hard spend ceiling (abort)** | **USD ${sp.hardSpendCeilingUsd}** |`);
gm.push('');
gm.push(`**Cost basis.** ${sp.basis}`);
gm.push('');
write('GATES-AND-APPLICABILITY-207.md', `${gm.join('\n')}\n`);

// ---------------------------------------------------------------- execution gate proof

const AUTHORIZED = {
  productOwnerReviewRecorded: true,
  cohortExecutionAuthorized: true,
  authorizationReference: 'HYPOTHETICAL-208-AUTHORIZATION',
};
const scenarios: { name: string; result: ReturnType<typeof cohortExecutionPermitted> }[] = [
  {
    name: 'AS THE REPOSITORY STANDS TODAY (no review, no authorization)',
    result: cohortExecutionPermitted({
      repoRoot, governedTransportSmokePassed: true,
      authorization: {
        productOwnerReviewRecorded: false, cohortExecutionAuthorized: false,
        authorizationReference: null,
      },
    }),
  },
  {
    name: 'PREREGISTRATION RECORD ABSENT (everything else satisfied)',
    result: cohortExecutionPermitted({
      repoRoot: '/nonexistent-repo-root-for-207-proof',
      governedTransportSmokePassed: true, authorization: AUTHORIZED,
    }),
  },
  {
    name: 'PIN AND RECORD DISAGREE (everything else satisfied)',
    result: cohortExecutionPermitted({
      repoRoot, governedTransportSmokePassed: true, authorization: AUTHORIZED,
      pinOverride: 'f'.repeat(64),
    }),
  },
  {
    name: 'ALL CONDITIONS MET (hypothetical §208 authorization)',
    result: cohortExecutionPermitted({
      repoRoot, governedTransportSmokePassed: true, authorization: AUTHORIZED,
    }),
  },
];

const eg: string[] = [];
eg.push('SECTION 207 -- EXECUTION GATE PROOF');
eg.push('===================================');
eg.push('');
eg.push('Produced by scripts/render-207-artifacts.ts from the live gate. Zero provider calls.');
eg.push('');
eg.push(`source identity : ${identity}`);
eg.push('');
for (const s of scenarios) {
  eg.push('-'.repeat(78));
  eg.push(`SCENARIO: ${s.name}`);
  eg.push(`  permitted : ${String(s.result.permitted)}`);
  eg.push(`  pin       : ${s.result.pin}`);
  eg.push(`  verified  : ${s.result.verification?.code ?? 'record not loaded'}`);
  if (s.result.blockers.length === 0) eg.push('  blockers  : none');
  for (const b of s.result.blockers) eg.push(`  BLOCKER   : ${b}`);
  eg.push('');
}
eg.push('-'.repeat(78));
eg.push('The last scenario is the control. A gate that refused unconditionally would prove nothing');
eg.push('about the first three: it would only prove that it refuses.');
eg.push('');
write('EXECUTION-GATE-PROOF-207.txt', `${eg.join('\n')}\n`);

console.log('\nprovider calls: 0   database operations: 0   cohort authorized: NO');
