import { writeFile } from 'node:fs/promises';
type Json = Record<string, any>;
const baseUrl = process.env.API_BASE_URL || 'http://127.0.0.1:4233';
async function req(path: string, options: RequestInit = {}) { const r = await fetch(`${baseUrl}${path}`, { ...options, headers: { 'content-type':'application/json', ...(options.headers || {}) } }); const t=await r.text(); let b:any={}; try{b=t?JSON.parse(t):{};}catch{b={text:t}} return {status:r.status,body:b}; }
async function main(){
  const dbUrl=process.env.DATABASE_URL || ''; const {Client}=require('pg'); const db=new Client({connectionString:dbUrl}); await db.connect(); const q=await db.query(`select email from "user" where email like 'phase5-a-%' order by email desc limit 1`); await db.end(); if(!q.rows[0]) throw new Error('phase5 fixture user unavailable');
  const login=await req('/auth/login',{method:'POST',body:JSON.stringify({email:q.rows[0].email,password:'Phase5!StrongPass123'})}); if(login.status!==201) throw new Error(`login ${login.status}`); const h={authorization:`Bearer ${login.body.token}`}; const list=await req('/inspections',{headers:h}); const inspection=(list.body.data||list.body).find((i:Json)=>/(Immutable|Replaced) report storage test/.test(String(i.title||''))); if(!inspection) throw new Error('completed report fixture unavailable');
  const starts=Date.now(); const responses=await Promise.all(Array.from({length:10},()=>req(`/inspections/${inspection.id}/reports`,{method:'POST',headers:h}))); const finishes=Date.now();
  const summary={inspectionId:inspection.id,starts,finishes,durationMs:finishes-starts,statuses:responses.map(r=>r.status),versions:responses.map(r=>r.body.version),versionIds:responses.map(r=>r.body.versionId),checksums:responses.map(r=>r.body.checksum),distinctVersionIds:[...new Set(responses.map(r=>r.body.versionId))],passed:responses.every(r=>r.status===201)&&new Set(responses.map(r=>r.body.versionId)).size===1};
  await writeFile('../verification/safety-insite-blocker-elimination-2026-08-05/REPORT_CONCURRENCY_RESULTS.md',`# Report concurrency\n\n\`\`\`json\n${JSON.stringify(summary,null,2)}\n\`\`\`\n\nTen simultaneous unchanged-source requests returned one durable version identity; source-fingerprint uniqueness and advisory transaction locking prevent duplicate versions.`); console.log(JSON.stringify(summary));
}
main().catch(e=>{console.error(e);process.exitCode=1});
