export type SafetyCalendarEventType =
  | "inspection"
  | "corrective_action"
  | "follow_up"
  | "report_review"
  | "supervisor_review"
  | "custom";

export type SafetyCalendarEventStatus =
  | "Scheduled"
  | "Open"
  | "In Progress"
  | "Blocked"
  | "Completed"
  | "Overdue";

export type SafetyCalendarPriority = "Critical" | "High" | "Medium" | "Low";

/**
 * §276 / D-007 — where this event's authoritative copy lives.
 *
 * `server`  the row exists in Safety InSite. Authoritative.
 * `pending` the user created it while the server was unreachable. It lives only in the
 *           local outbox and has NOT been persisted yet; it is shown so the work is not
 *           silently lost, and marked so the user is not told it is saved when it is not.
 * `local`   a device-only record from the pre-reconciliation stores, kept visible while
 *           it waits to be migrated onto the server.
 */
export type SafetyCalendarEventOrigin = "server" | "pending" | "local";

export type SafetyCalendarEvent = {
  id: string;
  type: SafetyCalendarEventType;
  title: string;
  date: string;
  owner: string;
  location: string;
  priority: SafetyCalendarPriority;
  status: SafetyCalendarEventStatus;
  source: "company_assignment" | "corrective_action" | "personal_task";
  sourceId: string;
  sourceLabel: string;
  findingTitle?: string;
  createdAt?: string;
  completedAt?: string;
  /**
   * §276 / D-007. Absent on records written by code that predates reconciliation; the
   * reconciler stamps every event it returns, so nothing a surface renders is unstamped.
   */
  origin?: SafetyCalendarEventOrigin;
  /** Which server table backs this event, when one does. */
  serverKind?: "task" | "corrective_action";
  /**
   * Whether the calendar may edit or delete this event itself. The SERVER decides this:
   * work generated by an inspection is part of that inspection's record and is managed
   * from it. The browser copies the answer rather than deriving one.
   */
  editable?: boolean;
  inspectionId?: string;
  /** The outbox entry backing a `pending` event, so a retry can find it again. */
  clientRef?: string;
};
