import { SafeScopeScenarioDisambiguationRecord } from './scenario-disambiguation.types';

export const SAFESCOPE_SCENARIO_DISAMBIGUATION_REGISTRY: SafeScopeScenarioDisambiguationRecord[] = [
  {
    scenarioId: 'general-industry-powered-overhead-door-crush-point',
    label: 'General industry powered overhead door crush-point exposure',
    targetDomain: 'machine_guarding',
    targetMechanism: 'powered_door_crush_point',
    targetCitation: '29 CFR 1910.212(a)(3)(ii)',
    positiveSignals: [
      'powered overhead door',
      'overhead door',
      'powered door',
      'dock door',
      'roll-up door',
      'roll up door',
      'bay door',
      'door closed quickly',
      'door closing',
      'closing door',
      'photo-eye',
      'photo eye',
      'presence sensor',
      'reversing edge',
      'manual release',
      'warning device',
      'warning devices',
      'crush point',
      'crush zone',
      'pinch point',
      'employees pass under',
      'pass under the door',
      'pedestrian walkway',
      'pedestrian travel path',
      'walkway',
      'closing speed',
      'closing force',
    ],
    negativeSignals: [
      'forklift struck pedestrian',
      'backing alarm',
      'haul truck',
      'dump point',
      'unstable material storage',
      'stacked material',
      'falling object',
      'falling material',
      'storage rack',
      'suspended load',
      'hoisted load',
      'crane load',
    ],
    jurisdictionSignals: ['osha general industry', 'general industry', '1910'],
    industrySignals: ['general industry', 'warehouse', 'dock', 'loading dock', 'shipping', 'receiving', 'facility', 'plant'],
    equipmentSignals: [
      'powered overhead door',
      'overhead door',
      'powered door',
      'dock door',
      'roll-up door',
      'roll up door',
      'bay door',
      'photo-eye',
      'photo eye',
      'presence sensor',
      'reversing edge',
      'manual release',
    ],
    taskSignals: [
      'door closing',
      'closing door',
      'employees pass under',
      'pass under the door',
      'pedestrian walkway',
      'pedestrian travel path',
      'inspection',
      'maintenance',
      'troubleshooting',
    ],
    competingScenarioIds: [
      'general-industry-material-falling-object-storage',
      'construction-falling-object-overhead-work',
      'mobile-equipment-pedestrian-strike',
      'same-level-slip-trip-fall',
    ],
    humanReviewTriggers: [
      'Confirm whether employees pass under or near the powered door during operation.',
      'Verify photo-eye, presence sensor, reversing edge, warning device, and manual release function.',
      'Confirm door operating state, closing speed or force, and pedestrian travel path.',
      'Confirm whether the condition was observed during normal use, inspection, maintenance, or troubleshooting.',
    ],
  },
  {
    scenarioId: 'construction-falling-object-overhead-work',
    label: 'Construction falling-object exposure from overhead work',
    targetDomain: 'struck_by',
    targetMechanism: 'struck_by_falling_object',
    targetCitation: '29 CFR 1926.501(c)',
    positiveSignals: [
      'falling object',
      'dropped object',
      'overhead work',
      'tools overhead',
      'materials overhead',
      'toe board',
      'toeboard',
      'worker below',
      'employees below',
      'barricade below',
    ],
    negativeSignals: [
      'warehouse rack',
      'palletized material',
      'material storage',
      'stacked material',
      'suspended load',
      'hoisted load',
      'rigging',
    ],
    jurisdictionSignals: ['osha construction', 'construction', '1926'],
    industrySignals: ['construction'],
    equipmentSignals: ['scaffold', 'platform', 'aerial lift', 'elevated work area'],
    taskSignals: ['overhead work', 'work at height', 'construction access'],
    competingScenarioIds: [
      'general-industry-material-falling-object-storage',
      'crane-suspended-load-struck-by',
      'unstable-stack-collapse',
    ],
    humanReviewTriggers: [
      'Confirm whether object exposure is from active overhead construction work or stored material.',
      'Confirm whether workers are exposed below the falling-object hazard.',
    ],
  },
  {
    scenarioId: 'general-industry-material-falling-object-storage',
    label: 'General industry material storage falling-object exposure',
    targetDomain: 'material_handling',
    targetMechanism: 'falling_object_material',
    targetCitation: '29 CFR 1910.176(b)',
    positiveSignals: [
      'material storage',
      'stored overhead',
      'overhead storage',
      'stacked material',
      'palletized material',
      'warehouse',
      'rack',
      'falling material',
      'material fell',
      'object fell',
    ],
    negativeSignals: [
      'construction',
      '1926',
      'toe board',
      'toeboard',
      'scaffold',
      'suspended load',
      'hoisted load',
      'crane load',
    ],
    jurisdictionSignals: ['osha general industry', 'general industry', '1910'],
    industrySignals: ['general industry', 'warehouse', 'facility'],
    equipmentSignals: ['rack', 'shelf', 'pallet', 'storage area'],
    taskSignals: ['storage', 'material handling', 'warehouse operation'],
    competingScenarioIds: [
      'construction-falling-object-overhead-work',
      'crane-suspended-load-struck-by',
      'unstable-stack-collapse',
    ],
    humanReviewTriggers: [
      'Confirm whether the object was stored material or part of active overhead work.',
      'Confirm whether storage was stable and secure against sliding, collapse, or falling.',
    ],
  },
  {
    scenarioId: 'welding-cylinder-fire-explosion',
    label: 'Welding or fuel-gas cylinder fire/explosion exposure',
    targetDomain: 'welding_cutting_hot_work',
    targetMechanism: 'fire_explosion',
    targetCitation: '29 CFR 1910.253(b)(2)(ii)',
    positiveSignals: [
      'oxygen cylinder',
      'fuel gas cylinder',
      'acetylene',
      'welding cylinder',
      'cylinder separation',
      'stored together',
      'hot work',
      'torch cutting',
      'welding',
      'fire prevention',
    ],
    negativeSignals: [
      'unsecured cylinder',
      'missing valve cap',
      'cylinder restraint',
      'struck by cylinder',
      'falling cylinder',
    ],
    jurisdictionSignals: ['osha general industry', '1910'],
    industrySignals: ['general industry', 'maintenance shop', 'welding area'],
    equipmentSignals: ['oxygen cylinder', 'acetylene cylinder', 'fuel gas cylinder'],
    taskSignals: ['welding', 'cutting', 'hot work', 'cylinder storage'],
    competingScenarioIds: ['compressed-gas-cylinder-release'],
    humanReviewTriggers: [
      'Confirm whether the primary issue is fire/explosion separation or physical cylinder securement.',
      'Confirm cylinder contents and storage configuration.',
    ],
  },
  {
    scenarioId: 'compressed-gas-cylinder-release',
    label: 'Compressed gas cylinder pressure release or impact exposure',
    targetDomain: 'material_handling',
    targetMechanism: 'compressed_gas_cylinder_release',
    targetCitation: '29 CFR 1910.101(b)',
    positiveSignals: [
      'compressed gas cylinder',
      'gas cylinder',
      'unsecured cylinder',
      'missing valve cap',
      'valve cap',
      'cylinder restraint',
      'stored pressure',
      'cylinder fell',
      'cylinder impact',
    ],
    negativeSignals: [
      'oxygen and acetylene stored together',
      'fuel gas separation',
      'hot work',
      'welding sparks',
      'fire watch',
    ],
    jurisdictionSignals: ['osha general industry', '1910'],
    industrySignals: ['general industry', 'facility', 'shop'],
    equipmentSignals: ['gas cylinder', 'valve', 'cylinder cart'],
    taskSignals: ['storage', 'handling', 'transport'],
    competingScenarioIds: ['welding-cylinder-fire-explosion'],
    humanReviewTriggers: [
      'Confirm whether the primary exposure is stored-pressure release or fire/explosion.',
      'Confirm whether cylinders are secured and valve protection is installed.',
    ],
  },
  {
    scenarioId: 'coal-underground-methane-ventilation',
    label: 'Coal underground methane or ventilation-control deficiency',
    targetDomain: 'ventilation',
    targetMechanism: 'methane_gas_buildup',
    targetCitation: '30 CFR 75.333',
    positiveSignals: [
      'coal',
      'underground coal',
      'methane',
      'ventilation curtain',
      'curtain',
      'gas buildup',
      'airflow',
      'section ventilation',
    ],
    negativeSignals: [
      'metal nonmetal',
      'm/nm',
      'mnm',
      'part 57',
      'ventilation tubing',
      'diesel contaminant',
      'air quality contaminant',
    ],
    jurisdictionSignals: ['msha', '30 cfr 75', 'part 75', 'coal'],
    industrySignals: ['coal', 'underground coal', 'mining'],
    equipmentSignals: ['curtain', 'stopping', 'ventilation control'],
    taskSignals: ['mining', 'production', 'section work'],
    competingScenarioIds: ['mnm-underground-air-quality-ventilation'],
    humanReviewTriggers: [
      'Confirm coal versus metal/nonmetal mine context.',
      'Confirm whether methane accumulation or general contaminant buildup is the primary concern.',
    ],
  },
  {
    scenarioId: 'mnm-underground-air-quality-ventilation',
    label: 'Metal/nonmetal underground air-quality contaminant ventilation deficiency',
    targetDomain: 'ventilation',
    targetMechanism: 'air_quality_contaminant_buildup',
    targetCitation: '30 CFR 57.8520',
    positiveSignals: [
      'metal nonmetal',
      'm/nm',
      'mnm',
      'part 57',
      'underground metal',
      'underground nonmetal',
      'ventilation tubing',
      'damaged ventilation',
      'reduced airflow',
      'air quality',
      'contaminant buildup',
      'diesel contaminant',
    ],
    negativeSignals: [
      'coal',
      'methane',
      'part 75',
      '75.333',
      'ventilation curtain',
      'coal section',
    ],
    jurisdictionSignals: ['msha', '30 cfr 57', 'part 57', 'metal nonmetal', 'mnm'],
    industrySignals: ['metal nonmetal', 'underground mine', 'mining'],
    equipmentSignals: ['ventilation tubing', 'fan', 'duct'],
    taskSignals: ['underground work', 'development', 'maintenance'],
    competingScenarioIds: ['coal-underground-methane-ventilation'],
    humanReviewTriggers: [
      'Confirm whether the mine is coal or metal/nonmetal.',
      'Confirm whether the deficiency involves methane controls or general air-quality contaminants.',
    ],
  },
];

