import { SafeScopeHazardUniverseRecord } from './hazard-universe.types';

export const SAFESCOPE_HAZARD_UNIVERSE_REGISTRY: SafeScopeHazardUniverseRecord[] = [
  {
    hazardUniverseId: 'machine-guarding-rotating-equipment',
    label: 'Machine guarding - rotating equipment and nip points',
    domain: 'machine_guarding',
    priority: 'core',
    expectedMechanisms: ['rotating_equipment', 'rotating_equipment_nip_point', 'pinch_point'],
    expectedRegulatoryFamilies: ['MSHA guarding', 'OSHA machine guarding'],
    expectedControlThemes: ['guard exposed moving parts', 'prevent contact with nip points', 'verify guard before operation'],
    expectedEvidenceThemes: ['photos of exposed parts', 'employee access path', 'operating state', 'guard condition'],
    typicalScenarioExamples: ['unguarded conveyor tail pulley', 'unguarded belt drive', 'missing point-of-operation guard'],
    notes: ['Already represented in current benchmark set.']
  },
  {
    hazardUniverseId: 'loto-hazardous-energy',
    label: 'Lockout/tagout and hazardous energy control',
    domain: 'machine_guarding_loto',
    priority: 'core',
    expectedMechanisms: ['unexpected_startup', 'stored_energy_release', 'energized_equipment_contact'],
    expectedRegulatoryFamilies: ['MSHA maintenance guarding', 'OSHA LOTO'],
    expectedControlThemes: ['isolate energy', 'lockout/tagout', 'verify zero energy', 'block against motion'],
    expectedEvidenceThemes: ['energy source identification', 'lockout status', 'maintenance activity', 'zero-energy verification'],
    typicalScenarioExamples: ['maintenance with guard removed', 'crusher servicing without lockout', 'unexpected startup exposure'],
    notes: ['Current coverage exists; future expansion should distinguish electrical, hydraulic, pneumatic, gravity, and stored mechanical energy.']
  },
  {
    hazardUniverseId: 'falls-elevated-work',
    label: 'Fall protection - elevated work, leading edges, platforms, scaffolds',
    domain: 'fall_protection',
    priority: 'core',
    expectedMechanisms: ['fall_from_height', 'fall_from_ladder'],
    expectedRegulatoryFamilies: ['MSHA fall protection', 'OSHA construction fall protection', 'OSHA walking-working surfaces'],
    expectedControlThemes: ['guardrails', 'fall arrest', 'fall restraint', 'secure access', 'competent person inspection'],
    expectedEvidenceThemes: ['height', 'edge condition', 'anchor/system presence', 'employee exposure', 'access method'],
    typicalScenarioExamples: ['unprotected platform edge', 'missing scaffold guardrail', 'ladder does not extend above landing'],
    notes: ['Current coverage exists; future expansion should include holes, skylights, aerial lifts, roofs, and fixed ladders.']
  },
  {
    hazardUniverseId: 'mobile-equipment-traffic',
    label: 'Mobile equipment, powered haulage, pedestrian interface, traffic control',
    domain: 'mobile_equipment',
    priority: 'core',
    expectedMechanisms: ['pedestrian_strike', 'struck_by', 'run_off_embankment', 'collision', 'rollover'],
    expectedRegulatoryFamilies: ['MSHA berms and haulage', 'OSHA powered industrial trucks', 'OSHA construction equipment'],
    expectedControlThemes: ['separate pedestrians', 'traffic control', 'spotters', 'backup alarms', 'berms', 'exclusion zones'],
    expectedEvidenceThemes: ['equipment type', 'travel path', 'pedestrian exposure', 'visibility controls', 'road/berm condition'],
    typicalScenarioExamples: ['forklift operating near pedestrians', 'haul road missing berm', 'backing equipment without alarm'],
    notes: ['Current benchmark coverage is strong; future expansion should include seat belts, rollovers, blind spots, dumping, loading, and maintenance zones.']
  },
  {
    hazardUniverseId: 'electrical-shock-arc-flash',
    label: 'Electrical shock, exposed conductors, damaged cables, arc flash',
    domain: 'electrical',
    priority: 'core',
    expectedMechanisms: ['shock', 'shock_arc_flash', 'electrical_burn', 'fire_ignition'],
    expectedRegulatoryFamilies: ['MSHA electrical', 'OSHA electrical general industry', 'OSHA construction electrical'],
    expectedControlThemes: ['de-energize', 'repair enclosure', 'protect conductors', 'guard live parts', 'qualified electrical repair'],
    expectedEvidenceThemes: ['energized status', 'voltage if known', 'exposed parts', 'damage condition', 'accessibility'],
    typicalScenarioExamples: ['open junction box', 'damaged conductor', 'missing electrical cover', 'exposed live parts'],
    notes: ['Current coverage exists; future expansion should include GFCI, temporary wiring, grounding, panels, wet locations, and arc-flash work practices.']
  },
  {
    hazardUniverseId: 'slip-trip-housekeeping',
    label: 'Slips, trips, housekeeping, travelways, walking-working surfaces',
    domain: 'slip_trip_fall',
    priority: 'core',
    expectedMechanisms: ['slip', 'trip', 'same_level_fall'],
    expectedRegulatoryFamilies: ['MSHA housekeeping', 'OSHA walking-working surfaces'],
    expectedControlThemes: ['clean spill', 'remove obstruction', 'restore clear travelway', 'maintain dry walking surface'],
    expectedEvidenceThemes: ['walking surface condition', 'obstruction type', 'employee travel path', 'duration/frequency'],
    typicalScenarioExamples: ['oil spill in walkway', 'loose material in travelway', 'stored material blocking aisle'],
    notes: ['Current coverage exists; future expansion should include stairs, grating, ice, drainage, uneven floors, and lighting.']
  },
  {
    hazardUniverseId: 'ground-roof-rib-control',
    label: 'Ground control, roof control, rib control, highwall and loose material',
    domain: 'roof_rib_control',
    priority: 'core',
    expectedMechanisms: ['fall_of_ground', 'rib_fall', 'highwall_failure', 'rock_fall'],
    expectedRegulatoryFamilies: ['MSHA coal roof/rib control', 'MSHA ground control'],
    expectedControlThemes: ['restrict access', 'scale loose material', 'install support', 'qualified person examination'],
    expectedEvidenceThemes: ['location', 'ground condition', 'support condition', 'exposure path', 'examination record'],
    typicalScenarioExamples: ['loose roof in travelway', 'loose rib', 'unsupported ground', 'highwall instability'],
    notes: ['Current benchmark coverage includes coal roof and rib; future expansion should include surface highwalls and stockpiles.']
  },
  {
    hazardUniverseId: 'ventilation-air-quality',
    label: 'Ventilation, methane, oxygen deficiency, air quality controls',
    domain: 'ventilation',
    priority: 'core',
    expectedMechanisms: ['methane_gas_buildup', 'oxygen_deficiency', 'air_contaminant_accumulation'],
    expectedRegulatoryFamilies: ['MSHA ventilation', 'confined space atmospheric controls'],
    expectedControlThemes: ['restore ventilation', 'verify airflow', 'gas testing', 'restrict area'],
    expectedEvidenceThemes: ['airflow condition', 'gas readings', 'ventilation control condition', 'area occupancy'],
    typicalScenarioExamples: ['damaged ventilation curtain', 'methane accumulation', 'airflow deficiency'],
    notes: ['Current coverage exists for ventilation curtain/methane scenarios.']
  },
  {
    hazardUniverseId: 'emergency-egress-escapeways',
    label: 'Emergency preparedness, escapeways, blocked egress, emergency routes',
    domain: 'emergency_preparedness',
    priority: 'core',
    expectedMechanisms: ['egress_blockage', 'delayed_escape', 'emergency_response_delay'],
    expectedRegulatoryFamilies: ['MSHA escapeways', 'OSHA emergency routes'],
    expectedControlThemes: ['remove obstruction', 'restore clear egress', 'verify lifeline/route integrity'],
    expectedEvidenceThemes: ['route condition', 'obstruction type', 'passability', 'emergency equipment condition'],
    typicalScenarioExamples: ['blocked escapeway', 'stored material in emergency route', 'missing lifeline continuity'],
    notes: ['Current benchmark coverage includes escapeway blockage.']
  },
  {
    hazardUniverseId: 'health-respiratory-silica-dust',
    label: 'Respirable dust, silica, airborne contaminants, respiratory exposure',
    domain: 'health_respiratory',
    priority: 'core',
    expectedMechanisms: ['silica_inhalation', 'dust_inhalation', 'airborne_contaminant_exposure'],
    expectedRegulatoryFamilies: ['OSHA silica', 'MSHA respirable dust', 'respiratory protection'],
    expectedControlThemes: ['wet methods', 'dust collection', 'exposure control plan', 'respiratory protection where required'],
    expectedEvidenceThemes: ['task creating dust', 'control method', 'sampling/measurement data', 'duration/frequency'],
    typicalScenarioExamples: ['dry cutting concrete', 'dusty drilling', 'inadequate dust suppression'],
    notes: ['Current coverage includes silica; future expansion should include coal dust, diesel particulate, nuisance dust, and respiratory protection program issues.']
  },
  {
    hazardUniverseId: 'hazcom-chemical-labeling-sds',
    label: 'Hazard communication, chemical labeling, SDS, chemical exposure',
    domain: 'hazardous_materials',
    priority: 'core',
    expectedMechanisms: ['chemical_exposure', 'chemical_burn', 'inhalation_exposure', 'incompatible_storage'],
    expectedRegulatoryFamilies: ['OSHA HazCom', 'chemical storage and labeling'],
    expectedControlThemes: ['label container', 'identify chemical hazards', 'make SDS available', 'train affected employees'],
    expectedEvidenceThemes: ['container label', 'chemical identity', 'SDS availability', 'employee use/exposure'],
    typicalScenarioExamples: ['unlabeled secondary container', 'missing SDS', 'chemical storage incompatibility'],
    notes: ['Current benchmark covers labeling; future expansion should include storage, compatibility, spill response, and PPE selection.']
  },
  {
    hazardUniverseId: 'confined-space-entry',
    label: 'Confined space entry, atmospheric testing, attendant, rescue',
    domain: 'confined_space',
    priority: 'core',
    expectedMechanisms: ['asphyxiation', 'toxic_atmosphere', 'engulfment', 'entrapment'],
    expectedRegulatoryFamilies: ['OSHA permit-required confined spaces', 'atmospheric testing'],
    expectedControlThemes: ['stop entry', 'evaluate hazards', 'test atmosphere', 'permit system', 'attendant and rescue provisions'],
    expectedEvidenceThemes: ['space classification', 'entry status', 'atmospheric readings', 'permit', 'attendant/rescue plan'],
    typicalScenarioExamples: ['tank entry without testing', 'confined space without attendant', 'oxygen-deficient entry hazard'],
    notes: ['Current benchmark covers confined space basics; future expansion should include rescue, isolation, engulfment, and alternate entry.']
  },
  {
    hazardUniverseId: 'excavation-trenching-collapse',
    label: 'Excavation and trenching collapse, protective systems, access/egress',
    domain: 'trenching_and_excavation',
    priority: 'core',
    expectedMechanisms: ['collapse', 'engulfment', 'struck_by_falling_material'],
    expectedRegulatoryFamilies: ['OSHA excavation protective systems', 'competent person inspection'],
    expectedControlThemes: ['slope', 'shore', 'shield', 'remove employees', 'provide safe egress'],
    expectedEvidenceThemes: ['depth', 'soil condition', 'protective system', 'employee entry', 'competent person inspection'],
    typicalScenarioExamples: ['unprotected trench', 'no ladder in excavation', 'spoil pile at edge'],
    notes: ['Coverage gap was recently closed by adding trenching evidence coverage.']
  },
  {
    hazardUniverseId: 'cranes-rigging-suspended-loads',
    label: 'Cranes, rigging, hoisting, suspended loads',
    domain: 'cranes_rigging_hoisting',
    priority: 'high',
    expectedMechanisms: ['struck_by_suspended_load', 'dropped_load', 'rigging_failure', 'crane_contact'],
    expectedRegulatoryFamilies: ['OSHA cranes and derricks', 'MSHA hoisting where applicable'],
    expectedControlThemes: ['inspect rigging', 'establish exclusion zone', 'qualified operator/signal person', 'do not work under suspended load'],
    expectedEvidenceThemes: ['load path', 'rigging condition', 'operator/signal controls', 'employee position'],
    typicalScenarioExamples: ['employee under suspended load', 'damaged sling', 'uncontrolled hoisting zone'],
    notes: ['Likely thin or not started; should be part of next expansion pack.']
  },
  {
    hazardUniverseId: 'material-handling-storage',
    label: 'Material handling, storage, stacking, falling objects',
    domain: 'material_handling',
    priority: 'high',
    expectedMechanisms: ['struck_by_falling_object', 'caught_between_material', 'overexertion', 'unstable_stack_collapse'],
    expectedRegulatoryFamilies: ['OSHA material handling/storage', 'MSHA materials storage'],
    expectedControlThemes: ['secure stored material', 'maintain stable stacking', 'use mechanical aids', 'keep employees clear'],
    expectedEvidenceThemes: ['stack stability', 'material type', 'employee position', 'handling method'],
    typicalScenarioExamples: ['unstable pallets', 'pipe rolling hazard', 'stored material falling into walkway'],
    notes: ['Important future expansion area.']
  },
  {
    hazardUniverseId: 'hot-work-welding-cutting-fire',
    label: 'Welding, cutting, hot work, fire watch, combustible exposure',
    domain: 'welding_cutting_hot_work',
    priority: 'high',
    expectedMechanisms: ['fire_ignition', 'burn', 'fume_inhalation', 'explosion'],
    expectedRegulatoryFamilies: ['OSHA welding/cutting', 'fire prevention', 'hot work permits'],
    expectedControlThemes: ['remove combustibles', 'fire watch', 'ventilation', 'hot work permit', 'PPE'],
    expectedEvidenceThemes: ['hot work activity', 'combustibles nearby', 'fire watch', 'extinguisher availability', 'ventilation'],
    typicalScenarioExamples: ['grinding near combustibles', 'welding without fire watch', 'cutting on unknown container'],
    notes: ['Important future expansion area.']
  },
  {
    hazardUniverseId: 'fire-protection-emergency-equipment',
    label: 'Fire protection, extinguishers, alarms, emergency equipment',
    domain: 'fire_protection',
    priority: 'high',
    expectedMechanisms: ['fire_spread', 'delayed_fire_response', 'blocked_fire_equipment'],
    expectedRegulatoryFamilies: ['OSHA fire protection', 'MSHA fire protection/emergency equipment'],
    expectedControlThemes: ['restore access', 'inspect extinguishers', 'maintain alarms', 'remove combustibles'],
    expectedEvidenceThemes: ['equipment condition', 'inspection tag', 'access clearance', 'location coverage'],
    typicalScenarioExamples: ['blocked extinguisher', 'expired extinguisher inspection', 'missing fire suppression inspection'],
    notes: ['Important future expansion area.']
  },
  {
    hazardUniverseId: 'ppe-deficiency',
    label: 'PPE deficiencies and exposure-specific protective equipment',
    domain: 'ppe',
    priority: 'high',
    expectedMechanisms: ['eye_injury', 'hearing_damage', 'hand_injury', 'respiratory_exposure', 'impact_injury'],
    expectedRegulatoryFamilies: ['OSHA PPE', 'MSHA PPE'],
    expectedControlThemes: ['select proper PPE', 'verify use', 'train employees', 'replace defective PPE'],
    expectedEvidenceThemes: ['task exposure', 'PPE worn/not worn', 'condition of PPE', 'training/selection basis'],
    typicalScenarioExamples: ['no eye protection during grinding', 'no gloves for sharp material', 'hearing protection not used'],
    notes: ['Should not become a catch-all; PPE is usually lower hierarchy than engineering controls.']
  },
  {
    hazardUniverseId: 'tools-hand-power',
    label: 'Hand tools and power tools',
    domain: 'tools_equipment',
    priority: 'high',
    expectedMechanisms: ['cut_laceration', 'amputation', 'projectile', 'electric_shock', 'entanglement'],
    expectedRegulatoryFamilies: ['OSHA tools', 'MSHA equipment condition'],
    expectedControlThemes: ['remove defective tool', 'guard tool', 'inspect before use', 'train operators'],
    expectedEvidenceThemes: ['tool type', 'guard condition', 'cord condition', 'operator exposure', 'task being performed'],
    typicalScenarioExamples: ['grinder missing guard', 'damaged extension cord', 'defective hand tool'],
    notes: ['May require adding new domain or mapping to existing machine/electrical/PPE domains.']
  },
  {
    hazardUniverseId: 'ergonomics-manual-handling',
    label: 'Ergonomics, manual lifting, awkward posture, repetitive motion',
    domain: 'ergonomics',
    priority: 'medium',
    expectedMechanisms: ['overexertion', 'musculoskeletal_disorder', 'strain_sprain'],
    expectedRegulatoryFamilies: ['general duty / ergonomics guidance', 'material handling best practices'],
    expectedControlThemes: ['mechanical aid', 'redesign lift', 'team lift', 'reduce repetition', 'adjust work height'],
    expectedEvidenceThemes: ['load weight', 'frequency', 'posture', 'duration', 'available mechanical aids'],
    typicalScenarioExamples: ['repetitive lifting', 'awkward overhead work', 'heavy manual material handling'],
    notes: ['Needs careful governance because regulatory basis may be less direct.']
  },
  {
    hazardUniverseId: 'heat-cold-stress',
    label: 'Heat stress, cold stress, environmental exposure',
    domain: 'environmental_exposure',
    priority: 'medium',
    expectedMechanisms: ['heat_illness', 'cold_stress', 'dehydration'],
    expectedRegulatoryFamilies: ['OSHA heat guidance', 'general duty', 'MSHA health/safety controls where applicable'],
    expectedControlThemes: ['rest breaks', 'shade/cooling', 'hydration', 'acclimatization', 'monitor symptoms'],
    expectedEvidenceThemes: ['temperature', 'workload', 'duration', 'controls available', 'worker symptoms'],
    typicalScenarioExamples: ['outdoor high-heat work', 'hot plant area', 'cold exposure without controls'],
    notes: ['Likely future or medium priority depending target market.']
  },
  {
    hazardUniverseId: 'noise-hearing-conservation',
    label: 'Noise exposure and hearing conservation',
    domain: 'health_exposure',
    priority: 'medium',
    expectedMechanisms: ['noise_induced_hearing_loss'],
    expectedRegulatoryFamilies: ['OSHA occupational noise', 'MSHA noise exposure'],
    expectedControlThemes: ['noise monitoring', 'engineering controls', 'hearing protection', 'hearing conservation program'],
    expectedEvidenceThemes: ['noise measurements', 'duration', 'hearing protection use', 'audiometric/program records'],
    typicalScenarioExamples: ['high-noise crusher area', 'jackhammer operation', 'uncontrolled noise exposure'],
    notes: ['Needs measurement/evidence-heavy reasoning.']
  }
];
