export const TAXONOMY = {
  electrical: { family: 'Electrical', keywords: ['electrical', 'wire', 'conductor', 'cord', 'cable', 'exposed', 'exposed wiring', 'live wire', 'damaged cord', 'open electrical panel', 'temporary wiring', 'wiring through doorway', 'temporary wiring through doorway', 'live wire hanging'] },
  machine: { family: 'Machine', keywords: ['machine guard', 'guard missing', 'missing guard', 'crusher drive guard', 'drive guard', 'pulley guard', 'chain guard', 'gear guard', 'unguarded gear train', 'unguarded machine', 'moving parts', 'pinch point', 'guard detached', 'guard removed', 'pulley', 'chain'] },
  fall: { family: 'Fall', keywords: ['open edge', 'unguarded edge', 'fall hazard', 'fall protection', 'elevated platform', 'second floor', 'mezzanine', 'no guardrail', 'missing guardrail', 'missing rail', 'ladder', 'ladder not extended', 'not extended 3 feet', 'height', 'fall'] },
  housekeeping: { family: 'Housekeeping', keywords: ['blocked', 'aisle', 'debris', 'trip', 'slip', 'oil', 'clutter', 'oil spill', 'spill', 'slip hazard', 'trip hazard', 'poor housekeeping', 'walkway obstruction', 'cleanup', 'needs cleanup', 'area needs cleanup', 'blocked access', 'unsafe access', 'access blocked', 'walkway blocked'] },
  ppe: { family: 'PPE', keywords: ['no ppe', 'missing ppe', 'ppe missing', 'safety gear missing', 'not wearing', 'no hard hat', 'without hard hat', 'missing hard hat', 'hard hat', 'helmet', 'head protection', 'no safety glasses', 'safety glasses', 'eye protection', 'no gloves', 'gloves', 'hearing protection'] },
  poweredMobileEquipment: { family: 'Powered Mobile Equipment', keywords: ['forklift', 'powered industrial truck', 'mobile equipment', 'equipment traffic', 'pedestrian', 'pedestrians', 'operating near pedestrians', 'traffic control', 'no traffic control', 'mobile equipment traffic', 'vehicle pedestrian', 'struck by', 'struck-by', 'spotter', 'backing vehicle', 'backing alarm', 'no alarm'] },
  hazardCommunication: { family: 'Hazard Communication', keywords: ['unlabeled chemical', 'unlabeled chemical containers', 'chemical container', 'chemical containers', 'chemical label', 'missing label', 'hazcom', 'hazard communication', 'sds', 'safety data sheet'] }
};
