import { StandardFamilyCandidateRecord } from './standard-family-candidate.types';

export const STANDARD_FAMILY_REGISTRY: StandardFamilyCandidateRecord[] = [
  {
    id: 'candidate-machine-guarding',
    title: 'Advisory Machine Guarding Standards Review',
    jurisdictionContext: ['msha', 'osha'],
    candidateFamily: 'machine_guarding',
    relatedScenarioFamilies: ['conveyor-cleanup', 'unguarded-conveyor-pulley'],
    relatedHazardDomains: ['machine_guarding'],
    relatedEquipmentIndicators: ['conveyor', 'pulley'],
    relatedTaskIndicators: ['cleanup', 'inspection'],
    relatedMechanismOfInjuryIndicators: ['rotating_equipment_nip_point'],
    relatedExposureIndicators: ['worker near belt'],
    relatedMissingControlIndicators: ['guard missing', 'no LOTO'],
    evidenceRequired: ['guard status', 'LOTO verification'],
    evidenceGaps: ['access control', 'energy state'],
    confidenceBoosters: ['observation of moving parts'],
    confidenceReducers: ['vague description'],
    humanReviewTriggers: ['high risk task'],
    reasoningNotes: ['Review for advisory guarding standards.'],
    whyItMayApply: 'Review mapping for potential hazard.',
    factsSupportingApplicability: [],
    factsStillMissing: [],
    sourceAuthorityTier: 'advisory',
    confidenceBand: 'medium',
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-fire-protection',
    title: 'Advisory Fire Protection Standards Review',
    jurisdictionContext: ['osha'],
    candidateFamily: 'fire_protection',
    relatedScenarioFamilies: ['fire-extinguisher-ambiguity'],
    relatedHazardDomains: ['fire_protection'],
    relatedEquipmentIndicators: ['extinguisher'],
    relatedTaskIndicators: ['inspection'],
    relatedMechanismOfInjuryIndicators: ['fire_extinguisher_access_failure'],
    relatedExposureIndicators: ['emergency access'],
    relatedMissingControlIndicators: ['clearance'],
    evidenceRequired: ['clearance measurements'],
    evidenceGaps: ['clearance status'],
    confidenceBoosters: ['photo evidence'],
    confidenceReducers: ['vague description'],
    humanReviewTriggers: ['emergency access'],
    reasoningNotes: ['Review for advisory fire access standards.'],
    whyItMayApply: 'Review mapping for potential hazard.',
    factsSupportingApplicability: [],
    factsStillMissing: [],
    sourceAuthorityTier: 'advisory',
    confidenceBand: 'medium',
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-loto',
    title: 'Advisory Hazardous Energy Control Standards Review',
    jurisdictionContext: ['osha', 'msha'],
    candidateFamily: 'machine_guarding_loto',
    relatedScenarioFamilies: ['energized-servicing'],
    relatedHazardDomains: ['machine_guarding'],
    relatedEquipmentIndicators: ['machinery'],
    relatedTaskIndicators: ['servicing', 'repair'],
    relatedMechanismOfInjuryIndicators: ['unexpected_startup'],
    relatedExposureIndicators: ['repairman'],
    relatedMissingControlIndicators: ['LOTO'],
    evidenceRequired: ['LOTO verification'],
    evidenceGaps: ['energy state'],
    confidenceBoosters: ['clear observation'],
    confidenceReducers: ['vague task description'],
    humanReviewTriggers: ['high risk'],
    reasoningNotes: ['Review for advisory LOTO standards.'],
    whyItMayApply: 'Review mapping for potential hazard.',
    factsSupportingApplicability: [],
    factsStillMissing: [],
    sourceAuthorityTier: 'advisory',
    confidenceBand: 'medium',
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-mobile-equipment',
    title: 'Advisory Mobile Equipment Standards Review',
    jurisdictionContext: ['msha', 'osha'],
    candidateFamily: 'mobile_equipment',
    relatedScenarioFamilies: ['mobile-pedestrian'],
    relatedHazardDomains: ['mobile_equipment'],
    relatedEquipmentIndicators: ['forklift', 'loader'],
    relatedTaskIndicators: ['transport'],
    relatedMechanismOfInjuryIndicators: ['pedestrian_strike'],
    relatedExposureIndicators: ['worker on foot'],
    relatedMissingControlIndicators: ['separation'],
    evidenceRequired: ['separation measures'],
    evidenceGaps: ['separation measures'],
    confidenceBoosters: ['clear observation'],
    confidenceReducers: ['vague location'],
    humanReviewTriggers: ['high risk'],
    reasoningNotes: ['Review for advisory mobile equipment standards.'],
    whyItMayApply: 'Review mapping for potential hazard.',
    factsSupportingApplicability: [],
    factsStillMissing: [],
    sourceAuthorityTier: 'advisory',
    confidenceBand: 'medium',
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-fall-protection',
    title: 'Advisory Fall Protection Standards Review',
    jurisdictionContext: ['osha'],
    candidateFamily: 'fall_protection',
    relatedScenarioFamilies: ['elevated-fall'],
    relatedHazardDomains: ['fall_protection'],
    relatedEquipmentIndicators: ['ladder', 'platform'],
    relatedTaskIndicators: ['work at height'],
    relatedMechanismOfInjuryIndicators: ['fall_from_height'],
    relatedExposureIndicators: ['worker'],
    relatedMissingControlIndicators: ['guardrail'],
    evidenceRequired: ['fall height'],
    evidenceGaps: ['fall height'],
    confidenceBoosters: ['clear height observation'],
    confidenceReducers: ['vague height'],
    humanReviewTriggers: ['high risk'],
    reasoningNotes: ['Review for advisory fall protection standards.'],
    whyItMayApply: 'Review mapping for potential hazard.',
    factsSupportingApplicability: [],
    factsStillMissing: [],
    sourceAuthorityTier: 'advisory',
    confidenceBand: 'medium',
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-hazcom',
    title: 'Advisory HazCom Standards Review',
    jurisdictionContext: ['osha'],
    candidateFamily: 'hazcom',
    relatedScenarioFamilies: ['chemical-exposure-unclear'],
    relatedHazardDomains: ['hazcom'],
    relatedEquipmentIndicators: ['container'],
    relatedTaskIndicators: ['handling'],
    relatedMechanismOfInjuryIndicators: ['chemical_exposure'],
    relatedExposureIndicators: ['worker'],
    relatedMissingControlIndicators: ['labeling'],
    evidenceRequired: ['SDS availability'],
    evidenceGaps: ['chemical identity'],
    confidenceBoosters: ['photo evidence'],
    confidenceReducers: ['unknown chemical'],
    humanReviewTriggers: ['unknown substance'],
    reasoningNotes: ['Review for advisory HazCom standards.'],
    whyItMayApply: 'Review mapping for potential hazard.',
    factsSupportingApplicability: [],
    factsStillMissing: [],
    sourceAuthorityTier: 'advisory',
    confidenceBand: 'medium',
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-electrical',
    title: 'Advisory Electrical Standards Review',
    jurisdictionContext: ['osha', 'msha'],
    candidateFamily: 'electrical',
    relatedScenarioFamilies: ['electrical-damage'],
    relatedHazardDomains: ['electrical'],
    relatedEquipmentIndicators: ['cord', 'panel'],
    relatedTaskIndicators: ['operation'],
    relatedMechanismOfInjuryIndicators: ['shock'],
    relatedExposureIndicators: ['user'],
    relatedMissingControlIndicators: ['insulation'],
    evidenceRequired: ['equipment state'],
    evidenceGaps: ['equipment state'],
    confidenceBoosters: ['photo of damage'],
    confidenceReducers: ['vague location'],
    humanReviewTriggers: ['hazard present'],
    reasoningNotes: ['Review for advisory electrical standards.'],
    whyItMayApply: 'Review mapping for potential hazard.',
    factsSupportingApplicability: [],
    factsStillMissing: [],
    sourceAuthorityTier: 'advisory',
    confidenceBand: 'medium',
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-emergency-preparedness',
    title: 'Advisory Emergency Preparedness Standards Review',
    jurisdictionContext: ['osha'],
    candidateFamily: 'emergency_preparedness',
    relatedScenarioFamilies: ['blocked-emergency-access'],
    relatedHazardDomains: ['emergency_preparedness'],
    relatedEquipmentIndicators: ['exit', 'pathway'],
    relatedTaskIndicators: ['egress'],
    relatedMechanismOfInjuryIndicators: ['egress_blockage'],
    relatedExposureIndicators: ['occupants'],
    relatedMissingControlIndicators: ['clearance'],
    evidenceRequired: ['clearance status'],
    evidenceGaps: ['clearance status'],
    confidenceBoosters: ['photo of blocked exit'],
    confidenceReducers: ['vague description'],
    humanReviewTriggers: ['emergency access'],
    reasoningNotes: ['Review for advisory emergency preparedness standards.'],
    whyItMayApply: 'Review mapping for potential hazard.',
    factsSupportingApplicability: [],
    factsStillMissing: [],
    sourceAuthorityTier: 'advisory',
    confidenceBand: 'medium',
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  }  ,
  {
    id: 'candidate-confined-space',
    title: 'Advisory Confined Space Standards Review',
    jurisdictionContext: ['osha', 'msha'],
    candidateFamily: 'confined_space',
    relatedScenarioFamilies: ['confined_space_atmosphere_gap'],
    relatedHazardDomains: ['confined_space'],
    relatedEquipmentIndicators: ['confined space', 'tank', 'vessel'],
    relatedTaskIndicators: ['entry', 'cleaning', 'inspection'],
    relatedMechanismOfInjuryIndicators: ['asphyxiation', 'engulfment'],
    relatedExposureIndicators: ['entrant', 'attendant'],
    relatedMissingControlIndicators: ['permit', 'testing', 'ventilation'],
    evidenceRequired: ['permit status', 'atmosphere test results'],
    evidenceGaps: ['entry status', 'atmosphere conditions'],
    confidenceBoosters: ['permit required space identified'],
    confidenceReducers: ['vague location description'],
    humanReviewTriggers: ['confined space entry'],
    reasoningNotes: ['Review for advisory confined space standards.'],
    whyItMayApply: 'Review mapping for potential confined space hazard.',
    factsSupportingApplicability: [],
    factsStillMissing: [],
    sourceAuthorityTier: 'advisory',
    confidenceBand: 'medium',
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-excavation-trenching',
    title: 'Advisory Excavation and Trenching Standards Review',
    jurisdictionContext: ['osha', 'msha'],
    candidateFamily: 'excavation_trenching',
    relatedScenarioFamilies: ['trenching_and_excavation_cavein_gap', 'excavation_cavein'],
    relatedHazardDomains: ['excavation_trenching', 'trenching_and_excavation'],
    relatedEquipmentIndicators: ['trench', 'excavation'],
    relatedTaskIndicators: ['digging', 'trenching', 'shoring'],
    relatedMechanismOfInjuryIndicators: ['caught_in_cave_in', 'engulfment'],
    relatedExposureIndicators: ['worker in trench'],
    relatedMissingControlIndicators: ['shoring', 'sloping', 'shielding', 'spoil pile setback'],
    evidenceRequired: ['depth', 'soil type', 'protective system'],
    evidenceGaps: ['trench depth', 'protective system status'],
    confidenceBoosters: ['worker in deep un-shored trench'],
    confidenceReducers: ['shallow excavation < 5ft without cave-in signs'],
    humanReviewTriggers: ['trench entry'],
    reasoningNotes: ['Review for advisory excavation and trenching standards.'],
    whyItMayApply: 'Review mapping for potential trenching/excavation hazard.',
    factsSupportingApplicability: [],
    factsStillMissing: [],
    sourceAuthorityTier: 'advisory',
    confidenceBand: 'medium',
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-housekeeping',
    title: 'Advisory Housekeeping Standards Review',
    jurisdictionContext: ['osha', 'msha'],
    candidateFamily: 'housekeeping',
    relatedScenarioFamilies: ['housekeeping_slip_trip'],
    relatedHazardDomains: ['slip_trip_fall', 'walking_working_surfaces'],
    relatedEquipmentIndicators: ['walkway', 'travelway', 'floor'],
    relatedTaskIndicators: ['walking', 'access'],
    relatedMechanismOfInjuryIndicators: ['slip_trip_fall_same_level'],
    relatedExposureIndicators: ['pedestrian traffic'],
    relatedMissingControlIndicators: ['clear travelway', 'spill cleanup'],
    evidenceRequired: ['condition of walkway'],
    evidenceGaps: ['spill status', 'walking surface condition'],
    confidenceBoosters: ['fluid or debris on active walkway'],
    confidenceReducers: ['vague location'],
    humanReviewTriggers: ['housekeeping exposure'],
    reasoningNotes: ['Review for advisory housekeeping and walking-working surface standards.'],
    whyItMayApply: 'Review mapping for potential housekeeping hazard.',
    factsSupportingApplicability: [],
    factsStillMissing: [],
    sourceAuthorityTier: 'advisory',
    confidenceBand: 'medium',
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  }
];
