import { SafeScopeReasoningScenario } from './reasoning-scenario.types';

export const SAFESCOPE_REASONING_SCENARIOS: SafeScopeReasoningScenario[] = [
  {
    scenarioId: 'msha-surface-mine-unguarded-conveyor',
    name: 'MSHA surface mine unguarded conveyor',
    description: 'Surface aggregate mine conveyor guarding concern with known employee exposure.',
    request: {
      hazardObservation: 'Unguarded conveyor tail pulley with employee access during cleanup.',
      siteType: 'surface aggregate mine',
      taskContext: 'workplace inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'conveyor tail pulley',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'machine_guarding',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'mobile-equipment-loader-blind-spot-no-spotter',
    name: 'Mobile equipment loader blind spot no spotter',
    description: 'Loader operating near workers with blind spot and no spotter.',
    request: {
      hazardObservation: 'Front-end loader operating near ground workers with blind spot exposure and no spotter assigned.',
      siteType: 'surface aggregate mine',
      taskContext: 'mobile equipment operation inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'front-end loader',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'mobile_equipment',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'mobile-equipment-forklift-seatbelt-question',
    name: 'Mobile equipment forklift seatbelt question',
    description: 'Forklift operation where seatbelt and operator protection need clarification.',
    request: {
      hazardObservation: 'Forklift operating in warehouse with operator seatbelt use and travel path controls unclear.',
      siteType: 'general industry facility',
      taskContext: 'warehouse mobile equipment inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'forklift',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'mobile_equipment',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'mobile-equipment-defective-backup-alarm',
    name: 'Mobile equipment defective backup alarm',
    description: 'Mobile equipment operating with backup alarm concern.',
    request: {
      hazardObservation: 'Loader backing in active work area with backup alarm not functioning.',
      siteType: 'surface mine',
      taskContext: 'equipment operation inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'loader backup alarm',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'mobile_equipment',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'mobile-equipment-preop-inspection-defect',
    name: 'Mobile equipment pre-op inspection defect',
    description: 'Equipment operated with unresolved pre-use inspection defect.',
    request: {
      hazardObservation: 'Mobile equipment operated after pre-op inspection noted brake defect not corrected.',
      siteType: 'surface aggregate mine',
      taskContext: 'pre-operation inspection review',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'mobile equipment brakes',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'mobile_equipment',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'mobile-equipment-raised-bucket-exposure',
    name: 'Mobile equipment raised bucket exposure',
    description: 'Loader bucket raised near employees creating struck-by/crush exposure.',
    request: {
      hazardObservation: 'Loader parked with raised bucket near employees walking through the work area.',
      siteType: 'surface aggregate mine',
      taskContext: 'mobile equipment parking inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'loader raised bucket',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'mobile_equipment',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'machine-guarding-rotating-shaft-general-industry',
    name: 'Machine guarding rotating shaft exposure',
    description: 'General industry rotating shaft exposure with employee access.',
    request: {
      hazardObservation: 'Exposed rotating shaft on production equipment with employee access during operation.',
      siteType: 'general industry facility',
      taskContext: 'production floor inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'rotating shaft',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'machine_guarding',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'machine-guarding-point-of-operation-press',
    name: 'Machine guarding point of operation press',
    description: 'Point-of-operation exposure on press equipment.',
    request: {
      hazardObservation: 'Point of operation on press is accessible during cycling without adequate guard or device.',
      siteType: 'general industry facility',
      taskContext: 'press operation inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'mechanical press',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'machine_guarding',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'machine-guarding-removed-guard-crusher',
    name: 'Machine guarding removed guard on crusher',
    description: 'Mine plant equipment with guard removed from moving parts.',
    request: {
      hazardObservation: 'Guard removed from crusher drive belt area while employees access the plant walkway.',
      siteType: 'surface aggregate mine',
      taskContext: 'plant inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'crusher drive belt',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'machine_guarding',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'machine-guarding-bypassed-interlock',
    name: 'Machine guarding bypassed interlock',
    description: 'Interlocked guard bypassed during machine operation.',
    request: {
      hazardObservation: 'Interlocked machine guard appears bypassed, allowing operation with guard door open.',
      siteType: 'general industry facility',
      taskContext: 'machine operation inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'interlocked guard door',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'machine_guarding',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'machine-guarding-guarded-by-location-question',
    name: 'Machine guarding guarded-by-location question',
    description: 'Ambiguous machine guarding case where guarded-by-location needs qualified review.',
    request: {
      hazardObservation: 'Moving belt and pulley are elevated above normal reach, but access ladder is nearby and maintenance employees work in the area.',
      siteType: 'surface aggregate mine',
      taskContext: 'plant maintenance area inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'elevated belt and pulley',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'machine_guarding',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'osha-construction-open-edge',
    name: 'OSHA construction open edge fall exposure',
    description: 'Construction site elevated open edge with missing photos but known employee exposure.',
    request: {
      hazardObservation: 'Open edge on elevated platform with employees working nearby and no guardrail visible.',
      siteType: 'construction site',
      taskContext: 'steel erection work area',
      industryContext: 'construction',
      photosAvailable: false,
      employeeExposureKnown: true,
      equipmentInvolved: 'elevated platform',
    },
    expectation: {
      expectedJurisdiction: 'osha_construction',
      expectedHazardDomain: 'fall_protection',
      requiresMissingEvidence: true,
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'osha-general-industry-loto-maintenance',
    name: 'OSHA general industry maintenance LOTO concern',
    description: 'General industry maintenance task with potential hazardous energy exposure.',
    request: {
      hazardObservation: 'Maintenance employee working on energized conveyor drive without lockout tagout verification.',
      siteType: 'general industry facility',
      taskContext: 'maintenance',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'conveyor drive',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'lockout_tagout',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'loto-stored-energy-hydraulic-pressure',
    name: 'LOTO stored hydraulic energy concern',
    description: 'Hydraulic stored energy may remain after equipment shutdown.',
    request: {
      hazardObservation: 'Maintenance employee working on hydraulic press with stored pressure not verified as relieved.',
      siteType: 'general industry facility',
      taskContext: 'maintenance',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'hydraulic press',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'lockout_tagout',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'loto-unexpected-startup-conveyor-cleaning',
    name: 'LOTO unexpected startup during conveyor cleaning',
    description: 'Conveyor cleaning activity with possible unexpected startup exposure.',
    request: {
      hazardObservation: 'Employee cleaning around conveyor drive components with no lockout tagout verification before work.',
      siteType: 'surface aggregate mine',
      taskContext: 'conveyor cleanup maintenance',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'conveyor drive',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'lockout_tagout',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'loto-group-lockout-multiple-workers',
    name: 'LOTO group lockout multiple workers',
    description: 'Multiple employees working under a group lockout arrangement.',
    request: {
      hazardObservation: 'Multiple maintenance employees working under group lockout but individual lock control is unclear.',
      siteType: 'general industry facility',
      taskContext: 'group maintenance outage',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'process line',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'lockout_tagout',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'loto-energized-troubleshooting-boundary',
    name: 'LOTO energized troubleshooting boundary',
    description: 'Troubleshooting activity where energized work boundary must be clarified.',
    request: {
      hazardObservation: 'Technician troubleshooting energized equipment with guards open and lockout status unclear.',
      siteType: 'general industry facility',
      taskContext: 'energized troubleshooting',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'energized control cabinet',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'lockout_tagout',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'loto-gravity-energy-raised-equipment',
    name: 'LOTO gravity energy raised equipment',
    description: 'Raised equipment creates gravity/stored energy exposure.',
    request: {
      hazardObservation: 'Employee working beneath raised equipment without documented blocking or gravity energy control.',
      siteType: 'surface aggregate mine',
      taskContext: 'equipment maintenance',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'raised equipment',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'lockout_tagout',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'health-exposure-missing-sampling',
    name: 'Health exposure with missing sampling data',
    description: 'Dust exposure scenario that should require sampling or measurement evidence.',
    request: {
      hazardObservation: 'Possible respirable silica dust exposure during dry sweeping near material transfer point.',
      siteType: 'general industry facility',
      taskContext: 'cleanup',
      industryContext: 'manufacturing',
      photosAvailable: true,
      measurementsAvailable: false,
      employeeExposureKnown: true,
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'health_exposure',
      requiresMissingEvidence: true,
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'fall-protection-floor-hole-general-industry',
    name: 'Fall protection floor hole exposure',
    description: 'Unprotected floor hole with employee travel exposure.',
    request: {
      hazardObservation: 'Unprotected floor hole in walking path with no cover or guardrail.',
      siteType: 'general industry facility',
      taskContext: 'workplace inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'floor hole',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'fall_protection',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'fall-protection-portable-ladder-damaged',
    name: 'Fall protection damaged portable ladder',
    description: 'Damaged ladder used for elevated access.',
    request: {
      hazardObservation: 'Employee using damaged portable ladder with broken rung to access elevated work area.',
      siteType: 'general industry facility',
      taskContext: 'maintenance access',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'portable ladder',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'fall_protection',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'fall-protection-scaffold-missing-guardrail',
    name: 'Fall protection scaffold missing guardrail',
    description: 'Construction scaffold platform missing guardrail protection.',
    request: {
      hazardObservation: 'Scaffold platform has missing guardrail where employees are working at elevation.',
      siteType: 'construction site',
      taskContext: 'scaffold work',
      industryContext: 'construction',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'scaffold platform',
    },
    expectation: {
      expectedJurisdiction: 'osha_construction',
      expectedHazardDomain: 'fall_protection',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'fall-protection-mobile-equipment-access',
    name: 'Fall protection mobile equipment access',
    description: 'Fall exposure while accessing mobile equipment.',
    request: {
      hazardObservation: 'Employee climbs onto haul truck using damaged access ladder and missing handhold.',
      siteType: 'surface mine',
      taskContext: 'mobile equipment access inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'haul truck access ladder',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'fall_protection',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'fall-protection-personal-fall-arrest-question',
    name: 'Fall protection personal fall arrest question',
    description: 'Elevated work where fall arrest use and anchorage adequacy need clarification.',
    request: {
      hazardObservation: 'Employee working at height near open edge using harness, but anchorage point and tie-off status are unclear.',
      siteType: 'construction site',
      taskContext: 'elevated work inspection',
      industryContext: 'construction',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'fall arrest harness',
    },
    expectation: {
      expectedJurisdiction: 'osha_construction',
      expectedHazardDomain: 'fall_protection',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'electrical-damaged-cord-general-industry',
    name: 'Electrical damaged cord general industry',
    description: 'General industry damaged electrical cord with employee exposure.',
    request: {
      hazardObservation: 'Damaged electrical cord with exposed wire being used near a workbench.',
      siteType: 'general industry facility',
      taskContext: 'shop floor inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'portable electrical cord',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'electrical',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'electrical-exposed-live-parts-open-panel',
    name: 'Electrical exposed live parts open panel',
    description: 'Open electrical panel with exposed live parts and employee access.',
    request: {
      hazardObservation: 'Electrical panel cover is open with exposed live parts accessible to employees.',
      siteType: 'general industry facility',
      taskContext: 'electrical room inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'electrical panel',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'electrical',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'electrical-blocked-panel-access',
    name: 'Electrical blocked panel access',
    description: 'Electrical panel blocked by stored materials.',
    request: {
      hazardObservation: 'Electrical panel access is blocked by stored materials and cannot be safely reached.',
      siteType: 'general industry facility',
      taskContext: 'workplace inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'electrical panel',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'electrical',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'electrical-wet-location-gfci-missing',
    name: 'Electrical wet location GFCI concern',
    description: 'Electrical cord use in wet area with missing GFCI information.',
    request: {
      hazardObservation: 'Portable electrical cord used in wet location with no GFCI protection visible.',
      siteType: 'construction site',
      taskContext: 'temporary power inspection',
      industryContext: 'construction',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'portable electrical cord',
    },
    expectation: {
      expectedJurisdiction: 'osha_construction',
      expectedHazardDomain: 'electrical',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'electrical-temporary-wiring-damage',
    name: 'Electrical temporary wiring damage',
    description: 'Temporary wiring damaged in active work area.',
    request: {
      hazardObservation: 'Temporary wiring is damaged and routed across active work area where employees walk.',
      siteType: 'construction site',
      taskContext: 'temporary wiring inspection',
      industryContext: 'construction',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'temporary wiring',
    },
    expectation: {
      expectedJurisdiction: 'osha_construction',
      expectedHazardDomain: 'electrical',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'electrical-arc-flash-energized-panel-work',
    name: 'Electrical arc flash energized panel work',
    description: 'Energized panel work with arc flash and PPE boundary concerns.',
    request: {
      hazardObservation: 'Employee working inside energized electrical panel with arc flash boundary and PPE requirements unclear.',
      siteType: 'general industry facility',
      taskContext: 'energized electrical troubleshooting',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'energized electrical panel',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'electrical',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'confined-space-tank-entry-missing-testing',
    name: 'Confined space tank entry missing atmospheric testing',
    description: 'General industry tank entry with missing atmospheric testing information.',
    request: {
      hazardObservation: 'Employee preparing to enter a tank with limited entry and no atmospheric testing documented.',
      siteType: 'general industry facility',
      taskContext: 'tank entry preparation',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'process tank',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'confined_space',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'mobile-equipment-pedestrian-blind-spot',
    name: 'Mobile equipment pedestrian blind spot',
    description: 'Loader operating near pedestrian travel path with blind spot exposure.',
    request: {
      hazardObservation: 'Front-end loader operating near pedestrian walkway with blind spot exposure and no spotter.',
      siteType: 'surface aggregate mine',
      taskContext: 'workplace inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'front-end loader',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'mobile_equipment',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'powered-haulage-berm-dump-point',
    name: 'Powered haulage berm dump point concern',
    description: 'Mine dump point with inadequate berm and haul truck exposure.',
    request: {
      hazardObservation: 'Haul truck dumping at elevated dump point with inadequate berm at the edge.',
      siteType: 'surface mine',
      taskContext: 'haulage inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'haul truck',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'powered_haulage',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'powered-haulage-blind-intersection',
    name: 'Powered haulage blind intersection',
    description: 'Blind haul road intersection with haul truck traffic and limited visibility.',
    request: {
      hazardObservation: 'Haul road blind intersection has haul truck traffic with limited visibility and no traffic control signs.',
      siteType: 'surface mine',
      taskContext: 'haul road inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'haul truck traffic',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'powered_haulage',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'powered-haulage-stockpile-dumping-edge',
    name: 'Powered haulage stockpile dumping edge',
    description: 'Truck dumping at stockpile edge with dump-point control concerns.',
    request: {
      hazardObservation: 'Haul truck dumping near stockpile edge with unclear dump point control and berm adequacy.',
      siteType: 'surface aggregate mine',
      taskContext: 'stockpile dumping inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'haul truck',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'powered_haulage',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'powered-haulage-runaway-grade',
    name: 'Powered haulage runaway grade concern',
    description: 'Steep haul road grade with runaway or loss-of-control risk.',
    request: {
      hazardObservation: 'Steep haul road grade shows loose material and potential loss of control for loaded haul trucks.',
      siteType: 'surface mine',
      taskContext: 'haul road inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'loaded haul trucks',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'powered_haulage',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'powered-haulage-pedestrian-maintenance-zone',
    name: 'Powered haulage pedestrian maintenance zone',
    description: 'Haulage route near pedestrian maintenance activity.',
    request: {
      hazardObservation: 'Active haulage route passes beside pedestrian maintenance zone with no separation or traffic control plan.',
      siteType: 'surface aggregate mine',
      taskContext: 'maintenance area haulage inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'haulage route',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'powered_haulage',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'powered-haulage-reverse-alarm-spotter-question',
    name: 'Powered haulage reversing alarm spotter question',
    description: 'Haul truck backing near workers where alarm, spotter, and visibility need clarification.',
    request: {
      hazardObservation: 'Haul truck backing near workers with reverse alarm and spotter status unclear.',
      siteType: 'surface mine',
      taskContext: 'truck loading area inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'haul truck backing',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'powered_haulage',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
  {
    scenarioId: 'ground-control-highwall-cracking',
    name: 'Ground control highwall cracking',
    description: 'Surface mine highwall with visible cracking and employee exposure nearby.',
    request: {
      hazardObservation: 'Visible cracking and loose material on highwall above active work area.',
      siteType: 'surface mine',
      taskContext: 'pit inspection',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'highwall',
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'ground_control',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'hazcom-unlabeled-secondary-container',
    name: 'Hazard communication unlabeled secondary container',
    description: 'Unlabeled secondary chemical container in general industry facility.',
    request: {
      hazardObservation: 'Unlabeled secondary container with unknown chemical stored near maintenance area.',
      siteType: 'general industry facility',
      taskContext: 'chemical storage inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'secondary chemical container',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'hazard_communication',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'material-handling-suspended-load',
    name: 'Material handling suspended load exposure',
    description: 'Suspended load moving over employee travel area.',
    request: {
      hazardObservation: 'Suspended load being moved over employee travel path without controlled exclusion area.',
      siteType: 'general industry facility',
      taskContext: 'material handling operation',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'suspended load',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'material_handling',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'walking-working-surfaces-trip-hazard',
    name: 'Walking working surfaces trip hazard',
    description: 'Obstructed travelway with slip/trip exposure.',
    request: {
      hazardObservation: 'Extension cords and debris creating trip hazard across active walking working surface.',
      siteType: 'general industry facility',
      taskContext: 'workplace inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'walking working surface',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'walking_working_surfaces',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'fire-protection-blocked-extinguisher',
    name: 'Fire protection blocked extinguisher',
    description: 'Blocked fire extinguisher access in work area.',
    request: {
      hazardObservation: 'Fire extinguisher blocked by stored materials and not readily accessible.',
      siteType: 'general industry facility',
      taskContext: 'workplace inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'fire extinguisher',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'fire_protection',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'emergency-response-eyewash-access',
    name: 'Emergency response eyewash access issue',
    description: 'Emergency eyewash blocked or unavailable near chemical use area.',
    request: {
      hazardObservation: 'Emergency eyewash station blocked near chemical handling area.',
      siteType: 'general industry facility',
      taskContext: 'chemical handling inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'emergency eyewash station',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'emergency_response',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'ppe-missing-eye-protection',
    name: 'PPE missing eye protection',
    description: 'Employee performing grinding without eye or face protection.',
    request: {
      hazardObservation: 'Employee grinding metal without eye protection or face shield.',
      siteType: 'general industry facility',
      taskContext: 'grinding operation',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'grinder',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'ppe',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'welding-hot-work-combustibles',
    name: 'Welding hot work combustible exposure',
    description: 'Hot work performed near combustible material without fire watch information.',
    request: {
      hazardObservation: 'Welding hot work performed near combustible materials with no fire watch documented.',
      siteType: 'general industry facility',
      taskContext: 'hot work inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'welding equipment',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'welding_cutting_hot_work',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'cranes-rigging-damaged-sling',
    name: 'Cranes rigging damaged sling',
    description: 'Damaged rigging used for hoisting operation.',
    request: {
      hazardObservation: 'Damaged sling used to hoist suspended load during maintenance lift.',
      siteType: 'construction site',
      taskContext: 'hoisting operation',
      industryContext: 'construction',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'damaged sling',
    },
    expectation: {
      expectedJurisdiction: 'osha_construction',
      expectedHazardDomain: 'cranes_rigging_hoisting',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'excavation-trenching-no-protective-system',
    name: 'Excavation trenching missing protective system',
    description: 'Construction excavation with no visible protective system.',
    request: {
      hazardObservation: 'Employee working in trench with vertical walls and no protective system visible.',
      siteType: 'construction site',
      taskContext: 'trenching operation',
      industryContext: 'construction',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'trench excavation',
    },
    expectation: {
      expectedJurisdiction: 'osha_construction',
      expectedHazardDomain: 'excavation_trenching',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'traffic-control-pedestrian-vehicle-conflict',
    name: 'Traffic control pedestrian vehicle conflict',
    description: 'Vehicle traffic crossing pedestrian travel route without controls.',
    request: {
      hazardObservation: 'Forklift traffic crossing pedestrian walkway without signage, barriers, or traffic control.',
      siteType: 'general industry facility',
      taskContext: 'warehouse inspection',
      industryContext: 'manufacturing',
      photosAvailable: true,
      employeeExposureKnown: true,
      equipmentInvolved: 'forklift traffic',
    },
    expectation: {
      expectedJurisdiction: 'osha_general_industry',
      expectedHazardDomain: 'traffic_control',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'training-procedure-gap-new-task',
    name: 'Training procedure gap for new task',
    description: 'Employees assigned new task without documented procedure or task training.',
    request: {
      hazardObservation: 'Employees assigned new cleanup task without documented procedure or task training verification.',
      siteType: 'surface aggregate mine',
      taskContext: 'new cleanup task',
      industryContext: 'mining',
      photosAvailable: true,
      employeeExposureKnown: true,
    },
    expectation: {
      expectedJurisdiction: 'msha',
      expectedHazardDomain: 'training_procedure_gap',
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
    },
  },
  {
    scenarioId: 'vague-observation-low-confidence',
    name: 'Vague observation low confidence',
    description: 'Vague input should stay low confidence and ask for more information.',
    request: {
      hazardObservation: 'Possible issue observed.',
    },
    expectation: {
      expectedJurisdiction: 'unclear',
      expectedHazardDomain: 'unknown',
      expectedConfidence: 'low',
      requiresMissingEvidence: true,
      requiresCorrectiveActions: true,
      requiresVerificationRecommendation: true,
      minimumRecommendedQuestions: 1,
    },
  },
];
