export type ScenarioCoverageJurisdiction =
  | 'msha'
  | 'osha_general_industry'
  | 'osha_construction'
  | 'unclear';

export type ScenarioCoveragePriority = 'critical' | 'high' | 'medium' | 'low';

export type ScenarioCoverageDomain = {
  domain: string;
  label: string;
  priority: ScenarioCoveragePriority;
  relevantJurisdictions: ScenarioCoverageJurisdiction[];
  minimumScenarioTarget: number;
  subtypes: string[];
};

export const SCENARIO_COVERAGE_TAXONOMY: ScenarioCoverageDomain[] = [
  {
    domain: 'machine_guarding',
    label: 'Machine Guarding',
    priority: 'critical',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 6,
    subtypes: [
      'unguarded_belt',
      'unguarded_pulley',
      'nip_point',
      'pinch_point',
      'rotating_shaft',
      'point_of_operation_guard',
      'removed_or_bypassed_guard',
      'damaged_guard',
      'guarded_by_location_question',
      'maintenance_access_exposure',
    ],
  },
  {
    domain: 'lockout_tagout',
    label: 'Lockout / Tagout / Hazardous Energy',
    priority: 'critical',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 6,
    subtypes: [
      'maintenance_without_lockout',
      'unexpected_startup',
      'stored_energy',
      'blocked_energy_isolation',
      'verification_missing',
      'group_lockout',
      'energized_troubleshooting',
      'hydraulic_energy',
      'pneumatic_energy',
      'gravity_energy',
    ],
  },
  {
    domain: 'fall_protection',
    label: 'Fall Protection / Elevated Work',
    priority: 'critical',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 6,
    subtypes: [
      'open_edge',
      'missing_guardrail',
      'unprotected_platform',
      'ladder_exposure',
      'scaffold_exposure',
      'floor_hole',
      'travelway_fall_hazard',
      'mobile_equipment_access_fall',
      'fall_arrest_question',
    ],
  },
  {
    domain: 'electrical',
    label: 'Electrical Safety',
    priority: 'critical',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 6,
    subtypes: [
      'damaged_cord',
      'exposed_live_parts',
      'open_panel',
      'missing_cover',
      'blocked_electrical_panel',
      'improper_grounding',
      'gfci_missing',
      'wet_location_electrical',
      'temporary_wiring',
      'arc_flash_concern',
      'trailing_cable_damage',
    ],
  },
  {
    domain: 'confined_space',
    label: 'Confined Space',
    priority: 'critical',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 5,
    subtypes: [
      'permit_required_space',
      'atmospheric_hazard',
      'engulfment_hazard',
      'limited_entry_exit',
      'rescue_plan_missing',
      'ventilation_missing',
      'testing_missing',
      'entrant_attendant_issue',
    ],
  },
  {
    domain: 'hazard_communication',
    label: 'Hazard Communication',
    priority: 'high',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 4,
    subtypes: [
      'missing_label',
      'unlabeled_secondary_container',
      'sds_unavailable',
      'chemical_storage_issue',
      'employee_training_gap',
      'incompatible_chemicals',
      'unknown_substance',
    ],
  },
  {
    domain: 'mobile_equipment',
    label: 'Mobile Equipment',
    priority: 'critical',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 6,
    subtypes: [
      'pre_operation_inspection_gap',
      'backup_alarm_issue',
      'seatbelt_issue',
      'blind_spot_exposure',
      'pedestrian_interaction',
      'parking_brake_issue',
      'defective_lights',
      'equipment_access_egress',
      'rollover_exposure',
    ],
  },
  {
    domain: 'powered_haulage',
    label: 'Powered Haulage',
    priority: 'critical',
    relevantJurisdictions: ['msha'],
    minimumScenarioTarget: 6,
    subtypes: [
      'haul_road_condition',
      'berm_missing_or_inadequate',
      'dump_point_exposure',
      'traffic_pattern_conflict',
      'stockpile_dumping',
      'loader_truck_interaction',
      'backup_exposure',
      'road_grade_or_curve',
      'night_visibility',
    ],
  },
  {
    domain: 'ground_control',
    label: 'Ground Control',
    priority: 'critical',
    relevantJurisdictions: ['msha', 'osha_construction'],
    minimumScenarioTarget: 5,
    subtypes: [
      'highwall_instability',
      'bench_instability',
      'rock_fall',
      'slope_failure',
      'unsupported_ground',
      'excavation_wall_instability',
      'stockpile_sloughing',
      'ground_crack_or_void',
    ],
  },
  {
    domain: 'health_exposure',
    label: 'Health Exposure / Industrial Hygiene',
    priority: 'critical',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 8,
    subtypes: [
      'silica_dust',
      'respirable_dust',
      'noise',
      'welding_fume',
      'chemical_vapor',
      'diesel_particulate',
      'heat_stress',
      'sampling_missing',
      'exposure_duration_unknown',
      'respiratory_protection_question',
    ],
  },
  {
    domain: 'material_handling',
    label: 'Material Handling',
    priority: 'high',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 4,
    subtypes: [
      'manual_lifting',
      'suspended_load',
      'stacking_storage',
      'falling_material',
      'conveyor_material_spillage',
      'pinch_between_materials',
    ],
  },
  {
    domain: 'walking_working_surfaces',
    label: 'Walking Working Surfaces',
    priority: 'high',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 5,
    subtypes: [
      'slip_trip_fall',
      'housekeeping',
      'uneven_surface',
      'wet_surface',
      'stairway_issue',
      'travelway_obstruction',
      'floor_opening',
    ],
  },
  {
    domain: 'fire_protection',
    label: 'Fire Protection',
    priority: 'high',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 4,
    subtypes: [
      'blocked_extinguisher',
      'missing_extinguisher',
      'flammable_storage',
      'ignition_source',
      'hot_work_fire_watch',
      'emergency_exit_blocked',
    ],
  },
  {
    domain: 'emergency_response',
    label: 'Emergency Response',
    priority: 'high',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 4,
    subtypes: [
      'first_aid_access',
      'emergency_eyewash',
      'evacuation_route',
      'rescue_plan',
      'communication_gap',
      'emergency_drill_gap',
    ],
  },
  {
    domain: 'ppe',
    label: 'Personal Protective Equipment',
    priority: 'medium',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 4,
    subtypes: [
      'eye_face_protection',
      'hand_protection',
      'hearing_protection',
      'respirator_use',
      'high_visibility_apparel',
      'foot_protection',
      'ppe_condition',
    ],
  },
  {
    domain: 'welding_cutting_hot_work',
    label: 'Welding / Cutting / Hot Work',
    priority: 'high',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 4,
    subtypes: [
      'hot_work_fire_watch',
      'compressed_gas_cylinder',
      'flash_burn_exposure',
      'fume_exposure',
      'combustible_material_nearby',
      'regulator_or_hose_damage',
    ],
  },
  {
    domain: 'cranes_rigging_hoisting',
    label: 'Cranes / Rigging / Hoisting',
    priority: 'high',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 4,
    subtypes: [
      'suspended_load',
      'rigging_damage',
      'load_rating_question',
      'signal_person_issue',
      'crane_setup',
      'tagline_missing',
      'dropped_object_exposure',
    ],
  },
  {
    domain: 'excavation_trenching',
    label: 'Excavation / Trenching',
    priority: 'critical',
    relevantJurisdictions: ['osha_construction', 'msha'],
    minimumScenarioTarget: 5,
    subtypes: [
      'protective_system_missing',
      'spoil_pile_too_close',
      'water_accumulation',
      'access_egress_missing',
      'underground_utility',
      'competent_person_review',
    ],
  },
  {
    domain: 'traffic_control',
    label: 'Traffic Control / Work Zone Interaction',
    priority: 'high',
    relevantJurisdictions: ['msha', 'osha_construction', 'osha_general_industry'],
    minimumScenarioTarget: 4,
    subtypes: [
      'pedestrian_vehicle_interaction',
      'traffic_pattern_gap',
      'spotter_issue',
      'signage_missing',
      'temporary_work_zone',
      'blind_corner',
    ],
  },
  {
    domain: 'training_procedure_gap',
    label: 'Training / Procedure Gap',
    priority: 'medium',
    relevantJurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    minimumScenarioTarget: 4,
    subtypes: [
      'task_training_missing',
      'procedure_not_available',
      'new_task_not_reviewed',
      'contractor_orientation_gap',
      'supervisor_instruction_gap',
    ],
  },
  {
    domain: 'unknown',
    label: 'Unknown / Insufficient Information',
    priority: 'critical',
    relevantJurisdictions: ['unclear'],
    minimumScenarioTarget: 3,
    subtypes: [
      'vague_observation',
      'missing_site_type',
      'missing_exposure_information',
      'missing_photos',
      'unclear_task_context',
    ],
  },
];

export const SCENARIO_COVERAGE_DOMAIN_IDS = SCENARIO_COVERAGE_TAXONOMY.map((item) => item.domain);
