import { SafeScopeEvidenceGapRecord } from './evidence-gap-intelligence.types';

export const SAFESCOPE_EVIDENCE_GAP_INTELLIGENCE_REGISTRY: SafeScopeEvidenceGapRecord[] = [
  {
    gapId: 'machine-guarding-exposure-confirmation',
    label: 'Machine guarding exposure confirmation',
    hazardDomains: ['machine_guarding'],
    mechanisms: ['rotating_equipment', 'rotating_equipment_nip_point', 'pinch_point'],
    jurisdictions: ['msha', 'osha_general_industry'],
    triggerTerms: ['guard', 'unguarded', 'moving parts', 'rotating', 'pinch point', 'nip point', 'conveyor'],
    missingEvidenceTerms: ['exposure', 'distance', 'guard opening', 'access', 'employee task', 'measure'],
    impact: ['citation_selection', 'mechanism_selection', 'severity_risk', 'report_defensibility'],
    severity: 'high',
    whyItMatters: 'Guarding findings are more defensible when the exposed moving part, employee access route, and exposure distance are clear.',
    inspectorQuestion: 'What moving part is exposed, how can employees access it during normal work, and is the guard missing, damaged, or inadequate?',
    recommendedDisposition: 'proceed_with_human_review',
  },
  {
    gapId: 'fall-height-and-edge-condition',
    label: 'Fall height and edge-condition confirmation',
    hazardDomains: ['fall_protection', 'walking_working_surfaces', 'slips_trips_falls', 'slip_trip_fall'],
    mechanisms: ['fall_from_height', 'fall_on_stairway', 'fall_from_ladder'],
    jurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    triggerTerms: ['fall', 'edge', 'platform', 'stairway', 'ladder', 'guardrail', 'handrail', 'elevated'],
    missingEvidenceTerms: ['height', 'distance', 'open side', 'guardrail', 'handrail', 'anchor', 'tie off'],
    impact: ['citation_selection', 'severity_risk', 'corrective_action_quality', 'report_defensibility'],
    severity: 'high',
    whyItMatters: 'Fall-related citations and corrective actions depend heavily on height, walking surface, edge condition, and protection method.',
    inspectorQuestion: 'What is the approximate fall height, what surface or edge is involved, and what fall protection or railing is missing or inadequate?',
    recommendedDisposition: 'proceed_with_human_review',
  },
  {
    gapId: 'electrical-energized-status',
    label: 'Electrical energized-status confirmation',
    hazardDomains: ['electrical'],
    mechanisms: ['shock', 'shock_arc_flash'],
    jurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    triggerTerms: ['electrical', 'energized', 'live', 'conductor', 'wiring', 'panel', 'cable', 'arc flash'],
    missingEvidenceTerms: ['energized', 'voltage', 'exposed', 'qualified person', 'cover', 'insulation', 'lockout'],
    impact: ['mechanism_selection', 'severity_risk', 'corrective_action_quality', 'human_review'],
    severity: 'critical',
    whyItMatters: 'Electrical risk changes significantly depending on whether parts are energized, exposed, damaged, guarded, or locked out.',
    inspectorQuestion: 'Are the parts energized or assumed energized, what voltage is involved if known, and are live parts exposed to employee contact?',
    recommendedDisposition: 'hold_for_critical_evidence',
  },
  {
    gapId: 'mobile-equipment-pedestrian-interface',
    label: 'Mobile equipment and pedestrian interface confirmation',
    hazardDomains: ['mobile_equipment', 'powered_haulage'],
    mechanisms: ['pedestrian_strike', 'struck_by', 'run_off_embankment'],
    jurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    triggerTerms: ['forklift', 'haul truck', 'loader', 'mobile equipment', 'pedestrian', 'traffic', 'backing', 'blind spot'],
    missingEvidenceTerms: ['pedestrian route', 'traffic control', 'visibility', 'spotter', 'berm', 'backup alarm', 'separation'],
    impact: ['mechanism_selection', 'severity_risk', 'corrective_action_quality', 'human_review'],
    severity: 'high',
    whyItMatters: 'Mobile equipment findings require clarity on equipment movement, pedestrian exposure, traffic controls, visibility, and work-zone separation.',
    inspectorQuestion: 'What equipment was moving, where were pedestrians located, and what traffic controls, alarms, berms, spotters, or separation methods were present?',
    recommendedDisposition: 'proceed_with_human_review',
  },
  {
    gapId: 'airborne-contaminant-exposure-controls',
    label: 'Airborne contaminant exposure and controls confirmation',
    hazardDomains: ['health_exposure', 'health_respiratory', 'ventilation', 'environmental_exposure'],
    mechanisms: ['silica_inhalation', 'methane_gas_buildup', 'air_quality_contaminant_buildup', 'chemical_exposure'],
    jurisdictions: ['msha', 'osha_general_industry', 'osha_construction'],
    triggerTerms: ['dust', 'silica', 'air quality', 'ventilation', 'contaminant', 'methane', 'fume', 'vapor'],
    missingEvidenceTerms: ['sampling', 'measurement', 'ventilation', 'respirator', 'exposure duration', 'visible dust', 'airflow'],
    impact: ['citation_selection', 'severity_risk', 'corrective_action_quality', 'report_defensibility'],
    severity: 'high',
    whyItMatters: 'Health exposure findings need exposure pathway, duration, controls, and measurement context to avoid unsupported conclusions.',
    inspectorQuestion: 'What contaminant is suspected, how are employees exposed, what ventilation or respiratory controls are present, and are measurements or sampling available?',
    recommendedDisposition: 'proceed_with_human_review',
  },
  {
    gapId: 'chemical-identity-and-sds-confirmation',
    label: 'Chemical identity and SDS confirmation',
    hazardDomains: ['hazardous_materials', 'hazard_communication', 'health_exposure'],
    mechanisms: ['chemical_exposure', 'fire_explosion'],
    jurisdictions: ['osha_general_industry', 'osha_construction', 'msha'],
    triggerTerms: ['chemical', 'container', 'unlabeled', 'sds', 'hazcom', 'corrosive', 'flammable', 'caustic'],
    missingEvidenceTerms: ['chemical name', 'label', 'sds', 'hazard class', 'quantity', 'container', 'secondary container'],
    impact: ['citation_selection', 'mechanism_selection', 'corrective_action_quality', 'report_defensibility'],
    severity: 'medium',
    whyItMatters: 'Chemical findings require chemical identity, container status, SDS availability, and hazard class before selecting the most defensible corrective action.',
    inspectorQuestion: 'What chemical is involved, is the container labeled, is an SDS available, and what hazard class or exposure route applies?',
    recommendedDisposition: 'proceed_with_human_review',
  },
  {
    gapId: 'emergency-equipment-access-confirmation',
    label: 'Emergency equipment access confirmation',
    hazardDomains: ['emergency_preparedness', 'emergency_response', 'fire_protection'],
    mechanisms: ['emergency_equipment_access_failure', 'fire_extinguisher_access_failure', 'egress_blockage'],
    jurisdictions: ['osha_general_industry', 'osha_construction', 'msha'],
    triggerTerms: ['eyewash', 'emergency shower', 'fire extinguisher', 'egress', 'escapeway', 'blocked', 'obstructed'],
    missingEvidenceTerms: ['distance', 'access', 'blocked', 'inspection tag', 'location', 'path', 'available'],
    impact: ['citation_selection', 'corrective_action_quality', 'human_review', 'report_defensibility'],
    severity: 'high',
    whyItMatters: 'Emergency equipment and egress findings require access path, availability, location, obstruction, and inspection condition.',
    inspectorQuestion: 'What emergency equipment or egress path is affected, how is access blocked or limited, and is the equipment inspected and immediately usable?',
    recommendedDisposition: 'proceed_with_human_review',
  },
  {
    gapId: 'loto-energy-state-confirmation',
    label: 'LOTO energy-state confirmation',
    hazardDomains: ['machine_guarding_loto', 'lockout_tagout'],
    mechanisms: ['unexpected_startup', 'stored_energy_release'],
    jurisdictions: ['osha_general_industry', 'msha'],
    triggerTerms: ['lockout', 'tagout', 'loto', 'maintenance', 'servicing', 'stored energy', 'unexpected startup'],
    missingEvidenceTerms: ['energy source', 'locked out', 'verified zero energy', 'stored energy', 'procedure', 'authorized employee'],
    impact: ['mechanism_selection', 'severity_risk', 'corrective_action_quality', 'human_review'],
    severity: 'critical',
    whyItMatters: 'LOTO findings depend on task phase, energy source, isolation status, verification, and whether servicing or maintenance was underway.',
    inspectorQuestion: 'What task was being performed, what energy sources were present, were they locked out, and was zero-energy verification completed?',
    recommendedDisposition: 'hold_for_critical_evidence',
  },
];
