import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { NextConfig } from "next";

/**
 * §279 — THE FRONTEND'S RELEASE IDENTITY IS GENERATED BY THE BUILD, NOT MAINTAINED BY HAND.
 *
 * §279 Part A found the frontend had no version identity of any kind: no build stamp, no commit,
 * nothing a running tab could compare against the server. The backend already had `build-info.ts`,
 * and §270 had already measured what a hand-maintained literal does to it -- it reported a
 * timestamp four months older than the running build, confidently, for every release.
 *
 * So this does not add a second file to forget to update. It resolves the identity at BUILD time
 * from sources that cannot go stale, and `next.config.ts` is the right place because it is the one
 * piece of this project that runs in Node with the git working tree present and can inline the
 * result into the client bundle through `env`.
 *
 * The resolution chain mirrors the backend's deliberately, including its central rule: a value
 * that cannot be established reports `unknown` rather than something that looks like an answer.
 * `git rev-parse` is LAST, because on Vercel the platform variable is authoritative and the build
 * container may not even contain a `.git` directory.
 */
function firstEnv(names: string[]): string | null {
  for (const name of names) {
    const value = process.env[name];
    if (value && value.trim()) return value.trim();
  }
  return null;
}

function resolveGitSha(): string {
  const supplied = firstEnv(["VERCEL_GIT_COMMIT_SHA", "GIT_COMMIT", "GIT_SHA", "COMMIT_SHA"]);
  if (supplied) return supplied;
  try {
    return execFileSync("git", ["rev-parse", "HEAD"], {
      cwd: __dirname,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    // No git, no platform variable: say so. A fabricated sha would be worse than an absent one,
    // because support would chase a build that never existed.
    return "unknown";
  }
}

function resolveBuildTimestamp(): string {
  const supplied = firstEnv(["BUILD_TIMESTAMP", "VERCEL_DEPLOYMENT_CREATED_AT"]);
  if (supplied) {
    const parsed = new Date(/^\d{9,13}$/.test(supplied) ? Number(supplied) : supplied);
    if (!Number.isNaN(parsed.getTime())) return parsed.toISOString();
  }
  // The moment this configuration was evaluated IS the moment the build started, so unlike the
  // backend's checked-in literal there is nothing here that can be stale.
  return new Date().toISOString();
}

function resolveFrontendVersion(): string {
  try {
    const manifest = JSON.parse(readFileSync(resolve(__dirname, "package.json"), "utf8")) as {
      version?: string;
    };
    return typeof manifest.version === "string" ? manifest.version : "unknown";
  } catch {
    return "unknown";
  }
}

const gitSha = resolveGitSha();
const frontendVersion = resolveFrontendVersion();

/**
 * §290 — CONTROLLED-DEPLOYMENT INDEXING. THRESHOLD A IS DEPLOYED, NOT ANNOUNCED.
 *
 * Threshold A puts the candidate on production infrastructure with no external users. The
 * production alias is nevertheless publicly reachable -- Vercel exempts a project's own production
 * domain from the SSO that protects Preview -- so without this the release would be crawlable and
 * indexable by anyone who found it, before External Beta has been authorised and before any of the
 * Threshold-C claims, terms or clearance work is done.
 *
 * WHY A HEADER, AND NOT robots.txt. `Disallow: /` is the instinctive answer and it is the wrong
 * one: it forbids the CRAWL, which means a crawler that learns the URL from an external link can
 * still list it and will never fetch the page to discover a noindex. Blocking the crawl actively
 * prevents the de-indexing instruction from being seen. `X-Robots-Tag` travels on the response
 * itself, applies to every route and to non-HTML responses a `<meta>` tag cannot reach, and is
 * honoured by Google, Bing and the other major crawlers.
 *
 * WHY NOT AN ACCESS CONTROL. §290 is explicit that authentication remains the access boundary and
 * that no new access-control system is to be built for this. This is an indexing policy, not a
 * security control: it asks well-behaved crawlers not to list the site, and it is worth exactly
 * that and no more. Nothing here is load-bearing for confidentiality -- the product's own auth is.
 *
 * HOW IT IS LIFTED. Set `NEXT_PUBLIC_ALLOW_INDEXING=true` on the Vercel production environment and
 * redeploy. The default is to WITHHOLD indexing, so a forgotten variable fails toward "not
 * indexed" rather than toward an unannounced product being listed.
 */
const allowIndexing = process.env.NEXT_PUBLIC_ALLOW_INDEXING === "true";
const INDEXING_POLICY = allowIndexing ? "index, follow" : "noindex, nofollow";

const nextConfig: NextConfig = {
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [{ key: "X-Robots-Tag", value: INDEXING_POLICY }],
      },
    ];
  },
  // Verification builds and audit servers must never write into the `.next/`
  // directory a running `next dev` is using: a `next build` that lands there
  // while the dev server is live corrupts its output and the dev server then
  // answers 500 on every route (recorded as the local-dev cache fault in
  // blueprint 71.12). Setting NEXT_DIST_DIR gives an isolated build directory,
  // so an audit or a production-build check can run alongside `npm run dev`.
  distDir: process.env.NEXT_DIST_DIR || ".next",
  turbopack: {
    root: __dirname,
  },
  allowedDevOrigins: ["127.0.0.1", "localhost"],
  env: {
    NEXT_PUBLIC_FRONTEND_VERSION: frontendVersion,
    NEXT_PUBLIC_GIT_SHA: gitSha,
    NEXT_PUBLIC_BUILD_TIMESTAMP: resolveBuildTimestamp(),
    /**
     * The service-worker cache generation. Deriving it from the commit is what makes the
     * worker's existing `activate` purge -- which deletes every `insite-shell-*` cache that is
     * not the current generation -- actually do something. Until §279 the generation was the
     * literal `v1` in `public/sw.js`, so it never changed, so nothing was ever purged and every
     * release's chunks accumulated in one cache for the life of the installation.
     */
    NEXT_PUBLIC_SHELL_CACHE_GENERATION: gitSha === "unknown" ? "v1" : gitSha.slice(0, 12),
    /** Surfaced so the deployed build can be asked what policy it was built with. */
    NEXT_PUBLIC_INDEXING_POLICY: INDEXING_POLICY,
  },
};

export default nextConfig;
