export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ORG_OWNER = 'ORG_OWNER',
  SAFETY_DIRECTOR = 'SAFETY_DIRECTOR',
  SUPERVISOR = 'SUPERVISOR',
  AUDITOR = 'AUDITOR',
  WORKER = 'WORKER',
  VIEWER = 'VIEWER',
}
