import { StandardsIntelligenceRecord } from "./standards-intelligence.types";

export const STANDARDS_INTELLIGENCE_SEED: StandardsIntelligenceRecord[] = [
  {
    citation: "30 CFR 56.14107(a)",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "M",
    title: "Moving machine parts",
    plainLanguageSummary:
      "Moving machine parts must be guarded when they can contact miners or create contact, pinch-point, entanglement, or caught-in exposure.",
    hazardFamilies: ["Machine Guarding", "Caught-In/Between", "Entanglement"],
    equipmentTags: [
      "conveyor",
      "tail pulley",
      "head pulley",
      "belt",
      "roller",
      "idler",
      "shaft",
      "sprocket",
      "chain",
      "fan",
      "rotating part",
    ],
    taskTags: [
      "cleanup",
      "maintenance",
      "inspection",
      "normal operation",
      "repair",
      "adjustment",
    ],
    exposureTags: [
      "accessible",
      "reachable",
      "walkway",
      "travelway",
      "platform",
      "work area",
      "near worker",
      "line of fire",
    ],
    controlTags: [
      "guarding",
      "fixed guard",
      "barrier",
      "restricted access",
      "lockout",
      "tagout",
      "verify guard",
    ],
    consequenceTags: [
      "entanglement",
      "amputation",
      "crushing",
      "fatality",
      "caught-in",
    ],
    searchBoostTerms: [
      "unguarded",
      "missing guard",
      "damaged guard",
      "tail pulley",
      "pinch point",
      "moving parts",
      "conveyor",
    ],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    evidenceRequirements: [
      {
        question: "Is a moving machine part present?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question:
          "Can a miner or employee contact the moving part from a walkway, work area, platform, or maintenance position?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question:
          "Is guarding missing, damaged, removed, bypassed, or inadequate?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question:
          "Was cleanup, maintenance, inspection, or normal work occurring near the equipment?",
        requiredForPrimary: false,
        missingEvidenceImpact: "medium",
      },
      {
        question:
          "Was energy isolation or lockout/tagout needed before correction?",
        requiredForPrimary: false,
        missingEvidenceImpact: "medium",
      },
    ],
    exclusionRules: [
      {
        reason: "No moving machinery or machine part is described.",
        excludeWhenMissingAny: [
          "conveyor",
          "pulley",
          "belt",
          "shaft",
          "roller",
          "sprocket",
          "chain",
          "rotating",
          "moving part",
        ],
      },
    ],
    crossDomainLinks: [
      "Lockout / Stored Energy",
      "Electrical",
      "Powered Haulage",
      "Workplace Examination",
    ],
  },
  {
    citation: "30 CFR 57.14107(a)",
    agency: "MSHA",
    scope: "mining",
    part: "57",
    subpart: "M",
    title: "Moving machine parts",
    plainLanguageSummary:
      "Underground metal/nonmetal moving machine parts must be guarded when contact exposure exists.",
    hazardFamilies: ["Machine Guarding", "Caught-In/Between", "Entanglement"],
    equipmentTags: [
      "conveyor",
      "tail pulley",
      "belt",
      "roller",
      "idler",
      "shaft",
      "sprocket",
      "chain",
      "rotating part",
    ],
    taskTags: [
      "cleanup",
      "maintenance",
      "inspection",
      "normal operation",
      "repair",
    ],
    exposureTags: [
      "accessible",
      "reachable",
      "walkway",
      "travelway",
      "work area",
    ],
    controlTags: ["guarding", "fixed guard", "barrier", "lockout", "tagout"],
    consequenceTags: ["entanglement", "amputation", "crushing", "fatality"],
    searchBoostTerms: [
      "unguarded",
      "missing guard",
      "tail pulley",
      "moving parts",
      "conveyor",
    ],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    evidenceRequirements: [
      {
        question:
          "Is the operation underground metal/nonmetal or otherwise under Part 57?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question: "Is a moving machine part accessible to miners?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question:
          "Is guarding missing, damaged, removed, bypassed, or inadequate?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
    ],
    exclusionRules: [
      {
        reason: "No underground/Part 57 context is established.",
        excludeWhenMissingAny: ["underground", "part 57", "metal/nonmetal"],
      },
    ],
    crossDomainLinks: [
      "Lockout / Stored Energy",
      "Electrical",
      "Powered Haulage",
    ],
  },
  {
    citation: "30 CFR 56.14105",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "M",
    title: "Procedures during repairs or maintenance",
    plainLanguageSummary:
      "Machinery or equipment must be blocked against hazardous motion and power must be off when repairs or maintenance expose miners to hazardous motion.",
    hazardFamilies: [
      "Lockout / Stored Energy",
      "Machine Guarding",
      "Maintenance Safety",
    ],
    equipmentTags: [
      "conveyor",
      "belt",
      "crusher",
      "screen",
      "mobile equipment",
      "machinery",
      "powered equipment",
    ],
    taskTags: [
      "maintenance",
      "repair",
      "cleanup",
      "jam clearing",
      "adjustment",
      "troubleshooting",
    ],
    exposureTags: [
      "unexpected startup",
      "hazardous motion",
      "stored energy",
      "energized",
      "operating equipment",
    ],
    controlTags: [
      "lockout",
      "tagout",
      "block against motion",
      "de-energize",
      "verify zero energy",
    ],
    consequenceTags: ["caught-in", "crushing", "entanglement", "fatality"],
    searchBoostTerms: [
      "maintenance",
      "repair",
      "cleaning",
      "jam",
      "lockout",
      "tagout",
      "energized",
      "started unexpectedly",
    ],
    authorityTier: 1,
    applicabilityBandDefault: "supporting",
    severityDefault: "critical",
    evidenceRequirements: [
      {
        question:
          "Was repair, maintenance, cleanup, jam clearing, or adjustment occurring?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question:
          "Could equipment start, move, roll, rotate, or release stored energy?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question:
          "Was the equipment locked/tagged out, de-energized, or blocked against motion?",
        requiredForPrimary: false,
        missingEvidenceImpact: "high",
      },
    ],
    exclusionRules: [
      {
        reason:
          "No repair, maintenance, cleanup, or hazardous-motion work activity is described.",
        excludeWhenMissingAny: [
          "maintenance",
          "repair",
          "cleanup",
          "cleaning",
          "jam",
          "adjustment",
          "service",
        ],
      },
    ],
    crossDomainLinks: ["Machine Guarding", "Electrical", "Conveyor Safety"],
  },
  {
    citation: "30 CFR 56.12016",
    agency: "MSHA",
    scope: "msha",
    part: "56",
    subpart: "K",
    title: "Work on electrically powered equipment",
    plainLanguageSummary:
      "Electrical work or work on electrically powered equipment requires safe de-energization, lockout, and protection from electrical exposure where applicable.",
    hazardFamilies: ["Electrical", "Lockout / Stored Energy"],
    equipmentTags: [
      "electrical equipment",
      "panel",
      "conductor",
      "wire",
      "cable",
      "motor",
      "disconnect",
      "breaker",
    ],
    taskTags: [
      "electrical work",
      "maintenance",
      "troubleshooting",
      "repair",
      "inspection",
    ],
    exposureTags: [
      "energized",
      "live",
      "shock exposure",
      "arc flash",
      "exposed conductor",
    ],
    controlTags: [
      "de-energize",
      "lockout",
      "tagout",
      "qualified person",
      "verify absence of voltage",
    ],
    consequenceTags: [
      "shock",
      "electrocution",
      "arc flash",
      "burn",
      "fatality",
    ],
    searchBoostTerms: [
      "energized conductor",
      "live wire",
      "open panel",
      "electrical",
      "voltage",
      "breaker",
      "arc flash",
    ],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    evidenceRequirements: [
      {
        question:
          "Is electrical equipment, conductor, cable, wire, panel, or energized component involved?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question:
          "Is the component energized, live, exposed, damaged, or being worked on?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question: "Was a qualified person required for the work?",
        requiredForPrimary: false,
        missingEvidenceImpact: "medium",
      },
    ],
    exclusionRules: [
      {
        reason:
          "Energized-state wording alone is not enough without an electrical component or electrical work context.",
        excludeWhenMissingAny: [
          "electrical",
          "conductor",
          "wire",
          "cable",
          "panel",
          "breaker",
          "voltage",
          "live",
          "arc flash",
        ],
      },
    ],
    crossDomainLinks: ["Lockout / Stored Energy", "Machine Guarding"],
  },
  {
    citation: "1910.212(a)(1)",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "O",
    title: "Machine guarding - types of guarding methods",
    plainLanguageSummary:
      "Machines must have guarding to protect employees from hazards such as points of operation, ingoing nip points, rotating parts, flying chips, and sparks.",
    hazardFamilies: ["Machine Guarding", "Caught-In/Between"],
    equipmentTags: [
      "machine",
      "conveyor",
      "shaft",
      "belt",
      "pulley",
      "sprocket",
      "gear",
      "point of operation",
    ],
    taskTags: ["operation", "maintenance", "cleanup", "inspection"],
    exposureTags: [
      "point of operation",
      "ingoing nip point",
      "rotating part",
      "accessible",
    ],
    controlTags: ["machine guarding", "barrier", "device", "safeguard"],
    consequenceTags: ["amputation", "caught-in", "laceration", "crushing"],
    searchBoostTerms: [
      "machine guarding",
      "point of operation",
      "nip point",
      "rotating parts",
      "unguarded",
    ],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    evidenceRequirements: [
      {
        question:
          "Is this OSHA General Industry rather than MSHA or construction?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question: "Is there employee exposure to a machine hazard?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
    ],
    exclusionRules: [
      {
        reason: "Excluded when selected scope is MSHA-only.",
        keywordsAny: ["msha only", "mine site", "30 cfr"],
      },
    ],
    crossDomainLinks: ["Lockout / Stored Energy"],
  },
  {
    citation: "1910.219",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "O",
    title: "Mechanical power-transmission apparatus",
    plainLanguageSummary:
      "Mechanical power-transmission equipment such as belts, pulleys, shafts, gears, and sprockets must be guarded where employee exposure exists.",
    hazardFamilies: ["Machine Guarding", "Power Transmission"],
    equipmentTags: [
      "belt",
      "pulley",
      "shaft",
      "gear",
      "sprocket",
      "chain",
      "coupling",
    ],
    taskTags: ["operation", "maintenance", "inspection"],
    exposureTags: [
      "accessible",
      "rotating part",
      "nip point",
      "power transmission",
    ],
    controlTags: ["guarding", "barrier", "enclosure"],
    consequenceTags: ["entanglement", "amputation", "crushing"],
    searchBoostTerms: [
      "pulley",
      "belt",
      "shaft",
      "sprocket",
      "power transmission",
      "unguarded",
    ],
    authorityTier: 1,
    applicabilityBandDefault: "supporting",
    severityDefault: "high",
    evidenceRequirements: [
      {
        question: "Is OSHA General Industry applicable?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question: "Is power-transmission apparatus involved?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
    ],
    exclusionRules: [
      {
        reason: "Excluded when selected scope is MSHA-only.",
        keywordsAny: ["msha only", "mine site", "30 cfr"],
      },
    ],
    crossDomainLinks: ["Machine Guarding"],
  },
  {
    citation: "29 CFR 1910.147",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "J",
    title: "The control of hazardous energy",
    plainLanguageSummary:
      "Servicing and maintenance activities require control of hazardous energy to prevent unexpected energization, startup, or release of stored energy.",
    hazardFamilies: ["Lockout / Stored Energy"],
    equipmentTags: [
      "machine",
      "equipment",
      "conveyor",
      "press",
      "motor",
      "mechanical equipment",
    ],
    taskTags: [
      "servicing",
      "maintenance",
      "repair",
      "cleaning",
      "jam clearing",
      "adjustment",
    ],
    exposureTags: [
      "unexpected startup",
      "energization",
      "stored energy",
      "hazardous energy",
    ],
    controlTags: [
      "lockout",
      "tagout",
      "energy isolation",
      "zero energy verification",
    ],
    consequenceTags: ["caught-in", "crushing", "electrocution", "fatality"],
    searchBoostTerms: [
      "lockout",
      "tagout",
      "loto",
      "unexpected startup",
      "stored energy",
      "servicing",
    ],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    evidenceRequirements: [
      {
        question: "Is OSHA General Industry applicable?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question: "Was servicing or maintenance being performed?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question:
          "Could unexpected energization, startup, or stored energy release occur?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
    ],
    exclusionRules: [
      {
        reason:
          "Normal production operation without servicing or maintenance may not trigger LOTO.",
        excludeWhenMissingAny: [
          "maintenance",
          "servicing",
          "repair",
          "cleaning",
          "jam",
          "adjustment",
        ],
      },
    ],
    crossDomainLinks: ["Machine Guarding", "Electrical"],
  },
  {
    citation: "29 CFR 1926.501",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "M",
    title: "Duty to have fall protection",
    plainLanguageSummary:
      "Construction employers must provide fall protection where employees are exposed to fall hazards at applicable elevations or conditions.",
    hazardFamilies: ["Fall Protection", "Walking/Working Surfaces"],
    equipmentTags: [
      "roof",
      "scaffold",
      "ladder",
      "platform",
      "floor opening",
      "edge",
    ],
    taskTags: ["construction", "roofing", "elevated work", "scaffold work"],
    exposureTags: [
      "unprotected edge",
      "floor hole",
      "elevation",
      "fall distance",
    ],
    controlTags: [
      "guardrail",
      "fall arrest",
      "fall restraint",
      "cover",
      "warning line",
    ],
    consequenceTags: ["fall", "fatality", "fracture"],
    searchBoostTerms: [
      "fall protection",
      "unprotected edge",
      "floor hole",
      "guardrail",
      "six feet",
    ],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    evidenceRequirements: [
      {
        question: "Is construction work occurring?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
      {
        question: "What is the fall height or exposure condition?",
        requiredForPrimary: true,
        missingEvidenceImpact: "high",
      },
    ],
    exclusionRules: [
      {
        reason: "Construction scope not established.",
        excludeWhenMissingAny: [
          "construction",
          "1926",
          "roofing",
          "scaffold",
          "contractor",
        ],
      },
    ],
    crossDomainLinks: ["Scaffolds", "Ladders", "Walking/Working Surfaces"],
  },
];
