import { SafeScopeSourceRegistryEntry } from "./safescope-source-registry.types";

export const SAFESCOPE_SOURCE_REGISTRY: SafeScopeSourceRegistryEntry[] = [
  {
    sourceKey: "msha-30-cfr-standards",
    displayName: "MSHA 30 CFR Standards",
    agency: "MSHA",
    sourceType: "regulation",
    authorityTier: 1,
    allowedUse: "primary_regulatory_authority",
    baseUrl: "https://www.ecfr.gov/current/title-30",
    description:
      "Primary MSHA regulatory standards used for final citation matching and compliance applicability.",
    jurisdictionTags: [
      "msha",
      "mining",
      "metal-nonmetal",
      "coal",
      "surface",
      "underground",
    ],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["30 CFR"],
    defaultLessonTags: ["primary authority", "regulatory standard"],
    requiresApproval: true,
    approvedForAutoIngestion: true,
    refreshCadence: "monthly",
    ingestionNotes:
      "Ingest standards by part/subpart/section. Preserve citation, heading, standard text, effective date, and jurisdiction.",
    reviewerNotes:
      "Tier 1 authority. May support primary standards if scope and applicability are established.",
  },
  {
    sourceKey: "msha-program-policy-manual",
    displayName: "MSHA Program Policy Manual",
    agency: "MSHA",
    sourceType: "policy_manual",
    authorityTier: 2,
    allowedUse: "official_guidance",
    baseUrl: "https://www.msha.gov/regulations/program-policy-manual",
    description:
      "Official MSHA policy guidance supporting interpretation and enforcement context.",
    jurisdictionTags: ["msha", "mining"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["MSHA PPM"],
    defaultLessonTags: ["official policy guidance", "interpretation support"],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "quarterly",
    ingestionNotes:
      "Use for interpretive support only. Link guidance to specific CFR sections where possible.",
    reviewerNotes:
      "Tier 2 guidance. Should not replace CFR text, but can explain how a standard is interpreted.",
  },
  {
    sourceKey: "msha-fatality-reports",
    displayName: "MSHA Fatality Reports",
    agency: "MSHA",
    sourceType: "fatality_report",
    authorityTier: 3,
    allowedUse: "incident_learning",
    baseUrl: "https://www.msha.gov/data-and-reports/fatality-reports/search",
    description:
      "MSHA fatality alerts and fatal accident reports used for incident learning, prevention patterns, and evidence questions.",
    jurisdictionTags: ["msha", "mining", "fatality learning"],
    hazardTags: [
      "machine guarding",
      "powered haulage",
      "electrical",
      "fall hazard",
      "ground control",
      "confined space",
      "hazardous energy",
    ],
    equipmentTags: [
      "conveyor",
      "mobile equipment",
      "loader",
      "truck",
      "electrical equipment",
    ],
    taskTags: [
      "maintenance",
      "cleanup",
      "travel",
      "inspection",
      "repair",
      "operation",
    ],
    standardTags: [
      "workplace examination",
      "machine guarding",
      "lockout tagout",
      "powered haulage",
    ],
    defaultLessonTags: [
      "fatality prevention",
      "incident learning",
      "critical controls",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: true,
    refreshCadence: "weekly",
    ingestionNotes:
      "Extract title, date, mine type, accident classification, narrative, best practices, equipment, task, causal lessons, and related standards.",
    reviewerNotes:
      "Tier 3 incident learning. Supports reasoning and prevention, but does not replace primary regulatory standards.",
  },
  {
    sourceKey: "msha-safety-alerts",
    displayName: "MSHA Safety Alerts and Safety Materials",
    agency: "MSHA",
    sourceType: "best_practice_guidance",
    authorityTier: 4,
    allowedUse: "supporting_best_practice",
    baseUrl:
      "https://www.msha.gov/safety-and-health/safety-and-health-materials",
    description:
      "MSHA safety materials, alerts, and hazard prevention resources used as supporting best-practice intelligence.",
    jurisdictionTags: ["msha", "mining"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: [
      "best practice",
      "hazard prevention",
      "training support",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "monthly",
    ingestionNotes:
      "Use to enrich controls, evidence questions, training reminders, and prevention guidance.",
    reviewerNotes:
      "Tier 4 supporting guidance. Do not treat as a citation unless tied to an enforceable standard.",
  },
  {
    sourceKey: "osha-ecfr-1910",
    displayName: "OSHA 29 CFR 1910 General Industry Standards",
    agency: "OSHA",
    sourceType: "regulation",
    authorityTier: 1,
    allowedUse: "primary_regulatory_authority",
    baseUrl:
      "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910",
    description:
      "Primary OSHA General Industry regulatory standards for citation matching and applicability reasoning.",
    jurisdictionTags: ["osha", "general industry", "1910"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["29 CFR 1910"],
    defaultLessonTags: ["primary authority", "regulatory standard"],
    requiresApproval: true,
    approvedForAutoIngestion: true,
    refreshCadence: "monthly",
    ingestionNotes:
      "Ingest by subpart and section. Preserve standard text, citation, heading, and subpart context.",
    reviewerNotes:
      "Tier 1 authority. Use for final OSHA General Industry citation matching.",
  },
  {
    sourceKey: "osha-ecfr-1926",
    displayName: "OSHA 29 CFR 1926 Construction Standards",
    agency: "OSHA",
    sourceType: "regulation",
    authorityTier: 1,
    allowedUse: "primary_regulatory_authority",
    baseUrl:
      "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926",
    description:
      "Primary OSHA Construction regulatory standards for citation matching and applicability reasoning.",
    jurisdictionTags: ["osha", "construction", "1926"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["29 CFR 1926"],
    defaultLessonTags: ["primary authority", "regulatory standard"],
    requiresApproval: true,
    approvedForAutoIngestion: true,
    refreshCadence: "monthly",
    ingestionNotes:
      "Ingest by subpart and section. Preserve construction scope and standard hierarchy.",
    reviewerNotes:
      "Tier 1 authority. Use for final OSHA Construction citation matching.",
  },
  {
    sourceKey: "osha-fatality-catastrophe-data",
    displayName: "OSHA Fatality and Catastrophe Data",
    agency: "OSHA",
    sourceType: "incident_database",
    authorityTier: 3,
    allowedUse: "incident_learning",
    baseUrl: "https://www.osha.gov/ords/imis/accidentsearch.html",
    description:
      "OSHA accident investigation and fatality/catastrophe information used for incident learning patterns.",
    jurisdictionTags: ["osha", "incident learning", "fatality", "catastrophe"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: [
      "incident learning",
      "fatality prevention",
      "case pattern",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "monthly",
    ingestionNotes:
      "Extract event type, industry, hazard, task, equipment, narrative, and standards where available.",
    reviewerNotes:
      "Tier 3 incident learning. Useful for prevention patterns and scenario expansion.",
  },
  {
    sourceKey: "niosh-face-reports",
    displayName: "NIOSH FACE Reports",
    agency: "NIOSH",
    sourceType: "fatal_accident_report",
    authorityTier: 3,
    allowedUse: "incident_learning",
    baseUrl: "https://www.cdc.gov/niosh/face/",
    description:
      "NIOSH Fatality Assessment and Control Evaluation reports used for detailed fatality prevention lessons.",
    jurisdictionTags: ["niosh", "cdc", "fatality learning"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: [
      "fatality prevention",
      "control recommendations",
      "incident learning",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "monthly",
    ingestionNotes:
      "Extract incident sequence, root causes, recommendations, controls, equipment, and task context.",
    reviewerNotes:
      "Tier 3 incident learning. Strong prevention value but not primary regulatory authority.",
  },
  {
    sourceKey: "niosh-mining-publications",
    displayName: "NIOSH Mining Safety and Health Publications",
    agency: "NIOSH",
    sourceType: "research_publication",
    authorityTier: 4,
    allowedUse: "supporting_best_practice",
    baseUrl: "https://www.cdc.gov/niosh/mining/",
    description:
      "NIOSH mining research and guidance used for supporting best practices, exposure controls, and prevention strategies.",
    jurisdictionTags: ["niosh", "mining", "research"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: [
      "research support",
      "best practice",
      "prevention guidance",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "quarterly",
    ingestionNotes:
      "Use for supporting control recommendations and risk context. Tag carefully by hazard and equipment.",
    reviewerNotes:
      "Tier 4 research/best practice. Should support, not replace, regulatory standards.",
  },
  {
    sourceKey: "csb-investigation-reports",
    displayName: "Chemical Safety Board Investigation Reports",
    agency: "CSB",
    sourceType: "fatal_accident_report",
    authorityTier: 3,
    allowedUse: "incident_learning",
    baseUrl: "https://www.csb.gov/investigations/",
    description:
      "CSB investigation reports used for chemical process safety, explosion, fire, and systemic incident learning.",
    jurisdictionTags: [
      "chemical safety",
      "process safety",
      "incident learning",
    ],
    hazardTags: ["fire", "explosion", "chemical release", "process safety"],
    equipmentTags: ["tank", "vessel", "reactor", "piping", "pressure system"],
    taskTags: [
      "maintenance",
      "hot work",
      "startup",
      "shutdown",
      "chemical processing",
    ],
    standardTags: [],
    defaultLessonTags: [
      "incident learning",
      "process safety",
      "critical controls",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "monthly",
    ingestionNotes:
      "Use mainly for fire, explosion, chemical, confined space, hot work, and process safety lessons.",
    reviewerNotes:
      "Tier 3 incident learning. Strong for causal reasoning and controls, not primary OSHA/MSHA citation.",
  },
  {
    sourceKey: "osha-standard-interpretations",
    displayName: "OSHA Standard Interpretations",
    agency: "OSHA",
    sourceType: "standard_interpretation",
    authorityTier: 2,
    allowedUse: "official_guidance",
    baseUrl: "https://www.osha.gov/laws-regs/standardinterpretations",
    description:
      "Official OSHA letters of interpretation used to support applicability and explain ambiguous standard requirements.",
    jurisdictionTags: [
      "osha",
      "interpretation",
      "general industry",
      "construction",
    ],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["OSHA interpretation"],
    defaultLessonTags: ["official guidance", "interpretation support"],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "monthly",
    ingestionNotes: "Map each interpretation to the relevant OSHA citation.",
    reviewerNotes:
      "Tier 2 guidance. Use to support interpretation, not as standalone primary citation.",
  },
  {
    sourceKey: "osha-safety-health-topics",
    displayName: "OSHA Safety and Health Topics",
    agency: "OSHA",
    sourceType: "best_practice_guidance",
    authorityTier: 4,
    allowedUse: "supporting_best_practice",
    baseUrl: "https://www.osha.gov/safety-management/hazard-prevention",
    description:
      "OSHA hazard-specific guidance providing best practice recognition and control recommendations.",
    jurisdictionTags: ["osha", "hazard recognition", "best practice"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["OSHA topic"],
    defaultLessonTags: [
      "best practice",
      "hazard recognition",
      "control support",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "monthly",
    ingestionNotes: "Use for hazard recognition and control context.",
    reviewerNotes:
      "Tier 4 best-practice guidance. Not an enforceable standard, but provides strong context.",
  },
  {
    sourceKey: "osha-directives",
    displayName: "OSHA Directives",
    agency: "OSHA",
    sourceType: "best_practice_guidance",
    authorityTier: 2,
    allowedUse: "official_guidance",
    baseUrl: "https://www.osha.gov/enforcement/directives",
    description:
      "Official OSHA directives providing enforcement policy and interpretation context.",
    jurisdictionTags: ["osha", "enforcement", "policy"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["OSHA directive"],
    defaultLessonTags: ["official policy", "enforcement guidance"],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "quarterly",
    ingestionNotes: "Extract enforcement policy context for interpretations.",
    reviewerNotes:
      "Tier 2 guidance. Supports enforcement context, not primary regulatory authority.",
  },
  {
    sourceKey: "internal-supervisor-feedback",
    displayName: "Internal Supervisor Feedback and Site Memory",
    agency: "INTERNAL",
    sourceType: "internal_learning",
    authorityTier: 5,
    allowedUse: "internal_workspace_learning",
    baseUrl: "internal://supervisor-feedback",
    description:
      "Workspace-specific accepted/rejected classifications, standard selections, corrective actions, and closure outcomes.",
    jurisdictionTags: ["workspace learning", "site memory"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: [
      "site memory",
      "feedback learning",
      "trend intelligence",
    ],
    requiresApproval: false,
    approvedForAutoIngestion: true,
    refreshCadence: "daily",
    ingestionNotes:
      "Use to influence ranking and trend intelligence. Never allow internal feedback to override regulatory authority.",
    reviewerNotes:
      "Tier 5 internal learning. Supports prioritization and recurrence detection only.",
  },
  {
    sourceKey: "niosh-numbered-publications",
    displayName: "NIOSH Numbered Publications",
    agency: "NIOSH",
    sourceType: "niosh_publication",
    authorityTier: 4,
    allowedUse: "supporting_best_practice",
    baseUrl: "https://www.cdc.gov/niosh/docs/",
    description:
      "NIOSH numbered publications used for scientific, exposure-control, and prevention support.",
    jurisdictionTags: ["niosh", "cdc", "research", "occupational health"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: ["federal research", "health risk", "prevention"],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "quarterly",
    ingestionNotes:
      "Use as scientific support. Preserve publication number, topic, date, and recommendations.",
    reviewerNotes:
      "Federal research support. Not enforceable regulation; use with qualified review.",
  },
  {
    sourceKey: "niosh-health-hazard-evaluations",
    displayName: "NIOSH Health Hazard Evaluations",
    agency: "NIOSH",
    sourceType: "health_hazard_evaluation",
    authorityTier: 3,
    allowedUse: "supporting_best_practice",
    baseUrl: "https://www.cdc.gov/niosh/hhe/",
    description:
      "NIOSH Health Hazard Evaluations used for exposure assessment, health-risk reasoning, and control recommendations.",
    jurisdictionTags: ["niosh", "cdc", "health hazard evaluation", "exposure"],
    hazardTags: [
      "chemical exposure",
      "noise",
      "silica",
      "heat stress",
      "ergonomics",
    ],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: [
      "health risk",
      "exposure evaluation",
      "scientific support",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "quarterly",
    ingestionNotes:
      "Extract exposure type, sampling context, health findings, recommendations, and limitations.",
    reviewerNotes:
      "Scientific health-risk support. Not a compliance citation by itself.",
  },
  {
    sourceKey: "niosh-alerts",
    displayName: "NIOSH Alerts",
    agency: "NIOSH",
    sourceType: "niosh_alert",
    authorityTier: 4,
    allowedUse: "supporting_best_practice",
    baseUrl: "https://www.cdc.gov/niosh/docs/alerts/",
    description:
      "NIOSH alerts used for hazard recognition, prevention, and health-risk control recommendations.",
    jurisdictionTags: ["niosh", "cdc", "alert", "prevention"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: ["alert", "prevention", "health risk"],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "quarterly",
    ingestionNotes:
      "Use as preventive guidance and scientific support. Preserve date and hazard scope.",
    reviewerNotes: "Safety/health alert support. Not enforceable regulation.",
  },
  {
    sourceKey: "niosh-criteria-documents",
    displayName: "NIOSH Criteria Documents",
    agency: "NIOSH",
    sourceType: "criteria_document",
    authorityTier: 3,
    allowedUse: "supporting_best_practice",
    baseUrl: "https://www.cdc.gov/niosh/docs/criteria/",
    description:
      "NIOSH criteria documents used for scientific basis, exposure control, and health-risk reasoning.",
    jurisdictionTags: [
      "niosh",
      "cdc",
      "criteria document",
      "occupational health",
    ],
    hazardTags: [
      "chemical exposure",
      "respirable dust",
      "noise",
      "heat stress",
    ],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: ["scientific basis", "health risk", "exposure control"],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "annual",
    ingestionNotes:
      "Use to support health-risk reasoning and controls. Preserve limitations and publication date.",
    reviewerNotes:
      "Scientific support. Should not override OSHA/MSHA standards.",
  },
  {
    sourceKey: "osha-publications",
    displayName: "OSHA Publications",
    agency: "OSHA",
    sourceType: "training_material",
    authorityTier: 4,
    allowedUse: "supporting_best_practice",
    baseUrl: "https://www.osha.gov/publications",
    description:
      "OSHA publications used for training, hazard recognition, and control planning support.",
    jurisdictionTags: ["osha", "publication", "training"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["OSHA publication"],
    defaultLessonTags: [
      "training support",
      "hazard recognition",
      "control support",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "quarterly",
    ingestionNotes:
      "Use for training and control context. Link to underlying standards where possible.",
    reviewerNotes: "Supporting material. Not a substitute for regulatory text.",
  },
  {
    sourceKey: "osha-compliance-assistance",
    displayName: "OSHA Compliance Assistance Resources",
    agency: "OSHA",
    sourceType: "best_practice_guidance",
    authorityTier: 4,
    allowedUse: "supporting_best_practice",
    baseUrl: "https://www.osha.gov/complianceassistance",
    description:
      "OSHA compliance assistance resources used for control planning and plain-language support.",
    jurisdictionTags: ["osha", "compliance assistance"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: ["compliance assistance", "control support"],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "quarterly",
    ingestionNotes:
      "Use to support corrective actions and training context; do not treat as primary citation.",
    reviewerNotes:
      "Supporting guidance only unless tied to a specific standard.",
  },
  {
    sourceKey: "msha-compliance-assistance",
    displayName: "MSHA Compliance Assistance Resources",
    agency: "MSHA",
    sourceType: "best_practice_guidance",
    authorityTier: 4,
    allowedUse: "supporting_best_practice",
    baseUrl: "https://www.msha.gov/compliance-and-enforcement",
    description:
      "MSHA compliance assistance resources used for mining control planning, outreach, and training support.",
    jurisdictionTags: ["msha", "mining", "compliance assistance"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: [
      "compliance assistance",
      "training support",
      "control support",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "quarterly",
    ingestionNotes:
      "Use for mining-specific training and control support. Link to CFR where possible.",
    reviewerNotes: "Supporting guidance; should not replace 30 CFR.",
  },
  {
    sourceKey: "msha-health-topic-pages",
    displayName: "MSHA Health Topic Pages",
    agency: "MSHA",
    sourceType: "best_practice_guidance",
    authorityTier: 4,
    allowedUse: "supporting_best_practice",
    baseUrl: "https://www.msha.gov/safety-and-health",
    description:
      "MSHA health topic and safety-health pages used for hazard recognition and health control support.",
    jurisdictionTags: ["msha", "mining", "health"],
    hazardTags: ["silica", "noise", "dust", "heat stress"],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: [
      "health control",
      "hazard recognition",
      "training support",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "quarterly",
    ingestionNotes:
      "Use for health hazard context and controls; preserve link to standards where available.",
    reviewerNotes: "Supporting guidance. Not primary regulatory authority.",
  },
  {
    sourceKey: "ansi-assp-standards-metadata",
    displayName: "ANSI/ASSP Standards Metadata",
    agency: "ASSP",
    sourceType: "consensus_standard_metadata",
    authorityTier: 4,
    allowedUse: "context_only",
    baseUrl: "https://www.assp.org/standards",
    description:
      "Metadata-only reference to ANSI/ASSP consensus standards. Do not ingest copyrighted standards text unless licensed/provided by the user.",
    jurisdictionTags: ["ansi", "assp", "consensus standard", "metadata"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["ANSI", "ASSP"],
    defaultLessonTags: ["technical design support", "license check required"],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "annual",
    ingestionNotes:
      "Metadata/reference only. Store title, standard number, scope, and user-provided licensed excerpts only.",
    reviewerNotes:
      "Requires license check. Supports technical design context, not primary OSHA/MSHA citation.",
  },
  {
    sourceKey: "nfpa-standards-metadata",
    displayName: "NFPA Standards Metadata",
    agency: "NFPA",
    sourceType: "consensus_standard_metadata",
    authorityTier: 4,
    allowedUse: "context_only",
    baseUrl: "https://www.nfpa.org/codes-and-standards",
    description:
      "Metadata-only reference to NFPA standards. Do not ingest copyrighted standards text unless licensed/provided by the user.",
    jurisdictionTags: ["nfpa", "consensus standard", "metadata"],
    hazardTags: ["fire", "electrical", "chemical"],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["NFPA"],
    defaultLessonTags: ["technical design support", "license check required"],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "annual",
    ingestionNotes:
      "Metadata/reference only. Store public metadata and user-provided licensed excerpts only.",
    reviewerNotes:
      "Requires license check. Do not treat as primary OSHA/MSHA citation.",
  },
  {
    sourceKey: "astm-standards-metadata",
    displayName: "ASTM Standards Metadata",
    agency: "ASTM",
    sourceType: "consensus_standard_metadata",
    authorityTier: 4,
    allowedUse: "context_only",
    baseUrl: "https://www.astm.org/",
    description:
      "Metadata-only reference to ASTM standards. Do not ingest copyrighted standards text unless licensed/provided by the user.",
    jurisdictionTags: ["astm", "consensus standard", "metadata"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["ASTM"],
    defaultLessonTags: ["technical design support", "license check required"],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "annual",
    ingestionNotes:
      "Metadata/reference only. Store public metadata and user-provided licensed excerpts only.",
    reviewerNotes: "Requires license check. Supports technical context only.",
  },
  {
    sourceKey: "iso-standards-metadata",
    displayName: "ISO Standards Metadata",
    agency: "ISO",
    sourceType: "consensus_standard_metadata",
    authorityTier: 4,
    allowedUse: "context_only",
    baseUrl: "https://www.iso.org/standards.html",
    description:
      "Metadata-only reference to ISO standards. Do not ingest copyrighted standards text unless licensed/provided by the user.",
    jurisdictionTags: ["iso", "consensus standard", "metadata"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["ISO"],
    defaultLessonTags: ["technical design support", "license check required"],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "annual",
    ingestionNotes:
      "Metadata/reference only. Store public metadata and user-provided licensed excerpts only.",
    reviewerNotes: "Requires license check. Supports technical context only.",
  },
  {
    sourceKey: "acgih-tlv-metadata",
    displayName: "ACGIH TLV Metadata",
    agency: "ACGIH",
    sourceType: "consensus_standard_metadata",
    authorityTier: 4,
    allowedUse: "context_only",
    baseUrl: "https://www.acgih.org/science/tlv-bei-guidelines/",
    description:
      "Metadata-only reference to ACGIH TLV/BEI resources. Do not ingest copyrighted values or text unless licensed/provided by the user.",
    jurisdictionTags: [
      "acgih",
      "tlv",
      "bei",
      "metadata",
      "occupational health",
    ],
    hazardTags: ["chemical exposure", "noise", "heat stress"],
    equipmentTags: [],
    taskTags: [],
    standardTags: ["ACGIH TLV", "ACGIH BEI"],
    defaultLessonTags: [
      "health risk",
      "license check required",
      "technical support",
    ],
    requiresApproval: true,
    approvedForAutoIngestion: false,
    refreshCadence: "annual",
    ingestionNotes:
      "Metadata/reference only. Do not store copyrighted TLV/BEI values unless licensed/provided by the user.",
    reviewerNotes:
      "Requires license check. Supports health-risk reasoning, not OSHA/MSHA citation.",
  },
  {
    sourceKey: "internal-site-memory",
    displayName: "Internal Site Memory",
    agency: "INTERNAL",
    sourceType: "internal_site_memory",
    authorityTier: 5,
    allowedUse: "internal_workspace_learning",
    baseUrl: "internal://site-memory",
    description:
      "Site-specific context, recurring hazards, local controls, and operational history.",
    jurisdictionTags: ["workspace learning", "site memory"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: ["site context", "recurrence detection"],
    requiresApproval: false,
    approvedForAutoIngestion: true,
    refreshCadence: "daily",
    ingestionNotes:
      "Use for local context and recurrence. Never override external authority.",
    reviewerNotes:
      "Internal context only. Not a standard or external authority.",
  },
  {
    sourceKey: "internal-corrective-action-history",
    displayName: "Internal Corrective Action History",
    agency: "INTERNAL",
    sourceType: "internal_corrective_action_history",
    authorityTier: 5,
    allowedUse: "internal_workspace_learning",
    baseUrl: "internal://corrective-action-history",
    description:
      "Historical corrective actions, closure evidence, effectiveness checks, and repeat controls.",
    jurisdictionTags: ["workspace learning", "corrective action history"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: [
      "closure history",
      "control effectiveness",
      "recurrence detection",
    ],
    requiresApproval: false,
    approvedForAutoIngestion: true,
    refreshCadence: "daily",
    ingestionNotes:
      "Use for recurrence and effectiveness intelligence. Do not use as external authority.",
    reviewerNotes:
      "Internal context only. Supports prioritization and prevention.",
  },
  {
    sourceKey: "internal-repeat-findings",
    displayName: "Internal Repeat Findings",
    agency: "INTERNAL",
    sourceType: "internal_repeat_finding",
    authorityTier: 5,
    allowedUse: "internal_workspace_learning",
    baseUrl: "internal://repeat-findings",
    description:
      "Repeat findings used for recurrence detection, trend intelligence, and escalation logic.",
    jurisdictionTags: ["workspace learning", "repeat finding", "trend"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: ["repeat finding", "trend intelligence", "recurrence"],
    requiresApproval: false,
    approvedForAutoIngestion: true,
    refreshCadence: "daily",
    ingestionNotes:
      "Use to increase recurrence awareness and escalation. Never override external authority.",
    reviewerNotes: "Internal context only. Not a compliance citation.",
  },
  {
    sourceKey: "internal-training-records",
    displayName: "Internal Training Records",
    agency: "INTERNAL",
    sourceType: "internal_training_record",
    authorityTier: 5,
    allowedUse: "internal_workspace_learning",
    baseUrl: "internal://training-records",
    description:
      "Training and competency records used for local context, verification, and evidence gaps.",
    jurisdictionTags: ["workspace learning", "training", "competency"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: ["training verification", "competency", "local context"],
    requiresApproval: false,
    approvedForAutoIngestion: true,
    refreshCadence: "daily",
    ingestionNotes:
      "Use for competency context and evidence gaps. Do not use as external authority.",
    reviewerNotes:
      "Internal context only; may support training-related corrective actions.",
  },
  {
    sourceKey: "internal-near-misses",
    displayName: "Internal Near Misses",
    agency: "INTERNAL",
    sourceType: "internal_near_miss",
    authorityTier: 5,
    allowedUse: "internal_workspace_learning",
    baseUrl: "internal://near-misses",
    description:
      "Near-miss records used for trend intelligence, hazard recognition, and prevention planning.",
    jurisdictionTags: ["workspace learning", "near miss", "trend"],
    hazardTags: [],
    equipmentTags: [],
    taskTags: [],
    standardTags: [],
    defaultLessonTags: ["near miss", "prevention", "trend intelligence"],
    requiresApproval: false,
    approvedForAutoIngestion: true,
    refreshCadence: "daily",
    ingestionNotes:
      "Use for prevention and trend intelligence. Not a substitute for external authority.",
    reviewerNotes:
      "Internal context only. Supports prevention and recurrence analysis.",
  },
];

export function getSafeScopeSourceByKey(sourceKey: string) {
  return SAFESCOPE_SOURCE_REGISTRY.find(
    (source) => source.sourceKey === sourceKey,
  );
}

export function getSafeScopeSourcesByAuthorityTier(authorityTier: number) {
  return SAFESCOPE_SOURCE_REGISTRY.filter(
    (source) => source.authorityTier === authorityTier,
  );
}

export function getSafeScopeSourcesByAgency(agency: string) {
  const normalized = agency.toLowerCase();
  return SAFESCOPE_SOURCE_REGISTRY.filter(
    (source) => source.agency.toLowerCase() === normalized,
  );
}

export function getApprovedAutoIngestionSources() {
  return SAFESCOPE_SOURCE_REGISTRY.filter(
    (source) => source.approvedForAutoIngestion,
  );
}
