import { StandardFamilyCandidateRecord } from './standard-family-candidate.types';

export const STANDARD_FAMILY_REGISTRY: StandardFamilyCandidateRecord[] = [
  {
    id: 'candidate-machine-guarding',
    title: 'Advisory Machine Guarding Standards Review',
    jurisdictionContext: ['msha', 'osha'],
    candidateFamily: 'machine_guarding',
    relatedScenarioFamilies: ['conveyor-cleanup', 'unguarded-conveyor-pulley'],
    relatedHazardDomains: ['machine_guarding'],
    relatedEquipmentIndicators: ['conveyor', 'pulley'],
    relatedTaskIndicators: ['cleanup', 'inspection'],
    relatedMechanismOfInjuryIndicators: ['rotating_equipment_nip_point'],
    relatedExposureIndicators: ['worker near belt'],
    relatedMissingControlIndicators: ['guard missing', 'no LOTO'],
    evidenceRequired: ['guard status', 'LOTO verification'],
    evidenceGaps: ['access control', 'energy state'],
    confidenceBoosters: ['observation of moving parts'],
    confidenceReducers: ['vague description'],
    humanReviewTriggers: ['high risk task'],
    reasoningNotes: ['Review for advisory guarding standards.'],
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-fire-protection',
    title: 'Advisory Fire Protection Standards Review',
    jurisdictionContext: ['osha'],
    candidateFamily: 'fire_protection',
    relatedScenarioFamilies: ['fire-extinguisher-ambiguity'],
    relatedHazardDomains: ['fire_protection'],
    relatedEquipmentIndicators: ['extinguisher'],
    relatedTaskIndicators: ['inspection'],
    relatedMechanismOfInjuryIndicators: ['fire_extinguisher_access_failure'],
    relatedExposureIndicators: ['emergency access'],
    relatedMissingControlIndicators: ['clearance'],
    evidenceRequired: ['clearance measurements'],
    evidenceGaps: ['clearance status'],
    confidenceBoosters: ['photo evidence'],
    confidenceReducers: ['vague description'],
    humanReviewTriggers: ['emergency access'],
    reasoningNotes: ['Review for advisory fire access standards.'],
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-loto',
    title: 'Advisory Hazardous Energy Control Standards Review',
    jurisdictionContext: ['osha', 'msha'],
    candidateFamily: 'machine_guarding_loto',
    relatedScenarioFamilies: ['energized-servicing'],
    relatedHazardDomains: ['machine_guarding'],
    relatedEquipmentIndicators: ['machinery'],
    relatedTaskIndicators: ['servicing', 'repair'],
    relatedMechanismOfInjuryIndicators: ['unexpected_startup'],
    relatedExposureIndicators: ['repairman'],
    relatedMissingControlIndicators: ['LOTO'],
    evidenceRequired: ['LOTO verification'],
    evidenceGaps: ['energy state'],
    confidenceBoosters: ['clear observation'],
    confidenceReducers: ['vague task description'],
    humanReviewTriggers: ['high risk'],
    reasoningNotes: ['Review for advisory LOTO standards.'],
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-mobile-equipment',
    title: 'Advisory Mobile Equipment Standards Review',
    jurisdictionContext: ['msha', 'osha'],
    candidateFamily: 'mobile_equipment',
    relatedScenarioFamilies: ['mobile-pedestrian'],
    relatedHazardDomains: ['mobile_equipment'],
    relatedEquipmentIndicators: ['forklift', 'loader'],
    relatedTaskIndicators: ['transport'],
    relatedMechanismOfInjuryIndicators: ['pedestrian_strike'],
    relatedExposureIndicators: ['worker on foot'],
    relatedMissingControlIndicators: ['separation'],
    evidenceRequired: ['separation measures'],
    evidenceGaps: ['separation measures'],
    confidenceBoosters: ['clear observation'],
    confidenceReducers: ['vague location'],
    humanReviewTriggers: ['high risk'],
    reasoningNotes: ['Review for advisory mobile equipment standards.'],
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-fall-protection',
    title: 'Advisory Fall Protection Standards Review',
    jurisdictionContext: ['osha'],
    candidateFamily: 'fall_protection',
    relatedScenarioFamilies: ['elevated-fall'],
    relatedHazardDomains: ['fall_protection'],
    relatedEquipmentIndicators: ['ladder', 'platform'],
    relatedTaskIndicators: ['work at height'],
    relatedMechanismOfInjuryIndicators: ['fall_from_height'],
    relatedExposureIndicators: ['worker'],
    relatedMissingControlIndicators: ['guardrail'],
    evidenceRequired: ['fall height'],
    evidenceGaps: ['fall height'],
    confidenceBoosters: ['clear height observation'],
    confidenceReducers: ['vague height'],
    humanReviewTriggers: ['high risk'],
    reasoningNotes: ['Review for advisory fall protection standards.'],
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-hazcom',
    title: 'Advisory HazCom Standards Review',
    jurisdictionContext: ['osha'],
    candidateFamily: 'hazcom',
    relatedScenarioFamilies: ['chemical-exposure-unclear'],
    relatedHazardDomains: ['hazcom'],
    relatedEquipmentIndicators: ['container'],
    relatedTaskIndicators: ['handling'],
    relatedMechanismOfInjuryIndicators: ['chemical_exposure'],
    relatedExposureIndicators: ['worker'],
    relatedMissingControlIndicators: ['labeling'],
    evidenceRequired: ['SDS availability'],
    evidenceGaps: ['chemical identity'],
    confidenceBoosters: ['photo evidence'],
    confidenceReducers: ['unknown chemical'],
    humanReviewTriggers: ['unknown substance'],
    reasoningNotes: ['Review for advisory HazCom standards.'],
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-electrical',
    title: 'Advisory Electrical Standards Review',
    jurisdictionContext: ['osha', 'msha'],
    candidateFamily: 'electrical',
    relatedScenarioFamilies: ['electrical-damage'],
    relatedHazardDomains: ['electrical'],
    relatedEquipmentIndicators: ['cord', 'panel'],
    relatedTaskIndicators: ['operation'],
    relatedMechanismOfInjuryIndicators: ['shock'],
    relatedExposureIndicators: ['user'],
    relatedMissingControlIndicators: ['insulation'],
    evidenceRequired: ['equipment state'],
    evidenceGaps: ['equipment state'],
    confidenceBoosters: ['photo of damage'],
    confidenceReducers: ['vague location'],
    humanReviewTriggers: ['hazard present'],
    reasoningNotes: ['Review for advisory electrical standards.'],
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  },
  {
    id: 'candidate-emergency-preparedness',
    title: 'Advisory Emergency Preparedness Standards Review',
    jurisdictionContext: ['osha'],
    candidateFamily: 'emergency_preparedness',
    relatedScenarioFamilies: ['blocked-emergency-access'],
    relatedHazardDomains: ['emergency_preparedness'],
    relatedEquipmentIndicators: ['exit', 'pathway'],
    relatedTaskIndicators: ['egress'],
    relatedMechanismOfInjuryIndicators: ['egress_blockage'],
    relatedExposureIndicators: ['occupants'],
    relatedMissingControlIndicators: ['clearance'],
    evidenceRequired: ['clearance status'],
    evidenceGaps: ['clearance status'],
    confidenceBoosters: ['photo of blocked exit'],
    confidenceReducers: ['vague description'],
    humanReviewTriggers: ['emergency access'],
    reasoningNotes: ['Review for advisory emergency preparedness standards.'],
    advisoryGuardrails: {
      advisoryOnly: true,
      doesNotDeclareViolation: true,
      requiresQualifiedReview: true
    }
  }
];
