import { StandardsIntelligenceRecord } from "./standards-intelligence.types";

/**
 * InSite v1.0 GOVERNED SOURCE EXPANSION — 2026-08-28.
 *
 * =====================================================================================
 * WHY THIS FILE EXISTS
 * =====================================================================================
 *
 * The 2026-08-28 standards-architecture phase measured a bounded real-workflow result of
 * 16 matched / 1 no-standard-applicable / 26 expected-but-missing, and established that the
 * gap is NOT a corpus-loading problem: materializing the full governed corpus changed the
 * finding-level result by exactly zero citations. Nine hazard families that HazLenz recognises,
 * materialises as findings, risk-scores and prints in the report had no applicable regulatory
 * authority anywhere in the governed source set:
 *
 *   hot work · fire/explosion · compressed gas · confined space (construction) · PPE eye/face ·
 *   respiratory protection · material handling and storage · cranes/rigging/suspended loads ·
 *   ventilation
 *
 * That phase terminated `AUTHORITATIVE_SOURCE_MATERIAL_REQUIRED` rather than inventing the
 * missing regulations. This file is the acquisition that answers it.
 *
 * =====================================================================================
 * SOURCE AUTHORITY
 * =====================================================================================
 *
 * Every record below was retrieved on 2026-08-28 from the eCFR versioner API — the official
 * codified source for the Code of Federal Regulations — at these point-in-time editions:
 *
 *   Title 29 (Labor)             latest amended 2026-08-04, up to date as of 2026-08-26
 *   Title 30 (Mineral Resources) latest amended 2026-08-25, up to date as of 2026-08-26
 *
 * The retrieved XML for all 29 sections is preserved verbatim, with SHA-256 checksums, at
 * `verification/insite-v1-regulatory-source-acquisition-2026-08-28/source-evidence/`.
 * No blog, training site, law-firm summary, vendor page, search snippet, secondary compliance
 * summary or AI-generated text was used, and none may be.
 *
 * =====================================================================================
 * WHAT `plainLanguageSummary` IS, AND WHY IT IS NOT VERBATIM TEXT
 * =====================================================================================
 *
 * The repository's corpus contract does not store verbatim regulatory text: the projection in
 * `standards-intelligence-projection.ts` derives `standards_master.standardText` FROM
 * `plainLanguageSummary`, and the KG-3D/3E adjudications establish the house style — state what
 * the cited paragraph actually requires, and NAME any sibling paragraph that limits it rather
 * than silently absorbing or omitting it. These summaries follow that style, and each carries
 * `sourceUrl` and `retrievalDate` so a reviewer can compare the summary against the codified
 * text in one click.
 *
 * Records are CANDIDATES. None is reviewer-approved; see the phase's STATUS.md §9.
 */
export const V1_STANDARDS_EXPANSION: StandardsIntelligenceRecord[] = [
  // =========================================================================
  // HOT WORK — welding, cutting, brazing
  // =========================================================================
  {
    citation: "29 CFR 1910.252",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "Q",
    title: "Welding, cutting and brazing — General requirements",
    plainLanguageSummary:
      "Before welding or cutting begins the area must be inspected and the object moved to a safe location, or, where it cannot be moved, movable fire hazards must be removed and immovable ones shielded (29 CFR 1910.252(a)(2)(i)-(ii)). A fire watch is REQUIRED whenever welding or cutting is performed where other than a minor fire might develop, including where appreciable combustibles are within 35 feet of the point of operation, and the fire watch must be maintained for at least a half hour after the work finishes (29 CFR 1910.252(a)(2)(iii)). Ventilation requirements for the same operations are stated separately in paragraph (c).",
    hazardFamilies: ["Welding/HotWork", "Fire"],
    equipmentTags: ["torch", "welding machine", "cutting torch", "burning bar", "grinder", "pipe stand"],
    taskTags: ["welding", "cutting", "brazing", "burning", "hot work", "maintenance", "fabrication"],
    exposureTags: ["combustibles nearby", "sparks", "slag", "elevated work", "openings", "floor penetration"],
    controlTags: ["fire watch", "hot work permit", "fire blanket", "shielding", "remove combustibles", "fire extinguisher"],
    consequenceTags: ["fire", "burns", "structure loss", "fatality"],
    searchBoostTerms: ["no fire watch", "hot work", "welding near combustibles", "cutting torch", "sparks", "slag", "welding permit"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-Q/section-1910.252",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable? (Construction welding is 29 CFR 1926 subpart J.)", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was welding, cutting or brazing actually being performed, or about to be?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Were combustibles present within the exposure distance, and was a fire watch posted?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No hot-work operation is established; a permit record or a past operation is not an active hazard.", excludeWhenMissingAny: ["weld", "cut", "torch", "braz", "hot work", "burning"] },
    ],
    crossDomainLinks: ["Fire", "Confined Space", "Respiratory Protection"],
  },
  {
    citation: "29 CFR 1926.352",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "J",
    title: "Welding and cutting — Fire prevention",
    plainLanguageSummary:
      "On construction work the object to be welded, cut or heated must be moved to a designated safe location where practical; where it cannot be moved, movable fire hazards must be taken to a safe place or otherwise protected, and where neither is possible positive means must confine the heat, sparks and slag (29 CFR 1926.352(a)-(b)). Suitable fire extinguishing equipment must be immediately available in the work area and maintained ready for instant use (29 CFR 1926.352(d)), and additional personnel must be assigned to guard against fire whenever normal precautions are not sufficient (29 CFR 1926.352(e)). Welding, cutting or heating is prohibited outright where flammable paints or compounds, or heavy dust concentrations, create a hazard (29 CFR 1926.352(c)).",
    hazardFamilies: ["Welding/HotWork", "Fire"],
    equipmentTags: ["torch", "welding machine", "cutting torch", "burning bar"],
    taskTags: ["welding", "cutting", "heating", "brazing", "hot work", "construction"],
    exposureTags: ["combustibles nearby", "sparks", "slag", "flammable coatings", "dust concentration"],
    controlTags: ["fire watch", "fire extinguisher", "shielding", "remove combustibles", "confine sparks"],
    consequenceTags: ["fire", "burns", "explosion", "fatality"],
    searchBoostTerms: ["no fire watch", "hot work", "welding near combustibles", "cutting", "sparks", "construction welding"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-J/section-1926.352",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable? (General-industry welding is 29 CFR 1910 subpart Q.)", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was welding, cutting or heating actually being performed?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Were fire hazards present and what confinement or fire-watch measure was in place?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No hot-work operation is established.", excludeWhenMissingAny: ["weld", "cut", "torch", "heat", "hot work", "burning"] },
    ],
    crossDomainLinks: ["Fire", "Confined Space"],
  },
  {
    citation: "30 CFR 56.4100",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "C",
    title: "Smoking and use of open flames",
    plainLanguageSummary:
      "At surface metal and nonmetal mines no person may smoke or use an open flame where flammable or combustible liquids (including greases) or flammable gases are used or transported in a manner that could create a fire hazard, or are stored or handled (30 CFR 56.4100(a)-(b)). This is MSHA's ignition-source control for hot work near flammables; it is a prohibition on the ignition source rather than a fire-watch requirement, and MSHA states welding shielding and ventilation separately at 30 CFR 56.14213.",
    hazardFamilies: ["Fire", "Welding/HotWork"],
    equipmentTags: ["torch", "welding machine", "fuel tank", "grease", "flammable storage"],
    taskTags: ["welding", "cutting", "hot work", "fueling", "maintenance"],
    exposureTags: ["flammable liquids", "combustible liquids", "flammable gas", "storage area", "handling area"],
    controlTags: ["prohibit open flame", "no smoking", "remove flammables", "isolate ignition source"],
    consequenceTags: ["fire", "explosion", "burns", "fatality"],
    searchBoostTerms: ["open flame", "smoking", "flammable", "fuel", "grease", "hot work at mine"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-C/section-56.4100",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Were flammable or combustible liquids or gases present where the flame or smoking occurred?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No ignition source and no flammable/combustible material established.", excludeWhenMissingAny: ["flame", "smoking", "weld", "torch", "flammable", "combustible", "fuel", "grease"] },
    ],
    crossDomainLinks: ["Welding/HotWork"],
  },

  // =========================================================================
  // FIRE PROTECTION
  // =========================================================================
  {
    citation: "29 CFR 1910.157",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "L",
    title: "Portable fire extinguishers",
    plainLanguageSummary:
      "Where the employer provides portable fire extinguishers for employee use, they must be mounted, located and identified so that they are readily accessible without subjecting employees to injury (29 CFR 1910.157(c)(1)), selected and distributed by hazard class and travel distance (paragraph (d)), and inspected, maintained and annually tested (paragraph (e)). The section's own scope paragraph (a) makes the requirements conditional: they apply to extinguishers provided for employee use, and paragraphs (b)(1)-(2) describe the exemptions where a written fire-safety policy requires total evacuation instead.",
    hazardFamilies: ["FireProtection", "Fire"],
    equipmentTags: ["fire extinguisher", "extinguisher bracket", "fire cabinet", "standpipe"],
    taskTags: ["inspection", "housekeeping", "emergency response", "hot work"],
    exposureTags: ["obstructed access", "missing equipment", "travel distance", "combustible occupancy"],
    controlTags: ["accessible extinguisher", "monthly inspection", "annual maintenance", "signage"],
    consequenceTags: ["fire", "delayed response", "burns", "property loss"],
    searchBoostTerms: ["fire extinguisher", "extinguisher missing", "extinguisher blocked", "not inspected", "fire equipment"],
    authorityTier: 1,
    applicabilityBandDefault: "supporting",
    severityDefault: "medium",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-L/section-1910.157",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Are portable extinguishers provided for employee use at this workplace?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "What specific deficiency was observed — absent, obstructed, uninspected or unsuitable?", requiredForPrimary: true, missingEvidenceImpact: "medium" },
    ],
    exclusionRules: [
      { reason: "No portable fire extinguisher condition is described.", excludeWhenMissingAny: ["extinguisher", "fire equipment", "fire protection"] },
    ],
    crossDomainLinks: ["Fire", "Emergency Preparedness"],
  },
  {
    citation: "29 CFR 1926.150",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "F",
    title: "Fire protection",
    plainLanguageSummary:
      "The employer must develop a fire protection programme followed throughout all phases of construction, with firefighting equipment provided, conspicuously located and available at all times (29 CFR 1926.150(a)). A fire extinguisher rated at least 2A must be provided for each 3,000 square feet of protected building area, with travel distance from any point not exceeding 100 feet (29 CFR 1926.150(c)(1)(i)). Fire-hazard-specific requirements for welding and cutting are stated separately at 29 CFR 1926.352.",
    hazardFamilies: ["FireProtection", "Fire"],
    equipmentTags: ["fire extinguisher", "standpipe", "hose", "fire alarm"],
    taskTags: ["construction", "hot work", "housekeeping", "emergency response"],
    exposureTags: ["combustible storage", "travel distance", "missing equipment", "obstructed access"],
    controlTags: ["fire protection programme", "extinguisher coverage", "conspicuous location", "maintained equipment"],
    consequenceTags: ["fire", "burns", "structure loss"],
    searchBoostTerms: ["fire extinguisher", "fire protection", "no extinguisher", "construction fire"],
    authorityTier: 1,
    applicabilityBandDefault: "supporting",
    severityDefault: "medium",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-F/section-1926.150",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "What firefighting-equipment deficiency was observed?", requiredForPrimary: true, missingEvidenceImpact: "medium" },
    ],
    exclusionRules: [
      { reason: "No firefighting-equipment condition is described.", excludeWhenMissingAny: ["extinguisher", "fire protection", "fire equipment", "standpipe"] },
    ],
    crossDomainLinks: ["Fire", "Welding/HotWork"],
  },
  // =========================================================================
  // COMPRESSED GAS CYLINDERS
  // =========================================================================
  {
    citation: "29 CFR 1910.253",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "Q",
    title: "Oxygen-fuel gas welding and cutting",
    plainLanguageSummary:
      "Cylinders must be kept away from radiators and other heat sources, stored in well-protected, well-ventilated, dry locations, and valve protection caps must be in place where the cylinder is designed to accept one (29 CFR 1910.253(b)(2)). Oxygen cylinders in storage must be separated from fuel-gas cylinders and from combustible materials — especially oil or grease — by a minimum of 20 feet, or by a non-combustible barrier at least 5 feet high with a half-hour fire-resistance rating (29 CFR 1910.253(b)(4)(ii)). The general compressed-gas duty at 29 CFR 1910.101 also applies to the same cylinders.",
    hazardFamilies: ["CompressedGasCylinders", "Fire"],
    equipmentTags: ["oxygen cylinder", "acetylene cylinder", "fuel gas cylinder", "regulator", "cylinder cart", "valve cap", "manifold"],
    taskTags: ["welding", "cutting", "cylinder storage", "cylinder handling", "material handling"],
    exposureTags: ["unsecured", "upright", "storage area", "welding bay", "near ignition source", "oil or grease"],
    controlTags: ["secure cylinders", "valve protection cap", "segregate oxygen from fuel gas", "chain or restraint", "ventilated storage"],
    consequenceTags: ["explosion", "fire", "struck-by", "cylinder rocket", "fatality"],
    searchBoostTerms: ["unchained cylinder", "unsecured cylinder", "valve cap removed", "oxygen acetylene", "cylinder storage", "cylinders standing against wall"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-Q/section-1910.253",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Are oxygen-fuel gas cylinders involved, and what is their storage or restraint state?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Are valve protection caps fitted where the cylinder is designed for one?", requiredForPrimary: false, missingEvidenceImpact: "medium" },
    ],
    exclusionRules: [
      { reason: "No gas cylinder is described, or the cylinder is stated to be secured and capped.", excludeWhenMissingAny: ["cylinder", "oxygen", "acetylene", "fuel gas", "compressed gas"] },
    ],
    crossDomainLinks: ["Welding/HotWork", "Fire"],
  },
  {
    citation: "29 CFR 1910.101",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "H",
    title: "Compressed gases (general requirements)",
    plainLanguageSummary:
      "The employer must determine that compressed gas cylinders under its control are in a safe condition to the extent visual inspection can establish it (29 CFR 1910.101(a)), and in-plant handling, storage and utilisation of all compressed gases must follow Compressed Gas Association Pamphlet P-1-1965, incorporated by reference (29 CFR 1910.101(b)). Because the operative handling rules are incorporated by reference rather than stated in the section, the specific cylinder-securing and valve-cap duties for oxygen-fuel gas work are usually cited from 29 CFR 1910.253(b).",
    hazardFamilies: ["CompressedGasCylinders"],
    equipmentTags: ["gas cylinder", "portable tank", "cargo tank", "regulator", "safety relief device"],
    taskTags: ["cylinder inspection", "cylinder storage", "cylinder handling", "gas utilisation"],
    exposureTags: ["damaged cylinder", "corroded cylinder", "storage area", "in-plant handling"],
    controlTags: ["visual inspection", "safe condition determination", "CGA P-1 compliance", "relief device"],
    consequenceTags: ["explosion", "uncontrolled release", "struck-by", "fatality"],
    searchBoostTerms: ["compressed gas", "cylinder condition", "damaged cylinder", "gas cylinder inspection"],
    authorityTier: 1,
    applicabilityBandDefault: "supporting",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-H/section-1910.101",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is a compressed gas cylinder, portable tank or cargo tank involved?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No compressed gas container is described.", excludeWhenMissingAny: ["cylinder", "compressed gas", "portable tank", "cargo tank"] },
    ],
    crossDomainLinks: ["Welding/HotWork"],
  },
  {
    citation: "29 CFR 1926.350",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "J",
    title: "Gas welding and cutting",
    plainLanguageSummary:
      "On construction work valve protection caps must be in place and secured when cylinders are transported, moved or stored (29 CFR 1926.350(a)(1)), and compressed gas cylinders must be secured in an upright position at all times except, if necessary, for short periods while actually being hoisted or carried (29 CFR 1926.350(a)(9)). Cylinders must be kept far enough from welding or cutting operations that sparks, hot slag or flame will not reach them, or be protected by shielding (paragraph (a)(10)).",
    hazardFamilies: ["CompressedGasCylinders", "Welding/HotWork"],
    equipmentTags: ["oxygen cylinder", "acetylene cylinder", "fuel gas cylinder", "valve cap", "cylinder cart", "regulator"],
    taskTags: ["welding", "cutting", "cylinder transport", "cylinder storage", "construction"],
    exposureTags: ["unsecured", "not upright", "near sparks", "storage area", "hoisting"],
    controlTags: ["valve protection cap", "secure upright", "shield from sparks", "restraint"],
    consequenceTags: ["explosion", "fire", "struck-by", "fatality"],
    searchBoostTerms: ["unsecured cylinder", "valve cap", "cylinder not upright", "oxygen acetylene", "construction cylinder"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-J/section-1926.350",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "What is the cylinder's restraint, orientation and valve-cap state?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No gas cylinder is described.", excludeWhenMissingAny: ["cylinder", "oxygen", "acetylene", "fuel gas", "compressed gas"] },
    ],
    crossDomainLinks: ["Welding/HotWork", "Fire"],
  },
  {
    citation: "30 CFR 56.16005",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "O",
    title: "Securing gas cylinders",
    plainLanguageSummary:
      "Compressed and liquid gas cylinders must be secured in a safe manner (30 CFR 56.16005). MSHA states the companion valve-protection duty separately: valves must be protected by covers when cylinders are transported or stored, and by a safe location when the cylinders are in use (30 CFR 56.16006). An unrestrained cylinder is a violation of this section on its own, independent of whether the valve is capped.",
    hazardFamilies: ["CompressedGasCylinders"],
    equipmentTags: ["gas cylinder", "oxygen cylinder", "acetylene cylinder", "cylinder rack", "chain"],
    taskTags: ["cylinder storage", "cylinder handling", "welding", "cutting"],
    exposureTags: ["unsecured", "standing loose", "storage area", "shop"],
    controlTags: ["secure cylinders", "chain", "rack", "restraint"],
    consequenceTags: ["struck-by", "explosion", "cylinder rocket", "fatality"],
    searchBoostTerms: ["unchained cylinder", "unsecured cylinder", "cylinder not secured", "gas cylinder"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-O/section-56.16005",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is the cylinder secured, and by what means?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No gas cylinder is described, or the cylinder is stated to be secured.", excludeWhenMissingAny: ["cylinder", "oxygen", "acetylene", "compressed gas", "liquid gas"] },
    ],
    crossDomainLinks: ["Welding/HotWork"],
  },
  {
    citation: "30 CFR 56.16006",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "O",
    title: "Protection of gas cylinder valves",
    plainLanguageSummary:
      "Valves on compressed gas cylinders must be protected by covers when the cylinders are being transported or stored, and by a safe location when the cylinders are in use (30 CFR 56.16006). A cylinder with its valve protection cap removed while standing in storage violates this section even if the cylinder itself is restrained; restraint is required separately by 30 CFR 56.16005.",
    hazardFamilies: ["CompressedGasCylinders"],
    equipmentTags: ["gas cylinder", "valve cap", "valve cover", "oxygen cylinder", "acetylene cylinder"],
    taskTags: ["cylinder storage", "cylinder transport", "welding", "cutting"],
    exposureTags: ["cap removed", "valve exposed", "storage area", "transport"],
    controlTags: ["valve protection cap", "valve cover", "safe location"],
    consequenceTags: ["uncontrolled release", "cylinder rocket", "explosion", "fatality"],
    searchBoostTerms: ["valve cap removed", "valve protection cap", "cylinder cap missing", "uncapped cylinder"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-O/section-56.16006",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was the cylinder in transport, in storage, or in use, and was the valve protected accordingly?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No gas cylinder valve condition is described.", excludeWhenMissingAny: ["cylinder", "valve cap", "valve", "compressed gas"] },
    ],
    crossDomainLinks: ["Welding/HotWork"],
  },
  // =========================================================================
  // RESPIRATORY PROTECTION AND VENTILATION
  // =========================================================================
  {
    citation: "29 CFR 1910.134",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "I",
    title: "Respiratory protection",
    plainLanguageSummary:
      "Where engineering controls are not feasible, or while they are being instituted, appropriate respirators must be provided by the employer and used by employees (29 CFR 1910.134(a)(1)-(2)). The employer must establish and maintain a written respiratory protection programme with worksite-specific procedures, covering selection, medical evaluation, fit testing, proper use, maintenance and training, whenever respirators are necessary or required (29 CFR 1910.134(c)(1)). Providing a respirator without the programme, the medical evaluation and the fit test does not satisfy the section.",
    hazardFamilies: ["RespiratoryProtection", "OccupationalHealth"],
    equipmentTags: ["respirator", "half mask", "full facepiece", "papr", "cartridge", "dust mask", "scba"],
    taskTags: ["dry cutting", "grinding", "abrasive blasting", "spraying", "confined space entry", "chemical handling"],
    exposureTags: ["dust cloud", "breathing zone", "fume", "vapour", "mist", "oxygen deficiency", "airborne contaminant"],
    controlTags: ["respirator programme", "fit test", "medical evaluation", "cartridge selection", "engineering controls first"],
    consequenceTags: ["silicosis", "occupational lung disease", "asphyxiation", "chemical poisoning"],
    searchBoostTerms: ["no respirator", "not wearing a respirator", "dust cloud", "breathing zone", "respiratory protection", "fit test"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-I/section-1910.134",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable? (Construction adopts this section by reference at 29 CFR 1926.103.)", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is there an airborne contaminant, and is exposure established rather than assumed?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Were respirators necessary, and were they provided, fit-tested and used?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No airborne exposure and no respirator condition is described.", excludeWhenMissingAny: ["respirator", "dust", "fume", "vapour", "vapor", "mist", "breathing", "airborne"] },
    ],
    crossDomainLinks: ["Industrial Hygiene", "Confined Space", "Welding/HotWork"],
  },
  {
    citation: "29 CFR 1926.103",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "E",
    title: "Respiratory protection (construction)",
    plainLanguageSummary:
      "The requirements applicable to construction work under this section are identical to those set forth at 29 CFR 1910.134 (29 CFR 1926.103). The section is a cross-reference and carries no independent text, so the operative duties — programme, selection, medical evaluation, fit testing, use and maintenance — are those of 1910.134 applied to construction work. Citing this section rather than 1910.134 is what keeps the citation in the correct part for a construction inspection.",
    hazardFamilies: ["RespiratoryProtection", "OccupationalHealth"],
    equipmentTags: ["respirator", "half mask", "full facepiece", "papr", "cartridge", "dust mask"],
    taskTags: ["dry cutting", "grinding", "demolition", "abrasive blasting", "construction"],
    exposureTags: ["dust cloud", "breathing zone", "fume", "silica", "vapour"],
    controlTags: ["respirator programme", "fit test", "medical evaluation", "engineering controls first"],
    consequenceTags: ["silicosis", "occupational lung disease", "asphyxiation"],
    searchBoostTerms: ["no respirator", "respiratory protection", "dust", "construction respirator"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-E/section-1926.103",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is airborne exposure established, and were respirators provided and used?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No airborne exposure and no respirator condition is described.", excludeWhenMissingAny: ["respirator", "dust", "fume", "vapour", "vapor", "breathing", "silica"] },
    ],
    crossDomainLinks: ["Industrial Hygiene", "Confined Space"],
  },
  {
    citation: "29 CFR 1910.94",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "G",
    title: "Ventilation",
    plainLanguageSummary:
      "This section states local exhaust ventilation duties for specific operations — abrasive blasting (paragraph (a)), grinding, polishing and buffing (paragraph (b)), spray finishing (paragraph (c)) and open-surface tanks (paragraph (d)). It is operation-specific rather than a general duty to ventilate: a ventilation deficiency for an operation NOT listed here is not covered by this section, and welding ventilation in particular is stated at 29 CFR 1910.252(c) rather than here.",
    hazardFamilies: ["Ventilation", "OccupationalHealth"],
    equipmentTags: ["local exhaust", "hood", "duct", "fan", "spray booth", "blast cabinet", "open-surface tank"],
    taskTags: ["abrasive blasting", "grinding", "polishing", "buffing", "spray finishing", "dipping"],
    exposureTags: ["airborne contaminant", "breathing zone", "enclosed area", "inadequate exhaust"],
    controlTags: ["local exhaust ventilation", "hood design", "air volume", "make-up air"],
    consequenceTags: ["occupational lung disease", "chemical exposure", "fire"],
    searchBoostTerms: ["ventilation", "local exhaust", "no ventilation", "spray booth", "blasting", "exhaust hood"],
    authorityTier: 1,
    applicabilityBandDefault: "supporting",
    severityDefault: "medium",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-G/section-1910.94",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is the operation one this section covers — abrasive blasting, grinding/polishing/buffing, spray finishing or open-surface tanks?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "The operation is not one this section covers; welding ventilation is 1910.252(c).", excludeWhenMissingAny: ["blasting", "grinding", "polishing", "buffing", "spray", "dip tank", "open-surface tank"] },
    ],
    crossDomainLinks: ["Respiratory Protection", "Industrial Hygiene"],
  },
  {
    citation: "29 CFR 1926.353",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "J",
    title: "Ventilation and protection in welding, cutting, and heating",
    plainLanguageSummary:
      "Welding, cutting or heating in a confined space must be adequately ventilated by mechanical means to prevent accumulation of toxic materials or possible oxygen deficiency (29 CFR 1926.353(b)(1)); where that is not feasible, airline respirators must be used and an attendant with a pre-planned rescue capability must be stationed outside (29 CFR 1926.353(b)(2)). General mechanical or local exhaust ventilation is required for welding in confined spaces and for indoor work on the toxic metals the section enumerates (paragraphs (a) and (c)).",
    hazardFamilies: ["Ventilation", "Welding/HotWork", "RespiratoryProtection"],
    equipmentTags: ["local exhaust", "blower", "airline respirator", "duct", "welding machine", "torch"],
    taskTags: ["welding", "cutting", "heating", "confined space entry", "construction"],
    exposureTags: ["confined space", "enclosed area", "welding fume", "oxygen deficiency", "toxic metal"],
    controlTags: ["mechanical ventilation", "local exhaust", "airline respirator", "outside attendant", "rescue plan"],
    consequenceTags: ["asphyxiation", "metal fume fever", "occupational lung disease", "fatality"],
    searchBoostTerms: ["no ventilation", "welding in tank", "confined space welding", "welding fume", "ventilation"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-J/section-1926.353",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was welding, cutting or heating performed in a confined space or enclosed area?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "What ventilation or respiratory protection was in place, and was an outside attendant stationed?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No welding, cutting or heating operation is described.", excludeWhenMissingAny: ["weld", "cut", "heat", "torch", "braz"] },
    ],
    crossDomainLinks: ["Confined Space", "Respiratory Protection", "Fire"],
  },
  {
    citation: "30 CFR 56.5005",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "D",
    title: "Control of exposure to airborne contaminants",
    plainLanguageSummary:
      "Control of employee exposure to harmful airborne contaminants must be, insofar as feasible, by prevention of contamination, removal by exhaust ventilation, or dilution with uncontaminated air (30 CFR 56.5005). Respirators are permitted only where engineering controls have not been developed or where the nature of the work requires it, and then only for reasonable periods; where respirators are permitted a respiratory protective programme meeting ANSI Z88.2-1969 must be established. eCFR carries a note that an amendment published at 89 FR 28469 was delayed indefinitely at 91 FR 17143, so the text above is the operative requirement.",
    hazardFamilies: ["RespiratoryProtection", "Ventilation", "OccupationalHealth"],
    equipmentTags: ["respirator", "exhaust ventilation", "dust collector", "water spray", "enclosure"],
    taskTags: ["drilling", "crushing", "screening", "dumping", "maintenance", "cleanup"],
    exposureTags: ["dust", "airborne contaminant", "breathing zone", "silica", "fume"],
    controlTags: ["prevent contamination", "exhaust ventilation", "dilution", "respirator programme"],
    consequenceTags: ["silicosis", "occupational lung disease", "chemical exposure"],
    searchBoostTerms: ["dust", "airborne contaminant", "no respirator", "ventilation", "breathing zone", "dust control"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-D/section-56.5005",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is a harmful airborne contaminant exposure established?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Were engineering controls used first, and was a respirator programme in place where respirators were relied on?", requiredForPrimary: true, missingEvidenceImpact: "medium" },
    ],
    exclusionRules: [
      { reason: "No airborne contaminant exposure is described.", excludeWhenMissingAny: ["dust", "contaminant", "respirator", "fume", "airborne", "breathing"] },
    ],
    crossDomainLinks: ["Industrial Hygiene"],
  },
  {
    citation: "30 CFR 56.14213",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "M",
    title: "Ventilation and shielding for welding",
    plainLanguageSummary:
      "Welding operations must be shielded when performed at locations where arc flash could be hazardous to persons, and all welding operations must be well-ventilated (30 CFR 56.14213(a)-(b)). This is MSHA's welding ventilation and arc-flash shielding duty; it is stated in Subpart M with machinery and equipment rather than with fire prevention, and it is distinct from the ignition-source prohibition at 30 CFR 56.4100.",
    hazardFamilies: ["Ventilation", "Welding/HotWork"],
    equipmentTags: ["welding machine", "welding screen", "blower", "torch", "arc welder"],
    taskTags: ["welding", "cutting", "maintenance", "fabrication"],
    exposureTags: ["arc flash", "welding fume", "enclosed area", "nearby persons"],
    controlTags: ["welding screen", "shielding", "ventilation", "exhaust"],
    consequenceTags: ["arc eye", "metal fume fever", "burns", "occupational lung disease"],
    searchBoostTerms: ["welding", "arc flash", "welding screen", "ventilation", "welding fume"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "medium",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-M/section-56.14213",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was a welding operation performed, and were persons exposed to arc flash or fume?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No welding operation is described.", excludeWhenMissingAny: ["weld", "arc", "torch"] },
    ],
    crossDomainLinks: ["Welding/HotWork", "Respiratory Protection"],
  },
  // =========================================================================
  // PPE — EYE AND FACE PROTECTION
  // =========================================================================
  {
    citation: "29 CFR 1910.133",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "I",
    title: "Eye and face protection",
    plainLanguageSummary:
      "The employer must ensure that each affected employee uses appropriate eye or face protection when exposed to eye or face hazards from flying particles, molten metal, liquid chemicals, acids or caustic liquids, chemical gases or vapours, or potentially injurious light radiation (29 CFR 1910.133(a)(1)). Side protection is required where there is a hazard from flying objects (paragraph (a)(2)), and protectors must meet the consensus standards the section incorporates (paragraph (b)). The general PPE selection and hazard-assessment duty is stated separately at 29 CFR 1910.132.",
    hazardFamilies: ["PPE", "PersonalProtectiveEquipment"],
    equipmentTags: ["safety glasses", "goggles", "face shield", "welding helmet", "grinder", "bench grinder", "pedestal grinder"],
    taskTags: ["grinding", "cutting", "chipping", "welding", "chemical handling", "decanting"],
    exposureTags: ["flying particles", "molten metal", "liquid chemicals", "light radiation", "splash", "no eye protection"],
    controlTags: ["eye protection", "face shield", "side shields", "welding filter"],
    consequenceTags: ["eye injury", "blindness", "chemical burn", "facial injury"],
    searchBoostTerms: ["no eye protection", "no face shield", "safety glasses", "goggles", "eye or face protection", "grinder"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-I/section-1910.133",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is an eye or face hazard of the kind this section enumerates established?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was appropriate eye or face protection in use by the exposed employee?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No eye or face exposure is established, or protection is stated to be in use.", excludeWhenMissingAny: ["eye", "face", "goggle", "glasses", "shield", "grinding", "splash", "particle"] },
    ],
    crossDomainLinks: ["Machine Guarding", "Welding/HotWork", "Chemical Exposure"],
  },
  {
    citation: "29 CFR 1926.102",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "E",
    title: "Eye and face protection (construction)",
    plainLanguageSummary:
      "The employer must ensure that each affected employee uses appropriate eye or face protection when exposed to eye or face hazards from flying particles, molten metal, liquid chemicals, acids or caustic liquids, chemical gases or vapours, or potentially injurious light radiation (29 CFR 1926.102(a)(1)). Side protection is required where there is a hazard from flying objects, and filter lenses of the appropriate shade number are required for welding, cutting and brazing operations (paragraphs (a)(2) and (b)).",
    hazardFamilies: ["PPE", "PersonalProtectiveEquipment"],
    equipmentTags: ["safety glasses", "goggles", "face shield", "welding helmet", "filter lens"],
    taskTags: ["grinding", "cutting", "chipping", "welding", "demolition", "construction"],
    exposureTags: ["flying particles", "molten metal", "light radiation", "splash", "no eye protection"],
    controlTags: ["eye protection", "face shield", "side shields", "filter lens"],
    consequenceTags: ["eye injury", "blindness", "chemical burn"],
    searchBoostTerms: ["no eye protection", "no face shield", "safety glasses", "goggles", "construction PPE"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-E/section-1926.102",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is an eye or face hazard established and was protection in use?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No eye or face exposure is established.", excludeWhenMissingAny: ["eye", "face", "goggle", "glasses", "shield", "grinding", "particle"] },
    ],
    crossDomainLinks: ["Welding/HotWork", "Machine Guarding"],
  },
  {
    citation: "30 CFR 56.15004",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "N",
    title: "Eye protection",
    plainLanguageSummary:
      "All persons must wear safety glasses, goggles, face shields or other suitable protective devices when in or around an area of a mine or plant where a hazard exists which could cause injury to unprotected eyes (30 CFR 56.15004). The duty attaches to the area, not only to the task, so a person merely present in the hazard area is covered. MSHA states welding-specific protective equipment separately at 30 CFR 56.15007 and grinding-wheel eye protection at 30 CFR 56.15014.",
    hazardFamilies: ["PPE", "PersonalProtectiveEquipment"],
    equipmentTags: ["safety glasses", "goggles", "face shield", "grinder", "crusher", "plant area"],
    taskTags: ["grinding", "chipping", "crushing", "maintenance", "cleanup", "plant operation"],
    exposureTags: ["flying particles", "dust", "splash", "no eye protection", "hazard area"],
    controlTags: ["eye protection", "face shield", "goggles"],
    consequenceTags: ["eye injury", "blindness"],
    searchBoostTerms: ["no eye protection", "safety glasses", "goggles", "face shield", "eye hazard"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-N/section-56.15004",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Does a hazard exist in the area that could injure unprotected eyes?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No eye hazard is established.", excludeWhenMissingAny: ["eye", "goggle", "glasses", "shield", "grinding", "particle", "dust"] },
    ],
    crossDomainLinks: ["Machine Guarding", "Industrial Hygiene"],
  },

  // =========================================================================
  // MATERIAL HANDLING AND STORAGE
  // =========================================================================
  {
    citation: "29 CFR 1910.176",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "N",
    title: "Handling materials — general",
    plainLanguageSummary:
      "Storage of material must not create a hazard: bags, containers and bundles stored in tiers must be stacked, blocked, interlocked and limited in height so they are stable and secure against sliding or collapse (29 CFR 1910.176(b)). Aisles and passageways where mechanical handling equipment is used must be kept clear, in good repair and appropriately marked, with sufficient safe clearances (paragraph (a)), and storage areas must be kept free of accumulations that create tripping, fire, explosion or pest hazards (paragraph (c)).",
    hazardFamilies: ["MaterialHandling", "Struck-By"],
    equipmentTags: ["pallet", "rack", "racking", "tier", "bundle", "container", "forklift", "aisle"],
    taskTags: ["storage", "stacking", "material handling", "warehousing", "loading"],
    exposureTags: ["overhang", "unstable stack", "aisle obstruction", "above walkway", "collapse potential"],
    controlTags: ["stack securely", "block and interlock", "limit height", "clear aisles", "load limits"],
    consequenceTags: ["struck-by", "crushing", "collapse", "trip"],
    searchBoostTerms: ["stacked", "racking", "overhang", "unsecured load", "storage", "pallet", "collapse"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-N/section-1910.176",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is a storage or stacking condition described, and is it unstable, overhanging or obstructing?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No storage or material-stacking condition is described, or storage is stated to be within limits and secured.", excludeWhenMissingAny: ["stack", "storage", "stored", "rack", "pallet", "tier", "bundle", "aisle"] },
    ],
    crossDomainLinks: ["Powered Industrial Trucks", "Housekeeping"],
  },
  {
    citation: "29 CFR 1926.250",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "H",
    title: "General requirements for storage (construction)",
    plainLanguageSummary:
      "All materials stored in tiers must be stacked, racked, blocked, interlocked or otherwise secured to prevent sliding, falling or collapse (29 CFR 1926.250(a)(1)). Stored material must not exceed maximum safe floor load limits, which must be conspicuously posted in storage areas (paragraph (a)(2)), and aisles and passageways must be kept clear and in good repair for the free and safe movement of material handling equipment or employees (paragraph (a)(3)).",
    hazardFamilies: ["MaterialHandling", "Struck-By"],
    equipmentTags: ["pallet", "rack", "tier", "bundle", "brick", "lumber", "aisle"],
    taskTags: ["storage", "stacking", "material handling", "construction"],
    exposureTags: ["overhang", "unstable stack", "aisle obstruction", "collapse potential", "floor loading"],
    controlTags: ["stack securely", "block and interlock", "post load limits", "clear aisles"],
    consequenceTags: ["struck-by", "crushing", "collapse"],
    searchBoostTerms: ["stacked", "storage", "unsecured load", "overhang", "collapse", "construction storage"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-H/section-1926.250",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is a storage or stacking condition described that is unsecured or exceeds load limits?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No storage or material-stacking condition is described.", excludeWhenMissingAny: ["stack", "storage", "stored", "rack", "pallet", "tier", "aisle"] },
    ],
    crossDomainLinks: ["Powered Industrial Trucks", "Housekeeping"],
  },
  {
    citation: "30 CFR 56.16001",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "O",
    title: "Stacking and storage of materials",
    plainLanguageSummary:
      "Supplies must not be stacked or stored in a manner which creates tripping or fall-of-material hazards (30 CFR 56.16001). MSHA states the duty by outcome rather than by stacking method: the question is whether the stack as found creates a tripping or falling-material hazard, not whether a particular blocking or interlocking technique was used. Storage of hazardous materials is addressed separately at 30 CFR 56.16003.",
    hazardFamilies: ["MaterialHandling", "Struck-By", "TripsandFalls"],
    equipmentTags: ["pallet", "rack", "supplies", "stack", "storage area"],
    taskTags: ["storage", "stacking", "material handling", "cleanup"],
    exposureTags: ["overhang", "unstable stack", "walkway", "travelway", "fall of material"],
    controlTags: ["stable stacking", "secure storage", "clear travelways"],
    consequenceTags: ["struck-by", "trip", "crushing"],
    searchBoostTerms: ["stacked", "storage", "supplies", "fall of material", "tripping hazard"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "medium",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-O/section-56.16001",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Does the stacking or storage create a tripping or fall-of-material hazard?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No stacking or storage condition is described.", excludeWhenMissingAny: ["stack", "storage", "stored", "supplies", "pallet"] },
    ],
    crossDomainLinks: ["Housekeeping"],
  },
  // =========================================================================
  // CRANES, RIGGING AND SUSPENDED LOADS
  // =========================================================================
  {
    citation: "29 CFR 1910.184",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "N",
    title: "Slings",
    plainLanguageSummary:
      "Employees must be kept clear of loads about to be lifted and of suspended loads (29 CFR 1910.184(c)(9)). Slings must be inspected each day before use and removed from service if damaged or defective (paragraphs (d) and (e)(3)), and a sling must not be loaded beyond its rated capacity (paragraph (c)(1)). A cut, torn or otherwise damaged synthetic web sling must be removed from service immediately; the specific web-sling removal criteria are at paragraph (i)(9).",
    hazardFamilies: ["Lifting & Rigging", "SuspendedLoads", "Struck-By"],
    equipmentTags: ["sling", "nylon sling", "web sling", "chain sling", "wire rope", "hook", "shackle", "crane", "hoist"],
    taskTags: ["rigging", "lifting", "hoisting", "material handling", "steel erection"],
    exposureTags: ["under load", "drop zone", "fall zone", "suspended overhead", "guiding load", "damaged sling"],
    controlTags: ["keep clear", "daily inspection", "remove damaged sling", "rated capacity", "taglines"],
    consequenceTags: ["struck-by", "crushing", "dropped load", "fatality"],
    searchBoostTerms: ["suspended load", "sling", "cut sling", "damaged sling", "load overhead", "rigging", "crane hook"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-N/section-1910.184",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable? (Construction rigging is 29 CFR 1926.251 and 1926.1425.)", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was a sling in use, and what was its condition?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was any employee beneath or within the drop zone of a suspended load?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No sling or suspended load is described.", excludeWhenMissingAny: ["sling", "suspended", "hoist", "crane", "load", "rigging", "hook"] },
    ],
    crossDomainLinks: ["Cranes/Hoisting", "Material Handling"],
  },
  {
    citation: "29 CFR 1910.179",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "N",
    title: "Overhead and gantry cranes",
    plainLanguageSummary:
      "The operator must not carry loads over people, and must not leave the controls while a load is suspended (29 CFR 1910.179(n)(3)(vi) and (n)(3)(v)). The section also states running-rope inspection, hoist-limit testing and periodic inspection duties (paragraphs (j) and (m)). Sling condition and keeping employees clear of loads are stated separately at 29 CFR 1910.184; a suspended-load exposure often engages both.",
    hazardFamilies: ["Cranes/Hoisting", "SuspendedLoads", "Struck-By"],
    equipmentTags: ["overhead crane", "gantry crane", "bridge crane", "hoist", "trolley", "hook", "wire rope"],
    taskTags: ["lifting", "hoisting", "material handling", "maintenance"],
    exposureTags: ["load over people", "unattended suspended load", "drop zone", "travel path"],
    controlTags: ["do not carry over people", "attend the controls", "rope inspection", "limit switch test"],
    consequenceTags: ["struck-by", "crushing", "dropped load", "fatality"],
    searchBoostTerms: ["crane", "overhead crane", "suspended load", "load over", "hoist", "left suspended"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-N/section-1910.179",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable, and is the crane an overhead or gantry crane?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was a load carried over people or left suspended with the operator away from the controls?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No overhead or gantry crane operation is described; mobile cranes on construction are 29 CFR 1926 subpart CC.", excludeWhenMissingAny: ["crane", "hoist", "gantry", "bridge", "trolley"] },
    ],
    crossDomainLinks: ["Lifting & Rigging", "Material Handling"],
  },
  {
    citation: "29 CFR 1926.251",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "H",
    title: "Rigging equipment for material handling",
    plainLanguageSummary:
      "Rigging equipment must be inspected before use on each shift and as necessary during use, and defective rigging equipment must be removed from service (29 CFR 1926.251(a)(1) and (a)(6)). Rigging equipment must not be loaded beyond its recommended safe working load (paragraph (a)(2)), and synthetic web slings must be immediately removed from service where the section's damage criteria are met, including acid or caustic burns, melting, snags, punctures, tears or cuts, and broken or worn stitching (paragraph (i)(6)).",
    hazardFamilies: ["Lifting & Rigging", "SuspendedLoads"],
    equipmentTags: ["sling", "web sling", "chain sling", "wire rope", "shackle", "hook", "crane", "rigging"],
    taskTags: ["rigging", "lifting", "hoisting", "steel erection", "construction"],
    exposureTags: ["damaged sling", "cut sling", "overloaded", "suspended load", "drop zone"],
    controlTags: ["shift inspection", "remove defective rigging", "safe working load", "qualified rigger"],
    consequenceTags: ["dropped load", "struck-by", "crushing", "fatality"],
    searchBoostTerms: ["sling", "cut sling", "damaged sling", "rigging", "safe working load", "web sling"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-H/section-1926.251",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was rigging equipment in use and what was its condition?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No rigging equipment is described.", excludeWhenMissingAny: ["sling", "rigging", "shackle", "wire rope", "hook", "chain"] },
    ],
    crossDomainLinks: ["Cranes/Hoisting", "Material Handling"],
  },
  {
    citation: "29 CFR 1926.1425",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "CC",
    title: "Cranes and derricks — Keeping clear of the load",
    plainLanguageSummary:
      "While the operator is not moving a suspended load, no employee may be within the fall zone except employees engaged in hooking, unhooking or guiding the load, in the initial attachment of the load, or operating a concrete hopper or bucket (29 CFR 1926.1425(b)). Where employees are in the fall zone for those permitted reasons, the materials must be rigged to prevent unintentional displacement, hooks with self-closing latches or equivalent must be used, and the materials must be rigged by a qualified rigger (paragraph (c)). Hoisting routes that minimise employee exposure to hoisted loads must be used where available (paragraph (a)).",
    hazardFamilies: ["SuspendedLoads", "Cranes/Hoisting", "Struck-By"],
    equipmentTags: ["crane", "derrick", "hook", "load", "beam", "concrete bucket", "rigging"],
    taskTags: ["hoisting", "rigging", "guiding load", "steel erection", "construction"],
    exposureTags: ["fall zone", "under load", "suspended overhead", "guiding the load", "drop zone"],
    controlTags: ["keep clear of fall zone", "self-closing latch", "qualified rigger", "minimise hoisting route exposure"],
    consequenceTags: ["struck-by", "crushing", "dropped load", "fatality"],
    searchBoostTerms: ["suspended load", "fall zone", "under the load", "crane", "guiding a beam", "hoisted load"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-CC/section-1926.1425",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was a load suspended from a crane or derrick, and was any employee in the fall zone?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "If an employee was in the fall zone, were they hooking, unhooking or guiding the load, and were the paragraph (c) conditions met?", requiredForPrimary: false, missingEvidenceImpact: "medium" },
    ],
    exclusionRules: [
      { reason: "No crane or derrick suspended load is described.", excludeWhenMissingAny: ["crane", "derrick", "suspended", "hoist", "load", "fall zone"] },
    ],
    crossDomainLinks: ["Lifting & Rigging", "Fall Protection"],
  },
  {
    citation: "30 CFR 56.16009",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "O",
    title: "Suspended loads",
    plainLanguageSummary:
      "Persons must stay clear of suspended loads (30 CFR 56.16009). MSHA states the duty absolutely and without the fall-zone exceptions OSHA construction allows at 29 CFR 1926.1425(b) — there is no listed exception for guiding or hooking the load — so a person guiding a suspended load at a mine is exposed under this section. Taglines are the stated means of steadying or guiding a suspended load at 30 CFR 56.16007(a).",
    hazardFamilies: ["SuspendedLoads", "Struck-By"],
    equipmentTags: ["crane", "hoist", "load", "sling", "hook", "beam"],
    taskTags: ["hoisting", "rigging", "material handling", "maintenance"],
    exposureTags: ["under load", "suspended overhead", "drop zone", "guiding load"],
    controlTags: ["stay clear", "tagline", "exclusion zone"],
    consequenceTags: ["struck-by", "crushing", "dropped load", "fatality"],
    searchBoostTerms: ["suspended load", "under the load", "hoisted load", "stay clear", "crane"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-O/section-56.16009",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was a load suspended and was any person within its exposure zone?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No suspended load is described.", excludeWhenMissingAny: ["suspended", "hoist", "crane", "load", "overhead"] },
    ],
    crossDomainLinks: ["Lifting & Rigging"],
  },
  {
    citation: "30 CFR 56.16007",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "O",
    title: "Taglines, hitches, and slings",
    plainLanguageSummary:
      "Taglines must be attached to loads that may require steadying or guidance while suspended, and hitches and slings used to hoist materials must be suitable for the particular material handled (30 CFR 56.16007(a)-(b)). The tagline duty is what permits a load to be guided without a person entering the suspended-load zone that 30 CFR 56.16009 requires them to stay clear of.",
    hazardFamilies: ["Lifting & Rigging", "SuspendedLoads"],
    equipmentTags: ["tagline", "sling", "hitch", "hook", "crane", "hoist"],
    taskTags: ["rigging", "hoisting", "material handling"],
    exposureTags: ["guiding load", "suspended overhead", "unsuitable sling", "drop zone"],
    controlTags: ["tagline", "suitable sling", "correct hitch"],
    consequenceTags: ["struck-by", "dropped load", "crushing"],
    searchBoostTerms: ["tagline", "sling", "hitch", "guiding load", "suspended"],
    authorityTier: 1,
    applicabilityBandDefault: "supporting",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-O/section-56.16007",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Did the load require steadying or guidance, and was a tagline used?", requiredForPrimary: true, missingEvidenceImpact: "medium" },
    ],
    exclusionRules: [
      { reason: "No hoisting, sling or tagline condition is described.", excludeWhenMissingAny: ["tagline", "sling", "hitch", "hoist", "suspended", "crane"] },
    ],
    crossDomainLinks: ["SuspendedLoads"],
  },

  // =========================================================================
  // CONFINED SPACE — CONSTRUCTION
  // =========================================================================
  {
    citation: "29 CFR 1926.1204",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "AA",
    title: "Permit-required confined space program (construction)",
    plainLanguageSummary:
      "Each entry employer must implement measures to prevent unauthorised entry, identify and evaluate permit-space hazards before employees enter, and develop the procedures for safe entry — including specifying acceptable entry conditions, isolating the space and its physical hazards, purging or ventilating to control atmospheric hazards, and verifying acceptable conditions for the duration of the entry (29 CFR 1926.1204(a)-(c)). The employer must also provide an attendant outside the space and the equipment needed for safe entry, testing, communication and rescue (paragraphs (d)-(f)). General-industry permit spaces are governed separately by 29 CFR 1910.146.",
    hazardFamilies: ["Confined Space", "Atmospheric Hazards"],
    equipmentTags: ["manway", "hatch", "tank", "vessel", "vault", "gas detector", "tripod", "retrieval line"],
    taskTags: ["confined space entry", "cleaning", "welding", "inspection", "construction"],
    exposureTags: ["no permit", "no attendant", "untested atmosphere", "oxygen deficiency", "toxic atmosphere", "engulfment"],
    controlTags: ["entry permit", "attendant", "atmospheric testing", "continuous monitoring", "ventilation", "rescue plan", "isolation"],
    consequenceTags: ["asphyxiation", "engulfment", "toxic exposure", "fatality", "multiple fatality rescue"],
    searchBoostTerms: ["confined space", "no entry permit", "no attendant", "not tested", "manway", "tank entry", "permit space"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-AA/section-1926.1204",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable? (General-industry permit spaces are 29 CFR 1910.146.)", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Does the space meet the definition of a permit-required confined space?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Did an employee enter, and which programme element was absent — permit, attendant, testing, isolation or rescue?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No confined space entry is established.", excludeWhenMissingAny: ["confined space", "permit space", "tank", "vessel", "manway", "hatch", "vault", "entry"] },
    ],
    crossDomainLinks: ["Atmospheric Hazards", "Respiratory Protection", "Welding/HotWork"],
  },
  // =========================================================================
  // PROVISIONS THE COVERAGE MATRIX NAMED THAT THE GOVERNED SET DID NOT HOLD
  // The source-authority gate caught these: a matrix cell may not name a
  // provision the governed source set lacks. Acquired rather than de-scoped.
  // =========================================================================
  {
    citation: "29 CFR 1926.417",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "K",
    title: "Lockout and tagging of circuits (construction)",
    plainLanguageSummary:
      "Controls that are to be deactivated during work on energized or deenergized equipment or circuits must be tagged; deenergized equipment or circuits must be rendered inoperative and have tags attached at all points where they can be energized; and tags must plainly identify the equipment or circuits being worked on (29 CFR 1926.417(a)-(c)). This is construction's electrical lockout and tagging duty and is materially narrower than the general-industry hazardous-energy standard at 29 CFR 1910.147: it addresses tagging of circuits rather than a full energy-control programme with written procedures, periodic inspection and employee training.",
    hazardFamilies: ["Lockout/StoredEnergy", "Electrical"],
    equipmentTags: ["circuit", "breaker", "disconnect", "panel", "switch", "control", "tag"],
    taskTags: ["electrical work", "servicing", "maintenance", "repair", "construction"],
    exposureTags: ["energized circuit", "untagged control", "unexpected energization", "no lock or tag"],
    controlTags: ["tag controls", "render inoperative", "identify equipment", "isolation"],
    consequenceTags: ["electrocution", "shock", "arc flash", "unexpected startup", "fatality"],
    searchBoostTerms: ["lockout", "tagging", "tag", "circuit", "deenergized", "construction lockout", "no lock or tag"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-K/section-1926.417",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable? (General-industry hazardous energy is 29 CFR 1910.147.)", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was work performed on equipment or circuits, and were the controls tagged and rendered inoperative?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No electrical circuit work or control-tagging condition is described.", excludeWhenMissingAny: ["circuit", "tag", "lockout", "deenergiz", "energiz", "disconnect", "breaker"] },
    ],
    crossDomainLinks: ["Electrical"],
  },
  {
    citation: "30 CFR 56.15005",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "N",
    title: "Safety belts and lines",
    plainLanguageSummary:
      "Safety belts and lines must be worn when persons work where there is danger of falling, and a second person must tend the lifeline when bins, tanks or other dangerous areas are entered (30 CFR 56.15005). MSHA states the fall duty as personal fall protection worn by the person rather than as a hierarchy of guardrails, nets and arrest systems, so this section carries BOTH the fall-protection duty and the attendant duty for entry into bins and tanks — the nearest MSHA analogue to a confined-space attendant requirement.",
    hazardFamilies: ["FallProtection", "Confined Space"],
    equipmentTags: ["safety belt", "safety line", "lifeline", "harness", "lanyard", "bin", "tank", "silo", "platform"],
    taskTags: ["working at height", "bin entry", "tank entry", "maintenance", "cleanup"],
    exposureTags: ["danger of falling", "unprotected edge", "bin", "tank", "dangerous area", "no attendant"],
    controlTags: ["safety belt", "lifeline", "tend the lifeline", "second person", "fall protection"],
    consequenceTags: ["fall", "engulfment", "asphyxiation", "fatality"],
    searchBoostTerms: ["safety belt", "lifeline", "danger of falling", "bin", "tank", "attendant", "fall protection"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-N/section-56.15005",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was there a danger of falling, or was a bin, tank or other dangerous area entered?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was a safety belt and line worn, and was a second person tending the lifeline for an entry?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No fall exposure and no bin/tank entry is described.", excludeWhenMissingAny: ["fall", "height", "edge", "belt", "lifeline", "harness", "bin", "tank", "silo"] },
    ],
    crossDomainLinks: ["Confined Space"],
  },
  {
    citation: "30 CFR 56.3200",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "B",
    title: "Correction of hazardous ground conditions",
    plainLanguageSummary:
      "Ground conditions that create a hazard to persons must be taken down or supported before other work or travel is permitted in the affected area; until corrective work is completed the area must be posted with a warning against entry, and when left unattended a barrier must be installed to impede unauthorised entry (30 CFR 56.3200). This is MSHA's ground-control duty for highwalls, banks and unstable ground. It is NOT an excavation protective-systems standard: it does not require shoring, sloping or benching to a specified configuration the way 29 CFR 1926.652(a)(1) does, so a trench observation at a mine is answered by taking down or supporting the condition and barricading it, not by a trench box specification.",
    hazardFamilies: ["GroundControl", "Caught-In/Between"],
    equipmentTags: ["highwall", "bank", "muckpile", "stockpile", "face", "berm", "barrier", "warning sign"],
    taskTags: ["excavation", "mucking", "travel", "inspection", "scaling", "cleanup"],
    exposureTags: ["unstable ground", "loose material", "overhang", "undercut", "unsupported face", "travel below"],
    controlTags: ["take down", "support", "post warning", "install barrier", "restrict entry", "scaling"],
    consequenceTags: ["engulfment", "burial", "crushing", "fatality"],
    searchBoostTerms: ["highwall", "ground conditions", "unstable", "loose", "bank", "face", "barricade", "warning"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "critical",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-B/section-56.3200",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Do the ground conditions create a hazard to persons in the affected area?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was the condition taken down or supported, and was the area posted and barriered until corrected?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No ground or highwall condition is described.", excludeWhenMissingAny: ["ground", "highwall", "bank", "face", "muckpile", "stockpile", "loose", "unstable", "overhang"] },
    ],
    crossDomainLinks: ["Excavation"],
  },
  // =========================================================================
  // FINAL GAP CLOSURE — provisions the source-authority gate still reported
  // =========================================================================
  {
    citation: "29 CFR 1910.1053",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "Z",
    title: "Respirable crystalline silica (general industry)",
    plainLanguageSummary:
      "The employer must ensure no employee is exposed to respirable crystalline silica above the permissible exposure limit of 50 micrograms per cubic metre as an 8-hour time-weighted average (29 CFR 1910.1053(c)), must assess exposures (paragraph (d)), and must use engineering and work practice controls to reduce exposure to or below the PEL, supplementing with respiratory protection only where those controls cannot achieve it (paragraph (f)). Construction work is covered by the parallel standard at 29 CFR 1926.1153, which specifies control methods by task rather than by exposure assessment.",
    hazardFamilies: ["Industrial Hygiene", "RespiratoryProtection", "OccupationalHealth"],
    equipmentTags: ["saw", "grinder", "drill", "crusher", "vacuum", "water suppression", "respirator"],
    taskTags: ["cutting", "grinding", "drilling", "crushing", "abrasive blasting", "cleanup"],
    exposureTags: ["respirable dust", "silica", "breathing zone", "visible dust", "enclosed area"],
    controlTags: ["engineering controls", "water suppression", "local exhaust", "exposure assessment", "respirator"],
    consequenceTags: ["silicosis", "lung cancer", "occupational lung disease", "kidney disease"],
    searchBoostTerms: ["silica", "respirable dust", "dry cutting", "dust cloud", "concrete dust", "PEL"],
    authorityTier: 1,
    applicabilityBandDefault: "primary",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-Z/section-1910.1053",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable? (Construction silica is 29 CFR 1926.1153.)", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is the material silica-bearing and is respirable dust generated?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "What engineering controls were in use, and was exposure assessed?", requiredForPrimary: true, missingEvidenceImpact: "medium" },
    ],
    exclusionRules: [
      { reason: "No silica-bearing material or respirable dust generation is established.", excludeWhenMissingAny: ["silica", "concrete", "masonry", "stone", "brick", "dust", "quartz"] },
    ],
    crossDomainLinks: ["Respiratory Protection", "Ventilation"],
  },
  {
    citation: "29 CFR 1910.120",
    agency: "OSHA",
    scope: "osha-general-industry",
    part: "1910",
    subpart: "H",
    title: "Hazardous waste operations and emergency response",
    plainLanguageSummary:
      "Paragraph (q) governs emergency response to releases of hazardous substances without regard to location: the employer must have an emergency response plan, responders must be trained to the level of their duties, and employees must not engage in emergency response beyond that training (29 CFR 1910.120(q)(1)-(6)). Employees engaged in an incidental spill cleanup that can be safely handled by workers in the immediate release area are NOT emergency responders under paragraph (q), so establishing which of the two situations occurred is what determines whether this section applies at all.",
    hazardFamilies: ["ChemicalExposure", "Emergency Response"],
    equipmentTags: ["drum", "tote", "absorbent", "spill kit", "storm drain", "containment", "respirator"],
    taskTags: ["spill response", "cleanup", "decanting", "chemical handling", "emergency response"],
    exposureTags: ["uncontrolled release", "spill", "leak", "skin contact", "inhalation", "storm drain"],
    controlTags: ["emergency response plan", "trained responders", "containment", "PPE", "evacuation"],
    consequenceTags: ["chemical burn", "poisoning", "environmental release", "fatality"],
    searchBoostTerms: ["spill", "release", "leaking drum", "solvent", "cleanup", "storm drain", "emergency response"],
    authorityTier: 1,
    applicabilityBandDefault: "supporting",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1910/subpart-H/section-1910.120",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA General Industry applicable? (Construction is 29 CFR 1926.65.)", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was this an emergency response to an uncontrolled release, or an incidental spill handled safely by employees in the immediate area?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Were the responding employees trained to the level of their assigned duties?", requiredForPrimary: false, missingEvidenceImpact: "medium" },
    ],
    exclusionRules: [
      { reason: "No hazardous substance release or response is described.", excludeWhenMissingAny: ["spill", "release", "leak", "hazardous waste", "solvent", "chemical"] },
    ],
    crossDomainLinks: ["Hazard Communication", "Respiratory Protection", "PPE"],
  },
  {
    citation: "29 CFR 1926.65",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "D",
    title: "Hazardous waste operations and emergency response (construction)",
    plainLanguageSummary:
      "The construction analogue of 29 CFR 1910.120, with the same structure: paragraph (q) governs emergency response to releases of hazardous substances, requires an emergency response plan and training matched to assigned duties, and excludes incidental releases that can be safely handled by employees in the immediate release area (29 CFR 1926.65(q)). Citing this section rather than 1910.120 is what keeps the citation in the correct part for a construction inspection.",
    hazardFamilies: ["ChemicalExposure", "Emergency Response"],
    equipmentTags: ["drum", "tote", "absorbent", "spill kit", "containment", "respirator"],
    taskTags: ["spill response", "cleanup", "chemical handling", "construction", "emergency response"],
    exposureTags: ["uncontrolled release", "spill", "leak", "skin contact", "inhalation"],
    controlTags: ["emergency response plan", "trained responders", "containment", "PPE"],
    consequenceTags: ["chemical burn", "poisoning", "environmental release"],
    searchBoostTerms: ["spill", "release", "leaking drum", "solvent", "cleanup", "construction spill"],
    authorityTier: 1,
    applicabilityBandDefault: "supporting",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-D/section-1926.65",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Was this an emergency response to an uncontrolled release, or an incidental spill?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No hazardous substance release or response is described.", excludeWhenMissingAny: ["spill", "release", "leak", "hazardous waste", "solvent", "chemical"] },
    ],
    crossDomainLinks: ["Hazard Communication", "PPE"],
  },
  {
    citation: "29 CFR 1926.201",
    agency: "OSHA",
    scope: "osha-construction",
    part: "1926",
    subpart: "G",
    title: "Signaling (construction traffic control)",
    plainLanguageSummary:
      "Signalling by flaggers and the use of flaggers, including the warning garments flaggers wear, must conform to Part 6 of the Manual on Uniform Traffic Control Devices, incorporated by reference (29 CFR 1926.201(a)). Crane and hoist signalling is governed by the applicable ANSI standards rather than by this section (paragraph (b)). Because the operative requirements are incorporated by reference, this section establishes the duty but not the specific device or placement criteria; barricades are addressed separately at 29 CFR 1926.202.",
    hazardFamilies: ["TrafficControl", "MobileEquipment"],
    equipmentTags: ["flagger", "sign", "barricade", "cone", "warning garment", "haul road", "work zone"],
    taskTags: ["traffic control", "flagging", "construction", "haulage"],
    exposureTags: ["pedestrian in travel path", "no barricade", "no signage", "no designated crossing", "vehicle exposure"],
    controlTags: ["flagger", "signage", "barricade", "designated crossing", "high-visibility clothing"],
    consequenceTags: ["struck-by", "run-over", "fatality"],
    searchBoostTerms: ["flagger", "traffic control", "no barricade", "no signage", "pedestrian", "work zone"],
    authorityTier: 1,
    applicabilityBandDefault: "supporting",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-XVII/part-1926/subpart-G/section-1926.201",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is OSHA Construction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is vehicle or equipment traffic being directed, and was a flagger or signalling used?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No traffic-control or flagging condition is described.", excludeWhenMissingAny: ["flagger", "traffic", "signal", "barricade", "sign", "haul", "crossing"] },
    ],
    crossDomainLinks: ["Mobile Equipment"],
  },
  {
    citation: "30 CFR 56.4530",
    agency: "MSHA",
    scope: "mining",
    part: "56",
    subpart: "C",
    title: "Exits",
    plainLanguageSummary:
      "Buildings or structures in which persons work must have a sufficient number of exits to permit prompt escape in case of fire (30 CFR 56.4530). This is the surface metal and nonmetal egress duty, and it is materially narrower than the OSHA exit-route standard at 29 CFR 1910.36: it addresses the number of exits from occupied buildings for fire escape, not exit-route design, marking, maintenance or capacity. Firefighting, evacuation and rescue procedures are stated separately at 30 CFR 56.4330.",
    hazardFamilies: ["EmergencyEgress", "Fire"],
    equipmentTags: ["exit", "door", "building", "shop", "control room", "structure"],
    taskTags: ["occupancy", "evacuation", "inspection"],
    exposureTags: ["blocked exit", "single exit", "obstructed egress", "fire"],
    controlTags: ["sufficient exits", "unobstructed exit", "evacuation route"],
    consequenceTags: ["entrapment", "burns", "asphyxiation", "fatality"],
    searchBoostTerms: ["exit", "egress", "blocked exit", "escape", "evacuation"],
    authorityTier: 1,
    applicabilityBandDefault: "supporting",
    severityDefault: "high",
    sourceUrl: "https://www.ecfr.gov/current/title-30/chapter-I/subchapter-N/part-56/subpart-C/section-56.4530",
    retrievalDate: "2026-08-28",
    evidenceRequirements: [
      { question: "Is MSHA metal/nonmetal surface jurisdiction applicable?", requiredForPrimary: true, missingEvidenceImpact: "high" },
      { question: "Is a building or structure in which persons work involved, and are its exits sufficient for prompt escape?", requiredForPrimary: true, missingEvidenceImpact: "high" },
    ],
    exclusionRules: [
      { reason: "No building exit condition is described.", excludeWhenMissingAny: ["exit", "egress", "door", "escape", "building", "structure"] },
    ],
    crossDomainLinks: ["Fire"],
  },
];
