import { SafeScopeControlBrainRecord } from './controls-brain.types';

export const SAFESCOPE_CONTROLS_BRAIN_REGISTRY: SafeScopeControlBrainRecord[] = [
  {
    controlId: 'control-powered-overhead-door-crush-point',
    hazardDomains: ['machine_guarding'],
    mechanisms: ['powered_door_crush_point'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Stop or restrict pedestrian travel under or near the powered overhead door until the door safety devices and operating controls are verified.',
    permanentControl: 'Repair, adjust, or install powered-door protective devices such as photo-eyes, presence sensors, reversing edges, warning devices, manual release, and pedestrian separation controls so employees are protected from the closing-door crush or pinch point.',
    verificationEvidence: [
      'photo-eye or presence sensor functional test',
      'reversing edge functional test',
      'manual release verification',
      'warning device verification',
      'pedestrian path or barricade photo',
      'post-repair door operating test',
    ],
    failureModesIfNotVerified: [
      'door closes on pedestrian path',
      'photo-eye or reversing edge fails to stop or reverse door travel',
      'manual release unavailable or not functional',
      'employees continue passing under operating door',
      'closing speed or force remains uncontrolled',
    ],
    notes: [
      'Powered overhead door controls should verify the actual safety-device function, not just the presence of sensors.',
      'Pedestrian exposure should be controlled with separation, signage, barricades, or alternate routes when door operation creates a crush-point exposure.',
    ],
  },
  {
    controlId: 'control-machine-guarding-guard-exposed-moving-parts',
    hazardDomains: ['machine_guarding'],
    mechanisms: ['rotating_equipment', 'rotating_equipment_nip_point', 'pinch_point'],
    hierarchyLevel: 'isolation_or_guarding',
    immediateControl: 'Stop or restrict access to exposed moving machine parts until guarding is restored.',
    permanentControl: 'Install, repair, or restore guarding that prevents contact with rotating parts, nip points, and point-of-operation hazards.',
    verificationEvidence: ['photo of installed guard', 'post-correction inspection record', 'functional verification before operation'],
    failureModesIfNotVerified: ['continued access to nip point', 'guard removed after correction', 'guard does not prevent contact'],
    notes: ['Guarding controls should address the specific contact point, not just the general machine.'],
  },
  {
    controlId: 'control-excavation-protective-system',
    hazardDomains: ['excavation_trenching'],
    mechanisms: ['collapse'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Remove employees from the excavation until a protective system and safe access are verified.',
    permanentControl: 'Install an adequate protective system such as sloping, shoring, shielding, or trench box protection.',
    verificationEvidence: ['competent person inspection record', 'protective system documentation', 'photo of installed protective system'],
    failureModesIfNotVerified: ['unprotected wall collapse exposure', 'improper slope or shield use', 'employees re-enter before inspection'],
    notes: ['Excavation controls require competent person review and condition-specific verification.'],
  },
  {
    controlId: 'control-ground-roof-rib-support',
    hazardDomains: ['ground_control', 'roof_rib_control'],
    mechanisms: ['fall_of_ground', 'rib_fall'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Restrict access, barricade the affected area, and remove exposed persons from unsupported roof or rib conditions.',
    permanentControl: 'Scale loose material, install supplemental support, and follow the approved roof/rib control plan.',
    verificationEvidence: ['qualified person examination record', 'support installation record', 'area reopened verification'],
    failureModesIfNotVerified: ['loose rock or rib remains exposed', 'support not installed to plan', 'travel resumes before examination'],
    notes: ['Ground control must distinguish roof, rib, face, highwall, and loose material exposure.'],
  },
  {
    controlId: 'control-electrical-deenergize-repair-verify',
    hazardDomains: ['electrical'],
    mechanisms: ['shock', 'shock_arc_flash'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'De-energize the circuit and restrict access to exposed or damaged electrical components.',
    permanentControl: 'Repair damaged conductors, restore enclosure integrity, protect exposed conductors, and control shock or arc-flash exposure.',
    verificationEvidence: ['qualified electrical repair documentation', 'insulation or enclosure verification', 'return-to-service inspection'],
    failureModesIfNotVerified: ['energized conductor remains exposed', 'damaged cable returned to service', 'arc-flash/shock exposure not controlled'],
    notes: ['Electrical controls should verify energy state and physical repair, not just warning signage.'],
  },
  {
    controlId: 'control-fall-protection-edge-platform',
    hazardDomains: ['fall_protection', 'scaffolds'],
    mechanisms: ['fall_from_height', 'inadequate_guardrail'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Stop exposed work or restrict access to the fall exposure until protection is installed.',
    permanentControl: 'Install guardrails, scaffold guardrails, fall arrest, fall restraint, or equivalent fall protection appropriate to the exposure.',
    verificationEvidence: ['photo of fall protection system', 'competent person verification', 'pre-use inspection record'],
    failureModesIfNotVerified: ['open side remains unprotected', 'guardrail incomplete', 'fall arrest not anchored or worn correctly'],
    notes: ['Fall controls should identify whether the exposure is edge, platform, scaffold, ladder, or opening related.'],
  },
  {
    controlId: 'control-ladder-secure-access',
    hazardDomains: ['ladders', 'slips_trips_falls'],
    mechanisms: ['fall_from_ladder'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Remove the ladder from service or restrict ladder access until setup deficiencies are corrected.',
    permanentControl: 'Secure the ladder, provide stable access, maintain required extension above the landing, and correct misuse.',
    verificationEvidence: ['photo of corrected ladder setup', 'ladder inspection record', 'supervisor verification'],
    failureModesIfNotVerified: ['ladder shifts during use', 'insufficient extension above landing', 'unsafe access remains in use'],
    notes: ['Ladder findings need setup verification, not only worker retraining.'],
  },
  {
    controlId: 'control-housekeeping-slip-trip',
    hazardDomains: ['slip_trip_fall', 'walking_working_surfaces', 'slips_trips_falls'],
    mechanisms: ['slip', 'trip', 'slip_trip_fall'],
    hierarchyLevel: 'administrative_control',
    immediateControl: 'Barricade, warn, or restrict access until the walking or working surface is made safe.',
    permanentControl: 'Remove obstructions, clean spills, restore clear travelways, and maintain dry walking surfaces.',
    verificationEvidence: ['photo of cleared surface', 'housekeeping correction record', 'follow-up inspection'],
    failureModesIfNotVerified: ['material left in travelway', 'spill not fully removed', 'surface becomes contaminated again'],
    notes: ['Housekeeping controls should verify the surface condition after correction.'],
  },
  {
    controlId: 'control-mobile-equipment-pedestrian-separation',
    hazardDomains: ['mobile_equipment', 'traffic_control', 'powered_haulage'],
    mechanisms: ['pedestrian_strike', 'struck_by', 'struck_by_mobile_equipment'],
    hierarchyLevel: 'isolation_or_guarding',
    immediateControl: 'Stop or restrict mobile equipment movement until pedestrian separation or traffic controls are established.',
    permanentControl: 'Define exclusion zones, separate pedestrians from mobile equipment, establish traffic controls, use spotters where required, and verify visibility or backup-alarm controls.',
    verificationEvidence: ['traffic control verification', 'pedestrian separation documentation', 'spotter/alarm/visibility check'],
    failureModesIfNotVerified: ['pedestrians remain in equipment path', 'backup alarm or visibility control not functioning', 'traffic pattern unclear'],
    notes: ['Mobile equipment controls should prioritize separation and movement control before training alone.'],
  },
  {
    controlId: 'control-mobile-equipment-berm-edge',
    hazardDomains: ['mobile_equipment', 'powered_haulage'],
    mechanisms: ['run_off_embankment'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Restrict haulage or dump-point access until edge protection is verified.',
    permanentControl: 'Install or restore berms, edge controls, dump-point controls, and haul-road traffic controls.',
    verificationEvidence: ['berm inspection record', 'haul road/dump point verification', 'photo of restored edge protection'],
    failureModesIfNotVerified: ['vehicle over-edge exposure remains', 'berm insufficient for roadway condition', 'dump point reopened without verification'],
    notes: ['Berm controls should be tied to the travel path or dump-point exposure.'],
  },
  {
    controlId: 'control-loto-energy-isolation',
    hazardDomains: ['machine_guarding_loto', 'lockout_tagout'],
    mechanisms: ['unexpected_startup', 'stored_energy_release'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Stop maintenance or servicing work and restrict access until hazardous energy is isolated.',
    permanentControl: 'De-energize equipment, apply lockout/tagout, block equipment against motion where required, control stored energy, and verify zero energy.',
    verificationEvidence: ['lockout/tagout verification', 'zero-energy verification', 'qualified person or supervisor review'],
    failureModesIfNotVerified: ['unexpected startup remains possible', 'stored energy not controlled', 'blocking omitted where motion can occur'],
    notes: ['LOTO controls must verify isolation and stored-energy control before work continues.'],
  },
  {
    controlId: 'control-ventilation-methane-airflow',
    hazardDomains: ['ventilation'],
    mechanisms: ['methane_gas_buildup'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Restrict the affected area and evaluate methane, air quality, and ventilation status.',
    permanentControl: 'Restore or repair ventilation controls, correct airflow deficiencies, and verify airflow quantity and methane control.',
    verificationEvidence: ['ventilation examination record', 'airflow verification', 'methane or gas check documentation'],
    failureModesIfNotVerified: ['airflow deficiency remains', 'methane accumulation not evaluated', 'ventilation curtain/control not restored'],
    notes: ['Ventilation controls should verify both physical control integrity and atmosphere/airflow condition.'],
  },
  {
    controlId: 'control-emergency-egress-escapeway',
    hazardDomains: ['emergency_preparedness'],
    mechanisms: ['egress_blockage'],
    hierarchyLevel: 'elimination',
    immediateControl: 'Remove the obstruction or restrict travel until the escapeway or emergency route is clear.',
    permanentControl: 'Maintain clear escapeways, prevent storage in emergency routes, verify lifeline integrity, and document route inspection.',
    verificationEvidence: ['escapeway inspection record', 'photo of clear route', 'responsible person verification'],
    failureModesIfNotVerified: ['emergency route remains obstructed', 'lifeline or route marker compromised', 'materials stored again in escapeway'],
    notes: ['Emergency egress controls are urgent because delay can compromise evacuation.'],
  },
  {
    controlId: 'control-health-respiratory-silica',
    hazardDomains: ['health_respiratory', 'health_exposure'],
    mechanisms: ['silica_inhalation'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Restrict dust-generating work until exposure controls are verified.',
    permanentControl: 'Use wet methods, dust collection, exposure control methods, respiratory protection where required, and employee training.',
    verificationEvidence: ['silica control verification', 'exposure control method documentation', 'respiratory protection evaluation where required'],
    failureModesIfNotVerified: ['dust generation continues uncontrolled', 'engineering controls ineffective', 'respiratory protection used without proper evaluation'],
    notes: ['Health exposure controls should distinguish engineering controls from PPE-only responses.'],
  },
  {
    controlId: 'control-hazcom-label-sds-training',
    hazardDomains: ['hazardous_materials', 'hazard_communication'],
    mechanisms: ['chemical_exposure'],
    hierarchyLevel: 'administrative_control',
    immediateControl: 'Remove the unlabeled container from use or restrict use until chemical identity and hazards are known; segregate incompatible chemicals and use secondary containment where needed.',
    permanentControl: 'Label the chemical container, identify contents and hazards, make SDS available, segregate incompatible chemicals, maintain secondary containment where required, and train affected employees.',
    verificationEvidence: ['corrected container label', 'SDS availability verification', 'storage segregation photo', 'secondary containment verification', 'hazard communication correction record'],
    failureModesIfNotVerified: ['chemical identity remains unknown', 'container reused without label', 'employees lack hazard information'],
    notes: ['HazCom controls require identity, hazard communication, and access to supporting information.'],
  },
  {
    controlId: 'control-confined-space-entry',
    hazardDomains: ['confined_space'],
    mechanisms: ['asphyxiation'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Stop confined space entry and remove entrants if entry controls or atmospheric evaluation are missing.',
    permanentControl: 'Evaluate confined space hazards, implement permit-required confined space controls, test atmosphere, provide attendant and rescue provisions, and control atmospheric hazards.',
    verificationEvidence: ['confined space evaluation', 'atmospheric testing record', 'entry permit and attendant verification'],
    failureModesIfNotVerified: ['atmospheric hazard remains unknown', 'entry proceeds without permit controls', 'rescue or attendant provisions missing'],
    notes: ['Confined space controls require pre-entry evaluation and ongoing entry-control verification.'],
  },

  {
    controlId: 'control-cranes-rigging-suspended-load-zone',
    hazardDomains: ['cranes_rigging_hoisting'],
    mechanisms: ['struck_by_suspended_load', 'dropped_load', 'rigging_failure', 'crane_contact'],
    hierarchyLevel: 'isolation_or_guarding',
    immediateControl: 'Stop the lift and clear employees from the suspended-load path, fall zone, swing radius, or rigging failure zone.',
    permanentControl: 'Establish a controlled lift plan with exclusion zones, verified rigging, qualified operator/signal controls, tag-line or load-control methods where appropriate, and pre-lift communication.',
    verificationEvidence: ['lift plan or pre-lift briefing', 'photo/observation of exclusion zone', 'operator/signal person verification', 'rigging inspection record'],
    failureModesIfNotVerified: ['employees remain under load', 'rigging condition not verified', 'load path not controlled', 'signal communication unclear'],
    notes: ['Suspended-load controls must address both immediate employee location and the initiating lift/rigging condition.'],
  },


  {
    controlId: 'control-material-handling-stable-storage',
    hazardDomains: ['material_handling'],
    mechanisms: ['unstable_stack_collapse', 'falling_object_material', 'dropped_load'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Restrict access to the falling-object or collapse zone and stop material handling until the material is stabilized.',
    permanentControl: 'Store, rack, stack, block, or secure material so it cannot shift, collapse, roll, or fall into employee work or travel areas.',
    verificationEvidence: ['photo of stabilized material', 'storage/rack capacity verification', 'post-correction inspection record'],
    failureModesIfNotVerified: ['stack remains unstable', 'employees remain in fall path', 'material is restacked without capacity or stability verification'],
    notes: ['Material handling controls should verify stability and employee exposure, not just housekeeping cleanup.'],
  },
  {
    controlId: 'control-tools-remove-defective-from-service',
    hazardDomains: ['tools_equipment'],
    mechanisms: ['defective_tool_contact', 'abrasive_wheel_failure', 'tool_guarding_gap'],
    hierarchyLevel: 'elimination',
    immediateControl: 'Remove the defective, damaged, or unguarded tool from service and prevent use until corrected.',
    permanentControl: 'Repair, replace, guard, or inspect tools before use, and maintain a process for tagging defective tools out of service.',
    verificationEvidence: ['photo of tagged or replaced tool', 'tool inspection record', 'supervisor verification before reuse'],
    failureModesIfNotVerified: ['defective tool returned to use', 'guard remains missing', 'inspection process does not catch repeat defects'],
    notes: ['Tool controls should distinguish portable tools from fixed machine-guarding hazards.'],
  },
  {
    controlId: 'control-fire-protection-extinguisher-access',
    hazardDomains: ['fire_protection'],
    mechanisms: ['fire_extinguisher_access_failure', 'emergency_equipment_unavailable'],
    hierarchyLevel: 'administrative_control',
    immediateControl: 'Clear access to the extinguisher or replace unavailable fire protection equipment immediately.',
    permanentControl: 'Maintain fire extinguishers visible, accessible, inspected, mounted, identified, and protected from recurrent blockage.',
    verificationEvidence: ['photo of accessible extinguisher', 'current inspection tag', 'area housekeeping verification'],
    failureModesIfNotVerified: ['extinguisher remains blocked', 'inspection is expired', 'storage re-blocks the extinguisher'],
    notes: ['Extinguisher access controls should verify both physical access and readiness.'],
  },
  {
    controlId: 'control-hot-work-combustible-fire-watch',
    hazardDomains: ['welding_cutting_hot_work', 'fire_protection'],
    mechanisms: ['hot_work_ignition', 'combustible_exposure_fire', 'fire_watch_gap'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Stop hot work until combustibles are removed or shielded, extinguisher readiness is verified, and fire watch is assigned where required.',
    permanentControl: 'Use hot work authorization, combustible clearance, fire-resistant shielding, ventilation where needed, fire watch, extinguisher readiness, and post-work inspection.',
    verificationEvidence: ['hot work permit or authorization', 'fire watch record', 'combustible clearance photo', 'extinguisher verification'],
    failureModesIfNotVerified: ['combustibles remain near sparks', 'fire watch not assigned or trained', 'post-work inspection omitted'],
    notes: ['Hot work controls should control ignition source, fuel, exposure, and emergency readiness together.'],
  },
  {
    controlId: 'control-ppe-exposure-specific-selection',
    hazardDomains: ['ppe'],
    mechanisms: ['ppe_exposure_gap', 'eye_face_ppe_gap', 'hand_ppe_gap', 'abrasive_wheel_failure'],
    hierarchyLevel: 'ppe',
    immediateControl: 'Stop the exposure until task-specific PPE is selected, provided, worn, and verified.',
    permanentControl: 'Complete a hazard assessment, select exposure-specific PPE, replace damaged PPE, train affected employees, and verify PPE use does not substitute for higher-level controls.',
    verificationEvidence: ['PPE hazard assessment', 'photo/observation of correct PPE use', 'training or supervisor verification'],
    failureModesIfNotVerified: ['wrong PPE remains in use', 'PPE becomes the only control for a high-risk exposure', 'damaged PPE is reused'],
    notes: ['PPE is important but should not mask missing engineering, guarding, isolation, ventilation, or elimination controls.'],
  },

  {
    controlId: 'control-ergonomics-manual-handling-redesign',
    hazardDomains: ['ergonomics'],
    mechanisms: ['overexertion', 'musculoskeletal_disorder', 'strain_sprain'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Pause or limit high-risk manual handling until force, posture, repetition, or duration is reduced.',
    permanentControl: 'Redesign the task using mechanical assists, lift tables, staging changes, reduced load weights, improved reach heights, rotation, and recovery planning.',
    verificationEvidence: ['ergonomic assessment', 'photo/video of redesigned task', 'load/frequency verification', 'supervisor verification'],
    failureModesIfNotVerified: ['manual lift remains excessive', 'awkward posture persists', 'rotation used without reducing root exposure'],
    notes: ['Ergonomic corrective actions should reduce exposure drivers, not only instruct workers to lift properly.'],
  },
  {
    controlId: 'control-environmental-heat-cold-stress',
    hazardDomains: ['environmental_exposure', 'health_exposure'],
    mechanisms: ['heat_illness', 'cold_stress'],
    hierarchyLevel: 'administrative_control',
    immediateControl: 'Move affected workers to recovery, provide cooling or warming support, and adjust work based on symptoms and exposure conditions.',
    permanentControl: 'Measure environmental stressors, implement work/rest cycles, acclimatization or warming/cooling plans, hydration or dry clothing provisions, supervisor monitoring, and emergency response.',
    verificationEvidence: ['temperature/WBGT or wind chill data', 'work/rest schedule', 'recovery provision verification', 'symptom monitoring record'],
    failureModesIfNotVerified: ['exposure duration remains uncontrolled', 'workers are not monitored', 'emergency response is unclear'],
    notes: ['Heat/cold controls require environmental and workload context before confidence should be high.'],
  },
  {
    controlId: 'control-noise-hearing-conservation',
    hazardDomains: ['health_exposure'],
    mechanisms: ['noise_induced_hearing_loss'],
    hierarchyLevel: 'engineering_control',
    immediateControl: 'Restrict unprotected high-noise exposure until sound levels, exposure duration, and interim hearing protection are verified.',
    permanentControl: 'Perform noise monitoring or dosimetry, reduce noise at the source where feasible, apply administrative controls, select and fit hearing protection, and verify hearing conservation program requirements.',
    verificationEvidence: ['sound level reading', 'dosimetry result', 'engineering/admin control verification', 'hearing protection fit/training record', 'audiometric/program documentation'],
    failureModesIfNotVerified: ['noise exposure assumed without measurement', 'PPE relied on without fit/training', 'hearing conservation triggers not evaluated'],
    notes: ['Noise controls should prioritize measurement and source/control evaluation before relying only on earplugs.'],
  },
  {
    controlId: 'control-struck-by-falling-object-overhead',
    hierarchyLevel: 'engineering' as any,
    hazardDomains: ['struck_by' as any],
    mechanisms: ['struck_by_falling_object'],
    immediateControl: 'Barricade the lower exposure area and stop work below overhead tasks until falling-object controls are in place.',
    permanentControl: 'Install toe boards, screens, canopies, tool tethering, material securing, or equivalent dropped-object controls.',
    verificationEvidence: ['barricade photo', 'toe board or dropped-object control photo', 'supervisor verification'],
    failureModesIfNotVerified: ['employees remain exposed below overhead work', 'materials not secured', 'barricade removed early'],
    notes: ['Focus on object-fall exposure, not worker fall protection.'],
  },
  {
    controlId: 'control-health-bloodborne-sharps',
    hierarchyLevel: 'engineering' as any,
    hazardDomains: ['health_exposure'],
    mechanisms: ['bloodborne_pathogen_exposure'],
    immediateControl: 'Stop unsafe handling of sharps or contaminated materials and provide proper sharps disposal and PPE.',
    permanentControl: 'Implement exposure control procedures, training, PPE, cleanup supplies, and compliant sharps disposal.',
    verificationEvidence: ['sharps container photo', 'exposure control plan', 'training record'],
    failureModesIfNotVerified: ['sharps remain uncontrolled', 'employees lack exposure procedure', 'cleanup supplies unavailable'],
    notes: ['Biological exposure; do not route as HazCom chemical exposure.'],
  },
  {
    controlId: 'control-compressed-gas-cylinder-securement',
    hierarchyLevel: 'engineering' as any,
    hazardDomains: ['material_handling'],
    mechanisms: ['compressed_gas_cylinder_release'],
    immediateControl: 'Secure cylinders upright and remove unprotected or unstable cylinders from employee exposure areas.',
    permanentControl: 'Maintain cylinder restraints, valve caps where required, segregation, inspection, and storage controls.',
    verificationEvidence: ['cylinder chain/restraint photo', 'valve cap photo', 'storage inspection'],
    failureModesIfNotVerified: ['cylinders remain unsecured', 'valves unprotected', 'incompatible cylinders stored together'],
    notes: ['Stored-pressure hazard.'],
  },
  {
    controlId: 'control-emergency-eyewash-access',
    hierarchyLevel: 'engineering' as any,
    hazardDomains: ['emergency_preparedness'],
    mechanisms: ['emergency_equipment_access_failure'],
    immediateControl: 'Clear access to the eyewash/emergency equipment and restrict corrosive chemical use if immediate flushing is not available.',
    permanentControl: 'Maintain inspected, accessible emergency flushing equipment near corrosive exposure areas.',
    verificationEvidence: ['clear access photo', 'eyewash inspection tag', 'chemical use area distance check'],
    failureModesIfNotVerified: ['eyewash blocked again', 'inspection not current', 'corrosive use continues without emergency equipment'],
    notes: ['Emergency response equipment access.'],
  },
  {
    controlId: 'control-welding-cylinder-fire-explosion',
    hierarchyLevel: 'engineering' as any,
    hazardDomains: ['welding_cutting_hot_work'],
    mechanisms: ['fire_explosion'],
    immediateControl: 'Separate oxygen and fuel gas cylinders or remove them from hot work/fire exposure until storage is corrected.',
    permanentControl: 'Maintain required separation/barriers, valve protection, fire prevention, and hot work controls.',
    verificationEvidence: ['cylinder separation photo', 'valve protection photo', 'hot work/fire prevention checklist'],
    failureModesIfNotVerified: ['oxygen/fuel gas cylinders stored together', 'valves unprotected', 'ignition controls absent'],
    notes: ['Oxygen/fuel gas cylinder storage and fire/explosion control.'],
  },
  {
    controlId: 'control-construction-stairway-handrail',
    hierarchyLevel: 'engineering' as any,
    hazardDomains: ['slips_trips_falls'],
    mechanisms: ['fall_on_stairway'],
    immediateControl: 'Restrict access to the deficient stairway or provide alternate safe access until handrails are installed.',
    permanentControl: 'Install compliant stair rails/handrails and inspect temporary stairway access.',
    verificationEvidence: ['installed handrail photo', 'stairway inspection', 'access-control verification'],
    failureModesIfNotVerified: ['workers continue using missing-handrail stairway', 'temporary access remains uncontrolled'],
    notes: ['Construction stairway access, not leading-edge fall protection.'],
  },
  {
    controlId: 'control-mnm-underground-ventilation-air-quality',
    hierarchyLevel: 'engineering' as any,
    hazardDomains: ['ventilation'],
    mechanisms: ['air_quality_contaminant_buildup'],
    immediateControl: 'Restrict affected underground work area until ventilation is restored and air quality is verified.',
    permanentControl: 'Repair ventilation tubing or controls, verify airflow, and document air-quality/contaminant checks.',
    verificationEvidence: ['ventilation repair photo', 'airflow reading', 'air quality monitoring record'],
    failureModesIfNotVerified: ['airflow remains reduced', 'contaminants not evaluated', 'work resumes before ventilation restored'],
    notes: ['MNM underground ventilation and contaminant control.'],
  },

];
