import { SafeScopeEvidenceBrainRecord } from './evidence-brain.types';

export const SAFESCOPE_EVIDENCE_BRAIN_REGISTRY: SafeScopeEvidenceBrainRecord[] = [
  {
    evidenceId: 'evidence-powered-overhead-door-crush-point',
    hazardDomains: ['machine_guarding'],
    mechanisms: ['powered_door_crush_point'],
    question: 'Do employees pass under or near the powered overhead door during operation, and are the photo-eye, presence sensor, reversing edge, warning device, manual release, closing speed or force, and pedestrian travel path verified?',
    whyItMatters: 'Powered overhead door findings depend on both employee exposure to the closing-door crush point and functional verification of the protective devices that stop, reverse, warn, or allow emergency release.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Without exposure-path and safety-device function evidence, SafeScope should hold the conclusion for critical evidence instead of treating the door condition as fully defensible.',
  },
  {
    evidenceId: 'evidence-general-hazard-observation',
    hazardDomains: ['unknown'],
    mechanisms: [],
    question: 'What exactly was observed, where was it located, and what task or exposure was occurring?',
    whyItMatters: 'A complete hazard observation is the foundation for classification, jurisdiction routing, applicability, and corrective action reasoning.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Without a clear observation, SafeScope should not present a high-confidence conclusion.',
  },
  {
    evidenceId: 'evidence-jurisdiction-site-context',
    hazardDomains: ['machine_guarding', 'machine_guarding_loto', 'fall_protection', 'electrical', 'mobile_equipment', 'slip_trip_fall', 'slips_trips_falls'],
    mechanisms: [],
    question: 'Is this MSHA, OSHA General Industry, or OSHA Construction, and is the operation surface/underground or coal/metal-nonmetal?',
    whyItMatters: 'Many standards depend on jurisdiction and operating context. The same hazard can map to different citations.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Weak jurisdiction context can lead to the wrong citation even when the hazard family is correct, so the conclusion should remain in review until jurisdiction is defensible.',
  },
  {
    evidenceId: 'evidence-machine-guarding-exposure',
    hazardDomains: ['machine_guarding'],
    mechanisms: ['rotating_equipment', 'rotating_equipment_nip_point', 'pinch_point'],
    question: 'Can a person contact the moving part, nip point, pinch point, or point of operation during normal operation, cleaning, inspection, or maintenance?',
    whyItMatters: 'Machine guarding findings require proof of access/exposure to the hazardous moving part or point of operation.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Without access/exposure evidence, SafeScope should keep confidence limited and request more detail.',
  },
  {
    evidenceId: 'evidence-underground-mnm-guarding-scope',
    hazardDomains: ['machine_guarding'],
    mechanisms: ['rotating_equipment', 'rotating_equipment_nip_point'],
    question: 'Is the conveyor or rotating equipment located at an underground metal/nonmetal mine, a surface metal/nonmetal mine, or a coal mine?',
    whyItMatters: 'MSHA guarding citations may depend on underground versus surface scope.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'This evidence prevents surface/underground citation mismatch, so the conclusion should remain in review until the evidence is defensible.',
  },
  {
    evidenceId: 'evidence-loto-energy-isolation',
    hazardDomains: ['machine_guarding_loto', 'lockout_tagout'],
    mechanisms: ['unexpected_startup', 'stored_energy_release'],
    question: 'Was maintenance, servicing, unjamming, cleaning, or repair being performed, and were all hazardous energy sources isolated, locked/tagged, blocked, and verified at zero energy?',
    whyItMatters: 'LOTO and blocking conclusions depend on task state, energy sources, and verification of isolation.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Without task and energy-isolation evidence, SafeScope should not treat the LOTO conclusion as fully defensible.',
  },
  {
    evidenceId: 'evidence-electrical-exposed-live-parts',
    hazardDomains: ['electrical'],
    mechanisms: ['shock', 'shock_arc_flash'],
    question: 'Are conductors, live parts, damaged insulation, open enclosures, or energized components exposed, and is the circuit energized or potentially energized?',
    whyItMatters: 'Electrical findings require evidence of exposed electrical hazard and energized or potentially energized status.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing energized-status evidence should trigger qualified review and lower confidence.',
  },
  {
    evidenceId: 'evidence-fall-height-edge-protection',
    hazardDomains: ['fall_protection', 'scaffolds'],
    mechanisms: ['fall_from_height', 'inadequate_guardrail'],
    question: 'What is the fall height, what edge/open side/platform/scaffold condition exists, and what fall protection or guardrail system is present or missing?',
    whyItMatters: 'Fall protection applicability depends on height, exposure, work surface, and protective system details.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Without height and protection details, SafeScope should ask for measurements or photos before strong conclusions.',
  },
  {
    evidenceId: 'evidence-ladder-access-setup',
    hazardDomains: ['ladders', 'slips_trips_falls'],
    mechanisms: ['fall_from_ladder'],
    question: 'Is the ladder secured, set at a stable angle, extended above the landing where required, and being used for the observed access task?',
    whyItMatters: 'Ladder findings require setup, access, and use details to distinguish misuse from general walking-surface hazards.',
    importance: 'high',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Incomplete ladder setup evidence should keep findings in review status.',
  },
  {
    evidenceId: 'evidence-slip-trip-walking-surface',
    hazardDomains: ['slip_trip_fall', 'slips_trips_falls', 'walking_working_surfaces'],
    mechanisms: ['slip', 'trip', 'slip_trip_fall'],
    question: 'What surface condition, obstruction, housekeeping issue, spill, loose material, or travelway restriction creates the slip/trip exposure?',
    whyItMatters: 'Walking-surface findings require proof of the physical condition and employee travel/exposure path.',
    importance: 'high',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Photos and location context improve defensibility and prevent over-classifying minor housekeeping issues.',
  },
  {
    evidenceId: 'evidence-mobile-equipment-pedestrian-interface',
    hazardDomains: ['mobile_equipment', 'powered_haulage', 'traffic_control'],
    mechanisms: ['pedestrian_strike', 'struck_by', 'struck_by_mobile_equipment'],
    question: 'Are pedestrians/miners on foot exposed to moving equipment, backing equipment, blind spots, traffic routes, or missing separation controls?',
    whyItMatters: 'Mobile equipment findings require evidence of the equipment movement, pedestrian exposure, and separation/control condition.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing pedestrian-exposure evidence can cause mechanism confusion with general slip/trip hazards, so the conclusion should remain in review until the evidence is defensible.',
  },
  {
    evidenceId: 'evidence-berm-edge-dropoff',
    hazardDomains: ['mobile_equipment', 'powered_haulage'],
    mechanisms: ['run_off_embankment'],
    question: 'Is there a drop-off, elevated roadway edge, dump point, or embankment, and is the berm/guardrail adequate for the largest equipment using the route?',
    whyItMatters: 'Berm findings depend on roadway edge exposure, drop-off context, and adequacy relative to equipment size.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Berm adequacy conclusions need visual and dimensional context.',
  },
  {
    evidenceId: 'evidence-ground-roof-rib-control',
    hazardDomains: ['ground_control', 'roof_rib_control'],
    mechanisms: ['fall_of_ground', 'rib_fall'],
    question: 'What loose roof, loose rib, fractured ground, unsupported area, scaling need, or roof-control-plan issue is visible or reported?',
    whyItMatters: 'Ground-control conclusions require evidence of unstable material, exposure location, and control/support condition.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Ground-control findings should require qualified review when support conditions or plan compliance are uncertain.',
  },
  {
    evidenceId: 'evidence-ventilation-airflow-gas',
    hazardDomains: ['ventilation'],
    mechanisms: ['methane_gas_buildup'],
    question: 'What ventilation control, curtain, airflow, methane/gas reading, air-quality concern, or examination result supports the finding?',
    whyItMatters: 'Ventilation findings depend on control condition, airflow direction/quantity, gas hazard potential, and examination context.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Ventilation findings need airflow/gas evidence or qualified confirmation before high confidence.',
  },
  {
    evidenceId: 'evidence-escapeway-egress-clearance',
    hazardDomains: ['emergency_preparedness'],
    mechanisms: ['egress_blockage'],
    question: 'What obstruction, storage, damage, route condition, lifeline issue, or clearance problem affects the escapeway or emergency route?',
    whyItMatters: 'Escapeway findings require evidence that emergency travel, route integrity, or egress availability is affected.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Clear egress evidence helps distinguish emergency preparedness hazards from generic housekeeping, so the conclusion should remain in review until the evidence is defensible.',
  },
  {
    evidenceId: 'evidence-silica-exposure-controls',
    hazardDomains: ['health_respiratory', 'health_exposure'],
    mechanisms: ['silica_inhalation'],
    question: 'What task generates dust, what material is involved, what engineering controls are used, and are exposure measurements or Table 1/control-method details available?',
    whyItMatters: 'Respirable silica findings depend on task, material, control method, exposure duration/frequency, and measurement or prescribed-control evidence.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Health exposure findings should ask for measurements, exposure duration, or documented control method before high-confidence conclusions.',
  },
  {
    evidenceId: 'evidence-hazcom-container-identity',
    hazardDomains: ['hazardous_materials', 'hazard_communication'],
    mechanisms: ['chemical_exposure'],
    question: 'Is the container labeled, what chemical is inside, what hazards are communicated, and is the SDS or hazard information available?',
    whyItMatters: 'HazCom findings require container identity, label status, chemical hazard, and communication availability.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Unclear chemical identity or missing label evidence should keep the finding in review.',
  },
  {
    evidenceId: 'evidence-confined-space-entry-controls',
    hazardDomains: ['confined_space'],
    mechanisms: ['asphyxiation'],
    question: 'Was entry occurring or planned, has the space been evaluated, are atmospheric tests available, and are permit, attendant, rescue, and isolation controls in place?',
    whyItMatters: 'Confined-space findings require space classification, entry status, atmospheric hazard potential, and entry-control evidence.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing atmospheric testing or permit/control evidence should prevent overconfident conclusions.',
  },
  {
    evidenceId: 'evidence-excavation-trenching-collapse',
    hazardDomains: ['excavation_trenching'],
    mechanisms: ['collapse'],
    question: 'Is the excavation depth, employee entry exposure, ground/soil condition, protective system status, competent-person inspection status, and safe egress condition documented?',
    whyItMatters: 'Excavation and trenching conclusions depend on whether employees are exposed to cave-in hazards and whether protective systems, inspection, and egress controls are present.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Improves confidence, defensibility, review quality, and conclusion support by documenting depth, exposure, protective system status, competent-person inspection basis, and egress conditions before recommending corrective action.',
  },

  {
    evidenceId: 'evidence-cranes-rigging-suspended-load',
    hazardDomains: ['cranes_rigging_hoisting'],
    mechanisms: ['struck_by_suspended_load', 'dropped_load', 'rigging_failure', 'crane_contact'],
    question: 'What load is being lifted, what is the load path/fall zone, where are employees positioned, what rigging is used, and were operator/signal/exclusion controls verified?',
    whyItMatters: 'Crane and rigging findings depend on the relationship between the load, rigging condition, employee position, load path, and lift-control methods.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Without load-path, employee-position, rigging, and operator/signal evidence, SafeScope should not make a high-confidence crane or suspended-load conclusion.',
  },


  {
    evidenceId: 'evidence-material-handling-storage-stability',
    hazardDomains: ['material_handling'],
    mechanisms: ['unstable_stack_collapse', 'falling_object_material', 'dropped_load'],
    question: 'What material is stored or handled, how is it stacked/racked/secured, and are employees exposed to a collapse, shift, roll, or falling-object path?',
    whyItMatters: 'Material-handling findings depend on storage stability, load path, employee exposure, and whether the condition is active handling versus static storage.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Without stack stability and employee exposure evidence, SafeScope should avoid high-confidence conclusions and request more detail.',
  },
  {
    evidenceId: 'evidence-tools-equipment-condition',
    hazardDomains: ['tools_equipment'],
    mechanisms: ['defective_tool_contact', 'abrasive_wheel_failure', 'tool_guarding_gap'],
    question: 'What tool is involved, what defect or missing guard exists, was it available for use, and was it removed from service?',
    whyItMatters: 'Tool findings require proof of tool condition, exposure, use status, and correction before SafeScope can recommend durable action.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Tool condition evidence improves confidence, defensibility, review quality, and conclusion support by documenting whether the tool should be removed from service, repaired, guarded, or replaced before SafeScope recommends corrective action.',
  },
  {
    evidenceId: 'evidence-fire-protection-extinguisher-readiness',
    hazardDomains: ['fire_protection'],
    mechanisms: ['fire_extinguisher_access_failure', 'emergency_equipment_unavailable'],
    question: 'Is the extinguisher or fire protection equipment visible, accessible, inspected, identified, and suitable for the area hazard?',
    whyItMatters: 'Fire-protection findings depend on whether emergency equipment is actually ready and available when needed.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'This evidence improves confidence, defensibility, review quality, and conclusion support by documenting the factual condition before SafeScope recommends corrective action.',
  },
  {
    evidenceId: 'evidence-hot-work-fire-prevention',
    hazardDomains: ['welding_cutting_hot_work', 'fire_protection'],
    mechanisms: ['hot_work_ignition', 'combustible_exposure_fire', 'fire_watch_gap'],
    question: 'What hot work is occurring, what combustibles/flammables/dusts are nearby, and are fire watch, extinguisher, ventilation, permit/authorization, and post-work inspection controls documented?',
    whyItMatters: 'Hot work conclusions require ignition source, fuel exposure, controls, and emergency readiness evidence.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing fire watch, combustible clearance, or extinguisher evidence should trigger review before high-confidence conclusions.',
  },
  {
    evidenceId: 'evidence-ppe-exposure-specific-use',
    hazardDomains: ['ppe'],
    mechanisms: ['ppe_exposure_gap', 'eye_face_ppe_gap', 'hand_ppe_gap'],
    question: 'What exposure requires PPE, what PPE is required, what PPE is worn or missing, and are higher-level controls also needed?',
    whyItMatters: 'PPE findings are only meaningful when tied to the actual exposure and when SafeScope does not treat PPE as the only control for serious hazards.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'This evidence improves confidence, defensibility, review quality, and conclusion support by documenting the factual condition before SafeScope recommends corrective action.',
  },

  {
    evidenceId: 'evidence-ergonomics-manual-handling-risk',
    hazardDomains: ['ergonomics'],
    mechanisms: ['overexertion', 'musculoskeletal_disorder', 'strain_sprain'],
    question: 'What load, posture, reach, repetition, force, duration, recovery, and mechanical-assist condition supports the ergonomic or manual-handling finding?',
    whyItMatters: 'Ergonomic conclusions require evidence of exposure drivers, not just a generic statement that a task is hard or repetitive.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'This evidence improves confidence, defensibility, review quality, and conclusion support by documenting the biomechanical exposure before SafeScope recommends corrective action.',
  },
  {
    evidenceId: 'evidence-environmental-heat-cold-exposure',
    hazardDomains: ['environmental_exposure', 'health_exposure'],
    mechanisms: ['heat_illness', 'cold_stress'],
    question: 'What temperature, humidity/WBGT, wind chill, workload, PPE burden, exposure duration, acclimatization, recovery controls, and symptoms are present?',
    whyItMatters: 'Heat and cold stress findings require environmental, workload, duration, and worker-condition evidence before high-confidence conclusions.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'This evidence improves confidence, defensibility, review quality, and conclusion support by documenting heat/cold exposure conditions, controls, and symptom monitoring before SafeScope recommends corrective action.',
  },
  {
    evidenceId: 'evidence-noise-hearing-conservation',
    hazardDomains: ['health_exposure'],
    mechanisms: ['noise_induced_hearing_loss'],
    question: 'What noise source, measured sound level or dose, exposure duration, employee proximity, hearing protection, and hearing conservation program status are known?',
    whyItMatters: 'Noise findings require exposure characterization and program-control evidence; subjective loudness alone is not enough for a defensible conclusion.',
    importance: 'critical',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'This evidence improves confidence, defensibility, review quality, and conclusion support by documenting noise dose, duration, controls, hearing protection, and program status before SafeScope recommends corrective action.',
  },
  {
    evidenceId: 'evidence-struck-by-falling-object-overhead',
    hazardDomains: ['struck_by' as any],
    mechanisms: ['struck_by_falling_object'],
    question: 'What overhead task, falling-object source, employee exposure below, and dropped-object control evidence support the finding?',
    importance: 'critical',
    whyItMatters: 'This evidence is needed to support defensible hazard classification, citation selection, corrective action, and qualified review.',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing evidence may reduce confidence, require qualified review, or prevent closure until the condition is verified.',
  },
  {
    evidenceId: 'evidence-health-bloodborne-sharps',
    hazardDomains: ['health_exposure', 'bloodborne_pathogens'],
    mechanisms: ['bloodborne_pathogen_exposure'],
    question: 'What sharps, blood/bodily fluid exposure, exposure control plan, PPE, disposal, and training evidence support the finding?',
    importance: 'critical',
    whyItMatters: 'This evidence is needed to support defensible hazard classification, citation selection, corrective action, and qualified review.',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing evidence may reduce confidence, require qualified review, or prevent closure until the condition is verified.',
  },
  {
    evidenceId: 'evidence-compressed-gas-cylinder-release',
    hazardDomains: ['material_handling'],
    mechanisms: ['compressed_gas_cylinder_release'],
    question: 'What cylinder type, restraint condition, valve protection, segregation, and employee exposure evidence support the finding?',
    importance: 'critical',
    whyItMatters: 'This evidence is needed to support defensible hazard classification, citation selection, corrective action, and qualified review.',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing evidence may reduce confidence, require qualified review, or prevent closure until the condition is verified.',
  },
  {
    evidenceId: 'evidence-emergency-eyewash-access',
    hazardDomains: ['emergency_preparedness'],
    mechanisms: ['emergency_equipment_access_failure'],
    question: 'What corrosive exposure, eyewash location, access obstruction, inspection status, and travel distance evidence support the finding?',
    importance: 'critical',
    whyItMatters: 'This evidence is needed to support defensible hazard classification, citation selection, corrective action, and qualified review.',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing evidence may reduce confidence, require qualified review, or prevent closure until the condition is verified.',
  },
  {
    evidenceId: 'evidence-welding-cylinder-fire-explosion',
    hazardDomains: ['welding_cutting_hot_work'],
    mechanisms: ['fire_explosion'],
    question: 'What oxygen/fuel gas cylinder storage, separation, valve protection, ignition source, and fire prevention evidence support the finding?',
    importance: 'critical',
    whyItMatters: 'This evidence is needed to support defensible hazard classification, citation selection, corrective action, and qualified review.',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing evidence may reduce confidence, require qualified review, or prevent closure until the condition is verified.',
  },
  {
    evidenceId: 'evidence-construction-stairway-handrail',
    hazardDomains: ['slips_trips_falls'],
    mechanisms: ['fall_on_stairway'],
    question: 'What temporary stairway configuration, missing handrail/open side, employee use, and access control evidence support the finding?',
    importance: 'critical',
    whyItMatters: 'This evidence is needed to support defensible hazard classification, citation selection, corrective action, and qualified review.',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing evidence may reduce confidence, require qualified review, or prevent closure until the condition is verified.',
  },
  {
    evidenceId: 'evidence-mnm-underground-ventilation-air-quality',
    hazardDomains: ['ventilation'],
    mechanisms: ['air_quality_contaminant_buildup'],
    question: 'What damaged ventilation tubing/control, reduced airflow, work area exposure, and air-quality monitoring evidence support the finding?',
    importance: 'critical',
    whyItMatters: 'This evidence is needed to support defensible hazard classification, citation selection, corrective action, and qualified review.',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing evidence may reduce confidence, require qualified review, or prevent closure until the condition is verified.',
  },
  {
    evidenceId: 'evidence-industrial-hygiene-local-exhaust',
    hazardDomains: ['industrial_hygiene'],
    mechanisms: ['chemical_vapors_inhalation', 'toxic_gas_inhalation'],
    question: 'What air quality sampling concentration, local exhaust ventilation status, employee respiratory protection, and duration evidence support the finding?',
    importance: 'critical',
    whyItMatters: 'This evidence is needed to support defensible hazard classification, air contaminants compliance, and qualified review.',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing evidence may reduce confidence, require qualified review, or prevent closure until the condition is verified.',
  },
  {
    evidenceId: 'evidence-ergonomics-lift-assist',
    hazardDomains: ['ergonomics'],
    mechanisms: ['lifting_musculoskeletal_strain'],
    question: 'What load weight, manual handling frequency, forceful exertion, worker posture, and availability of lift-assist mechanical devices evidence support the finding?',
    importance: 'critical',
    whyItMatters: 'This evidence is needed to support defensible hazard classification, ergonomics strain mitigation, and qualified review.',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Missing evidence may reduce confidence, require qualified review, or prevent closure until the condition is verified.',
  },
  {
    evidenceId: 'evidence-excavation-access-egress',
    hazardDomains: ['excavation_trenching'],
    mechanisms: ['excavation_cave_in_or_entrapment'],
    question: 'Do employees enter the trench, is the excavation 4 feet or more in depth, are stairways, ladders, or ramps provided, and is the lateral travel distance to safe egress within 25 feet?',
    importance: 'critical',
    whyItMatters: 'Excavation egress is critical to prevent entrapment during trench cave-ins, collapses, or flooding. Safe egress must be immediately available for employees working in trenches 4 feet or more in depth.',
    acceptableEvidenceTypes: ['photo', 'measurement', 'employee_statement', 'inspection_observation', 'document_review', 'qualified_person_review', 'equipment_record'],
    defensibilityImpact: 'Without confirming trench depth, employee entry, and actual lateral egress distance, SafeScope should withhold a high-confidence advisory conclusion and require qualified review.',
  },
  {
    evidenceId: 'evidence-electrical-dead-front',
    hazardDomains: ['electrical'],
    mechanisms: ['shock', 'shock_arc_flash'],
    question: 'Is the outer electrical cabinet door open, is the interior dead-front protective cover missing, are live busbars or terminals exposed, and are unqualified workers exposed?',
    importance: 'critical',
    whyItMatters: 'Dead-front covers prevent accidental contact with live electrical parts when cabinet doors are opened by operators. A missing dead-front cover exposes technicians and workers to immediate high-voltage shock and arc flash potential.',
    acceptableEvidenceTypes: ['photo', 'employee_statement', 'inspection_observation', 'qualified_person_review'],
    defensibilityImpact: 'Without confirming whether the dead-front interior cover is in place inside an open cabinet, SafeScope must hold the advisory conclusion and require qualified review to maintain high confidence.',
  },
  {
    evidenceId: 'evidence-electrical-grounding-gfci',
    hazardDomains: ['electrical'],
    mechanisms: ['ground_fault_shock_pathway', 'shock'],
    question: 'Is temporary wiring or are portable extension cords in use, are they located in damp/wet areas, and is GFCI protection or an assured grounding log verified?',
    importance: 'critical',
    whyItMatters: 'Temporary power cords on construction sites are subject to severe wear and mud/water exposure. GFCI protection shuts off power immediately during ground faults to prevent electrocution.',
    acceptableEvidenceTypes: ['photo', 'document_review', 'inspection_observation', 'equipment_record'],
    defensibilityImpact: 'Without confirming GFCI breaker operation or an assured grounding log, temporary power findings should require qualified review to preserve defensibility and confidence.',
  },

];
