import { SafeScopeRegulatoryBrainRecord } from './regulatory-brain.types';

const bindingBoundary = {
  canCreateCitation: false,
  canDeclareViolation: false,
  canOverrideRegulation: false,
  canBypassHumanReview: false,
  canInfluenceReasoning: false,
  requiresQualifiedReview: true,
} as const;


const advisoryBoundary = {
  canCreateCitation: false,
  canDeclareViolation: false,
  canOverrideRegulation: false,
  canBypassHumanReview: false,
  canInfluenceReasoning: false,
  requiresQualifiedReview: true,
} as const;

export const SAFESCOPE_REGULATORY_BRAIN_REGISTRY: SafeScopeRegulatoryBrainRecord[] = [
  {
    recordId: 'reg-msha-56-14107-machine-guarding',
    title: 'MSHA surface metal/nonmetal machine guarding',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'metal_nonmetal_surface',
    citation: '30 CFR 56.14107',
    citationTitle: 'Moving machine parts',
    standardPart: '30 CFR Part 56',
    standardSubpart: 'Subpart M',
    hazardDomains: ['machine_guarding'],
    mechanisms: ['rotating_equipment', 'rotating_equipment_nip_point', 'pinch_point'],
    applicabilityTriggers: ['unguarded moving machine parts', 'conveyor pulley', 'rotating equipment', 'nip point', 'contact exposure'],
    exclusionTriggers: ['underground metal/nonmetal citation may require 30 CFR 57.14107', 'coal mine guarding may require separate coal standards'],
    requiredControls: ['guard moving machine parts', 'prevent contact with nip points', 'restrict access until guarded'],
    correctiveActionPatterns: ['install guard', 'repair guard', 'verify guard before operation', 'document post-correction inspection'],
    verificationEvidence: ['photo of installed guard', 'post-correction inspection record', 'equipment guarded before restart'],
    evidenceQuestions: ['What moving part is exposed?', 'Can a person contact the moving part during operation?', 'Is this surface metal/nonmetal or underground metal/nonmetal?'],
    plainLanguageSummary: 'Moving machine parts that can injure miners must be guarded to prevent contact.',
    sourceReference: '30 CFR 56.14107',
    boundary: bindingBoundary,
    notes: ['Read-only Brain record. Does not create citations or declare violations.'],
  },
  {
    recordId: 'reg-msha-57-14107-machine-guarding',
    title: 'MSHA underground metal/nonmetal machine guarding',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'metal_nonmetal_underground',
    citation: '30 CFR 57.14107',
    citationTitle: 'Moving machine parts',
    standardPart: '30 CFR Part 57',
    standardSubpart: 'Subpart M',
    hazardDomains: ['machine_guarding'],
    mechanisms: ['rotating_equipment', 'rotating_equipment_nip_point', 'pinch_point'],
    applicabilityTriggers: ['underground metal/nonmetal', 'unguarded conveyor', 'unguarded pulley', 'moving machine parts'],
    exclusionTriggers: ['surface metal/nonmetal may require 30 CFR 56.14107'],
    requiredControls: ['guard moving machine parts', 'prevent contact with rotating equipment', 'restrict access until guarded'],
    correctiveActionPatterns: ['install guard', 'repair guard', 'verify guard before operation', 'document post-correction inspection'],
    verificationEvidence: ['photo of installed guard', 'underground equipment inspection record', 'guard verification before restart'],
    evidenceQuestions: ['Is the mine underground metal/nonmetal?', 'What moving part is exposed?', 'Is the equipment operating or capable of movement?'],
    plainLanguageSummary: 'Underground metal/nonmetal moving machine parts must be guarded where contact could injure miners.',
    sourceReference: '30 CFR 57.14107',
    boundary: bindingBoundary,
    notes: ['Separated from 30 CFR 56.14107 so SafeScope can reason by mine scope.'],
  },
  {
    recordId: 'reg-msha-56-14105-repairs-maintenance',
    title: 'MSHA repairs or maintenance machinery power-off and blocking',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'metal_nonmetal_surface',
    citation: '30 CFR 56.14105',
    citationTitle: 'Procedures during repairs or maintenance',
    standardPart: '30 CFR Part 56',
    standardSubpart: 'Subpart M',
    hazardDomains: ['machine_guarding_loto', 'lockout_tagout'],
    mechanisms: ['unexpected_startup', 'stored_energy_release'],
    applicabilityTriggers: ['repairs', 'maintenance', 'servicing', 'crusher maintenance', 'guard removed', 'unexpected startup', 'blocking'],
    exclusionTriggers: ['OSHA general industry LOTO may require 29 CFR 1910.147'],
    requiredControls: ['power off equipment', 'block against hazardous motion', 'isolate energy', 'verify zero energy'],
    correctiveActionPatterns: ['stop maintenance', 'lock out and tag out energy sources', 'block equipment against motion', 'document zero-energy verification'],
    verificationEvidence: ['lockout verification', 'blocking verification', 'qualified person or supervisor verification'],
    evidenceQuestions: ['What task is being performed?', 'Could equipment start or move unexpectedly?', 'Has stored energy been controlled?'],
    plainLanguageSummary: 'Equipment under repair or maintenance must be powered off and blocked against hazardous motion where required.',
    sourceReference: '30 CFR 56.14105',
    boundary: bindingBoundary,
    notes: ['SafeScope must distinguish maintenance/servicing from ordinary guarding.'],
  },
  {
    recordId: 'reg-msha-56-12004-electrical-conductors',
    title: 'MSHA electrical conductor protection',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'metal_nonmetal_surface',
    citation: '30 CFR 56.12004',
    citationTitle: 'Electrical conductors',
    standardPart: '30 CFR Part 56',
    standardSubpart: 'Subpart K',
    hazardDomains: ['electrical'],
    mechanisms: ['shock', 'shock_arc_flash'],
    applicabilityTriggers: ['damaged electrical cable', 'exposed conductor', 'damaged conductor', 'energized conductor', 'arc flash', 'shock exposure'],
    exclusionTriggers: ['OSHA general industry electrical guarding may require 29 CFR 1910.303'],
    requiredControls: ['de-energize circuit', 'restrict access', 'repair damaged electrical cable', 'protect exposed conductors'],
    correctiveActionPatterns: ['de-energize circuit', 'repair damaged cable', 'verify insulation integrity before return to service'],
    verificationEvidence: ['electrical repair record', 'qualified electrical inspection', 'photo of repaired conductor or cable'],
    evidenceQuestions: ['Is the conductor energized?', 'Is insulation damaged?', 'Are employees exposed to contact or arc flash?'],
    plainLanguageSummary: 'Electrical conductors must be protected where damaged or exposed conductors could create shock or arc-flash exposure.',
    sourceReference: '30 CFR 56.12004',
    boundary: bindingBoundary,
    notes: ['Mechanism should preserve both shock and arc-flash potential when evidence supports it.'],
  },
  {
    recordId: 'reg-msha-56-15005-fall-protection',
    title: 'MSHA safety belts and lines / fall protection',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'metal_nonmetal_surface',
    citation: '30 CFR 56.15005',
    citationTitle: 'Safety belts and lines',
    standardPart: '30 CFR Part 56',
    standardSubpart: 'Subpart N',
    hazardDomains: ['fall_protection'],
    mechanisms: ['fall_from_height'],
    applicabilityTriggers: ['elevated work', 'platform', 'fall exposure', 'unguarded edge', 'fall restraint', 'fall arrest'],
    exclusionTriggers: ['OSHA construction leading edge may require 29 CFR 1926.501'],
    requiredControls: ['restrict access to fall exposure', 'provide fall protection', 'verify fall protection before work resumes'],
    correctiveActionPatterns: ['install guardrail', 'provide fall arrest or restraint', 'document supervisor verification'],
    verificationEvidence: ['photo of fall protection', 'inspection record', 'competent person verification'],
    evidenceQuestions: ['What is the fall height?', 'What edge or platform is exposed?', 'What fall protection is in use?'],
    plainLanguageSummary: 'Miners exposed to fall hazards must be protected with appropriate fall protection controls.',
    sourceReference: '30 CFR 56.15005',
    boundary: bindingBoundary,
    notes: ['Requires careful distinction between platforms, travelways, and work positioning.'],
  },
  {
    recordId: 'reg-msha-56-9300-berms-guardrails',
    title: 'MSHA berms or guardrails on roadways',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'metal_nonmetal_surface',
    citation: '30 CFR 56.9300',
    citationTitle: 'Berms or guardrails',
    standardPart: '30 CFR Part 56',
    standardSubpart: 'Subpart H',
    hazardDomains: ['mobile_equipment', 'powered_haulage'],
    mechanisms: ['run_off_embankment'],
    applicabilityTriggers: ['haul road', 'berm', 'drop off', 'dump point', 'edge control', 'mobile equipment over edge'],
    exclusionTriggers: ['pedestrian strike hazards require separate mobile equipment analysis'],
    requiredControls: ['install or restore berm', 'restrict haulage until edge control is restored', 'verify roadway edge protection'],
    correctiveActionPatterns: ['install berm', 'restore edge control', 'document berm inspection'],
    verificationEvidence: ['photo of berm', 'roadway inspection record', 'dump point verification'],
    evidenceQuestions: ['Is there a drop-off hazard?', 'What equipment travels the roadway?', 'Is berm height adequate for the equipment?'],
    plainLanguageSummary: 'Berms or guardrails are required where roadway drop-offs expose mobile equipment to over-edge hazards.',
    sourceReference: '30 CFR 56.9300',
    boundary: bindingBoundary,
    notes: ['SafeScope should separate run-off/over-edge hazards from pedestrian struck-by hazards.'],
  },
  {
    recordId: 'reg-msha-56-20003-housekeeping',
    title: 'MSHA housekeeping and travelway cleanliness',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'metal_nonmetal_surface',
    citation: '30 CFR 56.20003',
    citationTitle: 'Housekeeping',
    standardPart: '30 CFR Part 56',
    standardSubpart: 'Subpart Q',
    hazardDomains: ['slip_trip_fall', 'walking_working_surfaces'],
    mechanisms: ['trip', 'slip_trip_fall'],
    applicabilityTriggers: ['housekeeping', 'loose material', 'travelway obstruction', 'trip hazard', 'stored material in travelway'],
    exclusionTriggers: ['wet walking surface in OSHA general industry may require 29 CFR 1910.22'],
    requiredControls: ['remove obstruction', 'restore clear travelway', 'maintain orderly work area'],
    correctiveActionPatterns: ['remove loose material', 'restore clear travelway', 'document housekeeping correction'],
    verificationEvidence: ['photo of cleared travelway', 'inspection note', 'housekeeping correction record'],
    evidenceQuestions: ['What obstructs the travelway?', 'Is employee travel required through the area?', 'Has the material been removed or controlled?'],
    plainLanguageSummary: 'Workplaces and travelways must be kept clean and orderly to prevent slip, trip, and fall hazards.',
    sourceReference: '30 CFR 56.20003',
    boundary: bindingBoundary,
    notes: ['Applies to housekeeping and travelway order in metal/nonmetal mining context.'],
  },
  {
    recordId: 'reg-msha-75-202-roof-rib-control',
    title: 'MSHA underground coal roof, face, and rib control',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'coal_underground',
    citation: '30 CFR 75.202(a)',
    citationTitle: 'Protection from falls of roof, face and ribs',
    standardPart: '30 CFR Part 75',
    standardSubpart: 'Subpart C',
    hazardDomains: ['ground_control', 'roof_rib_control'],
    mechanisms: ['fall_of_ground', 'rib_fall'],
    applicabilityTriggers: ['loose roof', 'loose rib', 'rib control', 'unsupported rib', 'fall of ground', 'roof/rib hazard'],
    exclusionTriggers: ['metal/nonmetal ground control may require different part or subpart'],
    requiredControls: ['restrict access', 'scale loose material', 'install supplemental support', 'follow approved roof control plan'],
    correctiveActionPatterns: ['scale loose rib', 'install supplemental support', 'document qualified person examination'],
    verificationEvidence: ['qualified person examination', 'support installation record', 'photo of corrected rib/roof condition'],
    evidenceQuestions: ['Is the hazard roof, face, or rib?', 'Is the area traveled or occupied?', 'What support or control exists?'],
    plainLanguageSummary: 'Underground coal roof, face, and ribs must be supported or controlled to protect miners.',
    sourceReference: '30 CFR 75.202(a)',
    boundary: bindingBoundary,
    notes: ['Supports both roof-control and rib-control reasoning.'],
  },
  {
    recordId: 'reg-msha-75-333-ventilation-controls',
    title: 'MSHA underground coal ventilation controls',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'coal_underground',
    citation: '30 CFR 75.333',
    citationTitle: 'Ventilation controls',
    standardPart: '30 CFR Part 75',
    standardSubpart: 'Subpart D',
    hazardDomains: ['ventilation'],
    mechanisms: ['methane_gas_buildup'],
    applicabilityTriggers: ['ventilation curtain', 'airflow', 'methane', 'gas buildup', 'ventilation control damaged'],
    exclusionTriggers: ['non-coal ventilation standards may differ'],
    requiredControls: ['restore ventilation control', 'evaluate methane or air quality', 'restrict affected area until evaluated'],
    correctiveActionPatterns: ['repair ventilation curtain', 'verify airflow', 'document methane or gas check'],
    verificationEvidence: ['ventilation examination', 'airflow verification', 'methane check record'],
    evidenceQuestions: ['What ventilation control is affected?', 'Is airflow reduced or redirected?', 'Were methane or air quality checks performed?'],
    plainLanguageSummary: 'Underground coal ventilation controls must be maintained so airflow and gas control remain effective.',
    sourceReference: '30 CFR 75.333',
    boundary: bindingBoundary,
    notes: ['Ventilation cases require evidence of airflow, methane, and affected area status.'],
  },
  {
    recordId: 'reg-msha-75-380-escapeways',
    title: 'MSHA underground coal escapeways',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'coal_underground',
    citation: '30 CFR 75.380',
    citationTitle: 'Escapeways; bituminous and lignite mines',
    standardPart: '30 CFR Part 75',
    standardSubpart: 'Subpart D',
    hazardDomains: ['emergency_preparedness'],
    mechanisms: ['egress_blockage'],
    applicabilityTriggers: ['escapeway', 'blocked escapeway', 'obstructed escapeway', 'emergency egress', 'lifeline', 'escape route'],
    exclusionTriggers: ['ordinary housekeeping hazard outside escapeway may require different citation analysis'],
    requiredControls: ['remove obstruction', 'restore clear escapeway', 'verify emergency route integrity'],
    correctiveActionPatterns: ['remove stored material', 'verify escapeway is clear and passable', 'document escapeway inspection'],
    verificationEvidence: ['photo of cleared escapeway', 'escapeway inspection record', 'responsible person verification'],
    evidenceQuestions: ['Is the obstruction in a designated escapeway?', 'Is travel impeded?', 'Is the lifeline or route marking affected?'],
    plainLanguageSummary: 'Underground coal escapeways must remain clear and available for emergency travel.',
    sourceReference: '30 CFR 75.380',
    boundary: bindingBoundary,
    notes: ['SafeScope should distinguish escapeway blockage from general housekeeping and LOTO mechanisms.'],
  },
  {
    recordId: 'reg-msha-75-1725-machinery-equipment-maintenance',
    title: 'MSHA underground coal machinery and equipment maintenance',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'coal_underground',
    citation: '30 CFR 75.1725',
    citationTitle: 'Machinery and equipment; operation and maintenance',
    standardPart: '30 CFR Part 75',
    standardSubpart: 'Subpart R',
    hazardDomains: ['mobile_equipment'],
    mechanisms: ['pedestrian_strike'],
    applicabilityTriggers: ['underground coal mobile equipment', 'shuttle car', 'scoop', 'pedestrian interaction', 'miners on foot'],
    exclusionTriggers: ['surface MNM berms are not this citation'],
    requiredControls: ['maintain equipment in safe operating condition', 'separate pedestrians from mobile equipment', 'verify controls before operation'],
    correctiveActionPatterns: ['restrict access to equipment travel area', 'define pedestrian separation', 'document equipment control verification'],
    verificationEvidence: ['equipment examination', 'traffic control verification', 'pedestrian separation verification'],
    evidenceQuestions: ['What equipment is involved?', 'Are miners on foot exposed?', 'What visibility or separation controls exist?'],
    plainLanguageSummary: 'Underground coal machinery and equipment must be maintained and operated so miners are protected from equipment hazards.',
    sourceReference: '30 CFR 75.1725',
    boundary: bindingBoundary,
    notes: ['Used cautiously for underground coal mobile equipment/pedestrian interaction benchmark context.'],
  },
  {
    recordId: 'reg-osha-1926-652-excavation-protective-systems',
    title: 'OSHA construction excavation protective systems',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.652(a)(1)',
    citationTitle: 'Requirements for protective systems',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart P',
    hazardDomains: ['excavation_trenching'],
    mechanisms: ['collapse'],
    applicabilityTriggers: ['excavation', 'trench', 'cave-in', 'unprotected trench', 'protective system'],
    exclusionTriggers: ['not applicable to mining excavations without OSHA construction jurisdiction'],
    requiredControls: ['remove employees from excavation', 'install protective system', 'slope, shore, or shield'],
    correctiveActionPatterns: ['install protective system', 'slope', 'shore', 'shield', 'competent person inspection record'],
    verificationEvidence: ['competent person inspection', 'photo of protective system', 'depth and soil condition documentation'],
    evidenceQuestions: ['How deep is the excavation?', 'Are employees entering?', 'What protective system is installed?'],
    plainLanguageSummary: 'Employees in excavations must be protected from cave-in hazards by an appropriate protective system unless an exception applies.',
    sourceReference: '29 CFR 1926.652(a)(1)',
    boundary: bindingBoundary,
    notes: ['Depth, soil, and employee entry facts are critical.'],
  },
  {
    recordId: 'reg-osha-1926-501-leading-edge',
    title: 'OSHA construction fall protection leading edge or unprotected side',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.501(b)(1)',
    citationTitle: 'Unprotected sides and edges',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart M',
    hazardDomains: ['fall_protection'],
    mechanisms: ['fall_from_height'],
    applicabilityTriggers: ['leading edge', 'unprotected side', 'open edge', 'fall exposure', 'construction elevated work'],
    exclusionTriggers: ['scaffold guardrail-specific context may require 29 CFR 1926.451(g)(4)'],
    requiredControls: ['restrict access to fall exposure', 'provide guardrail or fall arrest/restraint', 'verify before work resumes'],
    correctiveActionPatterns: ['install guardrail', 'provide fall arrest or restraint', 'document competent person verification'],
    verificationEvidence: ['fall protection photo', 'competent person verification', 'corrected edge protection record'],
    evidenceQuestions: ['What is the fall distance?', 'Is this scaffold, leading edge, ladder, or other surface?', 'What protection is present?'],
    plainLanguageSummary: 'Construction employees exposed to unprotected sides or edges must be protected from falls.',
    sourceReference: '29 CFR 1926.501(b)(1)',
    boundary: bindingBoundary,
    notes: ['Needs scope-fit logic to separate scaffold and ladder standards.'],
  },
  {
    recordId: 'reg-osha-1926-451-scaffold-guardrails',
    title: 'OSHA construction scaffold guardrails',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.451(g)(4)',
    citationTitle: 'Scaffold guardrail systems',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart L',
    hazardDomains: ['scaffolds', 'fall_protection'],
    mechanisms: ['fall_from_height', 'inadequate_guardrail'],
    applicabilityTriggers: ['scaffold', 'missing guardrail', 'toprail', 'midrail', 'open side scaffold'],
    exclusionTriggers: ['non-scaffold leading edge may require 29 CFR 1926.501(b)(1)'],
    requiredControls: ['restrict scaffold use', 'install toprail and midrail', 'inspect scaffold before use'],
    correctiveActionPatterns: ['install scaffold guardrail', 'provide toprail and midrail', 'document competent person inspection'],
    verificationEvidence: ['scaffold inspection', 'photo of corrected guardrails', 'competent person verification'],
    evidenceQuestions: ['Is the work platform a scaffold?', 'Which guardrail component is missing?', 'Has a competent person inspected it?'],
    plainLanguageSummary: 'Scaffold platforms must have required fall protection such as guardrail systems when applicable.',
    sourceReference: '29 CFR 1926.451(g)(4)',
    boundary: bindingBoundary,
    notes: ['Scaffold-specific record should take precedence over general construction fall protection when scaffold terms are present.'],
  },
  {
    recordId: 'reg-osha-1926-1053-ladders',
    title: 'OSHA construction ladder access and use',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.1053(b)(1)',
    citationTitle: 'Ladder use requirements',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart X',
    hazardDomains: ['ladders', 'slips_trips_falls'],
    mechanisms: ['fall_from_ladder'],
    applicabilityTriggers: ['ladder', 'extension ladder', 'roof access', 'ladder landing', 'unsecured ladder'],
    exclusionTriggers: ['walking surface housekeeping without ladder may require another standard'],
    requiredControls: ['remove ladder from service if unsafe', 'secure ladder', 'extend ladder above landing where required'],
    correctiveActionPatterns: ['secure ladder', 'extend ladder above landing', 'verify ladder setup before use'],
    verificationEvidence: ['photo of ladder setup', 'ladder inspection', 'competent person or supervisor verification'],
    evidenceQuestions: ['What type of ladder is involved?', 'Is it secured?', 'Does it extend above the landing when used for access?'],
    plainLanguageSummary: 'Construction ladders must be set up and used safely to prevent falls.',
    sourceReference: '29 CFR 1926.1053(b)(1)',
    boundary: bindingBoundary,
    notes: ['Ladder mechanism should not be collapsed into generic slip/trip unless ladder facts are absent.'],
  },
  {
    recordId: 'reg-osha-1926-602-mobile-equipment',
    title: 'OSHA construction material handling equipment / mobile equipment',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.602(a)(9)',
    citationTitle: 'Earthmoving equipment',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart O',
    hazardDomains: ['mobile_equipment', 'traffic_control'],
    mechanisms: ['struck_by', 'pedestrian_strike'],
    applicabilityTriggers: ['backing equipment', 'backup alarm', 'spotter', 'loader', 'skid steer', 'construction mobile equipment'],
    exclusionTriggers: ['general industry powered industrial truck training may require 29 CFR 1910.178'],
    requiredControls: ['separate pedestrians', 'verify backup alarm or spotter', 'establish traffic controls'],
    correctiveActionPatterns: ['use spotter where required', 'verify backup alarm', 'define pedestrian exclusion zone'],
    verificationEvidence: ['backup alarm verification', 'spotter assignment record', 'traffic control layout'],
    evidenceQuestions: ['What mobile equipment is moving?', 'Is it backing?', 'Are pedestrians exposed?', 'What warning or visibility controls exist?'],
    plainLanguageSummary: 'Construction mobile equipment must be controlled to prevent struck-by hazards, especially backing or visibility hazards.',
    sourceReference: '29 CFR 1926.602(a)(9)',
    boundary: bindingBoundary,
    notes: ['Construction mobile equipment record must be separated from forklift/PIT standards.'],
  },
  {
    recordId: 'reg-osha-1926-1153-silica',
    title: 'OSHA construction respirable crystalline silica exposure control',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.1153(c)(1)',
    citationTitle: 'Specified exposure control methods',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart Z',
    hazardDomains: ['health_respiratory', 'health_exposure'],
    mechanisms: ['silica_inhalation'],
    applicabilityTriggers: ['silica', 'respirable crystalline silica', 'concrete dust', 'dry cutting', 'dust exposure'],
    exclusionTriggers: ['non-silica dust exposure requires separate health exposure analysis'],
    requiredControls: ['use wet methods or dust collection', 'limit employee exposure', 'verify engineering controls'],
    correctiveActionPatterns: ['use wet methods', 'use dust collection', 'control silica dust', 'document exposure control method'],
    verificationEvidence: ['exposure control method documentation', 'respiratory protection evaluation if required', 'photo/video of dust control'],
    evidenceQuestions: ['What material is being cut or disturbed?', 'Are wet methods or dust collection used?', 'Is respiratory protection required?'],
    plainLanguageSummary: 'Construction silica-generating tasks require exposure controls such as wet methods, dust collection, or other compliant controls.',
    sourceReference: '29 CFR 1926.1153(c)(1)',
    boundary: bindingBoundary,
    notes: ['Health exposure reasoning must ask for measurements or control method evidence where missing.'],
  },
  {
    recordId: 'reg-osha-1910-303-electrical-guarding',
    title: 'OSHA general industry guarding live electrical parts',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.303(g)(2)(i)',
    citationTitle: 'Guarding of live parts',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart S',
    hazardDomains: ['electrical'],
    mechanisms: ['shock', 'shock_arc_flash'],
    applicabilityTriggers: ['exposed energized wiring', 'live parts', 'unguarded electrical parts', 'junction box cover missing'],
    exclusionTriggers: ['MSHA electrical conductor issue may require 30 CFR 56.12004'],
    requiredControls: ['de-energize circuit', 'guard live parts', 'repair enclosure integrity'],
    correctiveActionPatterns: ['install junction box cover', 'guard exposed energized terminals', 'document electrical repair'],
    verificationEvidence: ['electrical repair record', 'photo of cover or enclosure', 'qualified person verification'],
    evidenceQuestions: ['Are the parts energized?', 'Can employees contact live parts?', 'Is the enclosure damaged or open?'],
    plainLanguageSummary: 'Live electrical parts must be guarded to prevent employee contact.',
    sourceReference: '29 CFR 1910.303(g)(2)(i)',
    boundary: bindingBoundary,
    notes: ['General industry electrical record. Construction and mining may require different standards.'],
  },
  {
    recordId: 'reg-osha-1910-212-machine-guarding',
    title: 'OSHA general industry point-of-operation machine guarding',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.212(a)(3)(ii)',
    citationTitle: 'Point of operation guarding',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart O',
    hazardDomains: ['machine_guarding'],
    mechanisms: ['pinch_point', 'rotating_equipment_nip_point', 'powered_door_crush_point'],
    applicabilityTriggers: ['point of operation', 'pinch point', 'machine guarding', 'unguarded press', 'caught between', 'powered overhead door', 'powered door', 'overhead door', 'dock door', 'roll-up door', 'photo-eye', 'presence sensor', 'reversing edge', 'manual release'],
    exclusionTriggers: ['LOTO during servicing may require 29 CFR 1910.147'],
    requiredControls: ['guard point of operation', 'prevent contact with pinch point', 'restrict use until guarded', 'verify powered-door safety devices and pedestrian path controls'],
    correctiveActionPatterns: ['install guard', 'guard point of operation', 'document post-correction inspection'],
    verificationEvidence: ['photo of guard', 'machine inspection record', 'guard verification before operation'],
    evidenceQuestions: ['What point of operation is exposed?', 'Can the operator contact the hazard zone?', 'Is the machine being operated or serviced?'],
    plainLanguageSummary: 'Machine points of operation must be guarded where employees could be injured.',
    sourceReference: '29 CFR 1910.212(a)(3)(ii)',
    boundary: bindingBoundary,
    notes: ['Must distinguish operating exposure from servicing/maintenance LOTO exposure.'],
  },
  {
    recordId: 'reg-osha-1910-147-loto',
    title: 'OSHA general industry control of hazardous energy',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.147(c)(1)',
    citationTitle: 'Energy control program',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart J',
    hazardDomains: ['machine_guarding_loto', 'lockout_tagout'],
    mechanisms: ['unexpected_startup', 'stored_energy_release'],
    applicabilityTriggers: ['lockout', 'tagout', 'loto', 'servicing', 'maintenance', 'unexpected startup', 'hazardous energy'],
    exclusionTriggers: ['ordinary machine operation guarding may require 29 CFR 1910.212'],
    requiredControls: ['stop servicing work', 'isolate hazardous energy', 'apply lockout/tagout', 'verify zero energy'],
    correctiveActionPatterns: ['apply lockout tagout', 'verify zero energy', 'document procedure review'],
    verificationEvidence: ['lockout/tagout record', 'zero-energy verification', 'authorized employee verification'],
    evidenceQuestions: ['Is the task servicing or maintenance?', 'What energy sources exist?', 'Was zero energy verified?'],
    plainLanguageSummary: 'Servicing or maintenance that exposes employees to hazardous energy requires an energy control program and lockout/tagout controls.',
    sourceReference: '29 CFR 1910.147(c)(1)',
    boundary: bindingBoundary,
    notes: ['LOTO records should take precedence over ordinary guarding when servicing or maintenance terms are present.'],
  },
  {
    recordId: 'reg-osha-1910-178-powered-industrial-trucks',
    title: 'OSHA general industry powered industrial truck training and safe operation',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.178(l)',
    citationTitle: 'Operator training',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart N',
    hazardDomains: ['mobile_equipment'],
    mechanisms: ['pedestrian_strike'],
    applicabilityTriggers: ['forklift', 'powered industrial truck', 'pedestrian', 'forklift traffic', 'operator training'],
    exclusionTriggers: ['construction earthmoving equipment may require 29 CFR 1926.602'],
    requiredControls: ['separate pedestrians', 'verify operator training', 'establish forklift traffic controls'],
    correctiveActionPatterns: ['define pedestrian exclusion zone', 'provide operator communication', 'document operator/pedestrian separation controls'],
    verificationEvidence: ['operator training record', 'traffic control verification', 'pedestrian separation observation'],
    evidenceQuestions: ['Is the equipment a powered industrial truck?', 'Are pedestrians exposed?', 'Is operator training/current authorization documented?'],
    plainLanguageSummary: 'Powered industrial truck operations require trained operators and controls to protect pedestrians and nearby employees.',
    sourceReference: '29 CFR 1910.178(l)',
    boundary: bindingBoundary,
    notes: ['SafeScope should not collapse forklift/pedestrian interaction into slip/trip mechanisms.'],
  },
  {
    recordId: 'reg-osha-1910-22-walking-working-surfaces',
    title: 'OSHA general industry walking-working surfaces',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.22(a)(2)',
    citationTitle: 'Walking-working surfaces',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart D',
    hazardDomains: ['slip_trip_fall', 'walking_working_surfaces'],
    mechanisms: ['slip', 'trip', 'slip_trip_fall'],
    applicabilityTriggers: ['wet floor', 'spill', 'walking surface', 'aisle', 'same-level fall', 'slip hazard'],
    exclusionTriggers: ['construction ladder or scaffold hazards require separate construction standards'],
    requiredControls: ['clean spill', 'maintain dry walking surface', 'restore clear aisle'],
    correctiveActionPatterns: ['clean spill', 'maintain walking-working surface', 'document correction'],
    verificationEvidence: ['photo of corrected surface', 'housekeeping record', 'inspection observation'],
    evidenceQuestions: ['What substance or obstruction is present?', 'Are employees walking through the area?', 'Has the surface been cleaned or dried?'],
    plainLanguageSummary: 'Walking-working surfaces must be maintained in a clean, orderly, and sanitary condition.',
    sourceReference: '29 CFR 1910.22(a)(2)',
    boundary: bindingBoundary,
    notes: ['General industry housekeeping and walking-surface record.'],
  },
  {
    recordId: 'reg-osha-1910-1200-hazcom-labeling',
    title: 'OSHA general industry hazard communication container labeling',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.1200(f)(1)',
    citationTitle: 'Labels and other forms of warning',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart Z',
    hazardDomains: ['hazardous_materials', 'hazard_communication'],
    mechanisms: ['chemical_exposure'],
    applicabilityTriggers: ['unlabeled container', 'secondary container', 'chemical container', 'hazcom', 'SDS', 'container label'],
    exclusionTriggers: ['unknown substance may require identification before applying label logic'],
    requiredControls: ['remove unlabeled container from use', 'label chemical container', 'make SDS available'],
    correctiveActionPatterns: ['label chemical container', 'identify contents and hazards', 'document hazard communication correction'],
    verificationEvidence: ['photo of corrected label', 'SDS availability verification', 'hazcom correction record'],
    evidenceQuestions: ['What chemical is in the container?', 'Is the container labeled?', 'Is the SDS available?'],
    plainLanguageSummary: 'Hazardous chemical containers must be labeled or otherwise identified with hazard communication information.',
    sourceReference: '29 CFR 1910.1200(f)(1)',
    boundary: bindingBoundary,
    notes: ['HazCom reasoning must avoid guessing chemical identity.'],
  },
  {
    recordId: 'reg-osha-1910-146-confined-space',
    title: 'OSHA general industry permit-required confined spaces',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.146(c)(1)',
    citationTitle: 'Permit-required confined space program',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart J',
    hazardDomains: ['confined_space'],
    mechanisms: ['asphyxiation'],
    applicabilityTriggers: ['confined space', 'permit required confined space', 'entry permit', 'oxygen deficiency', 'atmospheric hazard'],
    exclusionTriggers: ['construction confined spaces may require construction-specific standards'],
    requiredControls: ['stop confined space entry', 'evaluate confined space hazards', 'test atmosphere before entry', 'provide attendant and rescue provisions'],
    correctiveActionPatterns: ['implement permit-required confined space controls', 'document atmospheric testing', 'verify entry permit and attendant controls'],
    verificationEvidence: ['confined space evaluation', 'atmospheric testing record', 'entry permit', 'rescue provisions verification'],
    evidenceQuestions: ['Does the space meet confined space criteria?', 'Are atmospheric hazards present?', 'Was entry authorized under a permit system?'],
    plainLanguageSummary: 'Permit-required confined spaces must be evaluated and controlled before employee entry.',
    sourceReference: '29 CFR 1910.146(c)(1)',
    boundary: bindingBoundary,
    notes: ['Requires strong evidence-gathering before confident conclusions.'],
  },

  {
    recordId: 'reg-osha-1926-1425-clear-of-load',
    title: 'OSHA construction cranes and derricks - keeping clear of the load',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.1425',
    citationTitle: 'Keeping clear of the load',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart CC',
    hazardDomains: ['cranes_rigging_hoisting'],
    mechanisms: ['struck_by_suspended_load', 'dropped_load', 'rigging_failure', 'crane_contact'],
    applicabilityTriggers: ['suspended load', 'hoisted load', 'crane load', 'load path', 'employee under load', 'tag line', 'signal person'],
    exclusionTriggers: ['general industry sling-only findings may require 29 CFR 1910.184', 'mobile equipment struck-by hazards may require separate mobile equipment analysis'],
    requiredControls: ['keep employees clear of suspended loads', 'route loads to minimize exposure', 'establish exclusion zone', 'use qualified signal controls'],
    correctiveActionPatterns: ['stop lift', 'clear employees from load path', 'establish barricaded exclusion zone', 'verify operator and signal communication before lift resumes'],
    verificationEvidence: ['photo or observation of exclusion zone', 'lift plan or pre-lift briefing', 'signal person/operator verification'],
    evidenceQuestions: ['Was any employee under or within the fall zone of a suspended load?', 'What was the load path?', 'Were operator, signal person, tag line, and exclusion controls established?'],
    plainLanguageSummary: 'Employees must be kept clear of suspended or hoisted crane loads where they could be struck by a moving or falling load.',
    sourceReference: '29 CFR 1926.1425',
    boundary: bindingBoundary,
    notes: ['Read-only Brain record. Does not create citations or declare violations.'],
  },
  {
    recordId: 'reg-osha-1910-184-slings',
    title: 'OSHA general industry slings',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.184',
    citationTitle: 'Slings',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart N',
    hazardDomains: ['cranes_rigging_hoisting'],
    mechanisms: ['rigging_failure', 'dropped_load', 'struck_by_suspended_load'],
    applicabilityTriggers: ['damaged sling', 'wire rope sling', 'chain sling', 'synthetic sling', 'sling inspection', 'rated capacity', 'lifting strap'],
    exclusionTriggers: ['construction crane suspended-load routing may require 29 CFR 1926.1425', 'below-the-hook device may require additional specialized review'],
    requiredControls: ['remove damaged rigging from service', 'verify sling identification and rated capacity', 'inspect sling before use', 'use compatible rigging hardware'],
    correctiveActionPatterns: ['remove sling from service', 'replace damaged rigging', 'verify rated capacity and inspection status', 'document competent person review'],
    verificationEvidence: ['photo of sling condition', 'sling tag or rated capacity evidence', 'competent person inspection record'],
    evidenceQuestions: ['What type of sling or rigging is involved?', 'Is the sling damaged, missing identification, overloaded, or improperly configured?', 'Was a competent person inspection performed?'],
    plainLanguageSummary: 'Slings used for material handling must be suitable, inspected, and removed from service when damaged or defective.',
    sourceReference: '29 CFR 1910.184',
    boundary: bindingBoundary,
    notes: ['General industry sling record; construction crane operations may require additional Subpart CC analysis.'],
  },


  {
    recordId: 'reg-osha-1910-176-material-storage',
    title: 'OSHA general industry material storage',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.176(b)',
    citationTitle: 'Secure storage',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart N',
    hazardDomains: ['material_handling'],
    mechanisms: ['unstable_stack_collapse', 'falling_object_material', 'dropped_load'],
    applicabilityTriggers: ['material storage', 'stacked material', 'unstable stack', 'falling material', 'stored material', 'pallet', 'rack'],
    exclusionTriggers: ['active crane or hoisting load may require crane or rigging analysis', 'mobile equipment load movement may require powered industrial truck review'],
    requiredControls: ['secure stored material', 'stabilize stacks', 'maintain clear aisles', 'keep employees clear of falling-object path'],
    correctiveActionPatterns: ['restack unstable material', 'secure stored materials', 'remove employees from falling-object exposure', 'verify storage stability'],
    verificationEvidence: ['photo of corrected stack', 'storage area inspection record', 'supervisor verification'],
    evidenceQuestions: ['What material is stored?', 'How high is it stacked?', 'Is it stable, secured, racked, or leaning?', 'Are employees exposed to the fall path?'],
    plainLanguageSummary: 'Stored material must be stable and secure so it does not collapse, shift, or fall onto employees.',
    sourceReference: '29 CFR 1910.176(b)',
    boundary: bindingBoundary,
    notes: ['Use for stored or stacked material hazards; distinguish from crane/rigging and forklift travel hazards.'],
  },
  {
    recordId: 'reg-osha-1910-242-hand-power-tools',
    title: 'OSHA general industry hand and portable powered tools',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.242(a)',
    citationTitle: 'Condition of tools and equipment',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart P',
    hazardDomains: ['tools_equipment'],
    mechanisms: ['defective_tool_contact', 'abrasive_wheel_failure', 'tool_guarding_gap'],
    applicabilityTriggers: ['defective tool', 'damaged tool', 'power tool', 'hand tool', 'grinder', 'cutoff wheel', 'missing tool guard', 'damaged cord'],
    exclusionTriggers: ['fixed machine point-of-operation hazards may require machine guarding analysis', 'energized damaged electrical cords may require electrical analysis'],
    requiredControls: ['remove defective tools from service', 'inspect tools before use', 'restore guards', 'repair or replace damaged tools'],
    correctiveActionPatterns: ['tag tool out of service', 'replace damaged tool', 'verify tool guard and condition before reuse'],
    verificationEvidence: ['photo of tagged or repaired tool', 'tool inspection record', 'supervisor verification'],
    evidenceQuestions: ['What tool is involved?', 'What defect exists?', 'Is the tool powered, guarded, damaged, or modified?', 'Was it removed from service?'],
    plainLanguageSummary: 'Hand and portable powered tools must be maintained in safe condition and removed from service when defective.',
    sourceReference: '29 CFR 1910.242(a)',
    boundary: bindingBoundary,
    notes: ['Use for portable tools; do not confuse with fixed equipment guarding or electrical conductor findings.'],
  },
  {
    recordId: 'reg-osha-1910-157-extinguisher-access',
    title: 'OSHA general industry portable fire extinguisher access',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.157(c)(1)',
    citationTitle: 'Portable fire extinguisher access',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart L',
    hazardDomains: ['fire_protection'],
    mechanisms: ['fire_extinguisher_access_failure', 'emergency_equipment_unavailable'],
    applicabilityTriggers: ['blocked extinguisher', 'fire extinguisher blocked', 'extinguisher not accessible', 'missing extinguisher', 'expired extinguisher inspection'],
    exclusionTriggers: ['hot work ignition risk may require welding/cutting/hot work analysis', 'blocked emergency exit may require emergency preparedness analysis'],
    requiredControls: ['restore extinguisher access', 'mount and identify extinguisher', 'inspect extinguisher', 'keep path clear'],
    correctiveActionPatterns: ['clear blocked extinguisher', 'replace or inspect extinguisher', 'verify emergency equipment access'],
    verificationEvidence: ['photo of accessible extinguisher', 'inspection tag or record', 'area housekeeping verification'],
    evidenceQuestions: ['Which extinguisher or emergency equipment is affected?', 'Is access blocked?', 'Is the inspection current?', 'Is the extinguisher visible and identified?'],
    plainLanguageSummary: 'Portable fire extinguishers must be mounted, identified, and readily accessible when provided for employee use.',
    sourceReference: '29 CFR 1910.157(c)(1)',
    boundary: bindingBoundary,
    notes: ['Use for extinguisher availability/access; separate from hot work ignition-source controls.'],
  },
  {
    recordId: 'reg-osha-1910-252-hot-work-fire-watch',
    title: 'OSHA general industry welding, cutting, and brazing fire prevention',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.252(a)(2)(iii)(A)',
    citationTitle: 'Fire watchers',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart Q',
    hazardDomains: ['welding_cutting_hot_work', 'fire_protection'],
    mechanisms: ['hot_work_ignition', 'combustible_exposure_fire', 'fire_watch_gap'],
    applicabilityTriggers: ['hot work', 'welding', 'cutting', 'grinding sparks', 'combustibles nearby', 'no fire watch', 'fire watch'],
    exclusionTriggers: ['chemical flammable storage may require hazardous materials review', 'combustible dust may require specialized combustible dust review'],
    requiredControls: ['remove or shield combustibles', 'assign fire watch where required', 'verify extinguisher availability', 'control ignition sources'],
    correctiveActionPatterns: ['stop hot work until combustibles are controlled', 'assign fire watch', 'document hot work area inspection', 'verify extinguisher readiness'],
    verificationEvidence: ['hot work permit or authorization', 'fire watch documentation', 'photo of combustible clearance', 'extinguisher verification'],
    evidenceQuestions: ['What hot work is occurring?', 'What combustibles or flammables are nearby?', 'Is fire watch required and assigned?', 'Is extinguishing equipment available?'],
    plainLanguageSummary: 'Welding or cutting near combustible conditions requires fire prevention controls and fire watch where a fire could develop.',
    sourceReference: '29 CFR 1910.252(a)(2)(iii)(A)',
    boundary: bindingBoundary,
    notes: ['Hot work should outrank generic fire protection when ignition source and combustible exposure are central.'],
  },
  {
    recordId: 'reg-osha-1910-132-ppe-hazard-assessment',
    title: 'OSHA general industry PPE hazard assessment',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.132(d)(1)',
    citationTitle: 'Hazard assessment and PPE selection',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart I',
    hazardDomains: ['ppe'],
    mechanisms: ['ppe_exposure_gap', 'eye_face_ppe_gap', 'hand_ppe_gap'],
    applicabilityTriggers: ['missing ppe', 'no ppe', 'without eye protection', 'without face shield', 'without gloves', 'wrong ppe', 'damaged ppe'],
    exclusionTriggers: ['PPE-only reasoning should not replace higher-level hazard controls', 'respirator-specific issues may require respiratory protection review'],
    requiredControls: ['perform hazard assessment', 'select task-specific PPE', 'provide and require appropriate PPE', 'verify PPE condition and fit'],
    correctiveActionPatterns: ['stop task until PPE is provided', 'select PPE based on exposure', 'replace damaged PPE', 'document PPE hazard assessment'],
    verificationEvidence: ['PPE hazard assessment', 'photo or observation of correct PPE use', 'training or supervisor verification'],
    evidenceQuestions: ['What exposure requires PPE?', 'What PPE is missing or inadequate?', 'Is PPE the only control?', 'Was a hazard assessment completed?'],
    plainLanguageSummary: 'Employers must assess the workplace for hazards requiring PPE and select/provide appropriate protective equipment.',
    sourceReference: '29 CFR 1910.132(d)(1)',
    boundary: bindingBoundary,
    notes: ['PPE should be treated as exposure-specific and not as a substitute for engineering or isolation controls.'],
  },

  {
    recordId: 'reg-osha-general-duty-ergonomics-manual-handling',
    title: 'OSHA general duty / ergonomics manual handling context',
    agency: 'OSHA',
    authorityTier: 'tier_3_authoritative_guidance',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: 'General Duty / Ergonomics Guidance',
    citationTitle: 'Ergonomics and manual material handling',
    standardPart: 'Guidance',
    standardSubpart: 'Ergonomics',
    hazardDomains: ['ergonomics'],
    mechanisms: ['overexertion', 'musculoskeletal_disorder', 'strain_sprain'],
    applicabilityTriggers: ['manual lifting', 'heavy lift', 'awkward posture', 'repetitive motion', 'overexertion', 'ergonomic', 'material handling by hand'],
    exclusionTriggers: ['do not cite as a specific OSHA standard without legal review', 'powered material handling may require mobile equipment or material handling analysis'],
    requiredControls: ['reduce manual force', 'use mechanical assist', 'change work height or reach', 'rotate or redesign task'],
    correctiveActionPatterns: ['evaluate ergonomic risk factors', 'use mechanical lift assist', 'reduce weight/repetition/reach', 'verify task redesign'],
    verificationEvidence: ['photo/video of task posture', 'weight/frequency estimate', 'employee exposure duration', 'ergonomic assessment'],
    evidenceQuestions: ['What load is lifted or handled?', 'What is the weight, frequency, posture, reach, and duration?', 'Are mechanical assists or team lifts available?'],
    plainLanguageSummary: 'Ergonomic and manual-handling hazards require evaluation of force, posture, repetition, duration, and feasible task redesign or mechanical assistance.',
    sourceReference: 'OSHA/NIOSH ergonomics guidance context',
    boundary: advisoryBoundary,
    notes: ['Read-only guidance context. Do not treat as a standalone violation citation without review.'],
  },
  {
    recordId: 'reg-osha-niosh-heat-cold-environmental-exposure',
    title: 'OSHA/NIOSH heat and cold environmental exposure context',
    agency: 'OSHA',
    authorityTier: 'tier_3_authoritative_guidance',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: 'OSHA/NIOSH Heat and Cold Stress Guidance',
    citationTitle: 'Environmental heat and cold exposure',
    standardPart: 'Guidance',
    standardSubpart: 'Occupational health',
    hazardDomains: ['environmental_exposure', 'health_exposure'],
    mechanisms: ['heat_illness', 'cold_stress'],
    applicabilityTriggers: ['heat stress', 'heat illness', 'hot environment', 'wbgt', 'hydration', 'acclimatization', 'cold stress', 'hypothermia', 'frostbite'],
    exclusionTriggers: ['fire/hot work ignition hazards require hot work analysis', 'respiratory contaminants require health respiratory analysis'],
    requiredControls: ['evaluate environmental conditions', 'provide water shade or warming', 'adjust work rest cycles', 'monitor symptoms', 'plan emergency response'],
    correctiveActionPatterns: ['measure heat or cold stressors', 'implement work-rest and recovery controls', 'verify acclimatization and emergency response'],
    verificationEvidence: ['temperature/WBGT or wind chill data', 'work/rest schedule', 'hydration/warming provision', 'symptom monitoring record'],
    evidenceQuestions: ['What are the temperature, humidity, radiant heat, wind, workload, PPE burden, and exposure duration?', 'Are workers acclimatized and monitored?'],
    plainLanguageSummary: 'Heat and cold stress conclusions require environmental measurements, workload context, recovery controls, and symptom/emergency readiness evidence.',
    sourceReference: 'OSHA/NIOSH heat and cold stress guidance context',
    boundary: advisoryBoundary,
    notes: ['Guidance context supports hazard reasoning and corrective actions; specific citation decisions may require legal or qualified review.'],
  },
  {
    recordId: 'reg-osha-1910-95-occupational-noise',
    title: 'OSHA general industry occupational noise exposure',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.95',
    citationTitle: 'Occupational noise exposure',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart G',
    hazardDomains: ['health_exposure'],
    mechanisms: ['noise_induced_hearing_loss'],
    applicabilityTriggers: ['noise', 'loud area', 'decibel', 'dba', 'sound level', 'hearing protection', 'hearing conservation', 'audiogram'],
    exclusionTriggers: ['impact PPE deficiency may require PPE analysis', 'mining noise may require MSHA-specific noise analysis'],
    requiredControls: ['evaluate noise exposure', 'use feasible engineering or administrative controls', 'provide hearing protection where required', 'implement hearing conservation program where triggered'],
    correctiveActionPatterns: ['perform noise survey or dosimetry', 'control noise source', 'verify hearing protection selection and fit', 'document hearing conservation requirements'],
    verificationEvidence: ['sound level reading', 'dosimetry result', 'exposure duration', 'hearing protection verification', 'audiometric/program record'],
    evidenceQuestions: ['What equipment or task creates noise?', 'What are measured dBA or dose results?', 'How long are employees exposed?', 'What hearing protection and program controls are in place?'],
    plainLanguageSummary: 'Occupational noise findings require exposure characterization, controls, hearing protection, and hearing conservation review when action levels or limits are implicated.',
    sourceReference: '29 CFR 1910.95',
    boundary: bindingBoundary,
    notes: ['Noise findings should not rely only on subjective loudness when measurements are missing.'],
  },
  {
    recordId: 'reg-osha-1910-1030-bloodborne',
    title: 'OSHA general industry bloodborne pathogens',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.1030',
    citationTitle: 'Bloodborne pathogens',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart Z',
    hazardDomains: ['health_exposure'],
    mechanisms: ['bloodborne_pathogen_exposure'],
    applicabilityTriggers: ['blood', 'bodily fluids', 'sharps', 'contaminated needle', 'exposure control plan'],
    exclusionTriggers: [],
    requiredControls: ['implement exposure control plan', 'use sharps containers', 'provide PPE', 'vaccination'],
    correctiveActionPatterns: ['implement exposure control plan', 'provide sharps disposal', 'train personnel'],
    verificationEvidence: ['exposure control plan', 'sharps disposal documentation', 'training records'],
    evidenceQuestions: ['Are sharps or bodily fluids present?', 'Is there an exposure control plan?', 'Have employees been trained?'],
    plainLanguageSummary: 'Bloodborne pathogens require specific exposure control plans and practices to protect employees.',
    sourceReference: '29 CFR 1910.1030',
    boundary: bindingBoundary,
    notes: ['Critical health exposure record.'],
  },
  {
    recordId: 'reg-osha-1926-501c-falling-objects',
    title: 'OSHA construction protection from falling objects',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.501(c)',
    citationTitle: 'Protection from falling objects',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart M',
    hazardDomains: ['struck_by' as any],
    mechanisms: ['struck_by_falling_object'],
    applicabilityTriggers: ['falling object', 'overhead work', 'toe board', 'toeboard', 'barricade', 'dropped object', 'tools overhead', 'materials overhead'],
    exclusionTriggers: [],
    requiredControls: ['barricade lower level', 'install toe boards', 'secure tools and materials', 'control dropped-object exposure'],
    correctiveActionPatterns: ['barricade affected area', 'install falling object protection', 'secure overhead materials'],
    verificationEvidence: ['barricade photo', 'toe board verification', 'tool tethering or material control evidence'],
    evidenceQuestions: ['Are employees exposed below overhead work?', 'Are toe boards, screens, canopies, or barricades in place?', 'Are tools and materials secured from falling?'],
    plainLanguageSummary: 'Construction employees exposed to falling objects from overhead work require protective controls such as toe boards, screens, canopies, barricades, or secured materials.',
    sourceReference: '29 CFR 1926.501(c)',
    boundary: bindingBoundary,
    notes: ['Use for construction overhead dropped-object exposures, not general elevated fall exposure.'],
  },
  {
    recordId: 'reg-osha-1910-1200-hazcom-general',
    title: 'OSHA general industry hazard communication',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.1200',
    citationTitle: 'Hazard communication',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart Z',
    hazardDomains: ['hazcom' as any, 'hazard_communication' as any, 'hazardous_materials'],
    mechanisms: ['chemical_exposure'],
    applicabilityTriggers: ['hazcom', 'chemical storage', 'incompatible chemical', 'SDS', 'safety data sheet', 'chemical label', 'secondary containment', 'segregation'],
    exclusionTriggers: [],
    requiredControls: ['segregate incompatible chemicals', 'maintain labels', 'maintain SDS access', 'provide employee training'],
    correctiveActionPatterns: ['segregate chemicals', 'label containers', 'verify SDS access', 'train exposed employees'],
    verificationEvidence: ['chemical labels', 'SDS inventory', 'storage segregation photo', 'training records'],
    evidenceQuestions: ['Are chemicals labeled?', 'Are SDSs available?', 'Are incompatible chemicals segregated?', 'Is secondary containment needed?'],
    plainLanguageSummary: 'Hazard communication requires chemical identity, hazard information, SDS access, labeling, and employee training for hazardous chemicals.',
    sourceReference: '29 CFR 1910.1200',
    boundary: bindingBoundary,
    notes: ['General HazCom record for benchmark-level chemical storage and labeling reasoning.'],
  },
  {
    recordId: 'reg-osha-1910-151c-eyewash',
    title: 'OSHA general industry emergency eyewash and shower facilities',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.151(c)',
    citationTitle: 'Medical services and first aid - corrosive materials',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart K',
    hazardDomains: ['emergency_preparedness'],
    mechanisms: ['emergency_equipment_access_failure'],
    applicabilityTriggers: ['eyewash', 'emergency shower', 'corrosive', 'caustic', 'blocked eyewash', 'chemical splash', 'quick drenching'],
    exclusionTriggers: [],
    requiredControls: ['clear access to eyewash', 'verify corrosive exposure', 'inspect emergency equipment', 'train employees'],
    correctiveActionPatterns: ['clear eyewash access', 'inspect eyewash station', 'verify quick access from corrosive use area'],
    verificationEvidence: ['eyewash access photo', 'inspection tag', 'chemical inventory showing corrosives'],
    evidenceQuestions: ['Are corrosive materials used?', 'Can employees reach eyewash quickly?', 'Is the eyewash inspected and unobstructed?'],
    plainLanguageSummary: 'Where employees may be exposed to injurious corrosive materials, suitable quick-drenching or flushing facilities must be available for immediate emergency use.',
    sourceReference: '29 CFR 1910.151(c)',
    boundary: bindingBoundary,
    notes: ['Use for blocked or unavailable eyewash near corrosive exposure.'],
  },
  {
    recordId: 'reg-osha-1910-101b-compressed-gas',
    title: 'OSHA general industry compressed gas cylinder handling',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.101(b)',
    citationTitle: 'Compressed gases - in-plant handling, storage, and utilization',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart H',
    hazardDomains: ['material_handling'],
    mechanisms: ['compressed_gas_cylinder_release'],
    applicabilityTriggers: ['compressed gas cylinder', 'gas cylinder', 'cylinder valve cap', 'unsecured cylinder', 'cylinder restraint', 'oxygen cylinder', 'fuel gas cylinder'],
    exclusionTriggers: [],
    requiredControls: ['secure cylinders upright', 'protect valves', 'separate incompatible cylinders', 'inspect storage'],
    correctiveActionPatterns: ['chain or restrain cylinders', 'install valve caps', 'segregate cylinders', 'verify storage condition'],
    verificationEvidence: ['cylinder restraint photo', 'valve cap verification', 'storage inspection'],
    evidenceQuestions: ['Are cylinders secured?', 'Are valve caps installed where required?', 'Are cylinders protected from damage?'],
    plainLanguageSummary: 'Compressed gas cylinders must be handled, stored, and used in a manner that prevents damage, release, or struck-by hazards.',
    sourceReference: '29 CFR 1910.101(b)',
    boundary: bindingBoundary,
    notes: ['Use for unsecured compressed gas cylinders and missing valve protection.'],
  },
  {
    recordId: 'reg-osha-1910-253b2ii-cylinder-separation',
    title: 'OSHA general industry oxygen and fuel gas cylinder separation',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.253(b)(2)(ii)',
    citationTitle: 'Oxygen-fuel gas welding and cutting - cylinder storage',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart Q',
    hazardDomains: ['welding_cutting_hot_work'],
    mechanisms: ['fire_explosion'],
    applicabilityTriggers: ['oxygen cylinder', 'fuel gas cylinder', 'welding cylinder', 'acetylene', 'stored together', 'cylinder separation', 'hot work'],
    exclusionTriggers: [],
    requiredControls: ['separate oxygen and fuel gas cylinders', 'protect valves', 'control ignition sources', 'verify fire prevention controls'],
    correctiveActionPatterns: ['separate cylinders', 'protect valves', 'remove from hot work exposure', 'verify compliant storage'],
    verificationEvidence: ['cylinder storage photo', 'separation distance or barrier verification', 'valve protection evidence'],
    evidenceQuestions: ['Are oxygen and fuel gas cylinders separated?', 'Are valves protected?', 'Are cylinders near ignition or hot work exposure?'],
    plainLanguageSummary: 'Oxygen cylinders in storage must be separated from fuel-gas cylinders or combustible materials by distance or a noncombustible barrier.',
    sourceReference: '29 CFR 1910.253(b)(2)(ii)',
    boundary: bindingBoundary,
    notes: ['Use for oxygen/fuel gas cylinder storage and hot work fire/explosion exposure.'],
  },
  {
    recordId: 'reg-msha-57-8520-ventilation',
    title: 'MSHA underground metal/nonmetal ventilation',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha_metal_nonmetal_underground' as any,
    industryScope: 'mining',
    mineScope: 'underground' as any,
    citation: '30 CFR 57.8520',
    citationTitle: 'Ventilation plan and controls',
    standardPart: '30 CFR Part 57',
    standardSubpart: 'Subpart G',
    hazardDomains: ['ventilation'],
    mechanisms: ['air_quality_contaminant_buildup'],
    applicabilityTriggers: ['underground ventilation', 'ventilation tubing', 'reduced airflow', 'air quality', 'contaminant buildup', 'damaged ventilation'],
    exclusionTriggers: ['coal mine methane'],
    requiredControls: ['restore ventilation', 'verify airflow', 'monitor air quality', 'restrict affected work area'],
    correctiveActionPatterns: ['repair ventilation tubing', 'verify airflow', 'document air quality checks'],
    verificationEvidence: ['airflow reading', 'ventilation repair photo', 'air quality monitoring record'],
    evidenceQuestions: ['What ventilation control is damaged?', 'Is airflow reaching the working area?', 'Are contaminants or poor air quality possible?'],
    plainLanguageSummary: 'Underground metal/nonmetal mine workings require effective ventilation to control air quality and contaminant exposure.',
    sourceReference: '30 CFR 57.8520',
    boundary: bindingBoundary,
    notes: ['Use for underground MNM ventilation deficiencies; do not route to coal methane ventilation records.'],
  },
  {
    recordId: 'reg-msha-75-517-trailing-cable',
    title: 'MSHA underground coal trailing cable protection',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha_coal_underground' as any,
    industryScope: 'mining',
    mineScope: 'underground' as any,
    citation: '30 CFR 75.517',
    citationTitle: 'Power wires and cables; insulation and protection',
    standardPart: '30 CFR Part 75',
    standardSubpart: 'Subpart F',
    hazardDomains: ['electrical'],
    mechanisms: ['shock_arc_flash'],
    applicabilityTriggers: ['trailing cable', 'coal trailing cable', 'damaged cable', 'jacket damage', 'power cable', 'mobile equipment cable'],
    exclusionTriggers: ['metal nonmetal'],
    requiredControls: ['remove damaged cable from service', 'repair by qualified person', 'inspect cable protection', 'verify insulation integrity'],
    correctiveActionPatterns: ['remove cable from service', 'repair trailing cable', 'qualified electrical inspection'],
    verificationEvidence: ['cable inspection record', 'repair record', 'qualified electrician verification'],
    evidenceQuestions: ['Is the cable energized or used for mobile equipment?', 'Is insulation damaged?', 'Has a qualified person inspected or repaired it?'],
    plainLanguageSummary: 'Underground coal power wires and cables must be insulated and protected from mechanical damage to prevent shock and arc-flash exposure.',
    sourceReference: '30 CFR 75.517',
    boundary: bindingBoundary,
    notes: ['Use for underground coal trailing cable damage, not surface MNM electrical cable cases.'],
  },
  {
    recordId: 'reg-msha-56-5001-dust-exposure',
    title: 'MSHA surface metal/nonmetal airborne contaminant exposure',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha_metal_nonmetal_surface' as any,
    industryScope: 'mining',
    mineScope: 'surface' as any,
    citation: '30 CFR 56.5001',
    citationTitle: 'Exposure limits for airborne contaminants',
    standardPart: '30 CFR Part 56',
    standardSubpart: 'Subpart D',
    hazardDomains: ['health_exposure', 'health_respiratory'],
    mechanisms: ['silica_inhalation'],
    applicabilityTriggers: ['crusher dust', 'visible dust', 'silica', 'respirable dust', 'water spray', 'airborne contaminant', 'dust exposure'],
    exclusionTriggers: ['construction concrete cutting'],
    requiredControls: ['restore dust controls', 'sample exposure', 'use respiratory protection when required', 'verify water spray operation'],
    correctiveActionPatterns: ['repair water sprays', 'conduct exposure sampling', 'control crusher dust'],
    verificationEvidence: ['dust control inspection', 'sampling record', 'water spray verification'],
    evidenceQuestions: ['What dust source is present?', 'Are water sprays or ventilation working?', 'Has exposure sampling been performed?'],
    plainLanguageSummary: 'Surface metal/nonmetal mines must control airborne contaminant exposure, including respirable dust and silica exposure.',
    sourceReference: '30 CFR 56.5001',
    boundary: bindingBoundary,
    notes: ['Use for surface MNM crusher dust/silica exposure.'],
  },
  {
    recordId: 'reg-osha-1926-1052c1-stairway-handrails',
    title: 'OSHA construction stairway handrails',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.1052(c)(1)',
    citationTitle: 'Stairways - handrails',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart X',
    hazardDomains: ['slips_trips_falls'],
    mechanisms: ['fall_on_stairway'],
    applicabilityTriggers: ['temporary stairway', 'stairway', 'stairs', 'missing handrail', 'open side', 'construction access'],
    exclusionTriggers: [],
    requiredControls: ['install handrail', 'restrict access until corrected', 'inspect stairway', 'verify compliant access'],
    correctiveActionPatterns: ['install stairway handrail', 'control access', 'inspect temporary stairway'],
    verificationEvidence: ['handrail installation photo', 'stairway inspection record', 'access control evidence'],
    evidenceQuestions: ['Is the stairway used for construction access?', 'Is a handrail missing?', 'Are workers carrying materials on the stairway?'],
    plainLanguageSummary: 'Construction stairways generally require stair rails or handrails to reduce fall exposure during access between levels.',
    sourceReference: '29 CFR 1926.1052(c)(1)',
    boundary: bindingBoundary,
    notes: ['Use for temporary stairway missing handrail; distinguish from Subpart M leading-edge fall protection.'],
  },
  {
    recordId: 'reg-osha-1926-150-fire-fighting',
    title: 'OSHA construction fire fighting equipment',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.150(a)(1)',
    citationTitle: 'Fire protection',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart F',
    hazardDomains: ['fire_protection'],
    mechanisms: ['fire_or_explosion'],
    applicabilityTriggers: ['fire fighting equipment', 'extinguisher', 'fire protection program'],
    exclusionTriggers: ['general industry fire protection requires 1910.157'],
    requiredControls: ['provide fire fighting equipment', 'maintain fire protection program'],
    correctiveActionPatterns: ['provide extinguisher', 'inspect extinguisher access'],
    verificationEvidence: ['photo of extinguisher', 'inspection tag record'],
    evidenceQuestions: ['Is fire fighting equipment provided?', 'Is access clear?'],
    plainLanguageSummary: 'The employer must provide fire fighting equipment in accordance with this subpart.',
    sourceReference: '29 CFR 1926.150(a)(1)',
    boundary: bindingBoundary,
    notes: [],
  },
  {
    recordId: 'reg-osha-1926-451-scaffold-fall-protection',
    title: 'OSHA construction scaffold fall protection',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.451(g)(1)',
    citationTitle: 'Scaffolds - Fall protection',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart L',
    hazardDomains: ['scaffolds', 'fall_protection'],
    mechanisms: ['fall_from_elevation'],
    applicabilityTriggers: ['scaffold fall protection', 'scaffold guardrail', 'scaffold platform'],
    exclusionTriggers: [],
    requiredControls: ['provide fall protection on scaffolds', 'install guardrails'],
    correctiveActionPatterns: ['install scaffold guardrails', 'use personal fall arrest system'],
    verificationEvidence: ['photo of scaffold guardrail', 'fall arrest inspection record'],
    evidenceQuestions: ['Are guardrails installed on the scaffold?', 'What is the fall height?'],
    plainLanguageSummary: 'Each employee on a scaffold more than 10 feet above a lower level shall be protected from falling.',
    sourceReference: '29 CFR 1926.451(g)(1)',
    boundary: bindingBoundary,
    notes: [],
  },
  {
    recordId: 'reg-msha-56-4201-fire-fighting-equipment',
    title: 'MSHA metal/nonmetal fire fighting equipment',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'metal_nonmetal_surface',
    citation: '30 CFR 56.4201',
    citationTitle: 'Fire fighting equipment',
    standardPart: '30 CFR Part 56',
    standardSubpart: 'Subpart C',
    hazardDomains: ['fire_protection'],
    mechanisms: ['fire_or_explosion'],
    applicabilityTriggers: ['fire fighting equipment', 'extinguisher monthly inspection', 'fire extinguisher capacity'],
    exclusionTriggers: [],
    requiredControls: ['inspect fire extinguishers monthly', 'maintain fire fighting equipment'],
    correctiveActionPatterns: ['perform monthly extinguisher inspection', 'verify inspection tag'],
    verificationEvidence: ['photo of monthly inspection tag', 'fire extinguisher inspection log'],
    evidenceQuestions: ['Has the fire extinguisher been inspected within the last 30 days?', 'Is the extinguisher fully charged?'],
    plainLanguageSummary: 'Fire fighting equipment must be inspected monthly and maintained in operative condition.',
    sourceReference: '30 CFR 56.4201',
    boundary: bindingBoundary,
    notes: [],
  },
  {
    recordId: 'reg-osha-1910-1000-air-contaminants',
    title: 'OSHA general industry air contaminants',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.1000',
    citationTitle: 'Air contaminants',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart Z',
    hazardDomains: ['industrial_hygiene', 'health_exposure'],
    mechanisms: ['airborne_exposure'],
    applicabilityTriggers: ['air contaminants', 'permissible exposure limit', 'pel exceedance', 'toxic dust or fumes'],
    exclusionTriggers: [],
    requiredControls: ['comply with permissible exposure limits', 'implement engineering controls', 'use respirators pending engineering controls'],
    correctiveActionPatterns: ['perform personal exposure monitoring', 'install ventilation controls', 'provide respirator'],
    verificationEvidence: ['exposure sampling report', 'ventilation performance record', 'respiratory protection documentation'],
    evidenceQuestions: ['What air contaminant is present?', 'Are exposure levels above the PEL?', 'What engineering controls are used?'],
    plainLanguageSummary: 'An employee\'s exposure to any substance in Table Z-1, Z-2, or Z-3 shall not exceed the specified limits.',
    sourceReference: '29 CFR 1910.1000',
    boundary: bindingBoundary,
    notes: [],
  },
  {
    recordId: 'reg-msha-56-16007-rigging-hooks',
    title: 'MSHA metal/nonmetal rigging hooks',
    agency: 'MSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'msha',
    industryScope: 'mining',
    mineScope: 'metal_nonmetal_surface',
    citation: '30 CFR 56.16007',
    citationTitle: 'Taglines, ropes, and chains',
    standardPart: '30 CFR Part 56',
    standardSubpart: 'Subpart O',
    hazardDomains: ['cranes_rigging_hoisting'],
    mechanisms: ['struck_by_suspended_load'],
    applicabilityTriggers: ['hoisting hooks', 'rigging hook safety latch', 'load hook latch missing'],
    exclusionTriggers: [],
    requiredControls: ['equip hoisting hooks with safety latches', 'prevent ropes/chains from slipping'],
    correctiveActionPatterns: ['install safety latch on hook', 'remove damaged hook from service', 'replace hook with latched hook'],
    verificationEvidence: ['photo of hoisting hook with active safety latch', 'rigging inspection record'],
    evidenceQuestions: ['Is the hoisting hook equipped with an active safety latch?', 'Is there a risk of the load slipping from the hook?'],
    plainLanguageSummary: 'Hoisting hooks must be equipped with safety latches or other device to prevent load lines or chains from slipping.',
    sourceReference: '30 CFR 56.16007',
    boundary: bindingBoundary,
    notes: [],
  },
  {
    recordId: 'reg-osha-1926-651-excavation-access-egress',
    title: 'OSHA construction excavation access and egress',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.651(c)(2)',
    citationTitle: 'Access and egress',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart P',
    hazardDomains: ['excavation_trenching'],
    mechanisms: ['excavation_cave_in_or_entrapment'],
    applicabilityTriggers: ['trench access', 'excavation ladder', 'trench ramp', 'lateral travel egress', 'excavation egress'],
    exclusionTriggers: [],
    requiredControls: ['provide stairway ladder or ramp in excavation 4ft or deeper', 'locate egress within 25ft of lateral travel', 'verify egress stability and safety'],
    correctiveActionPatterns: ['provide safe means of egress in excavation', 're-locate ladder or ramp to limit lateral travel to 25ft', 'verify competent-person ramp structural approval'],
    verificationEvidence: ['photo of stairway ladder or ramp in trench', 'lateral distance measurement', 'competent person design approval record'],
    evidenceQuestions: ['Is the excavation 4 feet or more in depth?', 'Is a stairway, ladder, ramp, or other safe egress present?', 'Do employees have to travel more than 25 feet laterally to reach safe egress?', 'Is the egress located within the protective shoring system boundaries?'],
    plainLanguageSummary: 'A stairway, ladder, ramp or other safe means of egress shall be located in trench excavations that are 4 feet or more in depth so as to require no more than 25 feet of lateral travel by employees.',
    sourceReference: '29 CFR 1926.651(c)(2)',
    boundary: bindingBoundary,
    notes: ['Advisory-only. Do not declare a violation. Hold for evidence if trench entry exposure is unknown.'],
  },
  {
    recordId: 'reg-osha-1910-303-working-space',
    title: 'OSHA general industry electrical working space clearance',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.303(g)(1)',
    citationTitle: 'Working space around electrical equipment',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart S',
    hazardDomains: ['electrical'],
    mechanisms: ['energized_contact'],
    applicabilityTriggers: ['blocked panel', 'panel blocked', 'blocked access', 'working space electrical', 'obstructed electrical panel', 'pallets blocking panel', 'stored boxes electrical'],
    exclusionTriggers: ['exposed live parts require 1910.303(g)(2)(i)', 'MSHA clearance requires 30 CFR 56.12004'],
    requiredControls: ['maintain 3ft clear working space in front of panels', 'remove stored boxes or obstructions', 'keep area clean'],
    correctiveActionPatterns: ['remove obstructions in front of electrical panel', 'clear 3ft working space clearance', 're-locate storage'],
    verificationEvidence: ['photo of cleared working space in front of panel', 'clearance measurement'],
    evidenceQuestions: ['Is there at least 3 feet of clear working space in front of the electrical panel?', 'Is panel door closed and undamaged?', 'Are stored items or obstructions blocking access?'],
    plainLanguageSummary: 'Sufficient access and working space shall be provided and maintained about all electric equipment to permit ready and safe operation and maintenance of such equipment.',
    sourceReference: '29 CFR 1910.303(g)(1)',
    boundary: bindingBoundary,
    notes: ['Advisory-only. Do not declare a violation. Conflate blocked access with exposed live parts.'],
  },
  {
    recordId: 'reg-osha-1910-305-dead-front',
    title: 'OSHA general industry dead-front enclosure integrity',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.305(b)(1)',
    citationTitle: 'Cabinet box opening and dead-front covers',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart S',
    hazardDomains: ['electrical'],
    mechanisms: ['shock', 'shock_arc_flash'],
    applicabilityTriggers: ['missing dead-front', 'missing dead front', 'exposed live parts', 'inner cover missing', 'uncovered electrical panel', 'exposed busbars'],
    exclusionTriggers: ['closed panels require 1910.303(g)(1) working space instead'],
    requiredControls: ['install dead-front covers inside panel', 'enclose live terminals', 'close open knockouts'],
    correctiveActionPatterns: ['install missing dead-front cover', 'seal open cabinet knockouts', 'secure panel inner cover'],
    verificationEvidence: ['photo of installed dead-front cover', 'repair record by qualified electrician'],
    evidenceQuestions: ['Is the dead-front inner metal cover missing inside the open cabinet?', 'Are live terminals or busbars exposed?', 'Is the panel de-energized or locked out?'],
    plainLanguageSummary: 'Conductors entering boxes, cabinets, or fittings shall be protected from abrasion, and openings through which conductors enter shall be effectively closed.',
    sourceReference: '29 CFR 1910.305(b)(1)',
    boundary: bindingBoundary,
    notes: ['Enforce hold for evidence if energized status is unconfirmed.'],
  },
  {
    recordId: 'reg-osha-1910-333-energized-practices',
    title: 'OSHA general industry safety work practices for energized circuits',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.333',
    citationTitle: 'Selection and use of work practices',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart S',
    hazardDomains: ['electrical'],
    mechanisms: ['shock', 'shock_arc_flash', 'energized_contact'],
    applicabilityTriggers: ['energized troubleshooting', 'voltage testing', 'working on live parts', 'hot work permit electrical', 'qualified person electrical'],
    exclusionTriggers: [],
    requiredControls: ['de-energize circuits before working unless infeasible', 'use qualified persons wearing NFPA 70E PPE', 'implement energized hot work permit system'],
    correctiveActionPatterns: ['implement electrical safety work practices', 'utilize qualified electrician wearing certified Category PPE', 'obtain electrical hot work permit'],
    verificationEvidence: ['electrical hot work permit', 'PPE inspection record', 'qualified person electrical certificate'],
    evidenceQuestions: ['Is the electrical task performed by a qualified electrical person?', 'Are they wearing NFPA 70E-aligned PPE?', 'Has a hot work permit been authorized?'],
    plainLanguageSummary: 'Safety-related work practices shall be employed to prevent electric shock or other injuries resulting from either direct or indirect electrical contacts.',
    sourceReference: '29 CFR 1910.333',
    boundary: bindingBoundary,
    notes: ['Do not over-prescribe controls beyond available evidence. Require qualified review.'],
  },
  {
    recordId: 'reg-osha-1926-404-temporary-gfci',
    title: 'OSHA construction temporary wiring ground-fault protection',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_construction',
    industryScope: 'construction',
    mineScope: 'not_applicable',
    citation: '29 CFR 1926.404(b)(1)(ii)',
    citationTitle: 'Ground-fault circuit interrupters',
    standardPart: '29 CFR Part 1926',
    standardSubpart: 'Subpart K',
    hazardDomains: ['electrical'],
    mechanisms: ['ground_fault_shock_pathway', 'shock'],
    applicabilityTriggers: ['temporary construction power', 'missing gfci', 'outdoor extension cord', 'generator outlets', 'gfci missing', 'no ground fault protection'],
    exclusionTriggers: ['general industry electrical requires 1910.303 or 1910.305'],
    requiredControls: ['use ground-fault circuit interrupters on temporary outlets', 'implement assured equipment grounding conductor program'],
    correctiveActionPatterns: ['provide ground-fault circuit interrupter (GFCI) protection', 'implement assured grounding test program', 'verify GFCI reset button function'],
    verificationEvidence: ['photo of plug-in GFCI device', 'assured equipment grounding test log', 'photo of GFCI breaker'],
    evidenceQuestions: ['Are temporary outlets protected by ground-fault circuit interrupters (GFCI)?', 'Is an assured equipment grounding conductor program implemented instead?', 'Are extension cords in wet locations?'],
    plainLanguageSummary: 'All 120-volt, single-phase, 15- and 20-ampere receptacle outlets on construction sites, which are not a part of the permanent wiring, shall have ground-fault circuit interrupter protection.',
    sourceReference: '29 CFR 1926.404(b)(1)(ii)',
    boundary: bindingBoundary,
    notes: ['Enforce construction temporary power constraints. Do not overclaim when shoring or scaffolding rules apply.'],
  },
  {
    recordId: 'reg-osha-1910-305-flexible-cords',
    title: 'OSHA general industry flexible cords and cables uses',
    agency: 'OSHA',
    authorityTier: 'tier_1_binding_regulation',
    verificationStatus: 'approved_for_read_only_context',
    jurisdiction: 'osha_general_industry',
    industryScope: 'general_industry',
    mineScope: 'not_applicable',
    citation: '29 CFR 1910.305(g)(1)(iii)',
    citationTitle: 'Prohibited uses of flexible cords and cables',
    standardPart: '29 CFR Part 1910',
    standardSubpart: 'Subpart S',
    hazardDomains: ['electrical'],
    mechanisms: ['damaged_conductor_exposure', 'shock'],
    applicabilityTriggers: ['flexible cords', 'extension cords', 'power cords', 'running through walls', 'substitute for fixed wiring', 'flexible cord damage'],
    exclusionTriggers: ['construction temporary power requires 1926.404'],
    requiredControls: ['do not use flexible cords as substitute for fixed wiring', 'protect flexible cords from damage', 'remove damaged cords from service'],
    correctiveActionPatterns: ['replace damaged flexible cord', 'install permanent fixed wiring', 'remove flexible cord from prohibited use'],
    verificationEvidence: ['photo of removed flexible cord', 'photo of installed fixed conduit and receptacle'],
    evidenceQuestions: ['Is the flexible cord being used as a substitute for fixed wiring?', 'Is the flexible cord run through walls, ceilings, floors, doorways, or windows?', 'Is the cord insulation damaged or frayed?'],
    plainLanguageSummary: 'Flexible cords and cables may not be used as a substitute for the fixed wiring of a structure; run through holes in walls, ceilings, or floors; run through doorways, windows, or similar openings; or attached to building surfaces.',
    sourceReference: '29 CFR 1910.305(g)(1)(iii)',
    boundary: bindingBoundary,
    notes: ['Enforce general industry constraints. Do not over-prescribe controls beyond available evidence.'],
  },

];
