import { HazardDefinition } from './hazard-universe.types';

export const HAZARD_UNIVERSE_REGISTRY: HazardDefinition[] = [
  {
    hazardFamily: 'machine_guarding',
    displayName: 'Machine Guarding',
    hazardType: 'acute_safety',
    hazardSubtypes: ['rotating_parts', 'nip_points', 'flying_chips', 'sparks'],
    mechanismOfHarm: ['entanglement', 'crushing', 'amputation', 'struck_by'],
    hazardousEnergyOrAgent: ['mechanical_rotation', 'mechanical_reciprocation'],
    exposurePathways: ['reach_in', 'reach_over', 'reach_under', 'reach_through'],
    commonFieldIndicators: ['missing_guard', 'exposed_coupling', 'unguarded_pulley'],
    commonControlFailures: ['missing_guard', 'interlock_bypass', 'poor_maintenance'],
    preferredControlFamilies: ['engineering_enclosure', 'interlocked_barrier'],
    weakOrInsufficientControls: ['warning_signs_only', 'training_only', 'ppe_only'],
    evidenceNeeded: ['guarding_status', 'distance_from_hazard', 'opening_size'],
    relatedJurisdictions: ['osha_general', 'msha_mnm', 'osha_construction'],
    relatedStandardFamilies: ['machine_guarding'],
    correctiveActionPrinciples: ['enclosure', 'physical_barrier', 'interlock'],
    verificationEvidence: ['photo_of_installed_guard', 'interlock_test_log'],
    mandatoryReviewTriggers: ['complex_interaction', 'custom_equipment'],
    antiRegurgitationGuidance: 'Do not recommend retraining or signs as a primary fix for missing physical guards.'
  },
  {
    hazardFamily: 'lockout_tagout',
    displayName: 'Lockout/Tagout (LOTO)',
    hazardType: 'acute_safety',
    hazardSubtypes: ['unexpected_startup', 'stored_energy_release'],
    mechanismOfHarm: ['crushing', 'electrocution', 'burn', 'entrapment'],
    hazardousEnergyOrAgent: ['electrical', 'hydraulic', 'pneumatic', 'kinetic', 'potential', 'thermal', 'chemical'],
    exposurePathways: ['body_in_machine', 'hands_in_point_of_operation'],
    commonFieldIndicators: ['maintenance_without_locks', 'missing_tags', 'unverified_isolation'],
    commonControlFailures: ['failure_to_isolate', 'failure_to_verify_zero_energy', 'failure_to_lock'],
    preferredControlFamilies: ['energy_isolation_physical_lock'],
    weakOrInsufficientControls: ['tag_only', 'push_button_stop', 'verbal_agreement'],
    evidenceNeeded: ['isolation_point_status', 'lock_application', 'verification_method'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['lockout_tagout'],
    correctiveActionPrinciples: ['zero_energy_verification', 'one_person_one_lock'],
    verificationEvidence: ['lock_photo', 'zero_energy_verification_log'],
    mandatoryReviewTriggers: ['multiple_energy_sources', 'group_lockout'],
    antiRegurgitationGuidance: 'Do not accept "follow procedure" as a fix for a specific missing lock.'
  },
  {
    hazardFamily: 'electrical',
    displayName: 'Electrical Safety',
    hazardType: 'acute_safety',
    hazardSubtypes: ['energized_parts', 'arc_flash', 'ground_fault'],
    mechanismOfHarm: ['shock', 'electrocution', 'burn', 'blast_injury'],
    hazardousEnergyOrAgent: ['electrical'],
    exposurePathways: ['direct_contact', 'indirect_contact', 'approach_boundary'],
    commonFieldIndicators: ['exposed_wiring', 'missing_covers', 'improper_grounding'],
    commonControlFailures: ['exposed_wiring', 'missing_covers', 'improper_grounding'],
    preferredControlFamilies: ['enclosure', 'insulation', 'gfci'],
    weakOrInsufficientControls: ['tape_repair', 'verbal_warning'],
    evidenceNeeded: ['voltage_level', 'enclosure_integrity', 'grounding_status'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['electrical_safety'],
    correctiveActionPrinciples: ['insulate', 'guard', 'ground', 'disconnect'],
    verificationEvidence: ['photo_of_cover_installed', 'continuity_test_result'],
    mandatoryReviewTriggers: ['high_voltage', 'wet_locations'],
    antiRegurgitationGuidance: 'Do not recommend PPE (gloves) as primary fix for exposed live conductors.'
  },
  {
    hazardFamily: 'fall_protection',
    displayName: 'Fall Protection',
    hazardType: 'acute_safety',
    hazardSubtypes: ['elevated_work', 'open_edge', 'floor_hole', 'ladder_safety'],
    mechanismOfHarm: ['fall_to_lower_level'],
    hazardousEnergyOrAgent: ['gravity'],
    exposurePathways: ['unprotected_edge', 'unstable_surface'],
    commonFieldIndicators: ['missing_guardrail', 'improper_harness_use', 'no_anchor_point'],
    commonControlFailures: ['missing_guardrail', 'improper_harness_use', 'no_anchor_point'],
    preferredControlFamilies: ['passive_fall_protection', 'guardrails', 'hole_covers'],
    weakOrInsufficientControls: ['warning_line_only', 'safety_monitor_only'],
    evidenceNeeded: ['fall_height', 'edge_protection_status', 'harness_condition'],
    relatedJurisdictions: ['osha_construction', 'osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['fall_protection'],
    correctiveActionPrinciples: ['eliminate_hazard', 'prevent_fall', 'arrest_fall'],
    verificationEvidence: ['photo_of_guardrail', 'anchor_point_inspection'],
    mandatoryReviewTriggers: ['complex_rigging', 'unusual_heights'],
    antiRegurgitationGuidance: 'Do not recommend "be careful" for work above regulatory fall heights.'
  },
  {
    hazardFamily: 'walking_working_surfaces',
    displayName: 'Walking-Working Surfaces',
    hazardType: 'acute_safety',
    hazardSubtypes: ['floor_holes', 'slick_surfaces', 'uneven_ground'],
    mechanismOfHarm: ['slips', 'trips', 'falls', 'structural_collapse'],
    hazardousEnergyOrAgent: ['gravity', 'kinetic_human_motion'],
    exposurePathways: ['walking_path', 'work_area_floor'],
    commonFieldIndicators: ['ice', 'oil_spill', 'loose_cables', 'unprotected_hole'],
    commonControlFailures: ['poor_housekeeping', 'missing_covers', 'failed_drainage'],
    preferredControlFamilies: ['engineering_drainage', 'fixed_covers', 'non_slip_surfaces'],
    weakOrInsufficientControls: ['caution_tape_only', 'verbal_instruction'],
    evidenceNeeded: ['surface_condition', 'lighting_levels', 'hole_dimensions'],
    relatedJurisdictions: ['osha_general', 'osha_construction'],
    relatedStandardFamilies: ['walking_working_surfaces'],
    correctiveActionPrinciples: ['clear_path', 'cover_holes', 'dry_surfaces'],
    verificationEvidence: ['photo_of_cleared_area', 'inspection_log'],
    mandatoryReviewTriggers: ['uncovered_floor_holes', 'structural_loading_concerns'],
    antiRegurgitationGuidance: 'Do not recommend "watch your step" as primary fix for floor holes.'
  },
  {
    hazardFamily: 'mobile_equipment',
    displayName: 'Mobile Equipment',
    hazardType: 'acute_safety',
    hazardSubtypes: ['powered_industrial_trucks', 'earth_moving_equipment', 'haul_trucks'],
    mechanismOfHarm: ['struck_by', 'caught_between', 'rollover'],
    hazardousEnergyOrAgent: ['kinetic_mobile_equipment'],
    exposurePathways: ['blind_spot', 'line_of_fire', 'pedestrian_crossing'],
    commonFieldIndicators: ['excessive_speed', 'lack_of_segregation', 'disabled_alarms'],
    commonControlFailures: ['excessive_speed', 'lack_of_segregation', 'disabled_alarms'],
    preferredControlFamilies: ['physical_segregation', 'pedestrian_barriers'],
    weakOrInsufficientControls: ['verbal_warning', 'eye_contact_only'],
    evidenceNeeded: ['equipment_type', 'pedestrian_presence', 'segregation_status'],
    relatedJurisdictions: ['osha_general', 'msha_mnm', 'osha_construction'],
    relatedStandardFamilies: ['mobile_equipment'],
    correctiveActionPrinciples: ['segregate', 'illuminate', 'govern_speed'],
    verificationEvidence: ['photo_of_barriers', 'traffic_plan_document'],
    mandatoryReviewTriggers: ['mixed_traffic', 'high_congestion'],
    antiRegurgitationGuidance: 'Do not recommend eye contact as primary control for blind spots.'
  },
  {
    hazardFamily: 'powered_haulage',
    displayName: 'Powered Haulage',
    hazardType: 'acute_safety',
    hazardSubtypes: ['conveyors', 'belts', 'surface_haulage'],
    mechanismOfHarm: ['entanglement', 'struck_by', 'crushing'],
    hazardousEnergyOrAgent: ['kinetic_mechanical', 'kinetic_mobile'],
    exposurePathways: ['conveyor_walkway', 'haul_road'],
    commonFieldIndicators: ['moving_belts', 'unprotected_pulleys', 'haul_truck_traffic'],
    commonControlFailures: ['missing_guards', 'failed_pull_chords', 'poor_visibility'],
    preferredControlFamilies: ['engineering_guards', 'emergency_stop_systems'],
    weakOrInsufficientControls: ['training_only', 'signs_only'],
    evidenceNeeded: ['guarding_status', 'pull_chord_testing', 'berm_height'],
    relatedJurisdictions: ['msha_mnm'],
    relatedStandardFamilies: ['powered_haulage'],
    correctiveActionPrinciples: ['guard_moving_parts', 'install_estops', 'maintain_berms'],
    verificationEvidence: ['estop_test_record', 'guard_photo'],
    mandatoryReviewTriggers: ['disabled_pull_chords', 'missing_tail_pulley_guards'],
    antiRegurgitationGuidance: 'Do not recommend "caution" for unguarded high-speed conveyor belts.'
  },
  {
    hazardFamily: 'material_handling_storage',
    displayName: 'Material Handling and Storage',
    hazardType: 'acute_safety',
    hazardSubtypes: ['unstable_stacks', 'racking_failure', 'manual_handling'],
    mechanismOfHarm: ['struck_by_falling_object', 'crushing', 'ergonomic_injury'],
    hazardousEnergyOrAgent: ['gravity_stored_potential'],
    exposurePathways: ['aisles', 'loading_zones', 'under_racking'],
    commonFieldIndicators: ['leaning_pallets', 'damaged_racking', 'overloaded_shelves'],
    commonControlFailures: ['improper_stacking', 'lack_of_rack_anchoring', 'exceeding_load_limits'],
    preferredControlFamilies: ['engineered_racking', 'mechanical_stacking_aids'],
    weakOrInsufficientControls: ['signs_only', 'verbal_instruction'],
    evidenceNeeded: ['stack_height', 'rack_condition', 'load_weight'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['material_handling'],
    correctiveActionPrinciples: ['secure_loads', 'anchor_racks', 'limit_heights'],
    verificationEvidence: ['photo_of_secured_stack', 'load_rating_sign_photo'],
    mandatoryReviewTriggers: ['severely_damaged_racking', 'unstable_hazardous_materials'],
    antiRegurgitationGuidance: 'Do not recommend "stacking carefully" for damaged industrial racking.'
  },
  {
    hazardFamily: 'cranes_hoists_rigging',
    displayName: 'Cranes, Hoists, and Rigging',
    hazardType: 'acute_safety',
    hazardSubtypes: ['failed_rigging', 'overload', 'swing_radius_impact'],
    mechanismOfHarm: ['struck_by', 'crushing', 'structural_collapse'],
    hazardousEnergyOrAgent: ['gravity_suspended_load', 'mechanical_tension'],
    exposurePathways: ['under_load', 'swing_path', 'mechanical_failure_zone'],
    commonFieldIndicators: ['damaged_sling', 'unsecured_hook', 'no_barricades'],
    commonControlFailures: ['inadequate_inspection', 'exceeding_capacity', 'unqualified_operator'],
    preferredControlFamilies: ['load_cell_monitoring', 'physical_exclusion_zones'],
    weakOrInsufficientControls: ['verbal_taglines_only', 'visual_monitoring_only'],
    evidenceNeeded: ['load_weight', 'rigging_capacity', 'inspection_status'],
    relatedJurisdictions: ['osha_construction', 'osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['cranes_derrick_rigging'],
    correctiveActionPrinciples: ['verify_load', 'secure_perimeter', 'inspect_rigging'],
    verificationEvidence: ['rigging_inspection_tag_photo', 'lift_plan'],
    mandatoryReviewTriggers: ['critical_lift', 'damaged_lifting_hardware'],
    antiRegurgitationGuidance: 'Do not recommend "watching the load" as a fix for a damaged lifting chain.'
  },
  {
    hazardFamily: 'suspended_loads',
    displayName: 'Suspended Loads',
    hazardType: 'acute_safety',
    hazardSubtypes: ['overhead_work', 'load_swing', 'sling_failure'],
    mechanismOfHarm: ['struck_by_falling_object', 'crushing'],
    hazardousEnergyOrAgent: ['gravity_potential_energy'],
    exposurePathways: ['under_load', 'travel_path_of_load'],
    commonFieldIndicators: ['load_overhead', 'lack_of_exclusion_zone', 'no_warning_signal'],
    commonControlFailures: ['working_under_load', 'failed_rigging', 'no_barricades'],
    preferredControlFamilies: ['physical_exclusion_barriers', 'remote_release_hooks'],
    weakOrInsufficientControls: ['wearing_hard_hat_only', 'shouting_warnings'],
    evidenceNeeded: ['load_position', 'exclusion_zone_status', 'operator_visibility'],
    relatedJurisdictions: ['osha_general', 'msha_mnm', 'osha_construction'],
    relatedStandardFamilies: ['material_handling', 'cranes_rigging'],
    correctiveActionPrinciples: ['barricade_under_load', 'never_stand_under_load', 'inspect_slings'],
    verificationEvidence: ['photo_of_barricades', 'exclusion_zone_audit'],
    mandatoryReviewTriggers: ['personnel_observed_under_suspended_load'],
    antiRegurgitationGuidance: 'Do not recommend a hard hat as sufficient protection for standing under a 5-ton load.'
  },
  {
    hazardFamily: 'excavation_trenching_ground_control',
    displayName: 'Excavation and Ground Control',
    hazardType: 'acute_safety',
    hazardSubtypes: ['cave_in', 'falling_loads', 'underground_utilities'],
    mechanismOfHarm: ['engulfment', 'suffocation', 'struck_by'],
    hazardousEnergyOrAgent: ['soil_pressure', 'gravity'],
    exposurePathways: ['inside_trench', 'bottom_of_excavation'],
    commonFieldIndicators: ['missing_shoring', 'tension_cracks', 'water_in_trench'],
    commonControlFailures: ['no_protective_system', 'spoil_pile_too_close', 'no_competent_person'],
    preferredControlFamilies: ['trench_shields', 'shoring', 'sloping'],
    weakOrInsufficientControls: ['working_fast_only', 'ladder_only'],
    evidenceNeeded: ['trench_depth', 'soil_type', 'protective_system_type'],
    relatedJurisdictions: ['osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['excavation'],
    correctiveActionPrinciples: ['slope_it', 'shore_it', 'shield_it'],
    verificationEvidence: ['photo_of_trench_box', 'competent_person_log'],
    mandatoryReviewTriggers: ['trench_deeper_than_5ft_unprotected', 'hazardous_atmosphere_in_trench'],
    antiRegurgitationGuidance: 'Do not recommend "getting in and out quickly" for unprotected deep trenches.'
  },
  {
    hazardFamily: 'confined_space',
    displayName: 'Confined Space',
    hazardType: 'mixed',
    hazardSubtypes: ['permit_required', 'non_permit'],
    mechanismOfHarm: ['asphyxiation', 'engulfment', 'toxic_exposure'],
    hazardousEnergyOrAgent: ['atmospheric_hazard', 'stored_material'],
    exposurePathways: ['inhalation', 'entrapment'],
    commonFieldIndicators: ['small_openings', 'tanks', 'pits', 'lack_of_ventilation'],
    commonControlFailures: ['no_atmospheric_testing', 'no_attendant', 'failure_to_isolate'],
    preferredControlFamilies: ['ventilation', 'isolation', 'atmospheric_monitoring'],
    weakOrInsufficientControls: ['buddy_system_only', 'quick_peek'],
    evidenceNeeded: ['gas_test_results', 'entry_permit_status', 'attendant_presence'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['confined_space'],
    correctiveActionPrinciples: ['test_before_entry', 'ventilate', 'monitor_continuously'],
    verificationEvidence: ['permit_photo', 'gas_monitor_log'],
    mandatoryReviewTriggers: ['idlh_atmospheres', 'complex_rescue_plan'],
    antiRegurgitationGuidance: 'Do not recommend "entering quickly" to avoid testing.'
  },
  {
    hazardFamily: 'fire_explosion',
    displayName: 'Fire and Explosion',
    hazardType: 'acute_safety',
    hazardSubtypes: ['flammable_vapors', 'dust_explosion', 'chemical_reaction'],
    mechanismOfHarm: ['thermal_burn', 'blast_injury', 'smoke_inhalation'],
    hazardousEnergyOrAgent: ['thermal_fire', 'ignitable_vapors', 'combustible_dust'],
    exposurePathways: ['direct_heat', 'flame_spread', 'pressure_wave'],
    commonFieldIndicators: ['fuel_accumulation', 'spark_sources', 'sealed_containers'],
    commonControlFailures: ['poor_ventilation', 'lack_of_suppression', 'improper_bonding'],
    preferredControlFamilies: ['automatic_suppression', 'explosion_venting', 'inerting'],
    weakOrInsufficientControls: ['handheld_extinguisher_only', 'verbal_no_smoking_sign'],
    evidenceNeeded: ['fuel_load', 'ignition_sources', 'ventilation_rate'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['fire_protection', 'hazardous_locations'],
    correctiveActionPrinciples: ['eliminate_fuel', 'control_ignition', 'suppress_fire'],
    verificationEvidence: ['suppression_system_test_cert', 'bonding_continuity_log'],
    mandatoryReviewTriggers: ['large_scale_flammable_storage', 'explosive_atmospheres'],
    antiRegurgitationGuidance: 'Do not recommend fire extinguishers as a primary fix for massive fuel leaks.'
  },
  {
    hazardFamily: 'hot_work',
    displayName: 'Hot Work',
    hazardType: 'acute_safety',
    hazardSubtypes: ['welding', 'cutting', 'brazing', 'grinding'],
    mechanismOfHarm: ['burn', 'smoke_inhalation', 'property_damage'],
    hazardousEnergyOrAgent: ['thermal_fire', 'ignitable_vapors'],
    exposurePathways: ['direct_heat', 'flame_spread'],
    commonFieldIndicators: ['sparks', 'slag', 'open_flame'],
    commonControlFailures: ['no_fire_watch', 'missing_extinguisher', 'combustibles_nearby'],
    preferredControlFamilies: ['removal_of_combustibles', 'fire_barriers'],
    weakOrInsufficientControls: ['bucket_of_water', 'leaving_area_immediately'],
    evidenceNeeded: ['permit_status', 'fire_watch_presence', 'extinguisher_availability'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['fire_protection', 'hot_work'],
    correctiveActionPrinciples: ['clear_combustibles', 'assign_watch', 'verify_extinguishment'],
    verificationEvidence: ['hot_work_permit_photo', 'fire_watch_sign_off'],
    mandatoryReviewTriggers: ['near_fuel_tanks', 'high_dust_areas'],
    antiRegurgitationGuidance: 'Do not recommend PPE (aprons) as a primary fix for work near flammable gases.'
  },
  {
    hazardFamily: 'combustible_dust',
    displayName: 'Combustible Dust',
    hazardType: 'acute_safety',
    hazardSubtypes: ['coal_dust', 'grain_dust', 'metal_dust'],
    mechanismOfHarm: ['dust_explosion', 'flash_fire'],
    hazardousEnergyOrAgent: ['dust_combustion_energy'],
    exposurePathways: ['suspended_dust_cloud', 'accumulated_layer'],
    commonFieldIndicators: ['dust_accumulation_on_beams', 'hazy_atmosphere'],
    commonControlFailures: ['blowing_dust_with_compressed_air', 'lack_of_dust_collection'],
    preferredControlFamilies: ['dust_collection_systems', 'explosion_venting'],
    weakOrInsufficientControls: ['sweeping_only', 'dust_masks_only'],
    evidenceNeeded: ['dust_layer_thickness', 'particle_size', 'housekeeping_frequency'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['combustible_dust'],
    correctiveActionPrinciples: ['prevent_accumulation', 'eliminate_ignition', 'vent_explosions'],
    verificationEvidence: ['dust_collection_maintenance_log', 'housekeeping_audit_photo'],
    mandatoryReviewTriggers: ['dust_accumulation_exceeding_1/8_inch', 'unrated_electrical_in_dust_area'],
    antiRegurgitationGuidance: 'Do not recommend blowing down dust with compressed air (creates clouds).'
  },
  {
    hazardFamily: 'pressure_systems',
    displayName: 'Pressure Systems',
    hazardType: 'acute_safety',
    hazardSubtypes: ['hydraulic_lines', 'pneumatic_tools', 'pressure_vessels'],
    mechanismOfHarm: ['injection_injury', 'struck_by_flying_parts', 'blast'],
    hazardousEnergyOrAgent: ['stored_pressure_energy'],
    exposurePathways: ['line_of_fire', 'contact_with_leak'],
    commonFieldIndicators: ['bulging_hose', 'hissing_leak', 'unsecured_cylinders'],
    commonControlFailures: ['lack_of_relief_valves', 'improper_fittings', 'missing_whip_checks'],
    preferredControlFamilies: ['pressure_relief_devices', 'whip_checks', 'shielding'],
    weakOrInsufficientControls: ['gloves_only_for_leaks', 'verbal_instruction'],
    evidenceNeeded: ['psi_rating', 'fitting_compatibility', 'relief_valve_status'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['pressure_vessels', 'compressed_gas'],
    correctiveActionPrinciples: ['relieve_pressure', 'restrain_hoses', 'shield_leaks'],
    verificationEvidence: ['whip_check_photo', 'relief_valve_test_record'],
    mandatoryReviewTriggers: ['high_pressure_leaks', 'unsecured_compressed_gas_cylinders'],
    antiRegurgitationGuidance: 'Do not recommend "checking for leaks with hands" (injection hazard).'
  },
  {
    hazardFamily: 'chemical_transfer',
    displayName: 'Chemical Transfer',
    hazardType: 'acute_safety',
    hazardSubtypes: ['pumping', 'manual_pouring', 'hose_coupling'],
    mechanismOfHarm: ['chemical_splash', 'static_ignition', 'toxic_vapor_release'],
    hazardousEnergyOrAgent: ['chemical_potential', 'static_electricity'],
    exposurePathways: ['direct_skin_contact', 'eye_splash', 'inhalation'],
    commonFieldIndicators: ['leaking_hoses', 'no_containment', 'missing_grounding_straps'],
    commonControlFailures: ['lack_of_bonding/grounding', 'no_secondary_containment', 'incorrect_hose_rating'],
    preferredControlFamilies: ['closed_loop_transfer', 'engineered_secondary_containment', 'automatic_grounding_interlocks'],
    weakOrInsufficientControls: ['gloves_only', 'working_slowly'],
    evidenceNeeded: ['bonding_status', 'hose_integrity', 'containment_volume'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['flammable_liquids', 'process_safety'],
    correctiveActionPrinciples: ['bond_and_ground', 'contain_spills', 'prevent_splashes'],
    verificationEvidence: ['grounding_continuity_test', 'spill_kit_inspection'],
    mandatoryReviewTriggers: ['transferring_flammables_without_bonding', 'leaking_high_toxicity_chemicals'],
    antiRegurgitationGuidance: 'Do not recommend PPE as primary fix for lack of bonding/grounding during flammable transfer.'
  },
  {
    hazardFamily: 'emergency_egress',
    displayName: 'Emergency Egress',
    hazardType: 'emergency_readiness',
    hazardSubtypes: ['blocked_exit', 'unmarked_path', 'locked_door'],
    mechanismOfHarm: ['entrapment', 'smoke_inhalation', 'crushing_panic'],
    hazardousEnergyOrAgent: ['restricted_motion_emergency'],
    exposurePathways: ['exit_route', 'emergency_door'],
    commonFieldIndicators: ['material_in_hallway', 'chained_exit_door', 'burnt_out_exit_sign'],
    commonControlFailures: ['storage_in_exit_paths', 'unqualified_exit_hardware'],
    preferredControlFamilies: ['clear_exit_paths', 'panic_hardware'],
    weakOrInsufficientControls: ['verbal_instruction_on_path', 'flashlight_only'],
    evidenceNeeded: ['path_width', 'door_functionality', 'signage_visibility'],
    relatedJurisdictions: ['osha_general', 'osha_construction'],
    relatedStandardFamilies: ['emergency_egress'],
    correctiveActionPrinciples: ['clear_obstructions', 'ensure_marking', 'verify_access'],
    verificationEvidence: ['photo_of_clear_path', 'monthly_egress_audit'],
    mandatoryReviewTriggers: ['locked_emergency_exits', 'blocked_primary_egress'],
    antiRegurgitationGuidance: 'Do not recommend "moving material later" for blocked fire exits.'
  },
  {
    hazardFamily: 'emergency_equipment',
    displayName: 'Emergency Equipment',
    hazardType: 'emergency_readiness',
    hazardSubtypes: ['eyewashes', 'showers', 'fire_extinguishers', 'aeds'],
    mechanismOfHarm: ['delayed_medical_response', 'worsened_injury'],
    hazardousEnergyOrAgent: ['various_acute_energies'],
    exposurePathways: ['emergency_access'],
    commonFieldIndicators: ['blocked_shower', 'expired_extinguisher', 'empty_first_aid_kit'],
    commonControlFailures: ['storage_obstructions', 'missing_inspections', 'dead_batteries'],
    preferredControlFamilies: ['redundant_emergency_systems', 'automated_monitoring'],
    weakOrInsufficientControls: ['signs_pointing_to_blocked_gear', 'verbal_direction'],
    evidenceNeeded: ['inspection_date', 'obstruction_status', 'utility_connection'],
    relatedJurisdictions: ['osha_general', 'osha_construction'],
    relatedStandardFamilies: ['emergency_equipment'],
    correctiveActionPrinciples: ['clear_access', 'verify_function', 'maintain_readiness'],
    verificationEvidence: ['weekly_flush_log', 'extinguisher_tag_photo'],
    mandatoryReviewTriggers: ['inoperative_emergency_showers', 'missing_aed_in_high_risk_zone'],
    antiRegurgitationGuidance: 'Do not recommend "moving drums later" for blocked eyewash stations.'
  },
  {
    hazardFamily: 'personal_protective_equipment',
    displayName: 'Personal Protective Equipment',
    hazardType: 'acute_safety',
    hazardSubtypes: ['head_protection', 'eye_protection', 'foot_protection'],
    mechanismOfHarm: ['struck_by', 'impact', 'penetration'],
    hazardousEnergyOrAgent: ['various_acute_energies'],
    exposurePathways: ['head', 'eyes', 'limbs'],
    commonFieldIndicators: ['cracked_hard_hat', 'scratched_safety_glasses', 'non_rated_boots'],
    commonControlFailures: ['improper_selection', 'lack_of_enforcement', 'worn_out_equipment'],
    preferredControlFamilies: ['high_quality_ppe', 'regular_inspection_replacement'],
    weakOrInsufficientControls: ['verbal_reminder_only', 'using_personal_non_rated_gear'],
    evidenceNeeded: ['ansi_rating', 'equipment_condition', 'exposure_level'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['ppe'],
    correctiveActionPrinciples: ['select_appropriate_gear', 'inspect_daily', 'ensure_proper_fit'],
    verificationEvidence: ['ppe_inspection_record', 'fit_test_cert'],
    mandatoryReviewTriggers: ['missing_ppe_in_high_hazard_zone'],
    antiRegurgitationGuidance: 'Do not recommend PPE as the primary control when engineering/isolation is feasible.'
  },
  {
    hazardFamily: 'silica_respirable_dust',
    displayName: 'Respirable Crystalline Silica',
    hazardType: 'chronic_health',
    hazardSubtypes: ['dry_cutting', 'crushing', 'drilling'],
    mechanismOfHarm: ['silicosis', 'lung_cancer', 'kidney_disease'],
    hazardousEnergyOrAgent: ['respirable_silica_dust'],
    exposurePathways: ['inhalation'],
    commonFieldIndicators: ['visible_dust_clouds', 'dry_sawing', 'white_residue'],
    commonControlFailures: ['missing_water_suppression', 'failed_vacuum_collection'],
    preferredControlFamilies: ['engineering_wet_methods', 'hepa_vacuum_collection'],
    weakOrInsufficientControls: ['paper_dust_mask', 'blowing_dust_with_compressed_air'],
    evidenceNeeded: ['sampling_data', 'ventilation_flow', 'wet_method_usage'],
    relatedJurisdictions: ['osha_construction', 'osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['respiratory_protection', 'silica_exposure'],
    correctiveActionPrinciples: ['suppress_with_water', 'collect_at_source', 'isolate_workers'],
    verificationEvidence: ['air_sampling_report', 'maintenance_log_for_wet_systems'],
    mandatoryReviewTriggers: ['visible_dust_in_uncontrolled_area', 'missing_sampling_records'],
    antiRegurgitationGuidance: 'Do not recommend respirators until engineering controls (water/vacuum) are verified.'
  },
  {
    hazardFamily: 'welding_fumes',
    displayName: 'Welding Fumes',
    hazardType: 'chronic_health',
    hazardSubtypes: ['arc_welding', 'plasma_cutting'],
    mechanismOfHarm: ['metal_fume_fever', 'neurological_damage', 'lung_cancer'],
    hazardousEnergyOrAgent: ['toxic_metal_fumes', 'ozone'],
    exposurePathways: ['inhalation'],
    commonFieldIndicators: ['visible_smoke_plume', 'confined_welding', 'lack_of_exhaust'],
    commonControlFailures: ['failed_local_exhaust', 'improper_respirator_selection'],
    preferredControlFamilies: ['local_exhaust_ventilation', 'source_extraction'],
    weakOrInsufficientControls: ['general_room_ventilation_only', 'surgical_masks'],
    evidenceNeeded: ['fume_concentration', 'exhaust_velocity', 'base_metal_type'],
    relatedJurisdictions: ['osha_general', 'osha_construction'],
    relatedStandardFamilies: ['respiratory_protection', 'welding_safety'],
    correctiveActionPrinciples: ['extract_at_source', 'ventilate_area', 'protect_breathing'],
    verificationEvidence: ['ventilation_smoke_test', 'sampling_records'],
    mandatoryReviewTriggers: ['welding_in_confined_spaces', 'welding_on_stainless/galvanized'],
    antiRegurgitationGuidance: 'Do not recommend "holding breath" or "positioning head" as primary control.'
  },
  {
    hazardFamily: 'noise_exposure',
    displayName: 'Occupational Noise',
    hazardType: 'chronic_health',
    hazardSubtypes: ['impact_noise', 'continuous_noise'],
    mechanismOfHarm: ['hearing_loss', 'tinnitus'],
    hazardousEnergyOrAgent: ['acoustic_energy'],
    exposurePathways: ['ear_canal'],
    commonFieldIndicators: ['shouting_to_be_heard', 'ringing_ears', 'loud_machinery'],
    commonControlFailures: ['lack_of_enclosure', 'missing_mufflers', 'failure_to_wear_hpd'],
    preferredControlFamilies: ['engineering_enclosure', 'vibration_isolation', 'mufflers'],
    weakOrInsufficientControls: ['earplugs_only_without_fit_test', 'verbal_instruction'],
    evidenceNeeded: ['decibel_levels', 'dosimetry_data', 'exposure_duration'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['hearing_conservation'],
    correctiveActionPrinciples: ['enclose_source', 'dampen_vibration', 'reduce_exposure_time'],
    verificationEvidence: ['noise_map', 'audiometric_test_records'],
    mandatoryReviewTriggers: ['noise_levels_above_85db_without_control_program'],
    antiRegurgitationGuidance: 'Do not recommend earplugs as primary fix for missing engineering enclosures.'
  },
  {
    hazardFamily: 'heat_stress',
    displayName: 'Heat Stress',
    hazardType: 'chronic_health',
    hazardSubtypes: ['heat_exhaustion', 'heat_stroke', 'heat_cramps'],
    mechanismOfHarm: ['hyperthermia', 'organ_failure'],
    hazardousEnergyOrAgent: ['thermal_ambient_heat', 'radiant_heat'],
    exposurePathways: ['skin', 'metabolic_rate'],
    commonFieldIndicators: ['high_ambient_temp', 'direct_sun_exposure', 'heavy_workload'],
    commonControlFailures: ['lack_of_water', 'missing_rest_breaks', 'no_acclimation'],
    preferredControlFamilies: ['work_rest_cycles', 'cooling_stations', 'shading'],
    weakOrInsufficientControls: ['verbal_warning_only', 'unlimited_work_without_break'],
    evidenceNeeded: ['wet_bulb_globe_temp', 'humidity_levels', 'rest_schedule'],
    relatedJurisdictions: ['osha_general', 'msha_mnm', 'company_policy'],
    relatedStandardFamilies: ['heat_illness_prevention'],
    correctiveActionPrinciples: ['water', 'rest', 'shade', 'acclimation'],
    verificationEvidence: ['training_records', 'rest_break_log'],
    mandatoryReviewTriggers: ['extreme_heat_above_100f', 'employee_illness_symptoms'],
    antiRegurgitationGuidance: 'Do not recommend "working through it" for high heat indexes.'
  },
  {
    hazardFamily: 'cold_stress',
    displayName: 'Cold Stress',
    hazardType: 'chronic_health',
    hazardSubtypes: ['hypothermia', 'frostbite', 'trench_foot'],
    mechanismOfHarm: ['tissue_damage', 'systemic_failure'],
    hazardousEnergyOrAgent: ['thermal_cold', 'wind_chill'],
    exposurePathways: ['skin', 'respiratory'],
    commonFieldIndicators: ['sub_freezing_temp', 'high_wind', 'wet_clothing'],
    commonControlFailures: ['lack_of_warm_shelter', 'inadequate_clothing', 'prolonged_immobility'],
    preferredControlFamilies: ['heated_break_areas', 'wind_shields', 'work_rotation'],
    weakOrInsufficientControls: ['cotton_clothing_only', 'verbal_instruction'],
    evidenceNeeded: ['ambient_temp', 'wind_speed', 'clothing_layers'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['cold_stress_prevention'],
    correctiveActionPrinciples: ['warm_up', 'stay_dry', 'block_wind'],
    verificationEvidence: ['heated_shelter_inspection_photo', 'acclimation_log'],
    mandatoryReviewTriggers: ['wind_chill_below_minus_20f', 'visible_signs_of_frostbite'],
    antiRegurgitationGuidance: 'Do not recommend "toughening up" for sub-zero exposures.'
  },
  {
    hazardFamily: 'chemical_inhalation_contact',
    displayName: 'Chemical Inhalation and Contact',
    hazardType: 'chronic_health',
    hazardSubtypes: ['vapors', 'mists', 'direct_splash'],
    mechanismOfHarm: ['chemical_burn', 'systemic_toxicity', 'dermatitis'],
    hazardousEnergyOrAgent: ['chemical_reactive_agent'],
    exposurePathways: ['skin', 'eyes', 'respiratory'],
    commonFieldIndicators: ['strong_odors', 'open_vats', 'leaking_valves'],
    commonControlFailures: ['missing_enclosure', 'failed_ventilation', 'missing_ppe'],
    preferredControlFamilies: ['closed_transfer_systems', 'local_exhaust'],
    weakOrInsufficientControls: ['gloves_only', 'holding_breath'],
    evidenceNeeded: ['ppm_levels', 'sds_identity', 'exposure_time'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['air_contaminants', 'hazard_communication'],
    correctiveActionPrinciples: ['enclose_process', 'ventilate', 'protect_interface'],
    verificationEvidence: ['air_monitoring_data', 'ventilation_flow_verify'],
    mandatoryReviewTriggers: ['exposure_near_pel/tlv', 'highly_toxic_gas_usage'],
    antiRegurgitationGuidance: 'Do not recommend PPE as a substitute for closed-loop transfer systems.'
  },
  {
    hazardFamily: 'respiratory_protection',
    displayName: 'Respiratory Protection',
    hazardType: 'mixed',
    hazardSubtypes: ['improper_fit', 'wrong_cartridge', 'worn_out_filter'],
    mechanismOfHarm: ['inhalation_exposure', 'acute_poisoning'],
    hazardousEnergyOrAgent: ['airborne_contaminants'],
    exposurePathways: ['respiratory'],
    commonFieldIndicators: ['facial_hair_with_respirator', 'dirty_filters', 'smell_inside_mask'],
    commonControlFailures: ['no_fit_test', 'improper_storage', 'failed_seal_check'],
    preferredControlFamilies: ['engineering_controls_first', 'mandatory_fit_testing'],
    weakOrInsufficientControls: ['one_size_fits_all_approach', 'unvalidated_respirator_selection'],
    evidenceNeeded: ['fit_test_date', 'cartridge_type', 'user_medical_clearance'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['respiratory_protection'],
    correctiveActionPrinciples: ['ensure_seal', 'match_cartridge_to_hazard', 'clear_medical_baseline'],
    verificationEvidence: ['fit_test_record_photo', 'cartridge_replacement_log'],
    mandatoryReviewTriggers: ['respirator_use_without_fit_test', 'high_toxicity_environments'],
    antiRegurgitationGuidance: 'Do not recommend respirators as primary fix when ventilation is missing.'
  },
  {
    hazardFamily: 'ergonomic_strain',
    displayName: 'Ergonomics',
    hazardType: 'chronic_health',
    hazardSubtypes: ['lifting', 'repetitive_motion', 'posture'],
    mechanismOfHarm: ['musculoskeletal_disorder', 'nerve_damage'],
    hazardousEnergyOrAgent: ['biomechanical_force'],
    exposurePathways: ['spine', 'joints', 'tendons'],
    commonFieldIndicators: ['heavy_manual_lifting', 'awkward_reaches', 'vibrating_tools'],
    commonControlFailures: ['lack_of_mechanical_aids', 'poor_workstation_design'],
    preferredControlFamilies: ['mechanical_assists', 'workstation_redesign'],
    weakOrInsufficientControls: ['back_belt_only', 'training_on_posture_only'],
    evidenceNeeded: ['weight_of_load', 'frequency_of_task', 'posture_assessment'],
    relatedJurisdictions: ['osha_general', 'company_policy'],
    relatedStandardFamilies: ['ergonomics'],
    correctiveActionPrinciples: ['use_mechanical_lift', 'reduce_force', 'improve_posture'],
    verificationEvidence: ['photo_of_lift_assist', 'ergonomic_assessment_report'],
    mandatoryReviewTriggers: ['repetitive_heavy_lifting_above_50lbs'],
    antiRegurgitationGuidance: 'Do not recommend "lifting correctly" as a substitute for mechanical lifts.'
  },
  {
    hazardFamily: 'biological_exposure',
    displayName: 'Biological Hazards',
    hazardType: 'chronic_health',
    hazardSubtypes: ['bloodborne_pathogens', 'sewage', 'mold'],
    mechanismOfHarm: ['infection', 'chronic_allergy', 'toxicosis'],
    hazardousEnergyOrAgent: ['biological_pathogens', 'spores'],
    exposurePathways: ['injection', 'ingestion', 'inhalation', 'contact'],
    commonFieldIndicators: ['standing_water', 'medical_waste', 'animal_droppings'],
    commonControlFailures: ['improper_disposal', 'missing_disinfection', 'no_vaccination'],
    preferredControlFamilies: ['sterilization', 'disinfection', 'biohazard_containment'],
    weakOrInsufficientControls: ['regular_soap_only', 'ignoring_exposure'],
    evidenceNeeded: ['pathogen_type', 'exposure_mechanism', 'decontamination_status'],
    relatedJurisdictions: ['osha_general'],
    relatedStandardFamilies: ['bloodborne_pathogens', 'sanitation'],
    correctiveActionPrinciples: ['isolate_pathogen', 'decontaminate', 'immunize'],
    verificationEvidence: ['waste_manifest', 'decontamination_log'],
    mandatoryReviewTriggers: ['needle_stick_incident', 'raw_sewage_leak'],
    antiRegurgitationGuidance: 'Do not recommend "cleaning with water" for biohazardous spills.'
  },
  {
    hazardFamily: 'illumination_visibility',
    displayName: 'Illumination and Visibility',
    hazardType: 'mixed',
    hazardSubtypes: ['low_light', 'glare', 'burnt_out_lighting'],
    mechanismOfHarm: ['struck_by', 'trips', 'eye_strain'],
    hazardousEnergyOrAgent: ['visual_information_loss'],
    exposurePathways: ['eyes', 'walking_surface'],
    commonFieldIndicators: ['dim_hallways', 'shadowy_corners', 'blinding_glare'],
    commonControlFailures: ['failed_bulbs', 'inadequate_lighting_layout'],
    preferredControlFamilies: ['high_lumen_leds', 'emergency_lighting_redundancy'],
    weakOrInsufficientControls: ['flashlight_usage_only', 'verbal_caution'],
    evidenceNeeded: ['foot_candle_reading', 'fixture_status', 'glare_source'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['illumination'],
    correctiveActionPrinciples: ['add_fixtures', 'replace_bulbs', 'diffuse_glare'],
    verificationEvidence: ['lux_meter_log', 'night_time_inspection_photo'],
    mandatoryReviewTriggers: ['total_darkness_in_egress_path', 'precision_work_in_low_light'],
    antiRegurgitationGuidance: 'Do not recommend "carrying a flashlight" as a permanent fix for dark work zones.'
  },
  {
    hazardFamily: 'ventilation_air_quality',
    displayName: 'Ventilation and Air Quality',
    hazardType: 'chronic_health',
    hazardSubtypes: ['oxygen_deficiency', 'stale_air', 'contaminant_buildup'],
    mechanismOfHarm: ['asphyxiation', 'dizziness', 'chronic_respiratory_issues'],
    hazardousEnergyOrAgent: ['atmospheric_composition'],
    exposurePathways: ['inhalation'],
    commonFieldIndicators: ['stagnant_air', 'visible_fumes', 'high_humidity'],
    commonControlFailures: ['failed_hvac', 'blocked_vents', 'missing_local_exhaust'],
    preferredControlFamilies: ['balanced_hvac', 'hepa_filtration', 'make_up_air'],
    weakOrInsufficientControls: ['opening_windows_only', 'desk_fans_only'],
    evidenceNeeded: ['cfm_readings', 'co2_levels', 'air_turnover_rate'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['ventilation', 'air_contaminants'],
    correctiveActionPrinciples: ['supply_fresh_air', 'exhaust_contaminants', 'filter_air'],
    verificationEvidence: ['anemometer_reading_log', 'filter_replacement_records'],
    mandatoryReviewTriggers: ['oxygen_below_19.5%', 'toxic_contaminant_buildup'],
    antiRegurgitationGuidance: 'Do not recommend "getting fresh air breaks" as primary fix for toxic buildup.'
  },
  {
    hazardFamily: 'contractor_coordination',
    displayName: 'Contractor Coordination',
    hazardType: 'acute_safety',
    hazardSubtypes: ['overlapping_work_zones', 'uncommunicated_hazards'],
    mechanismOfHarm: ['struck_by', 'unintended_startup', 'fire'],
    hazardousEnergyOrAgent: ['conflicting_work_energies'],
    exposurePathways: ['multi_employer_worksite'],
    commonFieldIndicators: ['contractors_on_site_without_orientation', 'simultaneous_high_risk_tasks'],
    commonControlFailures: ['lack_of_coordination_meetings', 'no_joint_loto_program', 'missing_permits'],
    preferredControlFamilies: ['integrated_permit_to_work', 'joint_safety_briefings', 'host_employer_supervision'],
    weakOrInsufficientControls: ['verbal_contractor_instructions_only', 'assuming_contractor_knows_rules'],
    evidenceNeeded: ['orientation_records', 'permit_signatures', 'safety_coordination_logs'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['multi_employer_worksite', 'contractor_management'],
    correctiveActionPrinciples: ['coordinate_activities', 'verify_competency', 'ensure_shared_loto'],
    verificationEvidence: ['signed_coordination_permit', 'daily_huddle_log'],
    mandatoryReviewTriggers: ['high_risk_tasks_performed_by_unvetted_contractors'],
    antiRegurgitationGuidance: 'Do not recommend "letting contractors manage themselves" for complex joint tasks.'
  },
  {
    hazardFamily: 'training_procedure_supervision',
    displayName: 'Training, Procedure, and Supervision',
    hazardType: 'acute_safety',
    hazardSubtypes: ['unqualified_worker', 'obsolete_sop', 'lack_of_oversight'],
    mechanismOfHarm: ['various_acute_injuries'],
    hazardousEnergyOrAgent: ['behavioral_risk'],
    exposurePathways: ['human_error_zone'],
    commonFieldIndicators: ['worker_unsure_of_task', 'supervisor_not_present', 'unauthorized_modifications'],
    commonControlFailures: ['missing_training_records', 'failed_observation_program', 'confusing_sops'],
    preferredControlFamilies: ['competency_based_training', 'active_supervision_audits', 'error_proofed_procedures'],
    weakOrInsufficientControls: ['computer_based_training_only', 'disciplinary_action_only'],
    evidenceNeeded: ['training_cert_date', 'supervisor_audit_frequency', 'procedure_revision_date'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['training_requirements'],
    correctiveActionPrinciples: ['verify_competency', 'simplify_procedures', 'increase_field_presence'],
    verificationEvidence: ['training_roster_photo', 'completed_observation_form'],
    mandatoryReviewTriggers: ['untrained_personnel_in_high_hazard_tasks'],
    antiRegurgitationGuidance: 'Do not recommend "retraining" for hazards caused by missing physical guards.'
  },
  {
    hazardFamily: 'corrective_action_verification_failure',
    displayName: 'Corrective Action Verification Failure',
    hazardType: 'acute_safety',
    hazardSubtypes: ['recurring_hazard', 'closed_without_fix', 'failed_validation'],
    mechanismOfHarm: ['systemic_safety_failure'],
    hazardousEnergyOrAgent: ['uncontrolled_legacy_hazards'],
    exposurePathways: ['unverified_work_zones'],
    commonFieldIndicators: ['old_hazard_tags_present', 'repeated_citations', 'incomplete_repairs'],
    commonControlFailures: ['lack_of_photo_verification', 'no_second_party_sign_off', 'database_lag'],
    preferredControlFamilies: ['mandatory_photo_verification', 'independent_safety_validation'],
    weakOrInsufficientControls: ['self_closure_only', 'verbal_fix_confirmation'],
    evidenceNeeded: ['verification_photo', 'sign_off_role', 're-inspection_date'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['safety_management_systems'],
    correctiveActionPrinciples: ['inspect_the_fix', 'document_verification', 'analyze_recurrence'],
    verificationEvidence: ['verification_photo_gallery', 'manager_sign_off_audit'],
    mandatoryReviewTriggers: ['hazard_recurs_within_30_days_of_closure'],
    antiRegurgitationGuidance: 'Do not recommend "checking it next year" for critical life-safety corrective actions.'
  },
  {
    hazardFamily: 'slips_trips_falls_housekeeping',
    displayName: 'Slips, Trips, Falls, and Housekeeping',
    hazardType: 'acute_safety',
    hazardSubtypes: ['slick_surfaces', 'uneven_ground', 'cluttered_walkways', 'loose_cables'],
    mechanismOfHarm: ['slips', 'trips', 'same_level_fall'],
    hazardousEnergyOrAgent: ['gravity', 'kinetic_human_motion'],
    exposurePathways: ['walking_path', 'work_area_floor'],
    commonFieldIndicators: ['oil_spill', 'loose_material_walkway', 'blocked_aisle', 'uncoiled_hoses'],
    commonControlFailures: ['poor_housekeeping', 'failed_cleanup_protocol', 'lack_of_marking'],
    preferredControlFamilies: ['walkway_clearance', 'slip_resistant_treatment', 'cable_management'],
    weakOrInsufficientControls: ['caution_signs_only', 'verbal_instruction_only', 'ppe_shoes_only'],
    evidenceNeeded: ['surface_condition', 'obstruction_type', 'aisle_clearance_status'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['walking_working_surfaces', 'housekeeping'],
    correctiveActionPrinciples: ['clear_walkways', 'clean_spills_immediately', 'organize_materials'],
    verificationEvidence: ['photo_of_cleared_walkway', 'housekeeping_log'],
    mandatoryReviewTriggers: ['blocked_emergency_exit_routes', 'recurring_wet_areas_without_drainage'],
    antiRegurgitationGuidance: 'Do not recommend "caution signs" or "be careful" as the primary control for blocked pathways or spills.'
  },
  {
    hazardFamily: 'traffic_control',
    displayName: 'Traffic Control and Pedestrian Safety',
    hazardType: 'acute_safety',
    hazardSubtypes: ['pedestrian_crossing', 'vehicle_speeding', 'blind_intersection', 'work_zone_encroachment'],
    mechanismOfHarm: ['struck_by', 'collision', 'crushing'],
    hazardousEnergyOrAgent: ['kinetic_mobile_equipment', 'kinetic_vehicle'],
    exposurePathways: ['haul_road', 'warehouse_aisle', 'loading_dock'],
    commonFieldIndicators: ['missing_pedestrian_walkways', 'inadequate_signage', 'no_flaggers'],
    commonControlFailures: ['lack_of_physical_barriers', 'speeding_vehicles', 'unmarked_crosswalks'],
    preferredControlFamilies: ['physical_traffic_barriers', 'segregated_walkways', 'speed_limiters'],
    weakOrInsufficientControls: ['wear_high_vis_only', 'verbal_warnings_only', 'eye_contact_only'],
    evidenceNeeded: ['traffic_separation_barrier_status', 'signage_visibility', 'vehicle_speed_governors'],
    relatedJurisdictions: ['osha_construction', 'osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['traffic_control', 'vehicle_safety'],
    correctiveActionPrinciples: ['physically_segregate_traffic', 'install_clear_traffic_signage', 'enforce_speed_limits'],
    verificationEvidence: ['photo_of_traffic_barriers', 'site_traffic_plan'],
    mandatoryReviewTriggers: ['unmarked_pedestrian_vehicle_mixed_zones', 'active_construction_traffic_without_flagger'],
    antiRegurgitationGuidance: 'Do not recommend eye contact or high-visibility vests as primary controls instead of physical traffic segregation.'
  },
  {
    hazardFamily: 'compressed_gas',
    displayName: 'Compressed Gas Safety',
    hazardType: 'acute_safety',
    hazardSubtypes: ['unsecured_cylinders', 'missing_valve_caps', 'incompatible_storage', 'leaking_fittings'],
    mechanismOfHarm: ['blast', 'struck_by_projectile', 'asphyxiation', 'fire'],
    hazardousEnergyOrAgent: ['stored_pressure_energy', 'chemical_energy'],
    exposurePathways: ['line_of_fire', 'enclosed_work_area'],
    commonFieldIndicators: ['unsecured_oxygen_cylinder', 'missing_protective_cap', 'oxygen_fuel_stored_together'],
    commonControlFailures: ['failure_to_secure_cylinders', 'failure_to_segregate_oxygen_and_fuel', 'leaking_valves'],
    preferredControlFamilies: ['cylinder_racks_chains', 'fire_resistant_barriers', 'pressure_relief_devices'],
    weakOrInsufficientControls: ['caution_tags_only', 'be_careful_during_handling'],
    evidenceNeeded: ['securing_status', 'storage_separation_distance', 'valve_cap_presence'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['compressed_gas_cylinders'],
    correctiveActionPrinciples: ['secure_cylinders_upright', 'install_valve_caps', 'separate_oxygen_and_fuel'],
    verificationEvidence: ['photo_of_secured_cylinder_rack', 'storage_area_inspection_checklist'],
    mandatoryReviewTriggers: ['unsecured_compressed_gas_cylinders', 'oxygen_fuel_stored_together_without_barrier'],
    antiRegurgitationGuidance: 'Do not recommend warnings or safety labels as a replacement for chains or racks.'
  },
  {
    hazardFamily: 'hydraulic_pneumatic_energy',
    displayName: 'Hydraulic and Pneumatic Energy',
    hazardType: 'acute_safety',
    hazardSubtypes: ['unreleased_stored_pressure', 'failed_hoses', 'whipping_hoses', 'fluid_injection'],
    mechanismOfHarm: ['struck_by', 'fluid_injection_injury', 'crushing', 'amputation'],
    hazardousEnergyOrAgent: ['stored_hydraulic_pressure', 'pneumatic_pressure'],
    exposurePathways: ['line_of_fire', 'hands_near_fittings'],
    commonFieldIndicators: ['damaged_high_pressure_hoses', 'missing_whip_checks', 'unsupported_hydraulic_cylinders'],
    commonControlFailures: ['failure_to_bleed_pressure', 'missing_hose_restraints', 'lack_of_physical_blocks'],
    preferredControlFamilies: ['whip_checks_safety_cables', 'bleed_valves', 'mechanical_blocking_devices'],
    weakOrInsufficientControls: ['gloves_only', 'verbal_instruction_only', 'inspect_later'],
    evidenceNeeded: ['pressure_level_monitoring', 'whip_check_status', 'mechanical_block_status'],
    relatedJurisdictions: ['osha_general', 'msha_mnm', 'osha_construction'],
    relatedStandardFamilies: ['lockout_tagout', 'pneumatic_hydraulic_safety'],
    correctiveActionPrinciples: ['de_energize_and_bleed_pressure', 'install_whip_checks', 'apply_mechanical_blocks'],
    verificationEvidence: ['photo_of_installed_whip_checks', 'pressure_zero_verification_log'],
    mandatoryReviewTriggers: ['missing_whip_checks_on_high_pressure_lines', 'hydraulic_work_without_blocking_support'],
    antiRegurgitationGuidance: 'Do not recommend PPE (gloves/glasses) as primary controls for fluid injection or hose whipping hazards.'
  }
];
