import { HazardDefinition } from './hazard-universe.types';

export const HAZARD_UNIVERSE_REGISTRY: HazardDefinition[] = [
  {
    hazardFamily: 'machine_guarding',
    hazardSubtypes: ['rotating_parts', 'nip_points', 'flying_chips', 'sparks'],
    mechanismOfHarm: ['entanglement', 'crushing', 'amputation', 'struck_by'],
    hazardousEnergyOrAgent: ['mechanical_rotation', 'mechanical_reciprocation'],
    exposurePathways: ['reach_in', 'reach_over', 'reach_under', 'reach_through'],
    commonControlFailures: ['missing_guard', 'interlock_bypass', 'poor_maintenance'],
    preferredControlFamilies: ['engineering_enclosure', 'interlocked_barrier'],
    weakOrInsufficientControls: ['warning_signs_only', 'training_only', 'ppe_only'],
    evidenceRequired: ['guarding_status', 'distance_from_hazard', 'opening_size'],
    relatedJurisdictions: ['osha_general', 'msha_mnm', 'osha_construction'],
    relatedStandardFamilies: ['machine_guarding'],
    correctiveActionPrinciples: ['enclosure', 'physical_barrier', 'interlock'],
    verificationEvidence: ['photo_of_installed_guard', 'interlock_test_log'],
    humanReviewTriggers: ['complex_interaction', 'custom_equipment']
  },
  {
    hazardFamily: 'lockout_tagout',
    hazardSubtypes: ['unexpected_startup', 'stored_energy_release'],
    mechanismOfHarm: ['crushing', 'electrocution', 'burn', 'entrapment'],
    hazardousEnergyOrAgent: ['electrical', 'hydraulic', 'pneumatic', 'kinetic', 'potential', 'thermal', 'chemical'],
    exposurePathways: ['body_in_machine', 'hands_in_point_of_operation'],
    commonControlFailures: ['failure_to_isolate', 'failure_to_verify_zero_energy', 'failure_to_lock'],
    preferredControlFamilies: ['energy_isolation_physical_lock'],
    weakOrInsufficientControls: ['tag_only', 'push_button_stop', 'verbal_agreement'],
    evidenceRequired: ['isolation_point_status', 'lock_application', 'verification_method'],
    relatedJurisdictions: ['osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['lockout_tagout'],
    correctiveActionPrinciples: ['zero_energy_verification', 'one_person_one_lock'],
    verificationEvidence: ['lock_photo', 'zero_energy_verification_log'],
    humanReviewTriggers: ['multiple_energy_sources', 'group_lockout']
  },
  {
    hazardFamily: 'electrical',
    hazardSubtypes: ['energized_parts', 'arc_flash', 'ground_fault'],
    mechanismOfHarm: ['shock', 'electrocution', 'burn', 'blast_injury'],
    hazardousEnergyOrAgent: ['electrical'],
    exposurePathways: ['direct_contact', 'indirect_contact', 'approach_boundary'],
    commonControlFailures: ['exposed_wiring', 'missing_covers', 'improper_grounding'],
    preferredControlFamilies: ['enclosure', 'insulation', 'gfci'],
    weakOrInsufficientControls: ['tape_repair', 'verbal_warning'],
    evidenceRequired: ['voltage_level', 'enclosure_integrity', 'grounding_status'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['electrical_safety'],
    correctiveActionPrinciples: ['insulate', 'guard', 'ground', 'disconnect'],
    verificationEvidence: ['photo_of_cover_installed', 'continuity_test_result'],
    humanReviewTriggers: ['high_voltage', 'wet_locations']
  },
  {
    hazardFamily: 'fall_protection',
    hazardSubtypes: ['elevated_work', 'open_edge', 'floor_hole', 'ladder_safety'],
    mechanismOfHarm: ['fall_to_lower_level'],
    hazardousEnergyOrAgent: ['gravity'],
    exposurePathways: ['unprotected_edge', 'unstable_surface'],
    commonControlFailures: ['missing_guardrail', 'improper_harness_use', 'no_anchor_point'],
    preferredControlFamilies: ['passive_fall_protection', 'guardrails', 'hole_covers'],
    weakOrInsufficientControls: ['warning_line_only', 'safety_monitor_only'],
    evidenceRequired: ['fall_height', 'edge_protection_status', 'harness_condition'],
    relatedJurisdictions: ['osha_construction', 'osha_general', 'msha_mnm'],
    relatedStandardFamilies: ['fall_protection'],
    correctiveActionPrinciples: ['eliminate_hazard', 'prevent_fall', 'arrest_fall'],
    verificationEvidence: ['photo_of_guardrail', 'anchor_point_inspection'],
    humanReviewTriggers: ['complex_rigging', 'unusual_heights']
  },
  {
    hazardFamily: 'mobile_equipment',
    hazardSubtypes: ['powered_industrial_trucks', 'earth_moving_equipment', 'haul_trucks'],
    mechanismOfHarm: ['struck_by', 'caught_between', 'rollover'],
    hazardousEnergyOrAgent: ['kinetic_mobile_equipment'],
    exposurePathways: ['blind_spot', 'line_of_fire', 'pedestrian_crossing'],
    commonControlFailures: ['excessive_speed', 'lack_of_segregation', 'disabled_alarms'],
    preferredControlFamilies: ['physical_segregation', 'pedestrian_barriers'],
    weakOrInsufficientControls: ['verbal_warning', 'eye_contact_only'],
    evidenceRequired: ['equipment_type', 'pedestrian_presence', 'segregation_status'],
    relatedJurisdictions: ['osha_general', 'msha_mnm', 'osha_construction'],
    relatedStandardFamilies: ['mobile_equipment'],
    correctiveActionPrinciples: ['segregate', 'illuminate', 'govern_speed'],
    verificationEvidence: ['photo_of_barriers', 'traffic_plan_document'],
    humanReviewTriggers: ['mixed_traffic', 'high_congestion']
  },
  {
    hazardFamily: 'hazcom_chemical_exposure',
    hazardSubtypes: ['unlabeled_container', 'missing_sds', 'improper_storage'],
    mechanismOfHarm: ['chemical_burn', 'inhalation_toxicity', 'absorption'],
    hazardousEnergyOrAgent: ['chemical_agent'],
    exposurePathways: ['skin_contact', 'inhalation', 'ingestion'],
    commonControlFailures: ['missing_labels', 'unknown_contents', 'incompatible_storage'],
    preferredControlFamilies: ['substitution', 'engineering_ventilation', 'secondary_containment'],
    weakOrInsufficientControls: ['ppe_only', 'smell_test'],
    evidenceRequired: ['container_labeling', 'sds_availability', 'chemical_identity'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['hazard_communication'],
    correctiveActionPrinciples: ['label', 'isolate', 'ventilate'],
    verificationEvidence: ['photo_of_compliant_label', 'sds_location_verify'],
    humanReviewTriggers: ['unknown_chemicals', 'toxic_mixtures']
  },
  {
    hazardFamily: 'confined_space',
    hazardSubtypes: ['permit_required', 'non_permit'],
    mechanismOfHarm: ['asphyxiation', 'engulfment', 'toxic_exposure'],
    hazardousEnergyOrAgent: ['atmospheric_hazard', 'stored_material'],
    exposurePathways: ['inhalation', 'entrapment'],
    commonControlFailures: ['no_atmospheric_testing', 'no_attendant', 'failure_to_isolate'],
    preferredControlFamilies: ['ventilation', 'isolation', 'atmospheric_monitoring'],
    weakOrInsufficientControls: ['buddy_system_only', 'quick_peek'],
    evidenceRequired: ['gas_test_results', 'entry_permit_status', 'attendant_presence'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['confined_space'],
    correctiveActionPrinciples: ['test_before_entry', 'ventilate', 'monitor_continuously'],
    verificationEvidence: ['permit_photo', 'gas_monitor_log'],
    humanReviewTriggers: ['idlh_atmospheres', 'complex_rescue_plan']
  },
  {
    hazardFamily: 'respiratory_dust_fume_exposure',
    hazardSubtypes: ['silica_dust', 'welding_fumes', 'lead_dust'],
    mechanismOfHarm: ['chronic_lung_disease', 'systemic_poisoning'],
    hazardousEnergyOrAgent: ['airborne_particulates', 'chemical_fumes'],
    exposurePathways: ['inhalation'],
    commonControlFailures: ['missing_dust_suppression', 'failed_ventilation', 'incorrect_respirator'],
    preferredControlFamilies: ['wet_methods', 'local_exhaust_ventilation'],
    weakOrInsufficientControls: ['paper_mask', 'blowing_with_compressed_air'],
    evidenceRequired: ['dust_visibility', 'sampling_results', 'ventilation_flow'],
    relatedJurisdictions: ['msha_mnm', 'osha_construction', 'osha_general'],
    relatedStandardFamilies: ['respiratory_protection', 'air_contaminants'],
    correctiveActionPrinciples: ['suppress_at_source', 'remove_from_air', 'protect_breathing'],
    verificationEvidence: ['air_sampling_report', 'ventilation_test_result'],
    humanReviewTriggers: ['visible_dust_clouds', 'confined_welding']
  },
  {
    hazardFamily: 'fire_prevention_hot_work',
    hazardSubtypes: ['welding_cutting', 'brazing', 'flammable_storage'],
    mechanismOfHarm: ['burn', 'smoke_inhalation', 'property_damage'],
    hazardousEnergyOrAgent: ['thermal_fire', 'ignitable_vapors'],
    exposurePathways: ['direct_heat', 'flame_spread'],
    commonControlFailures: ['no_fire_watch', 'missing_extinguisher', 'combustibles_nearby'],
    preferredControlFamilies: ['removal_of_combustibles', 'fire_barriers'],
    weakOrInsufficientControls: ['bucket_of_water', 'leaving_area_immediately'],
    evidenceRequired: ['permit_status', 'fire_watch_presence', 'extinguisher_availability'],
    relatedJurisdictions: ['osha_general', 'osha_construction', 'msha_mnm'],
    relatedStandardFamilies: ['fire_protection', 'hot_work'],
    correctiveActionPrinciples: ['clear_combustibles', 'assign_watch', 'verify_extinguishment'],
    verificationEvidence: ['hot_work_permit_photo', 'fire_watch_sign_off'],
    humanReviewTriggers: ['near_fuel_tanks', 'high_dust_areas']
  }
  // Note: Registry is sample-complete for audit, but extensible.
];
